### ISSUE TITLE
explain what's going to happen after a user submits a session proposal

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#100]
I was expecting to see a "We'll be in touch by X date to let you know if your session has been approved" kind of message. Or maybe that happens in an email afterwards?

**Comment by hannahkane** [comment]
can't add labels, but #81

**Comment by Saallen** [comment]
@ScottDowne we made a response email for submitted sessions- I couldnt find the issue though. 
Do you have a link?

**Comment by ScottDowne** [comment]
I do not. I looked and didn't find anything. I also can't remember an issue about emails.

**Comment by ScottDowne** [comment]
I want to flag this as a priority. Looks like this is fairly critical for shipping and was never on my radar.

**Comment by Saallen** [comment]
Sorry-I thought we had talked about this somewhere but its not in github.
If we are using the google form- will this not automatically create a response. 
I have copy now if needed for a response will add below this comment

**Comment by Saallen** [comment]
Thank you for submitting your proposal for Mozfest 2015.

Successful proposals will be announced in September 2015
Keep up to date with other festival news by signing up for updates here: http://mozillafestival.org/ or send us an email if you have any questions about your submission or the festival at festival@mozilla.org

You can tweet us too at @Mozillafestival using the #MozFest.
Tweet a hello or let us know about your session

Good Luck!

**Comment by ScottDowne** [comment]
@Saallen what do we want the subject to be for the email?

**Comment by ScottDowne** [comment]
@Saallen Idea, why not display this in the thank you page post submission?

How much do we need an email for this?

**Comment by ScottDowne** [comment]
Email should be sent now to the email provided when you filled out the form.
