### ISSUE TITLE
increase body leading

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/2015.mozillafestival.org#102]
/expect and all body copy - the leading is a little too tight for that font size

**Comment by ScottDowne** [comment]
A bit confused as to what's being asked.

Is the idea we bump up the font size? I never did get a proper size, I only guessed at that.

@vazquez thoughts?

**Comment by LauraHilliger** [comment]
the leading is the space between lines, in CSS the line-height. The font size is 20px and the line-height is 23px. I would suggest bumping it up to 26px, but @vazquez is the designer, so he should definitely take a look!

**Comment by ScottDowne** [comment]
I agree with you, the line-height is a bit weird.

27px line-height is the browser default, so I say we just don't specify line-height at all.

**Comment by vazquez** [comment]
Let's remove the declaration so that we use the browser default of 27px

**Comment by ScottDowne** [comment]
Fixed
