### ISSUE TITLE
Remove orphan on /location

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/2015.mozillafestival.org#103]
might get fixed w/ #102

**Comment by ScottDowne** [comment]
Is the orphan in question "Greenwich" under National Rail?

**Comment by LauraHilliger** [comment]
No it's under "Main Festival Venue" the orphan is "working"

**Comment by ScottDowne** [comment]
Odd, it's not an orphan for me. That content is in a max width of 840px so it shouldn't reflow until mobile.

Can I see a screenshot?

If I zoom to 120% it becomes an orphan.

**Comment by LauraHilliger** [comment]
hmm...it would need max-width 873 for me. Weird. 
http://i.imgur.com/oyH7wPA.png

**Comment by ScottDowne** [comment]
Turns out mac and linux's font rendering is different enough to cause issues like this.

I found a display that works for both.
