### ISSUE TITLE
Extend Participation Guidelines

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/2015.mozillafestival.org#104]
Consider a line like "Bad behavior will not be tolerated." under Diversity & Inclusion, or a bold point under "How to treat each another" like "Respect people's boundaries". Preferably both. We've had incidents 2 years running.

**Comment by ScottDowne** [comment]
@Saallen thoughts?

**Comment by Saallen** [comment]
Diversity & Inclusion should be changed as little as possible as this is a Mozilla wide piece.
I am open to adding new points under How to Treat each other:
Can we structure Bad Behaviour will not be tolerated another way @LauraHilliger - its very open.
Respect Boundaries can come under Be respective and Welcoming

**Comment by LauraHilliger** [comment]
I guess "Respect Boundaries" is enough, not sure how you indicate that we reserve the right to ban people if they are acting inappropriately other than with "bad behavior will not be tolerated" but maybe we don't need to SAY it.

**Comment by Saallen** [comment]
As Laura said above I think respect boundaries is enough. I am hoping we dont actually need to say we will barr people for bad behaviour.
