### ISSUE TITLE
Overflowing video preview on iPhone 5

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#106]
![photo 2](https://cloud.githubusercontent.com/assets/2896608/8011936/173b6728-0b72-11e5-9966-247a37504db9.PNG)

![photo 1](https://cloud.githubusercontent.com/assets/2896608/8011937/173d25f4-0b72-11e5-938b-bbebff6cbbf5.PNG)

**Comment by mmmavis** [comment]
oops not sure if the site is ready for mobile testing yet :see_no_evil:

**Comment by ScottDowne** [comment]
This was fixed.
