### ISSUE TITLE
Call for Proposals description

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#107]
Hi @edrushka @ScottDowne @cassiemc @KevZawacki 
This might be too much info for the top of the form but we never explain ourselves, themes or sessions in other places. Let me know what you think?

//////////////////////////////////////////////

Please fill in the fields below to propose your session.

[insert sched.com privacy piece- if we move forward with them]

Once you have submitted your session, you will not be able to edit it directly.

If you have any questions please send any questions or revisions to festival@mozilla.org.
Remember we believe in peer to peer sessions, learning through making and encourage dialog and hacking in small groups. Think participation not power points

You should expect anywhere between 5 – 50 participants in your session. Be prepared for a range of group sizes, abilities and ages. 
As a facilitator, you will frame the session goals, team up small groups, and ensure participants work productively & purposefully together.

Looking forward to reading your submission
This currently is an open call - sign up for updates if you are worried about closing dates

**Comment by Saallen** [comment]
The last comment - about the open call might not be well received and maybe I should add a date. 
31st of August.

**Comment by KevZawacki** [comment]
I think this would be helpful. Some minor edits to the copy:

Please fill in the fields below to propose your session. Note: once you have submitted your session, you will not be able to edit it directly.

[privacy copy]

If you have any questions, please email festival@mozilla.org. Remember: we believe in peer-to-peer sessions, learning through making, open dialog and hacking in small groups. Think participation, not PowerPoint.

You should expect anywhere between five and 50 participants at your session. Be prepared for a range of group sizes, abilities and ages. As a facilitator, you will frame the session goals, team up small groups and ensure participants work productively and purposefully together.

We're looking forward to reviewing your submission.

**Comment by Saallen** [comment]
Thanks @KevZawacki :+1:

**Comment by ScottDowne** [comment]
Updated
