### ISSUE TITLE
Headline and subheadline should be all caps

### ISSUE THREAD

**Issue by vazquez** [mozilla/2015.mozillafestival.org#108]
![screenshot 2015-06-05 15 48 52](https://cloud.githubusercontent.com/assets/1119821/8013946/a05523b4-0b9a-11e5-9a50-3d1c45156f83.png)

versus:

![screenshot 2015-06-05 15 51 27](https://cloud.githubusercontent.com/assets/1119821/8013966/c01de6e0-0b9a-11e5-8623-a3a0a2a135d1.png)

**Comment by ScottDowne** [comment]
Fixed.
