### ISSUE TITLE
ti.to purchasing comes after launch

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/2015.mozillafestival.org#115]
We're launching the site a call for proposals without ticket sales.

So we need a bit of messaging with that on our /ticket page.

**Comment by Saallen** [comment]
**Coming soon - tickets will be on sales from the 17th of June. 
If you have any questions please contact the festival team at festival@mozilla.org. **

What do others think of this @thornet @edrushka ?

**Comment by ScottDowne** [comment]
Fixed. I poked @vazquez a bit to get feedback on the layout of the text. Ended up like this:

![notyet](https://cloud.githubusercontent.com/assets/197334/8060542/f98df360-0e93-11e5-957b-efe608935bca.png)

@thornet @edrushka @Saallen 

It's live on staging right now: https://mozillafestival-org-2015.herokuapp.com/tickets

**Comment by Saallen** [comment]
That looks good - thanks :fireworks:

**Comment by ScottDowne** [comment]
Also, because it's live and landed, this should be closed.

Feedback on it should be filed as new tickets.
