### ISSUE TITLE
fix copy error on ticket page

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#121]
The text added in  #115 has an error. Also, I think it's a very straightforward message, and we don't need to add an email address (they can find us via 'Contact Us').

Recommend changing to:

Coming soon - tickets will go on sale June 17, 2015.

cc @Saallen @thornet

**Comment by ScottDowne** [comment]
Do you think I should also change the formatting of the two lines, one line, header or not?

**Comment by ScottDowne** [comment]
Fixed
