### ISSUE TITLE
Updates to the Mozfest Contact page

### ISSUE THREAD

**Issue by amirad** [mozilla/2015.mozillafestival.org#125]
Just noticed a couple things here:
•The "!" after Make it Better seems out of place and not mirrored in the other titles.
•Should #mozfest be hyperlinked to: https://twitter.com/search?f=realtime&q=%23mozfest&src=typd 
•Should email us also be hyperlinked

**Comment by edrushka** [comment]
Thanks Amria

**Comment by ScottDowne** [comment]
Updated on staging: https://mozillafestival-org-2015.herokuapp.com/contact
