### ISSUE TITLE
Edits to Participation Guidelines page - https://mozillafestival-org-2015.herokuapp.com/guidelines 

### ISSUE THREAD

**Issue by amirad** [mozilla/2015.mozillafestival.org#126]
In the inclusion and diversity section that "to" is left hanging and it looked like a broken sentence. Maybe shift that over to the next column?

In the 'raising issues' section, is there a way or link to contact Michelle? It's slightly unclear as to who or what to contact in that section.

**Comment by ScottDowne** [comment]
We had a way to contact Michelle initially but was pulled.
https://github.com/mozilla/2015.mozillafestival.org/issues/47
and
https://github.com/mozilla/2015.mozillafestival.org/commit/00afa81615143401acdc0291d083efa6e27cdc9b

**Comment by ScottDowne** [comment]
Fixed the orphaned word, but I didn't do anything about the contact info.

If it's still an issue (given that we used to have her info and removed it) we should file a new ticket with a bit more of an argument as to why.
