### ISSUE TITLE
Are Session Proposal dropdown labels correct?

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#128]
@Saallen Right now the labels under 'Theme' are Make, Lead, Teach, Invent, Play. Should those be under 'Mode'? Have we got those two titles switched?

**Comment by Saallen** [comment]
No, these are correct as the theme- Make, teach.... I just doubel checked on the old issue
Do you feel that Mode is not suitable @edrushka ?

**Comment by edrushka** [comment]
@Saallen If that works for the festival team (especially the space wranglers) I'm good! If you're not sure we can ask Kevin. Otherwise we can close this.

**Comment by Saallen** [comment]
I think it that it doesnt really matter what we call those filters as long as folks use it :)
