### ISSUE TITLE
Send email to 'Save the Date' list

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#129]
driver: @edrushka
copy: @KevZawacki 
copy signoff: @Sallen
email sender: @Saallen 

We should sent an alert to the people who signed up to Save the Date to let them know that tickets will be available for purchase on June 17. @Saallen do you have a message from last year that Kevin could review?

**Comment by Saallen** [comment]
I am working on this email<<<< [here] (https://festival.etherpad.mozilla.org/emailtemplates2015)  >>>
Would definitely appreciate some input and direction :8ball:

**Comment by KevZawacki** [comment]
Looks great — thanks for sharing, @Saallen. I dropped in a few minor edits.
Do we want to promote the 'call for proposals' in this email, as well? Or, too early?

**Comment by Saallen** [comment]
Hey @KevZawacki
I should of had labeled the emails better- save the date went out in May
This is email 2- New website and Call for Proposals email draft

**Comment by KevZawacki** [comment]
Ah, gotcha. Just added edits to the pad.

**Comment by Saallen** [comment]
:candy: thanks. Looks great- thanks

**Comment by ScottDowne** [comment]
Can we close this?

**Comment by Saallen** [comment]
yup :bomb:

**Comment by edrushka** [comment]
<<<<< @saallen >>>>>
(how can there be one zillion emoji and none for hug???!)
