### ISSUE TITLE
Finalize Ti.to issues before tickets sales go live

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#130]
Ticket sales start June 17 (should happen in the a.m. London time).

**The following issues should be resolved by EOD June 15.**
- [x] Add PayPal info to Ti.to -- @Saallen 
- [x] Go into account and click start to make sales live from the Ti.to end -- @Saallen 
- [x] create the patch -- @ScottDowne 

**EOD June 16**
- [x] @ScottDowne to connect with @jbuck to push the patch to prod, making Ti.to visible on the site

Scott, please edit the above if I've gotten anything wrong.

**Comment by Saallen** [comment]
Once Legal have completed the Terms for the Ti.to upgrade- I can then enter the Paypal account details and it should be fairly straightforward to going live with the ticket page.

**Comment by ScottDowne** [comment]
@Saallen Do we have a timeline for when Legal finishes? Is this something we should be concerned with?

**Comment by Saallen** [comment]
I am not concerned as TI.TO have gone through a legal review already. This is about legal drafting the contract. They know its a blocker to the site

**Comment by ScottDowne** [comment]
@Saallen Sounds good to me :)

**Comment by edrushka** [comment]
Worst case scenario we can update the tickets page with a new date. Let's not send the email from #129 until the contract is in place, though.

**Comment by edrushka** [comment]
@Saallen any updates? 
I think we need to change the date on the site.

**Comment by edrushka** [comment]
@Saallen have you heard from MoCo? I think we should prepare a plan B. What did we use last year?

**Comment by Saallen** [comment]
Legal is making the last amendments now- we have been working on the t&cs all day, Ti.to know the contract is coming and MozFest2015 ti.to account is prepped and ready to be linked as soon as the ink dries
