### ISSUE TITLE
Design comps for mobile

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#131]
driver: @edrushka
designer: @cassiemc (backup @vazquez) 
dev: @ScottDowne 

Complete the design comps for the Mozfest site so Scott can optimize for mobile.

**Comment by cassiemc** [comment]
Do we need to design full mobile comps, or just mobile QA? @ScottDowne I'd bet we could knock a lot of this out with a vidyo call. I'll schedule something for today. cc @edrushka

**Comment by edrushka** [comment]
How's this coming @cassiemc?

**Comment by cassiemc** [comment]
We don't need to do this as I've simply done a bunch of design QA in #132.
