### ISSUE TITLE
Mobile Design QA

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#132]

**Comment by cassiemc** [comment]
<img width="499" alt="01-homepage" src="https://cloud.githubusercontent.com/assets/1186326/8505061/c77e9c74-21aa-11e5-807f-bfa875b13dd9.png">
<img width="452" alt="02-homepage2" src="https://cloud.githubusercontent.com/assets/1186326/8505060/c77d8b22-21aa-11e5-961a-a7229a66eee5.png">
<img width="432" alt="03-homepage3" src="https://cloud.githubusercontent.com/assets/1186326/8505059/c77d7128-21aa-11e5-9922-e605e1aaee43.png">
<img width="494" alt="04-proposals" src="https://cloud.githubusercontent.com/assets/1186326/8505058/c77cde66-21aa-11e5-979a-d2d142dde4ea.png">
<img width="344" alt="05-proposals2" src="https://cloud.githubusercontent.com/assets/1186326/8505063/c77f4480-21aa-11e5-9dea-339435d9315e.png">
<img width="472" alt="06-location" src="https://cloud.githubusercontent.com/assets/1186326/8505062/c77f1dac-21aa-11e5-933d-32451ec7c013.png">
<img width="343" alt="07-about" src="https://cloud.githubusercontent.com/assets/1186326/8505066/c78f366a-21aa-11e5-8df2-ce3a07cf3b2c.png">
<img width="484" alt="08-about2" src="https://cloud.githubusercontent.com/assets/1186326/8505064/c78c77ae-21aa-11e5-8686-0a342d69c083.png">
![Uploading 09-about3.png…]()
<img width="582" alt="10-expect" src="https://cloud.githubusercontent.com/assets/1186326/8505068/c790c0b6-21aa-11e5-9da5-4f4a6124f23d.png">
<img width="320" alt="11-participation" src="https://cloud.githubusercontent.com/assets/1186326/8505067/c7901ef4-21aa-11e5-869b-ef19827ea667.png">

Lots of stuff here for you @ScottDowne – let me know if you have any Qs!

**Comment by cassiemc** [comment]
Translating all the comments from above into a checklist:

**Home**
- [ ] Less space above and below the play button
- [ ] More space below the subhead paragraph that is on top of the image

**Global (all inside pages)**
- [ ] Make the MozFest logo 15-20% smaller
- [ ] Get rid of the grey line between top nav items
- [ ] Scale the header images
- [ ] Scale the headline copy so that it fits horizontally in the viewport
- [ ] Hide the HR in the footer (can hide on mobile & desktop, on every page)

**Tickets**
- [ ] Make the fields shorter vertically
- [ ] Make the illustrations 20-30% smaller

**About**
- [ ] Fix the header image (it's being stretched vertically)
- [ ] Less space below the circles
- [ ] More space above the circles

**What to Expect**
- [ ] Move Mark Surman photo down below his typed name
- [ ] Make the Mark Surman photo about 20% smaller
- [ ] Increase horizontal space between Mark's signature and his photo

**Participation Guidelines**
- [ ] Headline is cut-off on the right

**Comment by ScottDowne** [comment]
Pull request: https://github.com/mozilla/2015.mozillafestival.org/pull/142

**Comment by ScottDowne** [comment]
I pushed them all to staging: https://mozillafestival-org-2015.herokuapp.com/

I'm going to close this but it's not ob prod yet.

@cassiemc or @alicoding feel free to take a look at my pr and staging link, if you see anything else that can be improved file it. If everything looks good, can we get @alicoding or jbuck to update prod?
