### ISSUE TITLE
Update tickets page with message

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#133]
It doesn't seem like ti.to will be working for ticket sales tomorrow, as we indicated on the site. We need to update the message here https://2015.mozillafestival.org/tickets

I suggest striking through the text that is already there, and underneath writing:
Oops! We hit a snag with our ticketing software. Tickets will be available for purchase soon. [Sign up] (link to BSD list) to be notified about festival news, including ticket sales.

@KevZawacki what do you think?

cc @ScottDowne @Saallen

**Comment by KevZawacki** [comment]
+1. I vote strike through + new copy beneath.

**Comment by edrushka** [comment]
Thanks Kevin,.

@Saallen can you OK this in this bug if you want to proceed, then assign to @ScottDowne to do the patch, and then Scott will give to @jbuck to push to prod.

Earlier is better, since many prospective ticket-buyers will be on London time.

Thanks, all!

**Comment by ScottDowne** [comment]
I'm going to queue up a patch so it's ready after sign off.

**Comment by ScottDowne** [comment]
A live demo: https://mozfest-2015-staging.herokuapp.com/tickets

Look good?

Patch here: https://github.com/mozilla/2015.mozillafestival.org/pull/134

**Comment by edrushka** [comment]
Thanks, Scott. Works for me! @Saallen?

**Comment by jbuck** [comment]
It's 2:19AM in London so I'm awfully tempted to just this to production now, and do any necessary fixes tomorrow.

**Comment by edrushka** [comment]
Gah! I'm hesitant without confirming with Sarah first, but it doesn't seem like there's *any* way we'll get ti.to live so OK @jbuck . If Sarah needs to make a change tomorrow, we'll have to prioritize that though, since we're doing this without her explicit signoff.

**Comment by ScottDowne** [comment]
I agree with @jbuck on this.

**Comment by edrushka** [comment]
ship it! fingers crossed.

**Comment by jbuck** [comment]
Shupped! :shipit: 

Should be 15 minutes before changes are seen live

**Comment by Saallen** [comment]
Hey guys this looks great- good call just to ship it incase there are any eager Europeans looking to get tickets. . Thanks
