### ISSUE TITLE
Update Webmaker logo on Mozfest website

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#137]
From @LauraReynal: As I was hanging out on the beautiful MozFest Website I saw that there is the old Webmaker logo on this page https://sendto.mozilla.org/page/s/mozfest-2015-save-the-date
It is in the footer. 

![screen shot 2015-07-01 at 18 25 19](https://cloud.githubusercontent.com/assets/8261945/8460716/e387f560-201e-11e5-8576-14a346ec085d.png)

/cc @Saallen @edrushka

**Comment by edrushka** [comment]
@KevZawacki could you please add this to the list of assets to update?

**Comment by KevZawacki** [comment]
All set. Added to our spreadsheet and flagged as P1: https://docs.google.com/spreadsheets/d/19v3SW-oX68t4R8uZ9NMkRS36beyKAXIzHS0d3zgU26I/edit#gid=0

**Comment by ScottDowne** [comment]
Can we close this?

**Comment by Saallen** [comment]
Hey- Yes. 
However should we archive the old 2014 website as people are still signing up for updates??
Not sure how to control this.

**Comment by ScottDowne** [comment]
@Saallen I can change the button in 2014.mozillafestival.org from "save the date" to "purchase tickets" and then link it to "2015.mozillafestival.org/tickets"

**Comment by Saallen** [comment]
@ScottDowne Can we archive the site so that when people search for the festival 2015 is the only site available? Is this recommendable?

**Comment by ScottDowne** [comment]
@Saallen I'm fine with that.

**Comment by hannahkane** [comment]
This ticket seems closeable, yes?
