### ISSUE TITLE
Re-visiting Session organisational tool

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#138]
We have sidelined sched.com for the moment so I would examine this repo as a possible new option.
https://github.com/opendatacity/re-data from 
https://re-publica.de/ festival from The Open Knowledge Foundation
https://re-publica.de/en/15/schedule#2015-05-07%2015:00---2015-05-07%2020:00

Looping in @edrushka @secretrobotron @ScottDowne

**Comment by ScottDowne** [comment]
I don't see a way to update what's in re-data easily.

**Comment by hannahkane** [comment]
Think we've decided to go with github as the solution. Can we close this?

**Comment by ScottDowne** [comment]
Yup :)
