### ISSUE TITLE
Update Webmaker logo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#141]
Update the Webmaker logo:
 - step 1: gather list of anywhere it appears
  - [ ] save the date footer
 - step 2: update it

I'm not sure who has the knowledge to drive this on Mozfest assets. 

<img width="722" alt="screenshot 2015-07-06 11 25 28" src="https://cloud.githubusercontent.com/assets/53411/8526001/ea58ec44-23d1-11e5-94e2-8066b337de94.png">

**Comment by thornet** [comment]
The assets live in BSD. @Saallen should be able to get you access and/or update files directly. I can help if anyone gets stuck. 

The structure is: 

1. BSD form (everything form-like on that page)
2. BSD wrapper (everything around it including background image, footer, navigation.

**Comment by Saallen** [comment]
We are moving off BSD and thus leaving the old webmaker logo behind :(
Volunteer sign up sheet is currently on the 2015 website is still on BSD but ready to move across to ti.to

**Comment by ScottDowne** [comment]
Closing this.

I updated staging to link to ti.to instead.

https://mozillafestival-org-2015.herokuapp.com/

We can make it an embed later if we still want to.
