### ISSUE TITLE
Call for Proposals page: Add submission deadline date

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#143]
@ScottDowne Can we add submission deadline date to the form for Call for Proposals?
Deadline for submission is 31st of August 2015 at 21:00 UTC
Thanks

**Comment by ScottDowne** [comment]
I can do this Monday when I come back. I don't think this blocks shipping anything.

**Comment by Saallen** [comment]
Agreed :+1:

**Comment by ScottDowne** [comment]
@Saallen is "Deadline for submission is 31st of August 2015 at 21:00 UTC" the copy we want to use?

**Comment by ScottDowne** [comment]
@Saallen Thoughts? https://mozillafestival-org-2015.herokuapp.com/proposals

**Comment by Saallen** [comment]
Good strong postitioning- thanks
