### ISSUE TITLE
Volunteer page - issue with form

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#147]
Glitch in the Mozfest matrix- the link we have for the Volunteer sign up form links to a ticket half filled by our very own spike-
![screen shot 2015-07-15 at 17 38 19](https://cloud.githubusercontent.com/assets/10194015/8704063/a0b43df2-2b18-11e5-87c1-f079f4409bf0.png)
Is there someone who can link the page correctly @edrushka

**Comment by edrushka** [comment]
@jbuck, do you know who can help with this since @ScottDowne is on PTO?

**Comment by edrushka** [comment]
@Saallen is contacting ti.to in case it's a glitch on their side.

**Comment by jbuck** [comment]
I think the correct link should be https://ti.to/Mozilla/mozfest-volunteers/

**Comment by ScottDowne** [comment]
My bad, I didn't look close enough. Looks like @jbuck fixed it. Thanks everyone for catching and patching :)
