### ISSUE TITLE
Website phase two

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#150]
I was wondering how to coordinate and take next steps with the website @secretrobotron - who shall be my point of contact- am I able to continue to ping scott or do I need to request new workflow?
Next steps
 - Find admin org space for proposals 
 - Find schedule app for festival
 - Make  soft  edits to website - 
   - add Vol info
   - Archive 2014 website
   - Update info on the google search page ( not sure what correct term is here)
 - Get ready for next stage of the website- :tulip:

**Comment by thornet** [comment]
+ issues #157 and #156 to be shipped as next phase of the website.

**Comment by Saallen** [comment]
Full list of new pages for next stage of website


Pages and sub sections to be built
  - [ ]   Info on the themes and sessions #156
  - [ ]  Themes pages w SW details - Live in September
   - [ ]  Youth zone 
   - [ ]  bios 
  - [ ] Fringe event page - Live in October
  - [ ]   Remote participation live in October

**Comment by hannahkane** [comment]
Is this ticket still needed? Seems like relevant pieces have been broken out into their own tickets.

**Comment by Saallen** [comment]
Nope- we have broken out each page into separate issues
