### ISSUE TITLE
Broken Volunteer link on wiki

### ISSUE THREAD

**Issue by thornet** [mozilla/2015.mozillafestival.org#151]
Reported via Marcia: 

broken link at the bottom of this page: https://wiki.mozilla.org/Mozfest/2015#Volunteers (The "here" link under volunteers)

https://sendto.mozilla.org/page/s/mozfest-2014-volunteer-reunion---11th-march-2015

**Comment by SpikeUK** [comment]
Old link deleted. I will add link to Sept volunteer meetup (when I have created it)
Spike

**Comment by ScottDowne** [comment]
This sounds resolved? Can we close this?

**Comment by SpikeUK** [comment]
I believe so.

Spike
