### ISSUE TITLE
What's the plan for volunteer tickets requested from BSD

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/2015.mozillafestival.org#153]
I just wanted to make sure we didn't forget these. We have roughly 40 people signed up as volunteers inside BSD and wondered how we deal with them? Do we migrate them or something?

cc @Saallen

**Comment by SpikeUK** [comment]
Thanks Scott!
Sarah A has imported these into new tool and I have checked that all the info is the same.
All under control thanks ;-)
Spike

On July 27, 2015 6:25:42 PM GMT+01:00, ScottDowne <notifications@github.com> wrote:
>I just wanted to make sure we didn't forget these. We have roughly 40
>people signed up as volunteers inside BSD and wondered how we deal with
>them? Do we migrate them or something?
>
>cc @Saallen 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/2015.mozillafestival.org/issues/153

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ScottDowne** [comment]
Sweet! Thanks all.
