### ISSUE TITLE
Site links for the 2015 site

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#155]
There are sites links below the 2014 site info on google search. If we archive the 2014 site will these links move across to 2015? 
How can we ensure this changes?
![screen shot 2015-07-28 at 14 35 47](https://cloud.githubusercontent.com/assets/10194015/8933142/23e776ba-3539-11e5-8aed-f48d1a8d80df.png)

**Comment by hannahkane** [comment]
duped by #169
