### ISSUE TITLE
Improve Mozfest messaging on /about and /what-to-expect 

### ISSUE THREAD

**Issue by thornet** [mozilla/2015.mozillafestival.org#157]
Mitchell Baker shared a few edits for how we talk about Mozfest. We should work these into copy on the website and in other materials: 

* "continuing the momentum" sounds boring to me.  I know we did something like this at Whistler -- not reinventing, but delivering on the promise of before.  So the core idea may well be right, though even so it sounds boring!
* Past materials have focused on how many people are there, how many sessions, etc.  That might be right for those materials, but aren't as helpful in getting people to understand the core of it, why it's different from other places.  In other words, it gives a sense of the size and scale but is a bit self-referential and logistical.
* the media document talks about leadership development as being the core theme (and I like it!).  The webpage currently conveys mostly web literacy  to me.  "Teach and build" does not make me think of the incredible range of activities MozFest brings.  If feels like the Maker Party web literacy work to me.  Great work of course, but only a fraction of what makes MozFest so stimulating.

cc @Saallen @KevZawacki

**Comment by KevZawacki** [comment]
Thanks, @thornet! Duly noted.

What are your thoughts on bringing the language and tone from Mark's 'What to Expect' message to the fore? (https://2015.mozillafestival.org/expect)

It's broader, and more aspirational.

**Comment by thornet** [comment]
Love it. 

Also, I'm working on some improved language around the themes of this year's Mozfest. I think we could include some of it in a next round of messaging as well:

https://festival.etherpad.mozilla.org/program

Maybe a combo of updating Mark's letter and either adding a section in "What to expect" about themes and/or tweaking the language in "About."

What do you all think?

cc @edrushka

**Comment by KevZawacki** [comment]
Excellent, hadn't seen this program doc -- thanks, @thornet! Taking a close look now.

**Comment by edrushka** [comment]
@KevZawacki will you let us know if you recommend adjusting the copy? Thanks!

**Comment by KevZawacki** [comment]
Let's weave the language from the program into various sections of the MozFest website, like @thornet suggests. 

In "About," we can add a third sentence to the graf up top: "... the Web's most pressing issues. **We explore topics like privacy, ethics, literacy and economy on the Web**."

Then, we can rewrite "The Present" section in the timeline below: "This year, **we're focusing on leadership, advocacy and impact. We'll train tomorrow's leaders, empower participants to make a positive difference on the Web, and work toward universal web literacy**."

In "What to Expect," we can add another graf to Mark's letter: "... find a fully-open platform. <br> **We're seeking leaders and mentors to join us in London this year; individuals eager to empower others and make a real impact online. If you're passionate about literacy, privacy and inclusion on the Web, we hope to see you in London. <br> Best, Mark**."

We can also add a new section between "A Note From Mark Surman" and "Participating at MozFest" titled "2015 Themes." We can list out the eight topics + "your idea." In terms of fitting it all: do we want to shorten the theme descriptions? Or, have the descriptions populate when you click/expand a theme? 

@thornet, @edrushka, thoughts?

**Comment by thornet** [comment]
Love the edits, @KevZawacki!

Let's to the text ones you suggest and we can leave out the more
substantial theme descriptions for now. That might be better blog or
printed program guide material.

On Thu, Aug 13, 2015 at 4:33 PM, Kevin Zawacki <notifications@github.com>
wrote:

> Let's weave the language from the program into various sections of the
> MozFest website, like @thornet <https://github.com/thornet> suggests.
>
> In "About," we can add a third sentence to the graf up top: "... the Web's
> most pressing issues. *We explore topics like privacy, ethics, literacy
> and economy on the Web*."
>
> Then, we can rewrite "The Present" section in the timeline below: "This
> year, *we're focusing on leadership, advocacy and impact. We'll train
> tomorrow's leaders, empower participants to make a positive difference on
> the Web, and work toward universal web literacy*."
>
> In "What to Expect," we can add another graf to Mark's letter: "... find a
> fully-open platform.
>
> *We're seeking leaders and mentors to join us in London this year;
> individuals eager to empower others and make a real impact online. If
> you're passionate about literacy, privacy and inclusion on the Web, we hope
> to see you in London. Best, Mark*."
>
> We can also add a new section between "A Note From Mark Surman" and
> "Participating at MozFest" titled "2015 Themes." We can list out the eight
> topics + "your idea." In terms of fitting it all: do we want to shorten the
> theme descriptions? Or, have the descriptions populate when you
> click/expand a theme?
>
> @thornet <https://github.com/thornet>, @edrushka
> <https://github.com/edrushka>, thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/157#issuecomment-130697711>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by mmmavis** [comment]
@KevZawacki could you take a quick look on https://mozillafestival-org-2015.herokuapp.com/ (staging) to make sure the updated copy look right to you? Thanks! :dancer:

**Comment by KevZawacki** [comment]
Hi @mmmavis, just did a proofread -- looks great!

**Comment by mmmavis** [comment]
awesome thanks @KevZawacki :smile: im pushing this live now
