### ISSUE TITLE
Social media plan for countering @mozfestuk

### ISSUE THREAD

**Issue by thornet** [mozilla/2015.mozillafestival.org#158]
There's a spammy account out there: https://twitter.com/mozfestuk

We need a plan to counter act, maybe with positive reinforcement of our proper channels, or escalation with Twitter. 

@Saallen mind working with @amirad on a tactic and then sharing with Lainie?

**Comment by amirad** [comment]
Woah, that account is crazy. Any idea who it is? Have we tried messaging or reaching out to them to discuss the account yet? 
@Saallen lmk when you're free to chat some next steps!

**Comment by SpikeUK** [comment]
Oh - they are getting active again :(

**Comment by Saallen** [comment]
Update for this issue.
Amira and myself chatted, and I also reached out to Kevin, Erika D and Karolyna from MoCo PR for advice. I am reluctant to reach out to these guys as I dont want to give them any attention or encourage them. I have experience with a  troll account on a previous event and reaching out to them was the worst thing we could do. Kevin, having worked on something similar before, advised not reaching out just yet but he did file a impersonation account with Twitter. I will keep this issue updated.

**Comment by SpikeUK** [comment]
Account Suspended - twitter message
Well, that was quick :)

Not sure if it is a troll or impersonation account - looks more like a 
parody or humorous homage.

But yes - best not to contact them publicly and give them material to 
work with.
Spike

**Comment by thornet** [comment]
Well done, team!

On Wed, Aug 12, 2015 at 11:59 AM, Spike <notifications@github.com> wrote:

> Account Suspended - twitter message
> Well, that was quick :)
>
> Not sure if it is a troll or impersonation account - looks more like a
> parody or humorous homage.
>
> But yes - best not to contact them publicly and give them material to
> work with.
> Spike
>
> On 12/08/2015 10:14, Sarah Allen wrote:
> >
> > Update for this issue.
> > Amira and myself chatted, and I also reached out to Kevin, Erika D and
> > Karolyna from MoCo PR for advice. I am reluctant to reach out to these
> > guys as I dont want to give them any attention or encourage them. I
> > have experience with a troll account on a previous event and reaching
> > out to them was the worst thing we could do. Kevin, having worked on
> > something similar before, advised not reaching out just yet but he did
> > file a impersonation account with Twitter. I will keep this issue
> > updated.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mozilla/2015.mozillafestival.org/issues/158#issuecomment-130230249
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/158#issuecomment-130243808>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org
