### ISSUE TITLE
Firefox tile for MozFest

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#159]
Have the opportunity for a Firefox tile for MozFest.
Need to figure out
* What I want the tile to say - directory or suggested tile
* Steps needed to get the tile designed

Once the above steps are covered then I need
* Once visuals and copy approved,  design submitted for translation
* Produce new tiles ( copy past translated copy)
* Email to Jean C

Would love help and suggestions for next steps from @cassiemc @KevZawacki @edrushka @hannahkane @thornet

**Comment by KevZawacki** [comment]
Excellent! Where should we have the tile point to? https://2015.mozillafestival.org/ is likely too vague, and https://2015.mozillafestival.org/tickets too direct. So, maybe https://2015.mozillafestival.org/expect?

Tile copy is generally super short. I'd recommend something like: "Celebrate the Web with Mozilla at MozFest" + a logo.

**Comment by edrushka** [comment]
Wait, but why is the homepage too vague? Could we link directly to the video? /expect is also an option, but I agree /tickets is too direct.

@KevZawacki, what do you think about "Help Mozilla build/shape/imagine/envision the open web", which is a little more specific than "celebrate" (I also worry 'celebrate' is too close to Maker Party messaging).

**Comment by KevZawacki** [comment]
Ah, nevermind — video is right there on the homepage. In that case, I think we *should* link to the homepage. 

+1 to swapping out "celebrate," as it does evoke Maker Party. I like "Help Mozilla shape the open Web at MozFest."

**Comment by Saallen** [comment]
@hannahkane @KevZawacki do we want to put a milestone on this for production- I will add this to the design assets required

**Comment by KevZawacki** [comment]
+ @HPaulJohnson, our tile expert

**Comment by Saallen** [comment]
CC @cassiemc too

**Comment by cassiemc** [comment]
@Saallen When is the due date for the tile design?

**Comment by Saallen** [comment]
I will refere to our tile guru @HPaulJohnson When do we need to submit the tile or when is optimum time for this?

**Comment by HPaulJohnson** [comment]
To clarify, are we talking about a tile on Mozilla.org, a directory tile which shows up on the new tab page in Firefox or both?

We should definitely do mozilla.org and I've already given them a heads up on that and actually doesn't require design (moz.org team handles that). We would just need to supply copy and logos/wordmarks.

For directory tiles we need to deliver final assets to that engagement team. The spec should be available from the Webmaker project. Question here is whether this is the right audience for our objective? Is the idea to sell tickets, reach Mozillians or something else?  If it's to sell lots of tickets it might be right, but if it's to reach Mozillians or attendees, not sure it's worth it.

**Comment by Saallen** [comment]
I would like to use it to sell tickets @HPaulJohnson 
Sean Bohan appraoched me with both options , directory or suggested tile but I am unsure what suits our objective here so will willing follow your lead here

**Comment by HPaulJohnson** [comment]
Great. Let's do both then. 

For Mozilla.org we just need a suggested headline (@kevzawacki can you provide something shorter than the suggested copy above) and the logo/wordmark (which i think i have in the dropbox0. I can do the rest working with that team via Bugzilla.

For Directory tile (same format as suggested tile), I will put in a request to Jean Collings now and get a sense of schedule for delivering the design.

**Comment by HPaulJohnson** [comment]
Talked to Jean and we can get a directory tile for October. Her only direction was:

"Need to make sure that the CTA is super clear (Content Services is very particular about what we ask needs to match where we point our users to). "

Let's discuss tomorrow a.m. when we meet what a realistic schedule might look like for delivering the final design.

**Comment by KevZawacki** [comment]
@HPaulJohnson How about: "Celebrate the Web at MozFest"

**Comment by cassiemc** [comment]
@HPaulJohnson Do you have the tile design requirements handy?

**Comment by HPaulJohnson** [comment]
Tile spec: https://drive.google.com/a/mozilla.com/file/d/0B_MJiF6wUoWPTWFwUDMyQWFYQ3dpSVpZWUE5eFpZWWVycjdv/view?usp=sharing

**Comment by cassiemc** [comment]
@hannahkane @HPaulJohnson  It seems we should elevate this one, due to the timing. Are we trying to complete this prior to October 9?

**Comment by cassiemc** [comment]
I'd suggest: 
* For the front of the tile, let's go with the graphic image with @KevZawacki's headline: "Celebrate the Web at MozFest". We could perhaps use the header image from the front page of the Mozfest site – https://2015.mozillafestival.org/assets/images/home.jpg
* On rollover, the CTA should be, "Click here to buy tickets" Could have some kind of ticket icon.

We should aim to complete this for October 9 as per the assigned milestone. Sound good @HPaulJohnson @Saallen @hannahkane? 

cc @natalieworth See https://drive.google.com/a/mozillafoundation.org/file/d/0B_MJiF6wUoWPTWFwUDMyQWFYQ3dpSVpZWUE5eFpZWWVycjdv/view for the specs, and templates you can download from that file. Let me know if you have any questions!

**Comment by hannahkane** [comment]
WFM. Thanks, @cassiemc.

**Comment by HPaulJohnson** [comment]
wfm. thx!

**Comment by Saallen** [comment]
:+1: Thanks

**Comment by natalieworth** [comment]
I've got the first drafts for the static/ rollover MozFest tile design. There are 2 versions of the rollover. One is without the ticket icon, and the other is with. I tried to match everything to Mozilla and the MozFest 2015 branding:
![01mozfest2015_tile](https://cloud.githubusercontent.com/assets/14876567/10208488/7d88a5f0-6788-11e5-9621-f96bcbd646a4.jpg)
![02mozfest2015_tile](https://cloud.githubusercontent.com/assets/14876567/10208490/7d89aa72-6788-11e5-91a5-631fe46c8aed.jpg)
![03mozfest2015_tile](https://cloud.githubusercontent.com/assets/14876567/10208489/7d89126a-6788-11e5-9c6a-17ebf63d17c8.jpg)

**Comment by HPaulJohnson** [comment]
@natalieworth looks great! i prefer the second rollover option with the ticket icon.

**Comment by cassiemc** [comment]
@natalieworth Can you please add these to redpen? I will leave some more specific design feedback

**Comment by natalieworth** [comment]
@cassiemc I've added the images to redpen: https://redpen.io/p/xn00ffb06d3af74c9f

**Comment by cassiemc** [comment]
Ok left some feedback there @natalieworth

**Comment by natalieworth** [comment]
@cassiemc For the Retina display, should I create/upload 2 versions? Or just edit the image at 2x the resolution and create only 1 version? I'm not sure what Mozilla's development needs are for the tiles. Thanks.

**Comment by cassiemc** [comment]
I am actually not sure either, but would default to the 2x version (they can always shrink it down). @sabrinang what have you done in the past?

**Comment by sabrinang** [comment]
@cassiemc In the past working with working with Aaron Thornburgh (from tiles team) we deliver images that are 560 x 380 for retina display on mobile (for future use). For desktop, they should display at half that size (50%) at 280 x 190 which I usually haven't needed to deliver (because they shrink it).

**Comment by cassiemc** [comment]
cool thanks @sabrinang!

**Comment by adiladiladil** [comment]
@natalieworth what's your email? I will WeTransfer the PSD to you

**Comment by cassiemc** [comment]
since I'm here... natalie@mozillafoundation.org

**Comment by natalieworth** [comment]
@cassiemc Made revisions on the tile versions for MozFest: https://redpen.io/p/xn00ffb06d3af74c9f

**Comment by natalieworth** [comment]
@cassiemc Updated iteration of the rollover tile: https://redpen.io/p/xn00ffb06d3af74c9f

**Comment by cassiemc** [comment]
Perfect @natalieworth thanks!

@HPaulJohnson Here are the final assets:
![mozfest-tile-front](https://cloud.githubusercontent.com/assets/1186326/10249310/9eca34d4-68f2-11e5-8d28-6d049874f167.jpg)
![mozfest-tile-back](https://cloud.githubusercontent.com/assets/1186326/10249315/a1b58568-68f2-11e5-97ac-a71c7d73b2ec.jpg)


Anything else you need from us before we close this?

**Comment by natalieworth** [comment]
@HPaulJohnson Here's the link to the google drive tile assets (final jpeg and psd files)
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0eE80Y3MySTRpdG8

**Comment by HPaulJohnson** [comment]
thanks, @natalieworth. I've submitted these to the Tiles team and will close this issue once I hear back from them that they have everything they need.

**Comment by HPaulJohnson** [comment]
Just heard back from Jean at MoCo; here's her feedback:

"Heard back from creative, small thing - can you add the Mozilla wordmark or logo on both tiles?"

@natalieworth can you incorporate this into design and I can resubmit?

**Comment by cassiemc** [comment]
@HPaulJohnson can it be the Mozfest logo, which has the mozilla logo in it?

**Comment by HPaulJohnson** [comment]
@cassiemc jean says, yes, the Mozfest logo will do the trick. thanks!

**Comment by natalieworth** [comment]
@cassiemc @HPaulJohnson I've updated the .psd file and jpeg images with the logo added. Paul, are their any specifications from the Tiles team about logo size? Thanks!
redpen: https://redpen.io/p/xn00ffb06d3af74c9f
google drive: https://drive.google.com/a/mozilla.com/folderview?id=0B20-0lpP23c0eE80Y3MySTRpdG8&usp=sharing

**Comment by HPaulJohnson** [comment]
No specs provided so these should work. @cassiemc if you are good with them I'll resubmit. Thanks, @natalieworth

**Comment by cassiemc** [comment]
@natalieworth The logo placement is okay but it's crowding the other content. I would make it about 15%-ish smaller so it sits a little more comfily in the corner away from the other text.

**Comment by natalieworth** [comment]
@cassiemc Reduced the size of the logo: https://redpen.io/p/xn00ffb06d3af74c9f

**Comment by cassiemc** [comment]
Yep that's better, thanks @natalieworth! Ready to go @HPaulJohnson 
(Natalie, fyi you can update the 'version' of the design on redpen from the gear icon next to the title)

**Comment by natalieworth** [comment]
@HPaulJohnson Final file links on google drive for jpegs and psd: https://drive.google.com/open?id=0B20-0lpP23c0eE80Y3MySTRpdG8

**Comment by HPaulJohnson** [comment]
Ugh. Comment from Jean at MoCo: 

>Hate to do this to you but any way to make the logo a bit larger? Content Services are saying that having a larger logo will make a better impact....

We could push back but I would prefer to just revert to the previous version, make the logo larger and call this one complete. 

@natalieworth possible to resend with larger logo?

**Comment by cassiemc** [comment]
Haha, yes let's just use the previous version. You had it right the first time @natalieworth!!! :)

**Comment by natalieworth** [comment]
Haha, @HPaulJohnson here's the link to the previous version: https://drive.google.com/open?id=0B20-0lpP23c0eE80Y3MySTRpdG8

**Comment by HPaulJohnson** [comment]
Approved! Should be live within 72 hours.

**Comment by cassiemc** [comment]
WOOHOO!

**Comment by Saallen** [comment]
Yahhhh :dancer:
