### ISSUE TITLE
Style guide needed for 2015

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#160]
This is a place marker issue for the time being.
I am building a design brief for Ravensbourne students to create a wayfinding system for this years festival. Everyyear they create really cool and diverse systems for their degree show so I am giving them the opportunity to design a system for us.
As I build the document I realise that I needed an updated style guide for this year for assets and any other design briefs we build.

**Comment by hannahkane** [comment]
Has this been duped by #222?

**Comment by Saallen** [comment]
Yes so will close this
