### ISSUE TITLE
Make changes to 'Submit a proposal' form

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#161]
We've finalized the changes from the discussion in #156.

**Comment by Saallen** [comment]
Keeping changes to form simple-
First change : adding extra detail to one question.

How do you see that working?
Outline your agenda for this session in 150 words. Please also describe the format of the session, such as workshop, fireside chat or other.

**Comment by Saallen** [comment]
Second change can you please remove audience and mode from the drop down menus.
Then expand the themes mulit choice:

'Themes - Please indicate the ideas which best represent your session'
Please then give these as options on a check box list with add your own option at the end
![screen shot 2015-08-13 at 19 23 51](https://cloud.githubusercontent.com/assets/10194015/9258052/201b3070-41f1-11e5-89f3-2929e353f763.png)

**Comment by Saallen** [comment]
Can I get a ping when we push this to the website as I will need to contact those who have already submitted a session to make them aware of the changes :8ball:

**Comment by ScottDowne** [comment]
@Saallen Should be on prod for tomorrow morning.

Question, how do you vision people people actually updating their proposal if they want to make changes, or do you suggest they submit a new one?

**Comment by Saallen** [comment]
I envision those who have submitted being given the option to add more themes to their section through emailing me...not a great vision but one that will work.

**Comment by ScottDowne** [comment]
@Saallen Ah, I get it. I think in general opening a line of communication is good.

**Comment by ScottDowne** [comment]
@Saallen One this I want to confirm.

You said checkbox list, but the image looks like radio buttons.

The only difference is checkboxes can have multiples selected and radio buttons can only have one.

Do we want to allow people to select multiple themes?

**Comment by Saallen** [comment]
Check- yes lets allow people to select multiple themes :smile:

**Comment by ScottDowne** [comment]
@Saallen another question :p 

Is it optional or must at least one be selected?

**Comment by Saallen** [comment]
Must be at least one I think

**Comment by ScottDowne** [comment]
@Saallen You can try it out here https://mozillafestival-org-2015.herokuapp.com/proposals

**Comment by ScottDowne** [comment]
Its is not production yet, but IS plugged into the production proposal data, so if you make tests you can ensure it worked.

**Comment by Saallen** [comment]
Hi @ScottDowne thanks so much for pushing the changes so fast. :dash: 
Could I ask for three things to be changed though?
* Add the following text :'Themes - Please indicate the ideas which best represent your session, you can choose more than one from the list below"
* Can Youth be added to the drop down list?
* Storytelling and journalism sit under each other- could you shuffle them a bit? As they are similar themes but helpful in our organisation of the topics.This is a nice to have change but not high neccesary if a lot of work.

**Comment by ScottDowne** [comment]
@Saallen Updated

**Comment by thornet** [comment]
@ScottDowne hero! 

We just had a super quick review, and we hope a final edit for that last section on themes: 

**Which topics are relevant for your session? You can choose multiple items.**
Advocacy
Citizenship
Data
Inclusion
Economics
Environment
Ethics and Values
Journalism
Leadership
Open Practices
Place
Privacy
Science
Sustainability
User Control
Web Literacy
Youth

**Comment by ScottDowne** [comment]
@thornet @Saallen Do we still want other or was that removed?

**Comment by Saallen** [comment]
We would still love other @ScottDowne :bow:

**Comment by ScottDowne** [comment]
Perfect

**Comment by ScottDowne** [comment]
@thornet @Saallen Updated: https://mozillafestival-org-2015.herokuapp.com/proposals

**Comment by thornet** [comment]
HERO!

On Fri, Aug 14, 2015 at 5:36 PM, ScottDowne <notifications@github.com>
wrote:

> @thornet <https://github.com/thornet> @Saallen
> <https://github.com/Saallen> Updated:
> https://mozillafestival-org-2015.herokuapp.com/proposals
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/161#issuecomment-131152744>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by ScottDowne** [comment]
Sending this to prod... I'll update this ticket when it's done. You still have 10ish minutes to slam on the breaks.

**Comment by ScottDowne** [comment]
Should be live for most people, some are still getting updated, should take some time for it to be everywhere.

**Comment by Saallen** [comment]
:bear: Thanks @ScottDowne
