### ISSUE TITLE
Change header on 2014 site to point users to 2015 site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#168]
The current header for the 2014 MozFest site might be misleading to users who are looking for the 2015 site, and includes a link to a BSD sign-up form:

![screen shot 2015-08-18 at 3 56 51 pm](https://cloud.githubusercontent.com/assets/8389648/9345007/c78280e2-45c1-11e5-865d-0ff4eb5c8078.png)

Can we change the copy to be "MozFest 2015 will be on Nov 6-8" and the button copy to be "Visit the 2015 site" and have it link to the 2015 site, rather than the BSD list?

**Comment by mmmavis** [comment]
@ScottDowne @jbuck can either of you point me to the 2014 repo and advice how I'm supposed to push changes live?

**Comment by jbuck** [comment]
@mmmavis I converted it to a static site here: https://github.com/jbuck/2014.mozillafestival.org-static

I don't actually have a way for you to push changes live yet, sorry :disappointed:

**Comment by mmmavis** [comment]
@jbuck hah no worries, that matches my guess :wink:  What would be the easiest way for us to push some changes live?  Should I submit a PR against https://github.com/jbuck/2014.mozillafestival.org-static and you can help with deploying?

**Comment by jbuck** [comment]
Yeah, I think that's the best way to handle this. We're not making many
more changes to the 2014 site anyways

**Comment by mmmavis** [comment]
@jbuck PR is ready: https://github.com/jbuck/2014.mozillafestival.org-static/pull/1
