### ISSUE TITLE
Add sitemap.xml to improve search results

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#169]
We want internal pages (e.g. Call for Proposals, Tickets, Location) to appear in google search results. See, for example, how the 2014 site appears:

![screen shot 2015-08-18 at 4 07 41 pm](https://cloud.githubusercontent.com/assets/8389648/9345170/49509806-45c3-11e5-98c8-bc454e78a8f2.png)

I found this, in case it's useful: http://www.relishtraymedia.com/blog/bid/257788/SEO-Sitelinks-How-to-Get-Google-Subheadings-in-Search-Results

**Comment by mmmavis** [comment]
```bash
│   ├── about.jsx
│   ├── contact.jsx
│   ├── expect.jsx
│   ├── fringe-events.jsx
│   ├── guidelines.jsx
│   ├── home.jsx
│   ├── location.jsx
│   ├── proposals.jsx
│   ├── session-add-success.jsx
│   ├── tickets.jsx
│   └── volunteer.jsx
```

We'll need description for each of the pages on the site
- https://2015.mozillafestival.org/
- https://2015.mozillafestival.org/
- https://2015.mozillafestival.org/
- https://2015.mozillafestival.org/

**Comment by mmmavis** [comment]
We'll need description for each of the pages on the site

- https://2015.mozillafestival.org/about
- https://2015.mozillafestival.org/contact
- https://2015.mozillafestival.org/expect
- https://2015.mozillafestival.org/fringe-events
- https://2015.mozillafestival.org/guidelines
- https://2015.mozillafestival.org/home
- https://2015.mozillafestival.org/location
- https://2015.mozillafestival.org/proposals
- https://2015.mozillafestival.org/session-add-success
- https://2015.mozillafestival.org/tickets
- https://2015.mozillafestival.org/volunteer

@hannahkane do you know how could help write these page descriptions?

**Comment by hannahkane** [comment]
@Saallen - would you be able to provide a brief description for each page?

**Comment by hannahkane** [comment]
Best practice: under 150 characters for each description

**Comment by Saallen** [comment]
Yup- will dig in this weekend

**Comment by hannahkane** [comment]
@Saallen - any progress on this?

**Comment by Saallen** [comment]
I dropped the ball here. Will get done early next week-

**Comment by Saallen** [comment]
@mmmavis Started describing the pages but not sure what the actual ask is? Am I describing the pages or giving a synopis of what is on the page?

**Comment by hannahkane** [comment]
I would suggest we just use the first sentence of so from each page. I also don't think we need a description for every page. Here are my suggestions:

- https://2015.mozillafestival.org/about: Mozilla's annual, hands-on festival (affectionately known as MozFest) is dedicated to forging the future of the open Web. 
- https://2015.mozillafestival.org/home: Three days of building a truly global web together.
Come with an idea, leave with a community.
- https://2015.mozillafestival.org/location: This year, MozFest returns to Ravensbourne, a media campus in the heart of London. 
- https://2015.mozillafestival.org/tickets: Tickets are available for youth and adults
- https://2015.mozillafestival.org/contact: Please email festival@mozilla.org with your questions and suggestions!
- https://2015.mozillafestival.org/expect: MozFest is an annual celebration of the world’s most valuable public resource: the open Web.
- https://2015.mozillafestival.org/guidelines: The Mozilla Festival respects Mozilla's community participation guidelines.
- https://2015.mozillafestival.org/volunteer: Volunteers are integral to what we do at Mozilla, and MozFest is no different.

**Comment by Saallen** [comment]
Thanks @hannahkane- this is great.

**Comment by mmmavis** [comment]
things to implement

- [ ] generate sidemap.xml
- [ ] add per-page description via `<meta>` tag
- [ ] add Open Graph tags

/cc @Pomax

**Comment by mmmavis** [comment]
Ah I totally underestimated the work needed to generate sitemap.  After consulting and walking through my not working code with @Pomax I realized this wasn't as simple as what I expected it to be.  

@hannahkane we'll need to move this to the next heartbeat. (excuse me for my wrong time estimate) :no_mouth:

**Comment by hannahkane** [comment]
This no longer seems like a priority. @Saallen - are you still seeing evidence of people being on the wrong site?

**Comment by Saallen** [comment]
We have had a serious drop in people signing up for updates from the 2014 website in th last three weeks so that is really great
