### ISSUE TITLE
MozFest 2015 site: Complete UI work

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#17]
Driver: @edrushka
UI Designer: @adiladiladil
Informed: @cassiemc @iamjessklein @sallen @ScottDowne 

### Individual pages for UI
**First set, due May 8**
- [ ] [Home/landing] (https://github.com/mozilla/mozillafestival.org/issues/18)
- [ ] [About] (https://github.com/mozilla/mozillafestival.org/issues/19)
- [ ] [Location] (https://github.com/mozilla/mozillafestival.org/issues/20)

**Second set, due May 15**
- [ ] [Submit a proposal] (https://github.com/mozilla/mozillafestival.org/issues/21)
- [ ] [View proposals] (https://github.com/mozilla/mozillafestival.org/issues/22)

Reference documents:
- [Meta-ticket for the completion of the entire MozFest site] (MozillaFoundation/plan#374) 
- [UI kickoff etherpad] (https://etherpad.mozilla.org/mozfestkickoff)
- [Wireframes] (http://marvl.in/3e6ii4)
- [Sitemap] (https://redpen.io/ey62366033576eeca9)

**Comment by adiladiladil** [comment]
![mozfest home-01](https://cloud.githubusercontent.com/assets/11046943/7452116/39ebbef8-f227-11e4-801d-0f4044aab8f8.jpg)

**Comment by adiladiladil** [comment]
![mozfest ui-02](https://cloud.githubusercontent.com/assets/11046943/7454247/c5b1bad8-f23f-11e4-909f-0b4a89cf481c.jpg)
![mozfest ui-03](https://cloud.githubusercontent.com/assets/11046943/7454248/c5b2bd2a-f23f-11e4-99a1-6afc67c9c997.jpg)

**Comment by adiladiladil** [comment]
![mozfest ui-04](https://cloud.githubusercontent.com/assets/11046943/7455019/bf13299e-f246-11e4-9c5f-9555f62b7564.jpg)

**Comment by cassiemc** [comment]
Nice first passes @adiladiladil! Left some feedback on the redpens. 

@edrushka Were you going o file separate issues for each of these pages? I see this ticket getting unwieldy super fast.

**Comment by edrushka** [comment]
I already filed all the individual pieces of feedback in the tickets for each page. Let's continue that moving forward:
- [Landing] (https://github.com/mozilla/mozillafestival.org/issues/18)
- [About] (https://github.com/mozilla/mozillafestival.org/issues/19)
- [Location] (https://github.com/mozilla/mozillafestival.org/issues/20)

**Comment by adiladiladil** [comment]
Hi All,

Thanks for the great feedback and direction

redpen link:

https://redpen.io/p/po1ca9644b3ee45253

**Comment by adiladiladil** [comment]
![mozfest home ui-06](https://cloud.githubusercontent.com/assets/11046943/7587903/694c49cc-f887-11e4-8f2d-ce183eb0c8f3.jpg)
![mozfest home ui-07](https://cloud.githubusercontent.com/assets/11046943/7587904/694cc384-f887-11e4-9ab3-55831b9be286.jpg)
![mozfest home ui-02](https://cloud.githubusercontent.com/assets/11046943/7587901/694b17d2-f887-11e4-9e5c-1db9f0783813.jpg)
![mozfest home ui-03](https://cloud.githubusercontent.com/assets/11046943/7587902/694c370c-f887-11e4-9944-cabad82856a7.jpg)
![mozfest home ui-04](https://cloud.githubusercontent.com/assets/11046943/7587905/694d4d40-f887-11e4-94c9-1da7cfa7c8bd.jpg)
![mozfest home ui-05](https://cloud.githubusercontent.com/assets/11046943/7587900/694adc5e-f887-11e4-8fb6-a75df58d0770.jpg)
![mozfest home ui-01](https://cloud.githubusercontent.com/assets/11046943/7587906/69531d1a-f887-11e4-98f0-3faf736c9f2a.jpg)

**Comment by ScottDowne** [comment]
Are these done enough for me to start?

They look done enough for me to start :D

**Comment by edrushka** [comment]
@ScottDowne we're still adjusting the footer, but if you want to get a jump on the rest of the homepage, I think that's fine. Connecting with @KevZawacki on final copy today (homepage will be simple).
