### ISSUE TITLE
Analytics - 

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#170]
Hey @ScottDowne did we set up any analytics on the Mozfest site to see where the traffic is coming from?
Just curious

**Comment by ScottDowne** [comment]
No, but we should.

**Comment by ScottDowne** [comment]
@adamlofting question, is there anything on the google analytics side that needs to be setup for this to work?

**Comment by adamlofting** [comment]
We already have a profile setup, so you can use this tracking code:

```js
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35433268-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by ScottDowne** [comment]
@adamlofting https://github.com/mozilla/2015.mozillafestival.org/pull/171/files r?

**Comment by ScottDowne** [comment]
It's building on production now. @adamlofting when do you think we'll have any interesting data? Would you say Monday?

**Comment by adamlofting** [comment]
'Interesting' is all about context :stuck_out_tongue_winking_eye: We have data coming in now though.

@Saallen can you check if you have access by logging in here: http://www.google.com/analytics 
I'm not an admin on that site, but if you don't I'll file a bug to get you added.

**Comment by Saallen** [comment]
Hey @adamlofting I am unable to access this page

**Comment by adamlofting** [comment]
@Saallen I've filed a bug to request access for you: https://bugzilla.mozilla.org/show_bug.cgi?id=1198195

**Comment by cassiemc** [comment]
@Saallen @adamlofting Can we close this?

**Comment by adamlofting** [comment]
:+1:
