### ISSUE TITLE
September 7: Closing the Call for Proposals

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#172]
On Monday at 9pm UTC the call for proposals closes.
The form should close.
Not sure how to execute this or what should be seen on the page.
any ideas @ScottDowne @hannahkane ?
We could just have the Google standard- this form is now closed

Second side to this is to change the URL - so that Space Wranglers and Pathways can still submitt to the form for another two weeks. I think I can do this on my side.

**Comment by hannahkane** [comment]
I don't know what would happen to https://2015.mozillafestival.org/proposals if we just changed the url. I think we probably need to actually un-embed the form from that page. Is that right, @ScottDowne?

I can ask @mmmavis to do this on Monday (since @ScottDowne is on the Fundraising team). (Note: this is 2pm MavisTime :))

We should replace the form with a message that the Call for Proposals has been closed. 

We'll also need to replace the Call for Proposals CTA on the homepage. Is there a different CTA we should be promoting?

**Comment by ScottDowne** [comment]
Sounds like we need a bit of design guidance, more than dev. It's not hard to swap in some content on the homepage, or update the /proposals link to say it's ended and thank everyone or something?

**Comment by ScottDowne** [comment]
Thanks for putting this on my radar, it previously wasn't.

**Comment by Saallen** [comment]
@hannahkane presently the CTA once the call closed will just be volunteer and tickets. We dont have another one unless its contact the team. We could just unembed the form and have note that says - Thanks for submitting , the Call fir Porposals is now closed. we will be reviewing all proposals for the next 3 weeks. We will contact eveyone before the end of September to let them know about their proposal. If you have any questions,please contact the team at festival@mozilla.org.- Copy might not be 100% right.

**Comment by Saallen** [comment]
@hannahkane its Bank holiday in the UK today but I will be monitoring github to see if I can be of any help so dont be afraid to ping me here or skype

**Comment by hannahkane** [comment]
I'd suggest:

Thanks for your interest in MozFest!  The Call for Proposals is now closed. We will be reviewing all submissions over the next three weeks. If you submitted a proposal, we will contact you before the end of September to let you know. If you have any questions, please contact the team at festival@mozilla.org.

Does that work, @Saallen ?

**Comment by hannahkane** [comment]
Also, updating ticket title to reflect pushed-back deadline

**Comment by Saallen** [comment]
:+1: looks good thanks @hannahkane

**Comment by Saallen** [comment]
Hi- can we close the Call for Proposals page today ?
I want the open call to be closed but access to the form still possible through the URL

Thanks Sarah

**Comment by ScottDowne** [comment]
I would suggest we decide on a new url to allow access to the form, and the old /proposals url should remain with no form and a mention about proposals being closed.

That way anyone with a bookmarket url or something won't get a working form or won't get a blank page.

**Comment by Saallen** [comment]
Good thinking @ScottDowne :tophat: I like that purposal

**Comment by mmmavis** [comment]
@Saallen [Proposals page](https://2015.mozillafestival.org/proposals) has been updated! You can still find the form via https://2015.mozillafestival.org/proposals-2015
