### ISSUE TITLE
Call for Proposals - Removing old deadline from the form

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#173]
Since we are extending the deadline is it possible to remove the old date from the form and update to the new date @hannahkane 
Don't want to start the comms around the new date until the page is refreshed.

**Comment by hannahkane** [comment]
@Saallen - do you mean the text in the header of this page? https://2015.mozillafestival.org/proposals

**Comment by Saallen** [comment]
Yes- The one line that says this form will close on the 31st of august at 9:00pm UTC.

**Comment by Saallen** [comment]
Hi @hannahkane is there any update on the removal of the old date from the website page and updating to the new date?

**Comment by hannahkane** [comment]
So sorry, @Saallen. I somehow missed that this was needed before Monday, and I had mistakenly grouped it in with the Monday tickets. Will see if we can get this done today.

**Comment by mmmavis** [comment]
fixed.
