### ISSUE TITLE
Moving proposals from Google Docs to Github

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#174]
We will move all proposed sessions from a Google Spreadsheet into Github Issues. This will allow us to curate and review the sessions with the program team. 

The session data in the spreadsheet will be migrated to this repo's issues: https://github.com/mozilla/mozfest-program/issues

Each Github Issue will be one session. Each issue should include the following information, which is available in the spreadsheet: 

- [ ]  Faciltator's name
- [ ]  Session description
- [ ]  Session agenda

I have questions around how to link github issue to faciliators contact details for SW contact and facilitation @hannahkane @thornet @ryanpitts 

- [x] Where do we store the facilitators contact detail for each proposal?
- [x] How do we faciliate the natural conversation of successful facilitators and SW on github to work together?

**Comment by hannahkane** [comment]
As discussed on today's call, it will be up to the SWs to facilitate communication with facilitators. They can invite them to join github to discuss issues there, or they can communicate via email.

**Comment by hannahkane** [comment]
Also, it looks like 48 of the session proposals have already been moved over. Were you wanting to do a mass import of the other sessions? Can we overwrite the 48 that are there, or has there been important conversation on those tickets that we need to retain?

**Comment by Saallen** [comment]
Hi- Those are Space and Pathway tracking sessions- I moved two sessions only from the proposals doc as a test. So we need to move all proposals over- 
Do you know who will be leading this migration @hannahkane ?
Are we able to do this migration today?
Can I chat with the dev who is leading this voodoo magic?

**Comment by hannahkane** [comment]
@mmmavis is leading on this. @mmmavis - possible to share an update here before end of day? Thanks!

**Comment by mmmavis** [comment]
Aiming to have this done by today, if not, early tomorrow.

I'm able to fetch data from the Google Spreadsheet and post issues to Github.  Now it's a matter of tying these two pieces together.  Gonna do some experiments under my personal repo first.

**Comment by thornet** [comment]
Thanks so much, @mmmavis! This rocks. Mind giving us a shout when it's done? We're planning to demo it today with the wrangler team.

**Comment by mmmavis** [comment]
Gonna start batch posting now.  Be ready for hundreds of GitHub notification. :smile:

**Comment by thornet** [comment]
We're bracing ourselves.

**Comment by Saallen** [comment]
Whoop . Go mavis!!

**Comment by mmmavis** [comment]
Done!  Everything up to Row445(Melissa's Privacy Bar) has been imported.  Rows are marked as "Don't Migrate" are ignored by the migrator.

One note, since we were batch uploading to Github async... issues didn't get entered in perfect order. (e.g., Row20 might get entered as a ticket before Row19).

Go team! :dancers: :dancers: :dancers:

**Comment by hannahkane** [comment]
Hooray! Every email notification was like a little message of joy. :) (but I'm glad the flood has ended)

@Saallen and @thornet - are we good to close this ticket?

**Comment by thornet** [comment]
THIS IS THE BEST THING OF ALL TIME!

Looks ready for me to close.

Note: we have some late submissions via another form. Sarah has the
details, but we may need to do another migration batch next week. Shouldn't
be many.

On Thu, Sep 10, 2015 at 10:04 PM, hannahkane <notifications@github.com>
wrote:

> Hooray! Every email notification was like a little message of joy. :) (but
> I'm glad the flood has ended)
>
> @Saallen <https://github.com/Saallen> and @thornet
> <https://github.com/thornet> - are we good to close this ticket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/174#issuecomment-139364980>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by hannahkane** [comment]
woohoo!
