### ISSUE TITLE
Call for Proposals- New URL

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#175]
Post 7th of September the Open Call for Proposals will close and we will no longer link it to the website. However I will need to still access the form.
Is there a smart way to allow this form to still function without closing it or do you think just removing the link to the website is sufficient? @hannahkane 
I just remember last year we needed to change the URL to continue to keep the form open

**Comment by mmmavis** [comment]
Done! Find the form on https://2015.mozillafestival.org/proposals-2015 instead :wink:

**Comment by Saallen** [comment]
Hi @mmmavis if I want to close this form can I just do this the normal way I close a google form? 
Via the form its self?
