### ISSUE TITLE
Implement "Spaces" page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#176]
Design ticket: #193

**Comment by hannahkane** [comment]
@Saallen - would it be possible to have this content finalized during the September 25th heartbeat?

**Comment by cassiemc** [comment]
Can you clarify what 'map out each space' means? Wondering if that means another digital asset or if that is more a planning thing. @Saallen @hannahkane

**Comment by cassiemc** [comment]
Also, how many spaces are there?

**Comment by Saallen** [comment]
Yes- I will have the content for the 25th of Sept @hannahkane 
@cassiemc - mapping out spaces refers to adding Space descriptions to the website and introducing the teams who run each space.  We have 8 spaces in total. 
There is a design request for Space Icons- similar to the Icons for Tracks.
This is the 1st item listed on the [asset request list] (https://docs.google.com/document/d/1luP9kJ2QlLGHpbAjCEyOf6oBjvJBeWk966gRUHFDtP0/edit) for 2015

**Comment by thornet** [comment]
For reference, the description of spaces looked like this on the website
last year:

http://2014.mozillafestival.org/tracks/

On Wed, Sep 9, 2015 at 3:44 PM, Sarah Allen <notifications@github.com>
wrote:

> Yes- I will have the content for the 25th of Sept @hannahkane
> <https://github.com/hannahkane>
> @cassiemc <https://github.com/cassiemc> - mapping out spaces refers to
> adding Space descriptions to the website and introducing the teams who run
> each space. We have 8 spaces in total.
> There is a design request for Space Icons- similar to the Icons for Tracks.
> This is the 1st item listed on the asset request list
> <https://docs.google.com/document/d/1luP9kJ2QlLGHpbAjCEyOf6oBjvJBeWk966gRUHFDtP0/edit>
> for 2015
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/176#issuecomment-138913142>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by cassiemc** [comment]
Are the track icons reusable from last year? (not sure if the content/subjects overlap)

**Comment by hannahkane** [comment]
Also curious to know if the icons are used in other formats. Are they, for example, going to be used in signage?

**Comment by hannahkane** [comment]
Added a design-specific ticket here: #193 
Changed this ticket to be about implementation specifically.

**Comment by mmmavis** [comment]
@hannahkane url pref?

**Comment by mmmavis** [comment]
note for myself:
for copy refer to https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit (the section about Spaces)

**Comment by hannahkane** [comment]
Summary of changes and decisions from call today:
 - [ ] use icons as we have them now; will replace once new ones are delivered
 - [ ] add "Sessions" to navigation
 - [ ] change this page title to "Sessions"
 - [ ] change copy at top of page to match newly edited copy from google doc
 - [ ] the word "Pathways" from that intro paragraph will link to the Pathways page (#247)
 - [ ] use H1 style to add the work "Spaces" above the Journalism space

**Comment by hannahkane** [comment]
@mmmavis  - let me know if any of the above list doesn't make sense ^

**Comment by cassiemc** [comment]
@adiladil Have you been able to provide svgs for the first set of icons? Don't have to be perfect for this...

**Comment by mmmavis** [comment]
we can also push this page **without** the icons and add them back first thing on Monday?

**Comment by hannahkane** [comment]
wfm. would love to push this page live today if we can.

**Comment by mmmavis** [comment]
page is live on https://2015.mozillafestival.org/sessions.  please file a new ticket for further page edits. :+1:

**Comment by cassiemc** [comment]
fantastic work @mmmavis

**Comment by thornet** [comment]
Beautiful! Thanks, all.

**Comment by Saallen** [comment]
What a cool page to wake up to this morning - thanks everyone

**Comment by mmmavis** [comment]
:tada: :dancers: :dancers: :dancers:
