### ISSUE TITLE
Build "Our Submission Process" page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#177]
- [x] [Design is happening here](https://github.com/mozilla/2015.mozillafestival.org/issues/227)

**Comment by hannahkane** [comment]
@Saallen - what's your deadline for all of the phase 2 tickets?

Is there a particular CTA associated with the session repo, or is it just for people's information? That is, are we asking people to participate in the curation in any way?

**Comment by Saallen** [comment]
@hannahkane Some of them I tried to add milestones dates where I knew them.Will we make this part of the agenda on Tues to map all dates out?
There is no particular CTA here for this issue- more of a place so people can see what has been submitted and be aware of how we are doing this.

**Comment by thornet** [comment]
This is where the session program info will be: https://github.com/mozilla/mozfest-program/issues

**Comment by hannahkane** [comment]
I feel like it would be a little surprising for users to have a link to the github repo without any context. I'd suggest we create a page with a short bit of copy describing our selection process. We can link to the repo from there.

Is someone able to write this copy this heartbeat (by Sept 11)?

**Comment by Saallen** [comment]
Yes- I can share something for Friday- we are making a github tutorial and I can utilize some content for here.

**Comment by Saallen** [comment]
I am adding my proposed paragraph here but we might need to hold this action as we work through the privacy questions.

Proposed introductory paragraph-

This year we're using Github to manage, review and curate sessions for Mozfest. This tool will allow us to better collaborate and coordinate across the program, as well as provide a record for how the program came together. 
Over the course of the month of September our Space Wranglers, the Space curators, will be revewing all proposals with the intension to choose the most suitable sessions which will align with their Space objectives. You can follow this process on our Github repo
Unfortunately not all proposals can be accepted as the weekend is just not long enough to showcase them all. Please do not be disheartened if your session is not shortlistened for this years fesival. All those who proposed a session will be offered a free ticket to attend the festival weekend.

**Comment by hannahkane** [comment]
Paragraph looks good. Will wait until we get the OK from you to push this page to production.

**Comment by hannahkane** [comment]
@Saallen - Any word on whether we can create this page yet?

**Comment by Saallen** [comment]
@hannahkane we would like to hold advertisng the page as of yet until we more of the curation done.

**Comment by thornet** [comment]
@hannahkane we'll be ready to promote the Github repo on Oct. 1

@KevZawacki would you mind helping with the accompanying copy? We want to say: "Hey, check out all the great sessions in the making for Mozfest." on the festival website and link to the Github repo.

**Comment by KevZawacki** [comment]
@thornet certainly, here are my tweaks to @Saallen's copy:

This year, we're using GitHub to manage, review and curate sessions for MozFest. GitHub allows us to better collaborate and coordinate across the program.

Over the course of September, MozFest's Space Wranglers will be reviewing all proposals and choosing sessions that best align with their Space objectives. You can follow this process on our [GitHub repo](https://github.com/mozilla/mozfest-program/issues).

Unfortunately, not all proposals will be accepted; the weekend simply is not long enough. But there's good news: everyone who proposed a session will be gifted a free ticket to the festival.

**Comment by hannahkane** [comment]
No longer blocked. Design is in #227.

url: /submission-process

Final copy: 
This year, we're using GitHub to manage, review and curate sessions for MozFest. GitHub allows us to better collaborate and coordinate across the program in an open fashion.

Leading up to the event, MozFest's Space Wranglers will be reviewing all proposals and choosing sessions that best align with their Space objectives. You can follow this process on our [GitHub repo](https://github.com/mozilla/mozfest-program/issues).

Unfortunately, not all proposals will be accepted; the weekend simply is not long enough. But there's good news: everyone who proposed a session will be gifted a free ticket to the festival.

**Comment by mmmavis** [comment]
i can work on this today

**Comment by mmmavis** [comment]
up on https://2015.mozillafestival.org/submission-process

**Comment by hannahkane** [comment]
w00t. Thanks, @mmmavis!!
