### ISSUE TITLE
Build Fringe Events Page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#178]
Design ticket is #194

cc @hannahkane cc@thornet

**Comment by hannahkane** [comment]
Mid-October for launch

**Comment by hannahkane** [comment]
@Saallen - Who is responsible for mapping out the Fringe events criteria and writing the content for the form? Can those two tasks be completed this heartbeat (September 11)?

**Comment by Saallen** [comment]
I will look at this later tonight @hannahkane

**Comment by Saallen** [comment]
I tried to find last years page but cannot access the wordpress admin site to references last years description but here is what I have so far- would love feedback from @KevZawacki @thornet 

Sample content- MozFest is about celebrating working in the open and sharing as a community. There are many great and innovative events taking place worldwide which aligne with this ethos and we would love to share these events with the wider communtiy.
 If you are running an aligned event independantly of the festival fill out our Fringe Event form and we will share the details on our Fringe Events page. 
How do you know its an aligned event?
Your event can be held anywhere around the world but must align with the MozFest ethos- open collabortory workshops or dicsussion focused on building tools and resources to keep the web, free and innovative. 

Insert basic google form to fill out - here is last years [form] (https://docs.google.com/a/mozillafoundation.org/forms/d/12OSCSYC0Dwjzk48xeiIF93acCgRKsKg750SJ1NloWqs/edit#)

**Comment by hannahkane** [comment]
@Saallen - some questions for you:

Assuming the page where people submit their events for consideration is also the page where users can see the approved events. Is that right?

You mentioned over Skype that we need an approval step, right? Meaning we can't just put all submitted events directly onto the page, we first need someone to OK them?

**Comment by KevZawacki** [comment]
@Saallen Great copy! Some minor tweaks:

MozFest is about working in the open and sharing ideas with the greater community. There are several innovative events taking place around the world with this same philosophy, and we would love to align them with MozFest.

If you are running an aligned event independent of the festival, please fill out our Fringe Event form. We will share your event details on our Fringe Events page.

How do you know if your event is a Fringe Event? It can be held anywhere in the world, but must align with the MozFest ethos: open, collaborative workshops or discussions focused on building tools and resources to keep the Web free and innovative.

**Comment by Saallen** [comment]
@hannahkane Yes- i think it would be fine to have the two pieces on the same page.
@marcwalsh will be approving all events

@KevZawacki thanks Kevin- this looks great :jack_o_lantern:

**Comment by hannahkane** [comment]
No longer blocked

**Comment by mmmavis** [comment]
@hannahkane @Saallen @cassiemc 
Any thoughts on the page url? Do we plan to add a link to the nav bar?

**Comment by hannahkane** [comment]
I'd say /fringe for the url. 

Not sure at what level the link should live. I'm wondering if it would fit at the same level as "Get in touch," "Tweet," and "Volunteer," since it's another action / way to get involved. That would require an icon, and a CTA like "Attend a Fringe Event".

Thoughts on that idea @Saallen @cassiemc ?

**Comment by cassiemc** [comment]
wfm @hannahkane!

**Comment by Saallen** [comment]
That sounds good to me

**Comment by Saallen** [comment]
Hey @hannahkane do I need to build a new form to collect fringe info? or will we use last years? I ask as I think it could be good to ask some folks to fill out the form now so we open the page with some fringe events on there :palm_tree:

**Comment by cassiemc** [comment]
Maybe @mmmavis can help us figure out a best process here @Saallen, since @hannahkane is at a work week this week. Good idea to pre-populate a few.

**Comment by mmmavis** [comment]
oops sorry, didn't see ur question until now @Saallen 

> Hey @hannahkane do I need to build a new form to collect fringe info? or will we use last years? I ask as I think it could be good to ask some folks to fill out the form now so we open the page with some fringe events on there :palm_tree: 

The fringe page is WIP and hopefully can be done by tomorrow.  I'll create a form for you to send around for now later today. :grin:

**Comment by mmmavis** [comment]
@Saallen here's the form: https://docs.google.com/a/mozillafoundation.org/forms/d/1XCjIF3ptc4XAl7ql-pkhhIDc7dERYshrLHOFZgjdIUY/viewform

**Comment by mmmavis** [comment]
@cassiemc 
re: [Hannah's comment](https://github.com/mozilla/2015.mozillafestival.org/issues/178#issuecomment-146664063): we will need an icon for the new CTA. Do you know who I should talk to to get the icon?

**Comment by mmmavis** [comment]
@cassiemc oops, my bad! didn't realize the icon was provided in #257 :+1:

**Comment by cassiemc** [comment]
:+1:
