### ISSUE TITLE
MozFest 2015 site: Landing page UI

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#18]
Wireframe: https://marvelapp.com/3e6ii4
Footer: scroll down in marvelapp link

**Example functionality**
- Full-screen video, text disappears
   - Good example: http://mic.com/articles/109570/watch-the-doritos-ad-frito-lay-doesn-t-want-you-to-see
   - Another good example: http://creativemornings.com/talks/nobu-adilman/1

**Content**
- Mozfest video: https://vimeo.com/125496299 pw: dosed (we can download via this link)

**Comment by edrushka** [comment]
First iteration of Home Page: https://redpen.io/vsbc573f9391df1f2b

Feedback from meeting:
- hero image needs more diversity
- need video play button
@saallen pls add feedback if you have any

**Comment by edrushka** [comment]
Some options for hero image (we can use these, but they aren't from video):
- https://www.flickr.com/photos/mozillaeu/15435620399/in/set-72157648895117706

**Comment by Saallen** [comment]
Does the hero image have to be from the Video?

**Comment by iamjessklein** [comment]
Yes, because it's not just the image, it's the actual video (it's playable).

**Comment by Saallen** [comment]
:candy:

**Comment by cassiemc** [comment]
I added another good example of text on top of the video disappearing on Play: http://creativemornings.com/talks/nobu-adilman/1

**Comment by iamjessklein** [comment]
:heart: that example. Clean, and to the point.

**Comment by edrushka** [comment]
Latest version: https://redpen.io/hn0f7746976db58171 
Comments from today's call:
- Erika is weirded out by red colour but Sarah is good with it :)
- Maybe try just logo in footer@cassiemc any comments?
Anything to add, @cassiemc?

**Comment by edrushka** [comment]
Latest version: https://redpen.io/zx038080198c5ef124

To do:
- @cassiemc to give @adiladiladil an example of a good footer we like
- add colour to footer icon

**Comment by cassiemc** [comment]
Here's the very quick footer mockup you can use as a basis, @adiladiladil. http://cl.ly/avz1
(notes: perhaps dynamic photo feed, more colourful background, more hierarchy within the links, we may not need donate in the footer, to confirm)
Waiting for final footer content from @edrushka / Sarah

**Comment by Saallen** [comment]
Ref : MozFest 2015 : Footer links #30
