### ISSUE TITLE
Design UX/UI changes to Schedule app

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#180]
The design as is is here: http://ryanpitts.github.io/mozfest-test-schedule/

We need to make the following UX/UI changes:
 * Add Facilitator field to both card view and detail view of sessions
 * Add Pathway field to both card view and detail view of sessions
 * Change "Room" field label to "Space" 
 * Add Friday to available filters
 * Provide views by Space and by Pathway
 * Update look and feel to match MozFest site

**Comment by hannahkane** [comment]
mid or late october

**Comment by hannahkane** [comment]
@Saallen - can you please clarify the data you want to see on each session? So far I can see in Ryan's app:
 * the title of the session
 * the time and day
 * the room/location/space
 * track (I know we're not using tracks...so...what would this be called?)

Additionally, on the session detail page (when you click to view a particular session), I also see the full session description.

What needs to be added to the above list?
 * Facilitator
 * Pathway
 * Learning Objective

Are those right?

**Comment by hannahkane** [comment]
Modified this ticket to specifically be about design. Updated first comment to reflect recent Skype call with @Saallen

**Comment by SpikeUK** [comment]
Could we please consider associating a QR code to each session - providing the facility for attendees to get full details on their hand-held devices by scanning code?

**Comment by hannahkane** [comment]
Hey @SpikeUK - I want to make sure I understand the request. Can you describe the workflow you imagine? Is it for during the event itself? Would the QR codes be posted somewhere in the physical space for attendees to scan?

**Comment by cassiemc** [comment]
#### Notes
* Sessions can belong to more than one pathway
* Update 'space' on both card and detail views
* Spaces are thematic; 7 total. Pathways are more of a persona, that include sessions from different spaces.
* We also need spaces to see all pathways, and all spaces. These should all be filters at the top. Maybe need to evaluate how the filters are working -- how do you clear. 
* Update look and feel to match MozFest site
  -  update colour palette & button styles & fonts
  -  update logo

#### Questions
* How many pathways? 10ish or 40ish?
* Why are different sessions different colors (yellow vs. blue) - we'll need to update this
* Can the default tab be 'all' until the day of the event, then default to that current day?
* Any limitations with updating the styles?

**Comment by ryanpitts** [comment]
Can answer some of the questions:

_* Why are different sessions different colors (yellow vs. blue) - we'll need to update this_

The default length for sessions at SRCCON is 1 hour, but we generally have a handful that run longer than that (90 minutes to a full 2.5 hours). The alternate color (blue in this case) is just to call out sessions that run longer than default; those sessions also get "ghosted" into the next session block to signify that they'll still be running, or if to clue you in that it actually starts earlier if you happen to be skimming that part of the day on the schedule. (Maybe easier to see this effect using real data, with fewer total sessions: http://schedule.srccon.org/)

I'm generally _strongly_ against trying to use color to impart meaning, but this case (with only 2 categories) felt like it worked reasonably well. The alternate color is just there to draw your attention to the fact that "hey, something's different about this session."

Not sure how this would translate with MozFest schedule needs, but that's why the two colors exist on the demo :)

_* Can the default tab be 'all' until the day of the event, then default to that current day?_

Yep, that'd be an easy update to https://github.com/ryanpitts/mozfest-test-schedule/blob/gh-pages/js/schedule.js#L266-L283

**Comment by cassiemc** [comment]
Thanks so much @ryanpitts, you had answers way faster than we anticipated!

**Comment by ryanpitts** [comment]
GitHub email notifications ftw!

**Comment by SpikeUK** [comment]
@hannahkane Yes, that what was I was thinking about. I do not know what @Saallen was plotting for signage but was thinking about maybe linking this to electrons via QR codes.
Just something for possible discussion.

**Comment by Saallen** [comment]
Hi @cassiemc 
I can help answer those additional questions
* There are 8 Spaces in total
* Currenty we have 21 spaces and I expect one more to be submitted. Some of these pathways  ( 4 approx) are what we called solo pathways- not tied to any space
* I dont think there are any restrictions to updating styles

Hi @SpikeUK can you map out how you see this QR code working and the benefits it will offer the audience? Will these codes highlight where the session is within the building or just additional info if the audience scans the code?

**Comment by adiladiladil** [comment]
https://redpen.io/jn4056df4f0d941bd9

Here is the redpen link for people to start giving feedback

**Comment by adiladiladil** [comment]
Thanks for all the great feedback on redpen!
I'm going through those changes and mocking up some of what we spoke about yesterday during our call

**Comment by hannahkane** [comment]
@Saallen - just wanted to confirm an assumption. Will sessions have specific start times? I kind of got the impression during today's MLN team call that maybe they don't? If that's the case, that seems potentially very confusing for attendees!

**Comment by hannahkane** [comment]
I think we can close this ticket. @adiladil @cassiemc - do you agree?

**Comment by cassiemc** [comment]
Yes! :bomb: Close this sucker!

**Comment by cassiemc** [comment]
@adiladil can you please past the final annotated comps to this bug and close?

**Comment by adiladiladil** [comment]
![mozfest 2016 mobile scheduler-01](https://cloud.githubusercontent.com/assets/11046943/10107431/f9a810fc-6388-11e5-8806-c35227528655.jpg)
![mozfest 2016 mobile scheduler-05](https://cloud.githubusercontent.com/assets/11046943/10107435/f9ad9d6a-6388-11e5-9d72-7d2d54989571.jpg)
![mozfest 2016 mobile scheduler-06](https://cloud.githubusercontent.com/assets/11046943/10107433/f9aca87e-6388-11e5-89ae-a8f8a3d436a4.jpg)
![mozfest 2016 mobile scheduler-03](https://cloud.githubusercontent.com/assets/11046943/10107432/f9ab83b8-6388-11e5-9d91-2f9730637abd.jpg)
![mozfest 2016 mobile scheduler-04](https://cloud.githubusercontent.com/assets/11046943/10107436/f9aebdf8-6388-11e5-86f2-d06a2104c698.jpg)
![mozfest 2016 mobile scheduler-02](https://cloud.githubusercontent.com/assets/11046943/10107434/f9ada288-6388-11e5-8c5d-b528a30ad891.jpg)
![mozfest 2016 mobile scheduler-07](https://cloud.githubusercontent.com/assets/11046943/10107437/f9b244fa-6388-11e5-9153-3d6366ac4837.jpg)
![design-annotations-imported-01](https://cloud.githubusercontent.com/assets/11046943/10107455/1deef49e-6389-11e5-8431-1f4e0d6aba41.jpg)

**Comment by mmmavis** [comment]
@adiladil I couldn't find the .ai file in my inbox. Would you mind sending it to me again? Thanks! :dancer:

**Comment by mmmavis** [comment]
@hannahkane  @cassiemc @Saallen 

not sure if this was discussed already - do we plan to put "location" (eg., room number) on the Schedule app as well?

**Comment by hannahkane** [comment]
Yes, we should put "Location" on the app.  @saallen - will every session's location be related to the Space it's in. For example, if something is in the Youth Zone space, can we assume its location will be "2nd Floor" or something like that, or will there be exceptions to that rule?

**Comment by adiladiladil** [comment]
@mmmavis emailing you the AI file now

**Comment by cassiemc** [comment]
@hannahkane @Saallen This came up when @edrushka and I were talking about wayfinding yesterday. Will likely have more details later today, but it would be soooo good to be able to put the actual room number as well as the floor in the app schedule.

**Comment by thornet** [comment]
+1 to adding room number / name in addition to floor number. In Ravensbourne, there's is a mix of room numbers and names. For example: 

Big Space, 4th Floor
107, 1st Floor
Walker Space, Ground Floor

Also, for each session, will a user be able to see all the pathways it's a part of? i.e. one session may be in 3+ pathways.

**Comment by hannahkane** [comment]
I think the design will allow for multiple pathways, perhaps just comma separated?
