### ISSUE TITLE
Messaging for when tickets are all sold out

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#182]
- [ ] Remove "TICKETS" from header nav
 - [ ] remove buttons on /tickets page
 - [ ] add copy to /tickets. "Tickets to attend MozFest 2015 are sold out! However, you can still participate remotely (link to /remote page). We hope to see you in 2016!" 
 - [ ] replace copy and button on homepage with same text as above

**Comment by hannahkane** [comment]
Suggestion: 
 - [ ] I'd suggest we keep the link to /tickets in the navigation though we might add "(Sold out!)," so people know
 - [ ] remove buttons on /tickets page
 - [ ] add copy to /tickets. Suggested text: "Tickets to attend MozFest 2015 are sold out! However, you can still participate remotely (link to /remote page). We hope to see you in 2016!" 
 - [ ] replace copy and button on homepage with same text as above

**Comment by hannahkane** [comment]
hmm...Remote participation CTA doesn't work if we're not going to have that page until November. Is there another CTA we can offer? Or should we just say, "See you in 2016!"?

**Comment by cassiemc** [comment]
@hannahkane What about a link to the Fringe events page? Not sure when that will be done in dev.

**Comment by hannahkane** [comment]
@cassiemc - yes, I think the Fringe events page could work while we wait for the Remote participation page, though I think the Remote page is more appropriate. @Saallen - any chance we could finalize the content for the Remote page earlier?

**Comment by Saallen** [comment]
Yes- I am going to loop chad in now

**Comment by hannahkane** [comment]
Removing from this milestone. Will put back when tickets are sold or nearly sold out. @Saallen - can you provide an update on the tickets remaining?

**Comment by Saallen** [comment]
We are just under half way there currently

**Comment by hannahkane** [comment]
@Saallen - how are we doing now?

**Comment by Saallen** [comment]
We have 100 tickets left :) :ticket:

**Comment by SpikeUK** [comment]
@Saallen \o/ brilliant going!! \o/

**Comment by hannahkane** [comment]
Woohoo! When do you expect we'll sell out and will need to remove the section from the site?

**Comment by cassiemc** [comment]
@Saallen update?

**Comment by hannahkane** [comment]
@Saallen - are tickets still available?

**Comment by hannahkane** [comment]
I'd suggest we get this PR ready to go, since it's likely to happen soon. @mmmavis - possible to get this ready?

**Comment by hannahkane** [comment]
I think we should still do this. Updated the first comment to say we should remove "TICKETS" from the header nav entirely, since this MozFest has passed.
