### ISSUE TITLE
By Oct 16: Change messaging when all volunteers places are filled

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#183]
Changes are to the /volunteer page.

Replace Ticket-shaped button with the following copy: "Thanks for your interest. All Volunteer roles have now been filled."

**Comment by hannahkane** [comment]
Changes are to this page only, right? https://2015.mozillafestival.org/volunteer

Suggest:

Keep all copy the same, but replace the button at the bottom with "Thanks for your interest! All of our volunteer roles have been filled at this time."

That work, @Saallen?

**Comment by SpikeUK** [comment]
Fine with me too @hannahkane - thank you

**Comment by Saallen** [comment]
Thanks @hannahkane Hannah- maybe we could add- "You can still attend the festival by registering for a ticket" or is this over kill?

**Comment by hannahkane** [comment]
@Saallen - I think we guessed that tickets would be sold out before volunteer roles filled. Is that not true?

**Comment by SpikeUK** [comment]
Of the tickets 'sold' no more than 40% will actually turn out to really be volunteers. The rest are not really understanding that these are LOCAL roles. Of the 211 tickets sold only 69 are actually from the UK. This is not an exact measure but is a good indication.

**Comment by Saallen** [comment]
@hannahkane Last year we sold out on the ticket page around the same time as the volunteer page filled. However there is no science here and is anyones guess which action fills first

**Comment by hannahkane** [comment]
OK, well, we'll cross that bridge when we come to it then! :)

**Comment by Saallen** [comment]
THANKS :bow:

**Comment by hannahkane** [comment]
@mmmavis - can you please land this ticket some time this week, per MozFest team request? Thanks!

**Comment by mmmavis** [comment]
live on http://2014.mozillafestival.org/volunteer/ :tada:

**Comment by hannahkane** [comment]
Nice! Thanks. :)

**Comment by SpikeUK** [comment]
Thank you @mmmavis ! Thank you @hannahkane ! :dancer:

**Comment by mmmavis** [comment]
:hamster:
