### ISSUE TITLE
  MozFest 2015 site: About page UI

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#19]
Wireframe: https://marvelapp.com/3e6ii4#5248779

**Example functionality**
- Veritical layout of timeline: https://about.canva.com/

**Content**
- @saallen should we reuse the same About copy from last year for now?

**Comment by Saallen** [comment]
Yes- Only alteration at present is to remove Mark from the list of program team members for the time being

**Comment by edrushka** [comment]
First iteration: https://redpen.io/jaa15fc8544f29e6cc

- need to decide if we want map direction (cleaner, slicker) or post-it note direction (hands-on, friendlier). @Saallen your thoughts?

**Comment by edrushka** [comment]
@adiladiladil - we decided to go with the Post-it note version. Cassie put some design feedback in the Red pen.

**Comment by edrushka** [comment]
Latest version: https://redpen.io/wqd5924723487af6ca
Comments from today's call:
- Love it!

Anything to add @cassiemc? Sarah emailed Adil photos to try in the boxes.

**Comment by edrushka** [comment]
Latest version: https://redpen.io/fo7faaa54c582f179f

To Do:
- explore some different treatments for photos
-- circular matte
-- perhaps some original drawings
-- perhaps some infographics

**Comment by edrushka** [comment]
Need:
- hero banner image
- photos for timeline
- drawings for timeline
