### ISSUE TITLE
Design page for Space descriptions and Space Wrangler bios

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#193]
There are 8 "Spaces" for this year's MozFest (these are similar to "tracks," and each "Space" corresponds both to a specific theme and to a physical location). We need a page on the site that describes each space, and provides information (name, twitter handle, and possibly short bio) about the "Space Wranglers" (volunteers and staff in charge of curating that Space).

For reference, this is the comparable page on last year's site: http://2014.mozillafestival.org/tracks/

**Comment by hannahkane** [comment]
@Saallen - is October 8 okay for a final copy deadline?

**Comment by Saallen** [comment]
@hannahkane Adding copy here : [Space Decriptions] (https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edit#)
@KevZawacki could you review what we have and make suggestions for copy changes?

**Comment by Saallen** [comment]
Thinking about numbers this year with a team of 53 strong - bios might over take the page. Could we organise a blog post form each space with link outs  to bios from there? I want to acknowledge this group but unsure of the best platform

**Comment by KevZawacki** [comment]
@Saallen Sure -- will take a look Monday.

**Comment by Saallen** [comment]
@KevZawacki should I ask SW to start writting blog posts we can use?

**Comment by KevZawacki** [comment]
@Saallen 8 blogs is definitely easier to digest than 53 bios. Where would these live -- on the MozFest website?

**Comment by Saallen** [comment]
@KevZawacki Would we be able to out them on the Mozilla blog and tweet links to them on the @mozillafestival twitter acccount? I dont think we have the bandwidth to make a new page on the website.

**Comment by KevZawacki** [comment]
@Saallen Sure, we can do that. We can also make a separate "page" for these posts on blog.webmaker.org, so they have a dedicated space. For example, blog.webmaker.org/MozFest2015.

**Comment by hannahkane** [comment]
I think it's a little strange to link to another site. Why wouldn't we just put the bios on the MozFest site?

Are the Space and Pathway copy final?

**Comment by hannahkane** [comment]
Calling the blocked until we get word that the copy is final.

**Comment by cassiemc** [comment]
Like @hannahkane I suspect linking out to the bios might also be strange. @Saallen do you have any examples of the length of bios? I think the expected behaviour here is that the bios would be accessed by clicking on the session lead name. Maybe there is a simple expand/contract behavior we can put in, if the bios are too long. We can definitely explore these problems/solutions in the design phase.

**Comment by cassiemc** [comment]
@Saallen Can you provide a two sentence description of how the Spaces and Pathways work? Then @KevZawacki can help us refine? 

We can reuse this for #212 and may want to use it in the app as well #196 

cc @hannahkane @HPaulJohnson

**Comment by KevZawacki** [comment]
A quick description of how Spaces and Pathways work together would be very helpful. Thanks, @cassiemc & @Saallen.

@Saallen, I've started editing the Space Descriptions copy. I worry that given their length and unique voices, it will be hard for readers to digest. Thoughts on condensing each one and applying a singular voice? It's what we've done for the printed [Festival Guide](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit). We can use these same descriptions on the website.

**Comment by Saallen** [comment]
cc @thornet will provide the descriptive two lines for spaces and pathways.
cc @KevZawacki Yes- I like how you have reduced the spaces here. I have amended the layout on the Space and Pathways [description page] 9https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edit#) after consulting with @cassiemc .

**Comment by adiladiladil** [comment]
![mozfest spaces-14](https://cloud.githubusercontent.com/assets/11046943/10199134/52fc2412-676d-11e5-99e3-c7d251c7b6ef.jpg)

redpen here:

https://redpen.io/p/eo124585c346099979

**Comment by hannahkane** [comment]
Looks awesome, @adiladil. Two comments:
 * I think we need to explore a design solution for displaying the space wrangler bios. Could be, as @cassiemc suggested above, that we expand/contract on click or hover.
 * @KevZawacki - I'm finding the inconsistency in space names sort of distracting. Some don't have the word "space," others do, and then there's "Youth Space Zone," which feels hard to grok. Any suggestions for making a more cohesive list of space names?

**Comment by KevZawacki** [comment]
@hannahkane Good point. Let's not use "Space" in the title, as it's redundant. (Similarly, let's not use "Pathway" in titles.)

We can use the titles from [this doc](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit).

**Comment by thornet** [comment]
Draft text about spaces and pathways:

To help you get the most out of MozFest, we organize the program into two
formats: Space and Pathways.

Spaces are physical hubs, typically located on a single floor in the venue,
that explore a big theme throughout the festival.

Pathways are series of sessions, often appearing across several floors,
that are tailored for participants to learn a set of skills.




On Wed, Sep 30, 2015 at 6:59 PM, Kevin Zawacki <notifications@github.com>
wrote:

> @hannahkane <https://github.com/hannahkane> Good point. Let's not use
> "Space" in the title, as it's redundant. (Similarly, let's not use
> "Pathway" in titles.)
>
> We can use the titles from this doc
> <https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/193#issuecomment-144476470>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by adiladiladil** [comment]
![mozfest-spacess-14-14](https://cloud.githubusercontent.com/assets/11046943/10212273/c274e538-67ca-11e5-91cb-902d2f2a17a8.jpg)


Profile rollover detail
![mozfest-home-14a](https://cloud.githubusercontent.com/assets/11046943/10212274/c8d4103e-67ca-11e5-85b1-edc25674e25a.jpg)

**Comment by Saallen** [comment]
This looks really great @adiladil :tulip: 
The word space doesnt need to be in any titles of Space - the same for the pathways- I added to the description page to differenciate between the two. In the interest in saving time could the bios be left to accompany the blog posts.  I worry about collecting more data here when the SW are already very busy at this time with faciliators. So each blog post comes with a mini bio on the team and we could start collecting these next week. What do others think of this ? cc @thornet cc @hannahkane cc @KevZawacki -

**Comment by thornet** [comment]
Yes, let's roll these pages out and add bios later.

**Comment by KevZawacki** [comment]
@adiladil, design looks awesome! @Saallen, that plan for bios works for me. 

Sorry, a little confused on one point. Is the copy in the redpen a placeholder, or the final version? I thought we were using [this copy](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit)?

**Comment by adiladiladil** [comment]
all the descriptions are placeholder

from what i understand copy is still getting worked out

**Comment by cassiemc** [comment]
@adiladil can you throw the latest into redpen? Looks great, just a couple small things we could probably work out with @mmmavis in the build, even, if she is raring to get started.

**Comment by hannahkane** [comment]
I think we can pass this off to @mmmavis for the build now, and incorporate the final copy there. I also really like the bios design and would love to use it if @cassiemc approves. 

It's okay if we don't have all the bios; we can add them as we go. This ticket is more about approving the design than about having all the final copy.

**Comment by cassiemc** [comment]
Bios design wfm, but we should add a word limit so we don't get weird scroll bars. On mobile, it should show on tap, and close when tapped outside of box. Does it need an 'x' to close?

**Comment by hannahkane** [comment]
@Saallen - are we asking for space wrangler photos?

**Comment by adiladiladil** [comment]
Here is the link to add feedback

https://redpen.io/p/eo124585c346099979

**Comment by Saallen** [comment]
@hannahkane some spaces have 5 SW others two so in the interest of Space I think we can leave out the photos. Is there a word limit for bios? about to jump into my weekly call with them all

**Comment by cassiemc** [comment]
@adiladil Can you add the design with the bio popup please?

**Comment by hannahkane** [comment]
@Saallen - the photo looks pretty nice in the bio pop-up in Adil's latest design, and wouldn't be affected by the number of wranglers. Are you sure you don't want to include it? (Totally fine if you don't)

**Comment by cassiemc** [comment]
Agree with @hannahkane hannah, each bio will have its own separate bio box

**Comment by Saallen** [comment]
totally up to you on the design front- I just do not want to hold up the release of this page. Let me know lenght of bios and picture sizes required

**Comment by cassiemc** [comment]
@Saallen The length of bios should be ~60 words max. The picture size should be minimum 220px by 220px (so it looks good on retina, actual size will be 110 by 110px).

I think we can launch this section without the bios & pics then add them later if it is a blocker. Not sure why it needs to be up by Friday though, are we doing a big push out for this content?

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Do we have what we need for @mmmavis to get started on this?

**Comment by cassiemc** [comment]
I believe @mmmavis said she was going to get started once @adiladil sent her files, and she may have started already. Mavis you can go ahead and base any structure on the redpens here: https://redpen.io/of7dccf8f93a997570

**Comment by adiladiladil** [comment]
@mmmavis whats your email? i will send AI file

**Comment by cassiemc** [comment]
since I'm here... mavis@mozillafoundation.org (there's a pattern here... :)

**Comment by adiladiladil** [comment]
thanks cas..sending to @mmmavis now!

**Comment by mmmavis** [comment]
@adiladiladil @cassiemc thanks! I've received the .ai file :tada: 

Are we still wokring on the Space icons? just checking - if yes I can just export the icons from the .ai files for now

**Comment by adiladiladil** [comment]
@mmmavis still working on icons...so you can just use a placeholder for the icons til finalized

**Comment by mmmavis** [comment]
@adiladiladil mind attaching the hero banner image to me?

**Comment by adiladiladil** [comment]
![spaces](https://cloud.githubusercontent.com/assets/11046943/10235920/b13a056a-686e-11e5-8fb3-a1f24f1a5f0e.jpg)

**Comment by Saallen** [comment]
@cassiemc Mark S has asked for a big push on festival content and website to be updated.
I will ask Space Wranglers for bios today on an email- thanks :)

**Comment by hannahkane** [comment]
I think we can close this ticket, but will wait for @adiladil and @cassiemc to confirm. Thanks for the speedy work!

**Comment by cassiemc** [comment]
Yes sounds good. Go team!
