### ISSUE TITLE
Design "Fringe Events" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#194]
Community members are invited to submit relevant local events to be included on the "Fringe Events" page. We need to have a page with an embedded google form for people to use to submit their events.

The page also needs to display the list of approved events.

Page copy is being discussed on #178
Form fields for 2015 are TBD

Last year's form is here: https://docs.google.com/a/mozillafoundation.org/forms/d/12OSCSYC0Dwjzk48xeiIF93acCgRKsKg750SJ1NloWqs/viewform?edit_requested=true

**Comment by hannahkane** [comment]
@Saallen - can you clarify if there will be any changes to the submission form this year? Can we just re-create the same fields on a new form for 2016?

**Comment by hannahkane** [comment]
@Saallen - any thoughts on the content of the Fringe form?

**Comment by Saallen** [comment]
Hi- @hannahkane I dont think we need to change the form- happy with the fields as is

**Comment by hannahkane** [comment]
Redpen is here for feedback from @cassiemc and @Saallen: https://redpen.io/p/vuff937f9e9f4f9e4c

**Comment by cassiemc** [comment]
Looks good! Just a couple small comments and a question for @mmmavis on the redpen about layout.

**Comment by hannahkane** [comment]
@adiladil - here's approved copy:

MozFest is about working in the open and sharing ideas with the greater community. There are several innovative events taking place around the world with this same philosophy, and we would love to align them with MozFest.

If you are running an aligned event independent of the festival, please fill out our Fringe Event form. We will share your event details on our Fringe Events page.

How do you know if your event is a Fringe Event? It can be held anywhere in the world, but must align with the MozFest ethos: open, collaborative workshops or discussions focused on building tools and resources to keep the Web free and innovative.

**Comment by Saallen** [comment]
Loving the Redpen and agree with @hannahkane comment about shown by date. Thought I would share our insiration for the page http://2014.okfestival.org/okfestival-fringe-events/

**Comment by mmmavis** [comment]
I imagine we want to have a dynamic fringe page? The submit-approve-display flow I have in mind is

1. people submit their events via a form our site (pretty much like the proposal form)
2. data gets into a Google Spreadsheet
3. Marc checks the spreadsheet regularly and flags the entries that should be displayed on the Fringe page
4. On page load, MozFest site pulls selected entries from the Spreadsheet and displays them on the Fringe page

This way it'll involve less human effort to maintain that page.

That said, now I think of it I think maybe we should * *not* * have the option for people to include any image.

Reasons:

1. we don't plan on hosting images for them (we could if we want, but it'll have to be done manually)
2. linking to external images slows down page load, not to mention the files people include might be extremely large so load time can get really bad

@Saallen is there a deadline for people to submit their fringe event? If there is then we can consolidate the list of events, host images on the MozFest site, and update the Fringe page all at once.  (this will be a static page)

**Comment by adiladiladil** [comment]
Redpen below

https://redpen.io/p/vuff937f9e9f4f9e4c

**Comment by Saallen** [comment]
@mmmavis I think last submissions should be the Friday of the festival weekend.We wont be able to monitor very well from that day onwards.

**Comment by cassiemc** [comment]
Update: @adiladil is going to redesign this page to represent the content without images. We are thinking of a more visual way to show date / time, so the page is still somewhat visual/colorful.

**Comment by cassiemc** [comment]
Possibly blocking #133

**Comment by adiladiladil** [comment]
updated with no images

https://redpen.io/p/vuff937f9e9f4f9e4c

**Comment by cassiemc** [comment]
Looks good @adiladil! Can you throw sample content in one event just to check the grid? Then I think R+

**Comment by cassiemc** [comment]
@adiladiladil Can you throw the final image from the redpen in this bug? Then we can close and @mmmavis can start building.

**Comment by adiladiladil** [comment]
Here is the final look
![mozfest home-13](https://cloud.githubusercontent.com/assets/11046943/10311794/4954a1d4-6c16-11e5-97ab-f0be9e04e1af.jpg)

**Comment by Saallen** [comment]
:rabbit:

**Comment by mmmavis** [comment]
@adiladil could you attach/send me the .ai file as well as the hero banner image? Thanks! :smiley:

**Comment by mmmavis** [comment]
turns out the hero banner image for this page is already existed in this repo: https://github.com/mozilla/2015.mozillafestival.org/blob/develop/public/assets/images/fringe.jpg

**Comment by adiladiladil** [comment]
@mmmavis here is the link to download http://we.tl/0aK9G2OtH6

**Comment by mmmavis** [comment]
@adiladil  lovely! thanks for the quick response!
