### ISSUE TITLE
Design Remote Participation page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#195]
Description - Curriculum, discourse channels and sessions the community can participate in without being at the festival. Opportunity to still be part of MozFest if not in Ravensbourne

- [ ] Find help building out workshops, curriculum or discourse conversations
- [ ] build resources
- [ ] design the page
- [ ] opportunity for feedback?

**Comment by hannahkane** [comment]
@Saallen - is October 15 an acceptable deadline for final content/copy?

**Comment by cassiemc** [comment]
@Saallen In the Mozfest assets doc (https://docs.google.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit#gid=0) I see a note "Waiting on confirmation from Jess & Chad" – I'm not sure what confirmation we're waiting for – can you clarify?

**Comment by Saallen** [comment]
Chad is going to help with content. I am waiting on jess to confirm here

**Comment by cassiemc** [comment]
@hannahkane This one slipped under the radar. I assume we'll need to do this asap. Adil has finished his contract so will see if @natalieworth can help. Is the content finalized @Saallen?

**Comment by hannahkane** [comment]
Lots of conversation happening in the [content ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/231). 

Would be great if @natalieworth could design a MozFest-looking page based on [Chad's page](http://chadsansing.github.io/curriculum-testing/moz-fest-remote-projects/index.html).

**Comment by natalieworth** [comment]
@hannahkane @cassiemc Are we still waiting on confirmed content for this page, or can I start designing? Thanks

**Comment by hannahkane** [comment]
Looks like content is ready:
https://docs.google.com/document/d/1Oic1ZK5Ct7ZY8kkTauVwNAuYiZzFwJv7SrcgUxvtvUM/edit

**Comment by natalieworth** [comment]
@hannahkane Is this an extension of the navigation on the MozFest site or will it have it's own url (I'm just wondering for the navigation area in the mockup)? Thanks

**Comment by hannahkane** [comment]
Maybe it's linked to from a fifth icon in the footer. @cassiemc - what do you think?

**Comment by natalieworth** [comment]
Hey @hannahkane @cassiemc I've got the 1st mockups for this page up on redpen. I've got a couple questions on there too:
https://redpen.io/p/wadf08cec2538fa546

cc @chadsansing if you want to double check content/ add or take anything away. Thanks!

**Comment by hannahkane** [comment]
@natalieworth - looks good. Once you've had a chance to incorporate the feedback on the redpen so far, maybe we can get a review from @fuzzyfox and @kgorr as mentioned in the comments there.

**Comment by chadsansing** [comment]
I know we're far along in design, but @thornet just shipped me this link:

http://asd.learnlearn.in/my-remote-mozfest-experience/

Worth including as alternative experience under conversations? Something like, "Imagine alternatives to onsite events?" 

@hannahkane, @natalieworth, @KGorr, @fuzzyfox, @cassiemc

**Comment by natalieworth** [comment]
@cassiemc @hannahkane @chadsansing Updates to this page on red pen: https://redpen.io/ao52fe4cf670e63803

cc @KGorr @fuzzyfox

**Comment by cassiemc** [comment]
The design looks great to me, @natalieworth R+. I think if there are additional copy or content changes, let's file those as new bugs @chadsansing so @mmmavis can start this build?

@natalieworth once you post final files here let's close this!

**Comment by cassiemc** [comment]
I see there are a number of copy edit suggestions in the redpen still. @chadsansing is there a copy doc @mmmavis can pull from for the final implementation, to avoid going through these iterations in the redpen?

**Comment by hannahkane** [comment]
Good point, @cassiemc. I can edit the copy doc now to reflect all changes made/suggested in the redpen, and will update the implementation ticket accordingly.

**Comment by cassiemc** [comment]
Thanks @hannahkane!

**Comment by chadsansing** [comment]
Just about there. Waiting on a l10n campaign blog post that would make a good link for that activity. @ldecoursy is on the job.

**Comment by hannahkane** [comment]
I think we can close this design ticket, in favor of the implementation ticket. @natalieworth - can you please add assets to [that ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/179)?
