### ISSUE TITLE
Implement UX/UI changes to Schedule app

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#196]
We're repurposing the SRCCON schedule app for this year's MozFest. 
* Code: https://github.com/ryanpitts/mozfest-test-schedule 
* README: https://github.com/ryanpitts/mozfest-test-schedule/blob/gh-pages/README.md

Design is happening in #180

**Comment by mmmavis** [comment]
Hi @adiladil sorry if you have already done this somewhere already - would you mind attaching all the assets and .ai files here? I couldn't find them on the design ticket. :eyes:  Thanks :dancers: 

/cc @hannahkane @cassiemc

**Comment by hannahkane** [comment]
Moving to next heartbeat

**Comment by Saallen** [comment]
@hannahkane What requirements are needed from facilitators around their session info, ie how many words, is there a particular layout, agenda & outcomes- as we will need to get updated session outlines from nearly all.
cc @thornet for previous years requiremenrs

**Comment by mmmavis** [comment]
@Saallen @thornet @hannahkane let's move this discussion to https://github.com/mozilla/2015.mozillafestival.org/issues/219 instead? :smile:

**Comment by cassiemc** [comment]
This seems dependant on #219 which has Nov 6 milestone, so adding the same milestone here and marking as blocked. Please update the issue @mmmavis or @hannahkane if I'm mistaken!

**Comment by hannahkane** [comment]
This is in progress, so Nov 6 milestone is correct. Thanks!

**Comment by hannahkane** [comment]
I think we can close this as all Schedule app work has moved to the https://github.com/mozilla/mozfest-schedule-app repo
