### ISSUE TITLE
Instructions on "Raising Issues at MozFest"

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/2015.mozillafestival.org#197]
Love the [participation guidelines page](https://2015.mozillafestival.org/guidelines), and +100 on clear guidelines for what to do if there's an issue to report. The OpenNews team was talking about that today, and we just wanted to raise one possible unintended consequence of the instructions.

On the one hand, encouraging people to "immediately contact the Festival Director" says that we take these reports seriously, which is great! But the risk is that people who are experiencing real problems stop and think to themselves, "Well, maybe this isn't something I should bug the *Festival Director* with ..." and then things go unreported.

It might be worth considering rewording that section to lower the friction, and giving people (especially those who might be in crisis) some additional lighter-weight ways of communicating. Possibly something like:

If you believe you‘re experiencing practices at MozFest which don't meet the above policies, or if you feel you are being harassed in any way, please contact us right away. We have a plan in place, with people ready to help you. Your concerns will be treated confidentially and respectfully.

You can contact us in any of these ways:
* Email: festival@mozilla.org
* Phone call or text message: XXX-XXX-XXXX (would have to set this up)
* Twitter Direct Message: @XXXXX (would have to set this up and open up public DMs)
* Contact the info desk at the festival venue and they will immediately find someone to help

**Comment by SpikeUK** [comment]
+1 - although I would add the option for people to be able to contact any member of Festival Staff with a radio (who will call the Festival Director/Info Desk).
Thank you @ryanpitts

**Comment by sinker** [comment]
having a clear set of guidelines for action, including what violations of policy lead to what repercussions, who is involved in it and what timeframe decisions happen is going to be key as well. Not all of that needs to be public-facing, but should be clearly planned and communicated out to all people involved including radio-holders who will absolutely be the first line of intake for many of these things.

**Comment by Saallen** [comment]
I build an internal events plan for every event and within this plan is how to deal with certain issues that may arise. It is an internal document but one that is brought onsite at every event. There is also  volunteer guidelines  on a reporting system and next steps should an incident occur. This years documents are in mid build.
I do really like the  different modes of contact and will make steps to impliement this.
Thanks all

**Comment by cassiemc** [comment]
@Saallen status? Should we close this?

**Comment by ioana-chiorean** [comment]
@Saallen should we implement @ryanpitts suggested text on the page? https://2015.mozillafestival.org/guidelines

<i>
If you believe you‘re experiencing practices at MozFest which don't meet the above policies, or if you feel you are being harassed in any way, please contact us right away. We have a plan in place, with people ready to help you. Your concerns will be treated confidentially and respectfully.

You can contact us in any of these ways:

    Email: festival@mozilla.org
    Phone call or text message: XXX-XXX-XXXX (would have to set this up)
    Twitter Direct Message: @XXXXX (would have to set this up and open up public DMs)
    Contact the info desk at the festival venue and they will immediately find someone to help
</i>

**Comment by cassiemc** [comment]
These are good suggestions. Need some guidance from @Saallen or @thornet about what to do here / if this should be prioritized.
