### ISSUE TITLE
Remove /public/tickets.html

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#199]
Looks like `/public/tickets.html` is not used anywhere in the code. Let's check the codebase thoroughly and remove that file if needed.

**Comment by hannahkane** [comment]
@mmmavis - should we address this in the current heartbeat?

**Comment by mmmavis** [comment]
yup yup :+1:

**Comment by cassiemc** [comment]
@hannahkane @mmmavis status? Moving over to the next heartbeat.
