### ISSUE TITLE
MozFest 2015 site: Location page UI

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#20]
Wireframe: https://marvelapp.com/3e6ii4#5248456

Content:
Use copy from the current page: http://2014.mozillafestival.org/what-to-expect/:
- [ ] main festival venue
- [ ] travel tips and tricks
- [ ] how to get there

**Comment by edrushka** [comment]
First iteration: https://redpen.io/bx4eb2f09f0c98cf5d

Feedback from meeting:
- only need one location pin (for Ravensbourne)
- consider showing image of the building (a few options, more on Flickr: [option 1] (https://www.flickr.com/photos/mozillaeu/15438093050/in/set-72157648895117706) [option 2] (https://www.flickr.com/photos/mozillaeu/15437556188/in/set-72157648895117706)
- need to communicate that we have all 9 floors of Ravensbourne. Maybe something along the lines of [this] (https://www.dropbox.com/s/kf6hwyh86vbk2cc/Screenshot%202015-05-04%2011.30.01.png?dl=0)

**Comment by edrushka** [comment]
Latest version: https://redpen.io/hm151ab8ebfb443743

Copy from 'main festival venue', 'travel tips and tricks' and 'how to get there' would not appear on this page, but be linked from the 'What to Expect' in the footer.
@cassiemc and @saallen, although I love the cleanness of the page in this iteration, I'm suddenly doubting the decision to remove all the copy. Thoughts?

**Comment by edrushka** [comment]
No new version today. Still working from https://redpen.io/hm151ab8ebfb443743
    
To Do:
- Map should be less detailed -- design something and we'll run it by Scott
- Should at least *link* to 3 areas of information: 1) transportation tips, 2) lodging tips, and 3) general travel tips. The actual content could all live in the What To Expect page that's linked from the footer

**Comment by KevZawacki** [comment]
Copy edits for this page can be found here: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit

They begin on the second page.
