### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#200]
cuz it's cute :+1:

**Comment by SpikeUK** [comment]
Like 
![icon](https://cloud.githubusercontent.com/assets/1629474/9808684/64fab386-5859-11e5-94de-fe75facd6d90.jpg)
but neater?

**Comment by sabrinang** [comment]
@SpikeUK -  :+1: Yeah I exported that logo into various sizes to be used as favicons 
![mozilla-festival_favicon-114x114](https://cloud.githubusercontent.com/assets/2492510/9862625/d5221ca2-5aee-11e5-8276-2f91c4fc3a98.png)
![mozilla-festival_favicon-32x32](https://cloud.githubusercontent.com/assets/2492510/9862626/d7f91ac0-5aee-11e5-842a-e3192eb16dcf.png)
![mozilla-festival_favicon-16x16](https://cloud.githubusercontent.com/assets/2492510/9862628/d9d8bac6-5aee-11e5-9e60-0fc9c3dd1466.png)

**Comment by SpikeUK** [comment]
Much better than my attempt @sabrinang - thank you.
(The teeny one looks like it has a little red heart in the centre - like :heart: )
