### ISSUE TITLE
Add Open Graph tags to enhance sharing experience on social media

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#201]
Some major platforms including Twitter, LinkedIn, and Facebook recognize [Open Graph](http://ogp.me/).  Since the pages on our site don't have Open Graph tags, the preview generated by these platform when sharing a MozFest site link doesn't look appealing.

Below is the preview on Facebook:
<img width="488" alt="screen shot 2015-09-10 at 10 25 38 pm" src="https://cloud.githubusercontent.com/assets/2896608/9807660/219fddc6-580b-11e5-8dbe-4cc6caf62f9b.png">

The minimum tags we should add are
- `og:title`: site title, can be as simple as MozFest 2015? or Mozilla Festival 2015?
- `og:description`: we can probably just copy what @hannahkane suggested in https://github.com/mozilla/2015.mozillafestival.org/issues/169#issuecomment-137248434
- `og:image`: an image to use as page preview (thumbnail)

**Comment by sabrinang** [comment]
@mmmavis 
The recommended resolution for an OG image is 1200 pixels x 630 pixels (1.91/1 ratio) - some social media channels crop it so it is 1:1 so the first graphic will work for both and I exported it 630 x 630 in case you need it.

![mozfest-opengraph-imagetag-1200x630](https://cloud.githubusercontent.com/assets/2492510/9861257/03bce460-5ae6-11e5-86ec-40cbed620dc2.png)
![mozfest-opengraph-imagetag-630x630](https://cloud.githubusercontent.com/assets/2492510/9861256/03b9ee5e-5ae6-11e5-96fb-a7c7e445129d.png)

Assets located here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eUWk2ZFA4QldXVzg&usp=sharing

**Comment by mmmavis** [comment]
> - `og:title`: site title, can be as simple as MozFest 2015? or Mozilla Festival 2015?
- `og:description`: we can probably just copy what @hannahkane suggested in https://github.com/mozilla/2015.mozillafestival.org/issues/169#issuecomment-137248434

any feedback? @hannahkane :hamster:

**Comment by hannahkane** [comment]
+1, and I'd say "Mozilla Festival 2015" for the title

**Comment by mmmavis** [comment]
Done.

preview on Facebook:
<img width="485" alt="screen shot 2015-09-21 at 5 07 49 pm" src="https://cloud.githubusercontent.com/assets/2896608/10008436/5be01480-6083-11e5-9bca-0f3cc0d15c8c.png">
