### ISSUE TITLE
Closing the two Proposal forms

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#203]
The Call for Proposals form was closed on Friday but I just dicsovered that there is another form from which the api pulls the fields for the website and this is still open.
I am not sure who has ownership of this form?
@ScottDowne  or @mmmavis Whom ever has access can they please close the form?
:closed_book: Thanks!

**Comment by SpikeUK** [comment]
Do you mean https://2015.mozillafestival.org/proposals-2015 @Saallen ?

**Comment by ScottDowne** [comment]
There is also this: https://docs.google.com/forms/d/1MdPWZ6GsMpDiZnq3qwCfQSJ-7icdCQYGWuHIXrPlO3g/viewform

I thought we wanted to keep it open for certain people, just not promoted on the main site? Which would be why we created the proposals-2015 link.

**Comment by Saallen** [comment]
Hey,

We did extend the link for nearly two  weeks but that deadline has now
passed too.
All submissions should be submitted already.

Thanks
Sarah

**Comment by hannahkane** [comment]
Can you clarify what you want shut down, please? Is it that https://2015.mozillafestival.org/proposals-2015 should no longer display the form, and should instead be replaced with the same message that currently appears on https://2015.mozillafestival.org/proposals?

**Comment by Saallen** [comment]
Hi Hannah
Yes, People are still submitting via the new link we provided last Tuesday.
This form should be closed and no one should be able to fill out the form.
As this link is internal we don't need to change messaging. Does this make
sense?

**Comment by hannahkane** [comment]
If we don't change the language, it will just 404. I think it would be better to provide messaging. Is that ok?

**Comment by mmmavis** [comment]
I don't have the ownership to the underlying Google Form but I can help update `/proposal-2015` so that it has the same messaging as what shows up on https://2015.mozillafestival.org/proposals

**Comment by mmmavis** [comment]
I updated the messaging on [`/proposals-2015`](https://2015.mozillafestival.org/proposals-2015).  Gonna keep this ticket open until the form owner disables the Google form(s). (@thecount is that person you?)

**Comment by ScottDowne** [comment]
@mmmavis I gave you edit access to the form, not sure if you can close it with that access. The owner of the form is @Saallen

**Comment by Saallen** [comment]
Hi- @ScottDowne when I try to access the form I get an access denied and submit a request to access request. :confused:

**Comment by ScottDowne** [comment]
@Saallen I just confirmed it's under your foundation email. Have you ever been able to access it?

**Comment by Saallen** [comment]
achievement unlocked :key:
