### ISSUE TITLE
Last importing of final sessions

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#206]
Hello @hannahkane @mmmavis 
I was just wondering when we will import last group of sessions from the google form to the mozfest-program github repo?
I wanted to let the SW know so they dont miss these stragglers in the curation process.

**Comment by mmmavis** [comment]
Hi @Saallen I'll run the export script again today.  Will update the status here.

**Comment by Saallen** [comment]
Thank you @mmmavis

**Comment by mmmavis** [comment]
@Saallen do you know which row in the Google Spreadsheet I should export data from?

**Comment by Saallen** [comment]
Hi
I highlighted it Yellow on the sheet :)
S

**Comment by mmmavis** [comment]
yay thanks! :smile:  Is the same format as https://github.com/mozilla/mozfest-program/issues/446 okay? or is there any additional field you would like to include?

**Comment by mmmavis** [comment]
@Saallen I just finished export everything from Row 447(Breaking the barrier of the web: learning HTML, CSS and Javascript) up to Row 494(IoT is too important for big IT).  I kept the format the same.

**Comment by SpikeUK** [comment]
:+1:  thank you :smiley_cat:
