### ISSUE TITLE
Design stickers

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#209]
Requirements:
 * Cog + Wordmark + 2015
 * should match color of t-shirt

Specs:
* 2 color 
* round
* 7.5cm in diameter

**Comment by hannahkane** [comment]
cc @cassiemc

**Comment by adiladiladil** [comment]
![mozfest cog sticker-01](https://cloud.githubusercontent.com/assets/11046943/10144785/7044ebac-65ed-11e5-87c7-041e53485625.png)

**Comment by adiladiladil** [comment]
![mozfest cog sticker-02-01](https://cloud.githubusercontent.com/assets/11046943/10144936/4c1dfa7e-65ee-11e5-915b-c45ed394cc7d.png)

**Comment by adiladiladil** [comment]
![mozfest cog sticker-02-03-01](https://cloud.githubusercontent.com/assets/11046943/10145299/3d6949e6-65f0-11e5-8c55-fc1aa23d8e5c.png)

**Comment by adiladiladil** [comment]
![mozfest cog sticker-02-03-04-01](https://cloud.githubusercontent.com/assets/11046943/10145448/2e49c002-65f1-11e5-8658-6bfc08df2c53.png)

**Comment by marcwalsh** [comment]
@cassiemc Printer deadline for this is 23rd October

**Comment by cassiemc** [comment]
@Saallen @marcwalsh We like the circle options but need to choose between the circle with just the cog, or the circle with the cog and the date. Can you let us know which one you prefer so we can close out this ticket?

**Comment by Saallen** [comment]
Hey-  if its between the circles,can we do with the date? 
If its between the 4 options I do love the last one :)

**Comment by adiladiladil** [comment]
@marcwalsh @Saallen Here is the link to the 3 favorited options. All are print ready for when the decision is made

http://we.tl/UbrItBg2kc

**Comment by cassiemc** [comment]
Fab, thanks @adiladiladil. @marcwalsh are we good to close this?

**Comment by marcwalsh** [comment]
They look good to me, any issues, I'll reopen!

**Comment by cassiemc** [comment]
Boom, thanks @marcwalsh and @adiladiladil!

**Comment by marcwalsh** [comment]
Printers have come back and said that the artwork does not fit in the print area. 

Would you be able to alter them ASAP and send them back to me please? @adiladiladil @cassiemc 

![image001](https://cloud.githubusercontent.com/assets/14007066/10794085/67488440-7d8b-11e5-89f4-18ef256d5cbf.png)

**Comment by cassiemc** [comment]
@adiladiladil let us know if you can make this small adjustment please!

**Comment by cassiemc** [comment]
@adiladiladil I would do this myself but I don't actually have this exact file.The link in this issue is no longer active. @marcwalsh or @adiladiladil can you reupload the source file?

**Comment by adiladiladil** [comment]
@cassiemc @marcwalsh Here is the update to the sticker

http://we.tl/qVrEYoNWmQ

**Comment by cassiemc** [comment]
@marcwalsh if you need additional bleed on this, let us know how much. We just need to make the white background square bigger.

**Comment by marcwalsh** [comment]
It's good, and printers are happy now!
