### ISSUE TITLE
MozFest 2015 site: Submit a proposal UI

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#21]
Wireframes: https://marvelapp.com/3e6ii4#5248448 and https://marvelapp.com/3e6ii4#5248447

#### Functionality
MVP:
- people can submit data
- staff can edit data (this doesn't need beautiful UI)
- people can view proposed submissions

Nice-to Have:
- people can edit data
- people can shares links to proposed submissions

@saallen, can you paste a link to last year's form for reference?

**Comment by Saallen** [comment]
Sure Thang!
https://docs.google.com/a/mozillafoundation.org/forms/d/18s7lBIRoE4toeIhmm_7bStFqoWf2v-pEdPrbw4Bk31A/edit#

**Comment by edrushka** [comment]
@Saallen We need to know if scheduling tool will include submit proposal functionality.

**Comment by Saallen** [comment]
It would be really great if people could upload proposals directly to the app but we can still opearate and open the call with the google form. If we do use the google form then the app wont need the functionality of people being able to edit their submissions.

**Comment by edrushka** [comment]
@adiladiladil we're going to go ahead and design this, moving forward on the assumption that the scheduling tool will *not* have this functionality. @iamjessklein has already done the wireframes for this form. https://marvelapp.com/3e6ii4#5248448 and https://marvelapp.com/3e6ii4#5248447

**Comment by edrushka** [comment]
Latest version: https://redpen.io/ty170d45b11e115cc1

**Comment by edrushka** [comment]
Latest version:  https://redpen.io/ypa9376b46c9b0c28b

Note: we're considering modelling the experience after this: https://build.webmaker.org/add and are investigating that here https://github.com/mozilla/mozillafestival.org/issues/27

@Saallen we still need to get Adil the final fields for the form

**Comment by edrushka** [comment]
Fields for form:

1) Title of session * [text box]
2) First Name * [text box]
3) Surname * [text box]
4) Email address * [text box]
5) Organization (if applicable) [text box]
6) Twitter handle (if applicable) [text box]
7) Other facilitators (if applicable) [text box]
8) What will your session or activity allow people to make, learn or do? Describe your session's goals in 150 words or less. * [text box]
9) How do you see that working? Describe your session's agenda in 150 words or less. * [text box]
10) How will you accommodate varying numbers of participants in your session? Tell us what you'll do with 5 participants. 15? 50? * [text box]
11) What do you see as outcomes after the festival? How will you and your participants take the learning and activities forward? *[text box]
12) Please select the tags that apply to your session [choose from the selection of tags]
Row one tags:
    Make
    Lead
    Teach
    Invent
    Play

Row two tags:
    Learning
    Craft
    Citizenship
    Science
    Journalism
    Arts

Row Three tags:
    Youth
    Artisans [tech, maker, coder, developer?]
    Activists
    Educators
    Localizers

**Comment by edrushka** [comment]
@Saallen please confirm those form fields and tags.

**Comment by edrushka** [comment]
@KevZawacki want to take a peek and see if anything strikes you as weird?

**Comment by Saallen** [comment]
Is there a way to ask them to select one tag per line- It would be great if they only could select one per line but happy if we just could ask them.
working on the sched.com upload versus the CFP google doc format. will update post call

**Comment by Saallen** [comment]
Yes- all questions are perfect and match last year. Thank you

**Comment by ScottDowne** [comment]
I'm a bit confused about tags.

Are there basically three lines of tags, and they can select one for each line?

Kinda feels like three dropdowns and not tags.

Would probably be more clear if each tag had a label that described it instead of calling it tag. Example, the third list could be "who should join"

**Comment by Saallen** [comment]
I picked three lines of tags according to Jess' wireframe and the design from Adil.
We can label them if you think this will help
* first line is focused as Themes
* Second line is Mode
* Third line is audience

**Comment by edrushka** [comment]
+1 we need to clarify otherwise people won't click tags that are helpful. @cassiemc I wonder if you could make a suggestion for integrating Sarah's titles in the comment above to make it clear for users. For reference, here's the latest design: https://redpen.io/upc0073ec48c1c8da5

**Comment by cassiemc** [comment]
I agree with @ScottDowne that if we are limiting it to one per group, it's much clearer as three labeled columns of dropdowns. cc @edrushka

**Comment by edrushka** [comment]
@Saallen does that work for you?

**Comment by Saallen** [comment]
Yes- that works for me .
Can we use each line as a filter on the sched.com app @ScottDowne ?

**Comment by ScottDowne** [comment]
This was done. The bit about tags is being fixed here: https://github.com/mozilla/2015.mozillafestival.org/issues/48
