### ISSUE TITLE
Design Name Tag

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#210]
**Name tag purpose**
* Visual recognition piece as registered participant 
* allows entry into all parties
* Must have space for attendee to write name on both side
* 2100 tags will be printed
* Firefox lanyard will be used in conjunction

Design I really liked from another festival-
![quartz name tage](https://cloud.githubusercontent.com/assets/10194015/9976541/fbd0b61c-5ede-11e5-805a-10ee9ce00c22.jpg)

Design from last year
Size : 
Colour :
- to be added

**Comment by SpikeUK** [comment]
![id_tag](https://cloud.githubusercontent.com/assets/1629474/9980748/d3854462-5f9b-11e5-82f1-98a852f169ff.jpg)
This is the Name Tag from MozFest 2014.
It s 147mm x 104mm which makes it a A6 size.

**Comment by cassiemc** [comment]
@SpikeUK thanks, very helpful! 
@Saallen good inspiration too. Do you have a photo of the ff lanyard?

**Comment by marcwalsh** [comment]
@cassiemc - We're not sure what we're able to get at the moment. Speaking to WPR and MoCo events to see if they have enough stock of one design. Otherwise we would be going for just a plain colour. If we get some from in house I'll send a photo ASAP.

**Comment by SpikeUK** [comment]
@cassiemc No problems. Would like to have the area of solid colour at the bottom of the name tag if possible. Volunteers will be sporting country flags to indicate other languages spoken (I hope).

**Comment by marcwalsh** [comment]
@cassiemc attached is the image of the lanyards we hope to get, if not they will be plain black. 
![20150924_133341](https://cloud.githubusercontent.com/assets/14007066/10075454/cc407674-62cd-11e5-8ffc-96172f5da032.jpg)

**Comment by marcwalsh** [comment]
Also @cassiemc there's a possibility we would be able to get this as a Ravensbourne project with some of their project students. Would this be preferred or we could keep it in house and get a Ravensbourne student to help with printing it.

**Comment by cassiemc** [comment]
Let's keep it in-house and get help with printing, thanks for asking @marcwalsh!

**Comment by adiladiladil** [comment]
![nametage-02-01](https://cloud.githubusercontent.com/assets/11046943/10175061/ef015886-66ba-11e5-93a7-747215f56f48.png)
![nametage-01](https://cloud.githubusercontent.com/assets/11046943/10175060/eefe70c6-66ba-11e5-959b-40a9e1e305ed.png)

**Comment by cassiemc** [comment]
I love the version with the gradient! Should there be space for a twitter handle? (could probably move short names up to one line). @marcwalsh any idea what kind of paper these will be printed on?

@adiladil could you make the white box a little wider so that the border around it is equal on the sides and bottoms?

**Comment by Saallen** [comment]
@cassiemc @adiladil I love the gradient too. Nice link back to the website design. 
We dont print the tags with names on there as we want people to write their own. 
Yes for leaving space for twitter handles.
This should be a double sided design and there should be space at the top for a punched hole where the lanyard will clip in.

**Comment by SpikeUK** [comment]
Also would like a bit of clearspace for volunteer language badges (as per my comment https://github.com/mozilla/2015.mozillafestival.org/issues/210#issuecomment-141994446 ) please.

**Comment by cassiemc** [comment]
Good call @SpikeUK thanks for the reminder. Could volunteers possibly put flag stickers on the top part of the tag, or near the name? (in other words, what's the thinking behind putting them at the bottom?) Do you have any examples of what these will look like, and size? Is this a thing specifically for volunteers or will other guests be prompted to use this system?

@adiladil since these will be filled out manually, we may want just a small, light grey prompt of 'Name' & 'Twitter handle' in the large whitespace to tell people what to write on their name tag. Does that sound right @Saallen ?

**Comment by marcwalsh** [comment]
@adiladil  Are you able to add a print mark for cutting the hole at the top please. Roughtly 5mm from the top of the card is where the hole should start? Thanks!

**Comment by cassiemc** [comment]
@marcwalsh do you know how the hole will be punched? This seems super specific, just wondering if it would be a long horizontal hole or a round one :)

**Comment by marcwalsh** [comment]
I'm not too sure, it's by a machine, but it's to the mark that we place. It's round as well :)

**Comment by SpikeUK** [comment]
@cassiemc The clearspace can beat the top if that helps to balance the design. I have not finalised flag sticker design or size as yet - depends what size stickers I can get for my printer and how much space we have. Am expecting most people (with languages other than English) to have one other language, but do have a couple of volunteers that speak three :O

**Comment by Saallen** [comment]
Hey @cassiemc Sure sounds like a good idea to have a prompt here

**Comment by adiladiladil** [comment]
![mozfest nametag-01](https://cloud.githubusercontent.com/assets/11046943/10254827/37ce0d6a-6914-11e5-833e-2620feb8208b.jpg)

Update

**Comment by cassiemc** [comment]
@adiladil redpen please? I have small tweaks

**Comment by adiladiladil** [comment]
@cassiemc  https://redpen.io/p/pa2d3b776193807831

**Comment by SpikeUK** [comment]
Like the one with the smaller "Name:" and "Twitter Handle:" text labels.
Can we leave out the word "Handle"? - I rarely hear that used - maybe just print big "@" as a clue?
But generally, lovely work all!! :) :) :)

**Comment by cassiemc** [comment]
Thanks @SpikeUK, agree wrt Handle. Left some additional comments on the redpen @adiladil: https://redpen.io/kjef1f07bbb2e8c2bd

**Comment by SpikeUK** [comment]
Just occurred to me @Saallen - is there a need for an easily spotted variant for under-16s?

**Comment by Saallen** [comment]
Hey @SpikeUK we do not need any varient for young people. Parents can write phone numbers on the other side at the event if they have young children they are letting run around but its not a requirement.

**Comment by SpikeUK** [comment]
OK @Saallen - was just a thought.

**Comment by adiladiladil** [comment]
updated nametag here

https://redpen.io/p/pa2d3b776193807831

**Comment by cassiemc** [comment]
@adiladil just a reminder this issue has the october 23 milestone, lots more in the oct 9 milestone ahead of this one :)

**Comment by adiladiladil** [comment]
@marcwalsh do you know the final dimensions of the nametags?

**Comment by marcwalsh** [comment]
@adiladiladil A6 please

**Comment by adiladiladil** [comment]
posting this for review and approval @cassiemc @Saallen @marcwalsh 
![nametag-01](https://cloud.githubusercontent.com/assets/11046943/10489165/e0a1d030-7269-11e5-8a9e-a6ca327623a9.jpg)

**Comment by cassiemc** [comment]
@adiladil Looks great! It's an odd twitter icon though. Can you use the standard one?

**Comment by adiladiladil** [comment]
How's this @cassiemc 
![nametag-01-01](https://cloud.githubusercontent.com/assets/11046943/10490000/fec66eb0-726c-11e5-8d5a-bf88658d08ba.jpg)

**Comment by marcwalsh** [comment]
@adiladiladil Looks great, I would make the hole to size at the top to ensure it and the cog are placed correctly. They are normally 5 / 6mm in diameter.

**Comment by adiladiladil** [comment]
@marcwalsh how far from the top does the hole get punched?

**Comment by marcwalsh** [comment]
5mm as well

**Comment by marcwalsh** [comment]
@adiladiladil 5mm as well

**Comment by adiladiladil** [comment]
here is the update 
![nametag-01](https://cloud.githubusercontent.com/assets/11046943/10490576/e550b668-726f-11e5-8981-98c4ce1c92c7.jpg)

**Comment by cassiemc** [comment]
I like it. R+ from me. @adiladil now just need the source file so @marcwalsh can print. Marc, do you need bleed set up?

**Comment by cassiemc** [comment]
@marcwalsh can we close this?

**Comment by adiladiladil** [comment]
@marcwalsh Here is the nametag file with bleed

http://we.tl/qmui08sjtx

**Comment by marcwalsh** [comment]
Sorry @cassiemc and @adiladiladil - Notficiations to this didn't show up. This should be fine! Again, will send to printers and any issues I will reopen!

Thank you!

**Comment by cassiemc** [comment]
Woohoo, thanks @marcwalsh!
