### ISSUE TITLE
Provide content for Festival Guide

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#211]
@Saallen - is there an outline for the content that will be included in the Festival Guide this year?

Also, is there an expected date for the actual final copy?

**Comment by hannahkane** [comment]
@Saallen - We'd love to start this project as soon as possible. Can you please share last year's design, so @adiladil can use it to start setting up the file.

Also, what's your timeline for having the content ready?

**Comment by Saallen** [comment]
Hey,
Mis communication on our side, Marc will upload details first thing in the
morning. While we don't have the copy, he has photos and we have tons of
old guides.

Today at 6pm PST is closing date for space copy so I will have full space
info before you you online uploaded here.

**Comment by marcwalsh** [comment]
@hannahkane - See images below of last year's guide.

![20150922_100806](https://cloud.githubusercontent.com/assets/14007066/10072891/ee6bc408-62bc-11e5-8e97-d088a492ab39.jpg)
![20150922_100814](https://cloud.githubusercontent.com/assets/14007066/10072892/ee6c8e24-62bc-11e5-9f4c-6587e41f2b36.jpg)
![20150922_100819](https://cloud.githubusercontent.com/assets/14007066/10072896/ee70cd0e-62bc-11e5-98da-df2ba58b8f1b.jpg)
![20150922_100827](https://cloud.githubusercontent.com/assets/14007066/10072893/ee6cbbce-62bc-11e5-969d-d47d94109669.jpg)
![20150922_100834](https://cloud.githubusercontent.com/assets/14007066/10072894/ee6e586c-62bc-11e5-9f64-58d8904a81c6.jpg)
![20150922_100843](https://cloud.githubusercontent.com/assets/14007066/10072895/ee6fa212-62bc-11e5-91b1-ceea57f1d9a3.jpg)
![20150922_100850](https://cloud.githubusercontent.com/assets/14007066/10072897/ee7e3f48-62bc-11e5-94ce-fc33ca996648.jpg)

**Comment by cassiemc** [comment]
@marcwalsh @Saallen Do you guys have working files for this, especially vectors for the map? This looks like a ton of work to reproduce and having the files would save an enormous amount of time.

Since this looks like a significant effort I'm also going to suggest here that we fill out a design brief to kickoff this piece of work. I'll find some time in our calendars asap to fill this out together, should take an hour, and will be based on questions in this template here: http://bit.ly/mozdesignbrief

**Comment by cassiemc** [comment]
@marcwalsh What's the best way to include you in the meeting invite? Do you have a mozilla email address (or another one where I can reach you?)

**Comment by Saallen** [comment]
@cassie I am pretty sure those maps are in the drop box I shared with you last week. I am checking for all the old files now.

**Comment by marcwalsh** [comment]
@cassiemc - I do indeed! mwalsh@mozilla.com

**Comment by cassiemc** [comment]
Great, thank you both!

**Comment by Saallen** [comment]
@cassiemc - it appears I didnt share the files on dropbox so have ammended that

**Comment by Saallen** [comment]
https://www.dropbox.com/home/Mozilla%20Festival%202014/Print%20Assets/Floor%20Maps

This is what you need re-floor maps

**Comment by KevZawacki** [comment]
@HPaulJohnson and I can help with the copy/messaging. Much of it already exists -- on the website, in the comms plan, etc.

**Comment by Saallen** [comment]
MVP for guide-
* How to navigate the festival narrative
* Map of the venue with key locations outlined, ie toilets and coffee
* description of the spaces
* contact info
* #mozhelp

Nice to have
* participation guidelines




cc @edrushka did Roberto ask about the festival guide and user feedback in his questionaire at the start of the year?

**Comment by cassiemc** [comment]
@HPaulJohnson @KevZawacki In our kickoff the other day we discussed having content for this by EOD today. I think tomorrow would be fine as well. Are we on track for this?

The design brief is here: https://docs.google.com/document/d/1HrdFapu28ChXPVVmwCZ7lnupDdYyDR3DMxwGwGFu0lE/edit

(Note: @edrushka we discovered that there was no feedback from the questionairre re. the guide, but there is plenty else to go on)

**Comment by KevZawacki** [comment]
We've created a Google Doc to house all the copy for the festival guide -- you can find it [here](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit). 

@Saallen, can you take a read through and share feedback? Anything missing? Are the space descriptions accurate?

@cassiemc, from a design standpoint, do we need more copy? Less?

cc @HPaulJohnson

**Comment by KevZawacki** [comment]
@Saallen Festival Guide updated with Pathways language! 

https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit

A question: will this new, shortened Spaces and Pathways language live both on the print guide and the website?

**Comment by hannahkane** [comment]
Re: adding this content to the website—looks like we should update https://2015.mozillafestival.org/expect and https://2015.mozillafestival.org/guidelines to reflect these latest updates. Also, @Saallen - do you want a "Pathways" page on the site (similar to the "Spaces" page)?

**Comment by cassiemc** [comment]
@hannahkane I think the descriptions make sense to live on What to Expect, but not on Participation Guidelines, which are more about attendee behavior. I also think it makes sense to have a small space for this in the app.

**Comment by hannahkane** [comment]
Sorry, @cassiemc, I didn't mean to suggest we add content about Spaces and Pathways to either the What to Expect or Participation pages. I just meant that in the google doc, it looked like there had been some updates made to the existing content of those pages, but Kevin has since said in the doc that the changes aren't substantive.

**Comment by cassiemc** [comment]
oh, thanks for clarifying @hannahkane! Do you think we should add that context though on the app, at least?

**Comment by hannahkane** [comment]
@cassiemc - Yes, def. I think there's already a space for it in the app design. See the lorem ipsum at the top of "Mozfest 2016 Mobile Scheduler 05". https://redpen.io/bp742d484e39748ec1

**Comment by cassiemc** [comment]
ok!

**Comment by Saallen** [comment]
@hannahkane , it would be really great to have the pathways also on the website. Could they be on the same page or should they be separate?

**Comment by hannahkane** [comment]
@Saallen - let's do it! I'll file a ticket to add a pathways page to the site.

@KevZawacki - I added a suggested revision for the Spaces and Pathways explainer to the google doc. What do you think?

**Comment by KevZawacki** [comment]
@hannahkane Excellent! Just accepted the edit.

**Comment by hannahkane** [comment]
This looks good to me. Can we close?

**Comment by cassiemc** [comment]
Sorry, didn't get a change to review this today. I'll look on Monday. Let's close this and I'll open a new issue if I see a need for any significant changes. Thanks @KevZawacki and @HPaulJohnson for the speedy work on this!
