### ISSUE TITLE
Design Festival Guide

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#212]
Content is being wrangled in #211 

@Saallen - can you provide last year's guide, so we can use it as a starting point / inspiration?

**Comment by hannahkane** [comment]
cc @cassiemc

**Comment by cassiemc** [comment]
Design brief is filled out here: https://docs.google.com/document/d/1HrdFapu28ChXPVVmwCZ7lnupDdYyDR3DMxwGwGFu0lE/edit

**Comment by marcwalsh** [comment]
@cassiemc Printer deadline for this is the 23rd October

**Comment by adiladiladil** [comment]
@marcwalsh do we have last years files?

**Comment by cassiemc** [comment]
@marcwalsh Okay! I thought it was the 26th from the design brief. In this case, we'll need some fast feedback and iterations next week so please be on standby. :) 

@adiladil will be posting the first draft on Monday – Adil is it possible to have it posted on redpen in the a.m. so folks in London can provide feedback that day?

**Comment by adiladiladil** [comment]
@marcwalsh @cassiemc @Saallen 

the vector floormaps were missing links here. Could someone direct me to where those files are
in the meantime here is the general layout:

I believe content still needs to be finalized 

https://redpen.io/fs0ebbbcee8c073867

![mozfest 2015 programme_v1-03](https://cloud.githubusercontent.com/assets/11046943/10585937/d29d7a78-7667-11e5-82fe-1de13584e817.jpg)

**Comment by cassiemc** [comment]
Hey @adiladil - all the vector maps should be in the drive folder here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B7cnpfRDzUyFVkFlaWdCVm1yUlk&usp=sharing#list

@HPaulJohnson @KevZawacki Can you guys comment on the finality of the content for this? If it's not already finalized, we'll need to it be done by EOD if possible. Deadline for this to be sent to the printer is this is Friday at noon ET (EOD London time).

**Comment by KevZawacki** [comment]
@cassiemc Content in [this doc](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit) is finalized and ready for layout.

**Comment by cassiemc** [comment]
thanks @KevZawacki! cc @adiladiladil ^^

**Comment by thornet** [comment]
Thanks! @KevZawacki I added some language about having agency and embracing fluidity at Mozfest. Think this is a really important message to include whenever we're talking to participants.

**Comment by cassiemc** [comment]
@KevZawacki Could you please review @thornet's additions and let us know when it's got your stamp of approval?

**Comment by adiladiladil** [comment]
@KevZawacki @thornet @cassiemc 

There are 24 pathways with descriptions and pathfinder info. it's a ton of content to fit. any way we can edit it down somehow to make room for the map and spaces

**Comment by cassiemc** [comment]
I hear ya @adiladiladil. Maybe shrink 'em down with something like "Visit our app or website for more space descriptions"? @KevZawacki

**Comment by KevZawacki** [comment]
@cassiemc Michelle's additions reviewed and good to go.

Re: leaving some content out, I defer to @thornet and @Saallen for guidance. 

@adiladiladil Do you have a rough idea of how many words we need to cut?

**Comment by Saallen** [comment]
Hey @adiladiladil it would be good to know how many words you need cutting. The Spaces are important and definitely need to have an explaination of how we have built pathways interwoven to the program. If we did have the space- I would love to keep them in but understand space restrictions.

**Comment by adiladiladil** [comment]
@Saallen It's not the spaces that need cut down. My concern is with the 24 pathways. if the copy within each of the pathways could be cut by half that would leave enough room for all the Spaces and additional content

**Comment by cassiemc** [comment]
@KevZawacki FYI ^^ I believe @adiladiladil was going to take a stab at shortening one of these in the design, but we could use a hand in shortening the others. Adil, can you upload a new comp for Kevin's reference?

**Comment by adiladiladil** [comment]
here is the link to the updated redpen:

https://redpen.io/p/qk2adb94ee9367c3cc



![mozfest 2015 programme_poster](https://cloud.githubusercontent.com/assets/11046943/10642291/f7bc2988-77ea-11e5-8534-bdb2c9032c53.jpg)

![mozfest 2015 poster_v2_poster](https://cloud.githubusercontent.com/assets/11046943/10642293/fa4ce44e-77ea-11e5-87d1-39f23aee8b0b.jpg)

![mozfest 2015 poster_v2-02](https://cloud.githubusercontent.com/assets/11046943/10642296/fe624754-77ea-11e5-9cf1-761c725a17ff.jpg)

**Comment by cassiemc** [comment]
This is fabulous @adiladiladil, thanks! Will dig into the redpen shortly. I quite like the blank WITH the pencil, I think it's a bit clearer what people are supposed to do with it, particularly if we attached markers to where the posters are hung.
@marcwalsh can we get supplies to hang markers with string next to some posters?

**Comment by Saallen** [comment]
Looks good @adiladiladil. Where do we make edit requests? red pen or here? cc @cassiemc

**Comment by cassiemc** [comment]
@Saallen I'm sure either would work

**Comment by KevZawacki** [comment]
@adiladil @cassiemc RedPen looks awesome! I dropped in some comments -- mostly fixing typos that are my fault to begin with. 

Also, the Pathways section needs some TLC -- many of the sections are labeled incorrectly. The proper organization can be found in the original [Google Doc](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit). Let me know if you have any questions. 

@adiladil @cassiemc A bit lost on what needs to be shortened -- apologies for the confusion. Are you saying if I trim the Pathways descriptions by half, we'll be able to add them to the guide? Or, should we simply include the titles, like we have now?

**Comment by adiladiladil** [comment]
@KevZawacki 

could we shorten this copy up a bit:

Spaces & Pathways

MozFest invites you to take control of your participation. This is a fluid event, designed to meet participants’ needs and help you seize opportunities for peer learning. We invite you to join in with an open mind and purposeful flexibility, as sessions shift and emerge to better serve you.

To help you navigate MozFest, we’ve introduced two concepts: Spaces and Pathways. Spaces are physical hubs, typically located on a single floor, with sessions exploring a shared theme. Pathways are a series of three or more sessions and experiences that often guide you through multiple Spaces. Each Pathway is tailored for participants to learn a particular set of skills. Participants are encouraged to make use of the recommended Pathways or design their own unique MozFest experience.

**Comment by KevZawacki** [comment]
Sure. How about:

Spaces & Pathways

MozFest invites you to take control of your participation and seize opportunities for peer learning. Join in with an open mind and purposeful flexibility.

To help you navigate MozFest, we’ve introduced two concepts: Spaces and Pathways. Spaces are physical hubs, typically located on a single floor, with sessions exploring a shared theme. Pathways are a series of three or more sessions and experiences that run through multiple Spaces and teach a particular set of skills. Feel free to design your own unique MozFest experience!

**Comment by adiladiladil** [comment]
Update here for another pass

https://redpen.io/hs155553dd47fa6643

![mozfest 2015 programme-02](https://cloud.githubusercontent.com/assets/11046943/10674885/4edacb8a-78cb-11e5-82f7-18abaa95d128.jpg)

**Comment by cassiemc** [comment]
@adiladiladil's latest is here: https://redpen.io/hs155553dd47fa6643
For the back, the poster, we're going with https://redpen.io/gkf52e8eebbc667a58 (@adiladiladil I left one final comment about the logo for that side)

**Comment by Saallen** [comment]
@adiladiladil @cassiemc - Have you tried to fold this guide to see how the poster page is divided?
I am unable to find 2014 guide with folds to show you what we mean but Simon our old designer spent alot of time on the layout of the poster page.

**Comment by Saallen** [comment]
Where are all the designs being kept as they are being finalised?

**Comment by adiladiladil** [comment]
Here is the update for another look over:

https://redpen.io/fn5db6b0b15647909f

![mozfest 2015 programme_v1-02](https://cloud.githubusercontent.com/assets/11046943/10694650/58101e6a-796d-11e5-8ee6-f37dab088e3f.jpg)

**Comment by adiladiladil** [comment]
Here is the guide with fold lines with last years as a comparison
![mozfest 2015 programme_folds-02](https://cloud.githubusercontent.com/assets/11046943/10695114/002d69f2-7970-11e5-88dd-596047b8c1c8.jpg)
![ee7e3f48-62bc-11e5-94ce-fc33ca996648](https://cloud.githubusercontent.com/assets/11046943/10695115/0245b4a6-7970-11e5-947f-9d3f714e012f.jpg)

**Comment by adiladiladil** [comment]
Here is the poster with the fold lines and last years as reference
![mozfest 2015 programme_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10695481/e52ebe6a-7971-11e5-98b7-b7e3d4310bb5.jpg)
![ee6fa212-62bc-11e5-91b1-ceea57f1d9a3](https://cloud.githubusercontent.com/assets/11046943/10695485/ebd30636-7971-11e5-914d-508c9fd4f438.jpg)

**Comment by adiladiladil** [comment]
Here is the poster with the fold lines and last years as reference
![mozfest 2015 programme_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10695551/3804c652-7972-11e5-803d-843a6352ecba.jpg)
![ee6fa212-62bc-11e5-91b1-ceea57f1d9a3](https://cloud.githubusercontent.com/assets/11046943/10695552/3919e284-7972-11e5-9310-02046e8fcaae.jpg)

**Comment by adiladiladil** [comment]
Here is another option to consider for the guide. you can see the folds here as well

![mozfest 2015 programme_v3-03](https://cloud.githubusercontent.com/assets/11046943/10695895/23f32a44-7974-11e5-871e-ccdf7bab5348.jpg)

**Comment by cassiemc** [comment]
@adiladiladil This latter option with the fold lines between columns is the best, let's do it!

**Comment by adiladiladil** [comment]
@cassiemc i agree. not sure why last years had folds running through text but this will eliminate that prob

**Comment by cassiemc** [comment]
@adiladiladil I'm done with my comments on the redpen for now :)

**Comment by adiladiladil** [comment]
@cassiemc great. i'm adding that one last line about the lift accessibility then uploading the latest latest version for everyone to take one last look

**Comment by marcwalsh** [comment]
Hey @adiladiladil and @cassiemc 

Michelle has noticed that theres a few pathways missing. She's writing up a list here:
https://public.etherpad-mozilla.org/p/festival-pathways

But if this isn't possible it would be good to add something along the lines of:

"There's event more amazing pathways are being added all the time, check out the latest list online
https://2015.mozillafestival.org/pathways"

**Comment by adiladiladil** [comment]
@marcwalsh added the new pathways 
@cassiemc new version is up on redpen

let me know once everyone has given feedback and proofed everything one last time

**Comment by adiladiladil** [comment]
@cassiemc @natalieworth 

newer new version on redpen

**Comment by cassiemc** [comment]
Ok @adiladil left my final review. There are a couple questions for @Saallen or @thornet re. the pathway names, a few punctuation and typesetting fixes, and a couple small design tweaks.

cc @marcwalsh

**Comment by adiladiladil** [comment]
and here is the final pass perhaps?

https://redpen.io/p/qk2adb94ee9367c3cc

![mozfest 2015 programme_vfinal maybe-03](https://cloud.githubusercontent.com/assets/11046943/10704576/d5c78428-79a5-11e5-9a2f-a809e19c6494.jpg)

**Comment by cassiemc** [comment]
Looks good to me @adiladiladil! Can you post the final print files here por favor?

**Comment by adiladiladil** [comment]
Here is the link to the master print AI file

http://we.tl/hsAVr7i30y

**Comment by adiladiladil** [comment]
and here is the link to all assets I've completed 

http://we.tl/G0gRr23qRa

**Comment by cassiemc** [comment]
Thanks so much @adiladiladil! @natalieworth see above for the vector map assets.

@marcwalsh Please let us know if the printer accepts the file as-is so we can close the issue. Have a great weekend all!

**Comment by cassiemc** [comment]
@adiladiladil just looking at your file, can you post version for @marcwalsh with and without the fold lines?

**Comment by adiladiladil** [comment]
@cadecairos @marcwalsh here are the two options with and without fold

http://we.tl/Z6ZXHQTcL7

**Comment by cadecairos** [comment]
I think you were trying to tag @cassiemc :)

**Comment by cassiemc** [comment]
thanks @adiladiladil !

**Comment by cassiemc** [comment]
@marcwalsh I'm going to close this issue. Please reopen if you need anything else.
