### ISSUE TITLE
Design icons for each of the 8 spaces

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#213]
The spaces are:
 - [ ] The Global Village
 - [ ] Journalism
 - [ ] Open Science [Note: just called 'Science' in the content doc]
 - [ ] Digital Citizenship
 - [ ] Mozilla Learning Networks
 - [ ] Participation
 - [ ] Youth Zone
 - [ ] Localization

**Comment by hannahkane** [comment]
@Saallen - can you confirm the above are correct? I thought there were 8 spaces, but I see 9 milestones in the program repo.

Also, can you provide a little guidance for whomever will be designing the icons? Some of these names are not entirely intuitive. Thanks!

**Comment by hannahkane** [comment]
cc @cassiemc

**Comment by Saallen** [comment]
Hi @hannahkane 
Voices of Diverse Leaders is not a space- it is  a pathway that sits within MLN
Tomorrow all Spaces must update their milestone descriptions by tomorrow COB so this will help with the icons I feel. This will be a good exercise for understanding clarity around the descriptions themselves. So happy to chat through them all with @adiladil if there is any confusion and will highlight this confusion with the SW too. thanks

**Comment by cassiemc** [comment]
Here are some icons for reference from last year: http://2014.mozillafestival.org/tracks/

**Comment by thornet** [comment]
Note: "Athena, the Connected Library" will likely be recast as "The Connected Village".

**Comment by Saallen** [comment]
Adding space descriptions [here ] (https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edit#) for ref

**Comment by cassiemc** [comment]
@Saallen @thornet Is it possible to organize the content in the google doc so it's a little easier to read and understand? For me it's hard to keep 'Spaces' and 'Pathways' separate in my head, and I'm not sure what an 'Independent Pathway' is. I'd suggest using the H1 > H2 > H3 structure so we can automate the table of contents and jump around the doc easier. https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edit#

I'd like to get started on the design for these early next week if possible since it has implications for lots of the other assets we need. Do you know when these will be final and approved?

Are the spaces listed in @hannahkane's first comment correct?

**Comment by Saallen** [comment]
Sorry- I meant to do this last week but I didnt get the time.
Independent pathways have no home space- so they are not curate with a space in mind. They have been submitted by partners and staff rather than curated by Space Wranglers. I have called them independent pathways to highlight them unable to sit under a space description.
I updated Hannahs top list

**Comment by hannahkane** [comment]
@Saallen - I thought the point of Pathways was that they could cross multiple Spaces. When displaying the Pathways, do we need to show how they are connected to a Space? The design does not account for that right now. Seems overly complicated to add that detail.

**Comment by Saallen** [comment]
Yes- they can. So I guess we dont need to connect them to a Space. Sorry I am so buried in this I cannot see the larger picture.
On this page then should we only display Space content or have Spaces decribed and Pathways beneath ?

**Comment by cassiemc** [comment]
Speaking with @Saallen this afternoon, I agree with @hannahkane that the pathways don't need to show how they are connected to a space. Also realized that each 'space' is a floor #, should we include that in the session details?

**Comment by hannahkane** [comment]
+1 Floor number seems critical for wayfinding. :)

**Comment by cassiemc** [comment]
I confirmed the spaces listed in comment 1 match those in the content doc here: https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edit

**Comment by adiladiladil** [comment]
![mozfest spaces-14](https://cloud.githubusercontent.com/assets/11046943/10198779/91b07f02-676b-11e5-92cf-9429ed981fd1.png)

**Comment by hannahkane** [comment]
This looks good, @adiladil. Did you mean to ad this to #193, though? I have some comments, but want to make sure I'm commenting on the right ticket. :)

**Comment by adiladiladil** [comment]
![mozfest space icons-01](https://cloud.githubusercontent.com/assets/11046943/10211050/a793643c-67bc-11e5-8d7b-41cf559b912c.png)

**Comment by thornet** [comment]
Inspiration from 2014: http://2014.mozillafestival.org/tracks/

**Comment by cassiemc** [comment]
@hannahkane I think it makes sense to critique these separately from #193. @adiladil already has lots of comments from that redpen, but can you add the next set of just the icons to a redpen at both large and small sizes?

**Comment by adiladiladil** [comment]
Here is the redpen for feedback on these icons

https://redpen.io/p/ad786b292a9765a31c

**Comment by hannahkane** [comment]
Flagging @thornet and @Saallen who might have more feedback on the icons

**Comment by SpikeUK** [comment]
Love most of the icons - thank you @adiladiladil - particularly love the use of two colours 
The only one I am not sure about is the 'Participation' one - the raised outstretched right hand says 'STOP' to me.

**Comment by marcwalsh** [comment]
Hey @cassiemc @adiladiladil - The 'Global Village' icon is missing at the moment.

**Comment by cassiemc** [comment]
@adiladil Lots of comments for you on the redpen.

**Comment by adiladiladil** [comment]
Thanks all. Am going through redpen now

**Comment by thornet** [comment]
@Saallen @adiladiladil I suggest we also run these icons by the wranglers, as they'll need to use and promote them and have the nuance of what their space should be communicating.

**Comment by cassiemc** [comment]
@thornet That sounds wise! @Saallen We should bear in mind that these icons are blocking design of several things we are trying to finalize by Friday that need to get to the printer by Oct 12.

**Comment by Saallen** [comment]
@cassiemc can I have a red pen link that I can share with our SW so they can make any comments or share highfives ?

**Comment by adiladiladil** [comment]
updated icons here:

https://redpen.io/p/ad786b292a9765a31c

**Comment by SpikeUK** [comment]
As @marcwalsh said above ^^ any reason why there is no "Global Village" icon?

**Comment by cassiemc** [comment]
@Saallen we will get this refined by EOD today - @adiladil is working on revisions now - and send you a link by your start of day tomorrow to share. (@spikeUK there is a global village icon now)

**Comment by cassiemc** [comment]
@adiladil any updates?

**Comment by SpikeUK** [comment]
@cassiemc thank you

**Comment by adiladiladil** [comment]
here is an update

https://redpen.io/p/ad786b292a9765a31c

laying out a few options for the ones which we had issues with


![mozfest space icons-01](https://cloud.githubusercontent.com/assets/11046943/10311671/c138ee54-6c15-11e5-850d-c58b4aacabe7.jpg)

**Comment by adiladiladil** [comment]
update here:

https://redpen.io/p/ad786b292a9765a31c

**Comment by cassiemc** [comment]
@Saallen the latest is here: https://redpen.io/jhf00503d5b10a1257 Can you let us know asap if there are any major issues with any of these?

@adiladil thanks for updating the latest redpen! My final comment is wrt to the hair on the youth icon and whether or not it should be symmetrical. Otherwise, r+, ready to build that icon cloud :)

**Comment by adiladiladil** [comment]
Great! moving onto other issues
sending out SVG icons to @mmmavis and will also send AI file to @natalieworth

**Comment by adiladiladil** [comment]
![mozfest space icons-01](https://cloud.githubusercontent.com/assets/11046943/10345326/eb84cf02-6cf6-11e5-87b2-8647685f07e0.jpg)

**Comment by cassiemc** [comment]
WOOT! :bomb: :+1: :100:  @adiladil

**Comment by Saallen** [comment]
Hi I will share these icons with the team in the morning- the only worry I have it the youth zone- as I mentioned on a redpen, I feel it should be gender neutral.  Thanks

**Comment by hannahkane** [comment]
Huzzah! :cake:

**Comment by adiladiladil** [comment]
@Saallen gender neutral lego head?
![screen shot 2015-10-07 at 2 00 22 pm](https://cloud.githubusercontent.com/assets/11046943/10346201/e2b89ade-6cfb-11e5-999b-53d934f32ce0.png)

legos are huge among kids. and this particular head does not have hair...so gender neutral?

**Comment by SpikeUK** [comment]
:+1:

**Comment by Saallen** [comment]
Yes, Lego heads are gender neutral. Happy with that :b thanks

**Comment by cassiemc** [comment]
@Saallen @adiladil I'm not convinced it looks like a lego head – I think context is lost without the yellow color. @Saallen if you can show the wranglers both choices (without telling them what it is) that would be appreciated! (Let's file any follow up issues as new ones)

**Comment by adiladiladil** [comment]
@cassiemc @Saallen sounds good to me

**Comment by adiladiladil** [comment]
Here are the final icon choices
![mozfest space icons-01](https://cloud.githubusercontent.com/assets/11046943/10399409/919b9b3e-6e80-11e5-9ea8-0ee723adf725.jpg)

@mmmavis I'm sending you the YOUTH SVG separately . then you should have all

@natalieworth I'm sending you the AI file for this as well
