### ISSUE TITLE
Moving 'About' and 'What To Expect' to top nav bar

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/2015.mozillafestival.org#218]
I was looking for information on the website earlier and I think that the 'About' and 'What To Expect' links are a little lost in the bottom nav bar. It felt more like I had to search for them than the tickets and location.

Would it be worth moving them to the top nav bar so they are more visable? It's just for first time MozFesters that are looking for info about the festival, that it's easy to find.

**Comment by hannahkane** [comment]
I'm +1 on this, especially the "What to Expect" page. Less sure of the "About" page. @Saallen - what do you think?

**Comment by Saallen** [comment]
I would be happy for the What to expect page to move up to top navigation bar to join Tickets and location. The About page can stay on the botton section.

Just noticed on the botton of the About page there is a CTA to submit a proposal- can we get this removed @hannahkane ?

**Comment by hannahkane** [comment]
Closing this, as I opened two separate, specific tickets to cover the details contained above

**Comment by hannahkane** [comment]
For reference, they are: #229, #230
