### ISSUE TITLE
Prepare data to feed the Schedule app

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#219]
I wanted to start an issue for @mmmavis to outline how she would like the info prepared ffor the export from Gihub of MozFest sessions. What format should we have the information in and will we need new issues for each?

**Comment by mmmavis** [comment]
Hey @Saallen , 

I suppose this is for feeding data to the Schedule app?

Question: After sessions have been selected do you plan to put them on a consolidated list (e.g., Google Spreadsheet)? Or they will stay as GitHub issues with special labels etc?

**Comment by Saallen** [comment]
Yes @mmmavis I believe we will need to put all the data on a spreadsheet before we import to schedule application. cc @ryanpitts for confirmation

**Comment by ryanpitts** [comment]
Yep, migrating accepted sessions into a spreadsheet will make life a lot easier. There will be a few columns of metadata that need to be added, like schedule block, start time, physical location, etc. Having it all in a spreadsheet will give one spot where edits can be made all the way up to and during the event.

Ultimately the schedule app needs a flat JSON file, which is easy to export (and re-export after changes) from a Google spreadsheet. I have a Python script that can help automate that part even.

**Comment by mmmavis** [comment]
implementation ticket for Schedule app: https://github.com/mozilla/2015.mozillafestival.org/issues/196

**Comment by mmmavis** [comment]
> Yep, migrating accepted sessions into a spreadsheet will make life a lot easier. There will be a few columns of metadata that need to be added, like schedule block, start time, physical location, etc. Having it all in a spreadsheet will give one spot where edits can be made all the way up to and during the event.

> Ultimately the schedule app needs a flat JSON file, which is easy to export (and re-export after changes) from a Google spreadsheet. I have a Python script that can help automate that part even.

Wooohoooo lovely!  Will find you when I reach that stage @ryanpitts :+1:

**Comment by mmmavis** [comment]
@Saallen question for you: do all sessions have the same duration? I was just looking at the [Schedule app finalized mockups](https://github.com/mozilla/2015.mozillafestival.org/issues/180#issuecomment-143294874) and realized we didn't mention anything about the physical space (eg., room number?) and the duration of each session. Would you like to have these info displayed?

**Comment by Saallen** [comment]
@mmmavis Yes- we are requesting that all sessions are one hour in lenght.
The schedule app will need to highlight
* Session name
* Session agenda
* Facilitator, twitter handle and organisation
* location
* start time
* Pathway
* do we need space? @thornet

**Comment by Saallen** [comment]
@mmmavis how many words will each sessions agenda be? I will need to start sourcing this info from the team so it would be good to prep them

**Comment by thornet** [comment]
Note that some sessions will have multiple pathways.

Do we have any opinions on how to display sessions/experiences that run
longer than 1 hour?

On Thu, Oct 15, 2015 at 2:59 PM, Sarah Allen <notifications@github.com>
wrote:

> @mmmavis <https://github.com/mmmavis> how many words will each sessions
> agenda be? I will need to start sourcing this info from the team so it
> would be good to prep them
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/219#issuecomment-148377197>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by cassiemc** [comment]
@mmmavis Let's discuss this at stand today with @adiladil if you need some ux/ui input. If not, full steam ahead :)

**Comment by mmmavis** [comment]
@Saallen 
> @mmmavis how many words will each sessions agenda be? I will need to start sourcing this info from the team so it would be good to prep them

I think technical-wise there's no cap on the length of text we are displaying.  From the [mockups](https://github.com/mozilla/2015.mozillafestival.org/issues/180#issuecomment-143294874) we show description of a session on the "Spaces" and "Pathways" pages only. Maybe ~100 words would work out well?

**Comment by mmmavis** [comment]
Um, just realized there will be [detailed session profile pages](https://cloud.githubusercontent.com/assets/11046943/10107432/f9ab83b8-6388-11e5-9d91-2f9730637abd.jpg) too. Maybe we can ask the team to provide summary(under 100 words) as well as detailed description to be displayed on the session profile pages?

**Comment by thornet** [comment]
Flagging here again that many sessions will be part of multiple pathways, so we'll need a way to indicate that.

**Comment by Saallen** [comment]
Hey @mmmavis 
How do we export the info from Github to Google spreadsheet?
Can we pull from a comment on a issue? Even if the commment is not the first one on the issue.

**Comment by thornet** [comment]
I'd suggest we have the wranglers update the top comment in each issue. You
can revise the text and that can be a good default.

On Sat, Oct 17, 2015 at 2:22 PM, Sarah Allen <notifications@github.com>
wrote:

> Hey @mmmavis <https://github.com/mmmavis>
> How do we export the info from Github to Google spreadsheet?
> Can we pull from a comment on a issue? Even if the commment is not the
> first one on the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/219#issuecomment-148913157>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by cassiemc** [comment]
This issue needs an assignee. Who's responsible @hannahkane? Looks like @Saallen or @mmmavis

**Comment by cassiemc** [comment]
Blocking #196

**Comment by hannahkane** [comment]
If I understand this issue correctly, it's now up to @Saallen to help corral the Space Wrangler and Pathfinders to update the spreadsheet that @mmmavis made, so assigning to @Saallen. If that's wrong, please feel free to correct.

**Comment by Saallen** [comment]
Yes , we hopefully will have this done before the end of the week- CC @mmmavis Michelle sent over an email earlier with more questions about the export and next steps

**Comment by hannahkane** [comment]
The end of the week feels like it's cutting it really close. Could we set an earlier deadline?

**Comment by thornet** [comment]
I suggest we do the following: 

* Get the data showing up now in the in schedule app. This would allow us to do testing and to promote the festival (we'd still like to sell another 200 tickets, and this would help a lot). We can message that the schedule is tentative for now. 
* Meanwhile, the wranglers can continue to refine the sessions in the spreadsheet. Timing and location will come in on a rolling basis.  

@mmmavis @hannahkane what do you think?

**Comment by cassiemc** [comment]
@mmmavis @hannahkane Is this mostly done, ie. can we file any followup issues separately?

**Comment by hannahkane** [comment]
I think we can close.
