### ISSUE TITLE
Copy on /volunteer

### ISSUE THREAD

**Issue by SpikeUK** [mozilla/2015.mozillafestival.org#220]
The last line of body text on /volunteer reads "The MozFest team meets bi-monthly in Mozilla’s London office, so come say hi and learn more. The next Mozpub is in September..." can we please change this to "The MozFest team meets bi-monthly in Mozilla’s London office, so come say hi and learn more. The next Mozpub is in October..."
Thank you

**Comment by hannahkane** [comment]
@mmmavis - are you able to make this change today? Let me know if you want me to put a ticket in teach.moz.org repo for tracking.

**Comment by SpikeUK** [comment]
Actually STOP! My error, we ARE having a MozPub in October - do please excuse me :( :( :(

**Comment by hannahkane** [comment]
@SpikeUK - it sounds like we *do* need a change, so that it reads October, is that right?

**Comment by SpikeUK** [comment]
Erm, er, sorry. Yes @hannahkane we do actually need to change the copy as per my original comment four days ago.
Apologies for the confusion :( :(

**Comment by hannahkane** [comment]
ok - @mmmavis - are you able to do this one today?

**Comment by mmmavis** [comment]
yup, working on it now

**Comment by SpikeUK** [comment]
Thank you @hannahkane and @mmmavis - sorry for my confusing messages earlier ^^
Spike
