### ISSUE TITLE
Outline main stage narrative

### ISSUE THREAD

**Issue by thornet** [mozilla/2015.mozillafestival.org#221]
Currently: 

## Welcome to Mozfest (Saturday morning) - 1 hour. 

* Music/dance/ice breaker: 7min
* Framing. Why are we here? The journey so far: 15min
* Case Study. What's possible at Mozfest?: 7min
* Space Wrangler cheer. 15min
* How to participate. 7min

## Conversation (Saturday lunchtime) - 1 hour

* On ecosystems. The most pressing issues of the day and Mozilla's role. 

## Conversations with diverse leaders (Saturday evening) - 2 hours

* Networked learning and local action (features learning and advocacy leaders): 30min + Q/A
* The inclusive web (features young people and L10n): 30min + Q/A
* Leading in the open (features fellows): 30min + Q/A

## Tomorrow's web (Sunday morning) - 1 hour

* The web we lost: 15min
* The web we want: 15min  
* What we made so far: 10min 
* Group photo: 10min

## Conversation (Saturday lunchtime) - 1 hour

* tbd

cc @Saallen @HPaulJohnson @KevZawacki @edrushka @benrito to review.

**Comment by KevZawacki** [comment]
@thornet wondering how the tentative Medium-led sessions fit in (outlined [here](https://docs.google.com/document/d/1F-qIP_z1BdqvrEWQXM8UYgv82YriutFeBe48UNV1Wdw/edit) in section I). 

Can/should we position the Saturday evening talks you list into interview format?

**Comment by thornet** [comment]
@KevZawacki yes, was thinking the Sat. evening pieces would be moderated by Medium. I can update the outline to better fit the Medium pitch.

**Comment by KevZawacki** [comment]
Or, we can update the Medium pitch to adhere to this outline. Whatever you think works best!

**Comment by thornet** [comment]
Let's have Medium fit this narrative. Good feedback from Mark that this is going in the right direction, although anticipate a bit of refining from him.

**Comment by KevZawacki** [comment]
Thanks for the guidance, @thornet. I've updated our [Medium doc](https://goo.gl/oLqmnp) accordingly. Should we ship to Gabe to take a look? Anyone else on our side need to take a look first?

cc @HPaulJohnson @Saallen

**Comment by thornet** [comment]
Let's do it! In parallel, I suggest we start populating a list of people
who can speak in these slots and lock 'em in.

On Wed, Sep 30, 2015 at 8:50 PM, Kevin Zawacki <notifications@github.com>
wrote:

> Thanks for the guidance, @thornet <https://github.com/thornet>. I've
> updated our Medium doc <https://goo.gl/oLqmnp> accordingly. Should we
> ship to Gabe to take a look? Anyone else on our side need to take a look
> first?
>
> cc @HPaulJohnson <https://github.com/HPaulJohnson> @Saallen
> <https://github.com/Saallen>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/221#issuecomment-144505186>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by HPaulJohnson** [comment]
Added a few comments in doc but ready to ship.

@thornet is there a place where we are collecting a list of possible speakers? If not, I'll create one to get that started.

**Comment by thornet** [comment]
Here's an initial pass for potential speakers:
https://festival.etherpad.mozilla.org/pleasecometotheparty

On Wed, Sep 30, 2015 at 10:13 PM, Paul Johnson <notifications@github.com>
wrote:

> Added a few comments in doc but ready to ship.
>
> @thornet <https://github.com/thornet> is there a place where we are
> collecting a list of possible speakers? If not, I'll create one to get that
> started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/221#issuecomment-144526766>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by KevZawacki** [comment]
@thornet Great line up -- just added my two-cents to the pad.

**Comment by thornet** [comment]
Closing as this as been vetted and is in action!
