### ISSUE TITLE
Create 2015 mozfest style guide

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#222]
This bug is about documenting what we have so that we can hand it off to our Wayfinding design contractor. You can base the template off of last year's: https://www.dropbox.com/home/Mozilla%20Festival%202014/MozFest%20Previous%20festival%20Design%20Assets?preview=mozfest_colour_typography_sheet.png

New styles should be building off the 2015 website, and should maintain the red and blue palette in the first row of the link above.

https://2015.mozillafestival.org

**Comment by cassiemc** [comment]
This should not take more than an hour or two to complete.

**Comment by adiladiladil** [comment]
![mozfest 2015 style guide-01](https://cloud.githubusercontent.com/assets/11046943/10144597/82b8908c-65ec-11e5-89e7-47315b66ed4d.png)

**Comment by cassiemc** [comment]
@adiladil we need to keep the red from the original guide because we are reusing some old printed banners. So we will really need to figure out how to make the pink and red work together. What about including the green from https://2015.mozillafestival.org/tickets and the brighter green from https://2015.mozillafestival.org/guidelines. It also seems like the oranges don't totally represent the feel we're going for. Maybe showing colors as gradients would be better – á la https://2015.mozillafestival.org/about

You should also make mention of the icons/illustrations used on the site.

**Comment by cassiemc** [comment]
@Saallen @marcwalsh Can you confirm when we need to provide this to the wayfinding contractor?

**Comment by adiladiladil** [comment]
Here's an update

![mozfest 2015 style guide-01](https://cloud.githubusercontent.com/assets/11046943/10174268/ec5c4e1e-66b6-11e5-8eef-0d1193b1cf51.png)

**Comment by adiladiladil** [comment]
Style guide update

![mozfest 2015 style guide-01](https://cloud.githubusercontent.com/assets/11046943/10174285/074495c4-66b7-11e5-8304-58a0c94ae984.png)

**Comment by cassiemc** [comment]
This is great adil, now just needs iconography. We can add in the Space icons once they are finalized. #213

**Comment by Saallen** [comment]
@cassiemc I dont have a date as of yet.

**Comment by cassiemc** [comment]
@adiladil – might be possible for @natalieworth to help finalize this once the icons are finished. Can you link to the source file here?

**Comment by adiladiladil** [comment]
@natalieworth WeTransferring the source file to you now

**Comment by natalieworth** [comment]
@cassiemc @adiladil  The original template in dropbox (at the top of this issue) is saying that the file doesn't exist. Is it possible to upload it again?

**Comment by natalieworth** [comment]
Draft of Adil's style guide is up on red pen, I'll add the icons once they are finalized:
https://redpen.io/usfbc5d965df379449

cc @adiladil @cassiemc

**Comment by Saallen** [comment]
hey @cassiemc can I share this style guide as is with the wayfinder company- who is not contracted as of yet

**Comment by cassiemc** [comment]
@natalieworth can you update the guide with Adil's icons as they are? Then it'll be complete and @Saallen we won't need to worry about sending them an update later. Shouldn't take but an hour.

**Comment by Saallen** [comment]
:+1:

**Comment by natalieworth** [comment]
@Saallen @cassiemc Added the final icons from Adil and here is the link to the .ai file on google drive: https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0Q2RyV2RQVnJGZ2s/view?usp=sharing

**Comment by natalieworth** [comment]
@cassiemc I've got the final style guide up on redpen: https://redpen.io/singles (The original layout wasn't in dropbox, so hopefully this template is similar) Thanks

cc @Saallen The final .ai file is here: https://drive.google.com/open?id=0B20-0lpP23c0czdPaGlfdFV4Unc

**Comment by cassiemc** [comment]
@natalieworth Can you repost the redpen link please? The one above just linked to the 'singles' page. The .ai file looks good but we need to update the Youth Zone icon.

**Comment by natalieworth** [comment]
@adiladil Could you link/ transfer me the final file again for the icons for the style guide? I believe the youth zone icon was updated again. Thanks

**Comment by adiladiladil** [comment]
@natalieworth emailing you updated file now

**Comment by natalieworth** [comment]
Hi @cassiemc, updated Style Guide up on redpen with new icons added: https://redpen.io/p/kw55b77d9dd770513b

**Comment by cassiemc** [comment]
Perfect @natalieworth! Can you post the final .eps file here then we'll close?

**Comment by cassiemc** [comment]
@natalieworth can you also shrink the design on redpen to 2x?

**Comment by natalieworth** [comment]
@cassiemc Final design is smaller on redpen: https://redpen.io/p/kw55b77d9dd770513b
If everything is okay with the design, I'll post the eps link here too

**Comment by cassiemc** [comment]
Looks good @natalieworth

**Comment by natalieworth** [comment]
Hi @Saallen , I've uploaded the final .eps file in the google drive: https://drive.google.com/open?id=0B20-0lpP23c0UzVaMUlBdTgzYW8

@cassiemc Is it good to close this issue?

**Comment by cassiemc** [comment]
Yep well done @natalieworth, thanks!
