### ISSUE TITLE
Design Sponsorship Banner

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#223]
@marcwalsh @Saallen Can you let us know the final sponsorship size and logos (will need vectors). We will still plan to have this ready for printing for October 19.

**Comment by Saallen** [comment]
@cassiemc At present we have one potential partnership  with Medium. I am waiting on a call to confirm the status of this partnership. @KevZawacki did we include the logo placement on the main stage as part of this partnership deal?

**Comment by KevZawacki** [comment]
@Saallen Logo placement TBD. @HPaulJohnson, thoughts?

**Comment by cassiemc** [comment]
@HPaulJohnson @Saallen Does medium still need a big banner? Should the mozfest logo be on this banner as well?

**Comment by HPaulJohnson** [comment]
It is still an open question as we are working through details with Medium next week. That said, I don't think this will be needed as the scope of their involvement is narrowing to a single, hosted conversation on Saturday evening. I think we can probably just represent their involvement on the screens on stage by having a graphic that says "A conversation with Medium" or something like that. The other place where their brand might show up is in the online agenda/program, again around the Saturday evening talks.

**Comment by cassiemc** [comment]
@HPaulJohnson Do you think we'll need this?

**Comment by HPaulJohnson** [comment]
@cassiemc We don't need to do this for Medium. We can use the screens during the Sat night conversations to represent the partnership but doesn't need to be any broader than that or in any of the print materials. 

cc/ @KevZawacki

**Comment by cassiemc** [comment]
Thanks @HPaulJohnson!
