### ISSUE TITLE
Design MozFest Posters

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#224]
* last year was one side of our festival guide
* incl. key rallying points from mark's speech
* times / locations
* adds cohesive feel to overall venue
* need to involve @HPaulJohnson /  @KevZawacki 

Can be printed up to the event b/c will be done on-site. cc @Saallen @hannahkane @marcwalsh

**Comment by cassiemc** [comment]
This should be the back of the Event Festival Guide #212

**Comment by marcwalsh** [comment]
It would be great to have these as a separate file alongside the festival guide for when printing onsite.

**Comment by cassiemc** [comment]
Good call thanks @marcwalsh.

**Comment by adiladiladil** [comment]
Here are the sketches for the back of the festival guide (festival poster)
https://redpen.io/p/qk2adb94ee9367c3cc

**Comment by adiladiladil** [comment]
![mozfest-2015-programme_v5-cover-1_poster_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578931/416c2e2e-7643-11e5-9c62-3b2df4de4c08.jpg)
![mozfest-2015-programme_v4-cover-1_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578930/416b54c2-7643-11e5-82f5-d78c969d81db.jpg)
![mozfest 2015 programme_v3 cover 1_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578929/416adf7e-7643-11e5-9fb2-c2c7ffdd8d25.jpg)
![Uploading MozFest 2015 PROGRAMME_V2 Cover 1_POSTER_POSTER.jpg…]()
![Uploading MozFest 2015 PROGRAMME_V1 Cover 1_POSTER.jpg…]()

**Comment by adiladiladil** [comment]
![mozfest-2015-programme_v5-cover-1_poster_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578946/50d434ba-7643-11e5-8b6a-588df80db134.jpg)
![mozfest-2015-programme_v4-cover-1_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578947/50d58a9a-7643-11e5-8e01-cc975da65ec7.jpg)
![mozfest 2015 programme_v3 cover 1_poster_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578944/50d2da16-7643-11e5-819e-6673d58f466c.jpg)
![mozfest 2015 programme_v2 cover 1_poster_poster](https://cloud.githubusercontent.com/assets/11046943/10578945/50d39c58-7643-11e5-92b0-c0a78bd8486a.jpg)
![mozfest 2015 programme_v1 cover 1_poster](https://cloud.githubusercontent.com/assets/11046943/10578948/50d9d4b0-7643-11e5-9ceb-c49988c36243.jpg)

**Comment by cassiemc** [comment]
@adiladil Cool choices. I'm feelin' that https://redpen.io/xgec28e91aae16a0f3 is the most on-brand and easiest to decipher while the others are cool options too. The redpen is 2x still so hard to leave comments on it, but wondered if we could group the date and location on one side (leave the other side open for whitespace), replace the text 'mozfest' with the logo, and play with the transparency of the white text where it overlaps the pink boxes so it is easier to read still.

@lovegushwa wondering if you have thoughts here.

Look forward to seeing the other side with the map & space details... I think that will be the more difficult part, and will need the most eyes on it to make sure it's accurate.

**Comment by adiladiladil** [comment]
@cassiemc just updated the redpen with smaller versions to annotate

**Comment by lovegushwa** [comment]
@cassiemc which version are you referring to as most on-brand? 
(redpen links to the thumbnail view of all the posters.)

**Comment by cassiemc** [comment]
@lovegushwa just left a comment on the redpen. This one: https://redpen.io/jt44765c0a34dfe43d
<img width="988" alt="screen shot 2015-10-19 at 3 36 03 pm" src="https://cloud.githubusercontent.com/assets/1186326/10589046/225aa162-7677-11e5-8bd7-5dc98e1630ef.png">

**Comment by lovegushwa** [comment]
@cassiemc cool. This version lends itself to environmental graphics nicely (large punchy vinyl blocks of text.) It should be a good and needed typographic extension to the visual system.

Regarding the conceptual directions; A. and B. give a nod to the hand done hackable Mozfest aesthetic.
F. highlights the fun and importance of Mozfest in London and probably has the most stick around on peoples walls after the event quality.

E. is typographically punchy, and visually spot on, but lacks a hackable / weby conceptual hook. What if we turn these into kind of madlib / fill in the blank posters and invite participation?

![screen shot 2015-10-19 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/12228435/10589648/499ed466-7661-11e5-9199-f4a460ac60b6.png)

CC @adiladil @marcwalsh

**Comment by adiladiladil** [comment]
@cassiemc @lovegushwa 

I REALLY like that idea. the text edit box could be slightly modified to fit the aesthetic of the rest of the design. I think it's great, fun, participatory, hack-centric

what does everyone else think?

**Comment by HPaulJohnson** [comment]
+1 that idea. i've seen signage used in this way before and it's a really powerful way to show the diversity of the community and the work itself.

**Comment by hannahkane** [comment]
<3

**Comment by cassiemc** [comment]
me too, <3 it! Awesome idea!

**Comment by thornet** [comment]
Love it! 

For a more inclusive, collective title, "Let's make a ___ web."

**Comment by adiladiladil** [comment]
![mozfest-2015-programme_v1_poster](https://cloud.githubusercontent.com/assets/11046943/10613824/efac313c-7724-11e5-967e-2f44f9f41e49.gif)

**Comment by thornet** [comment]
omg, so cool. i also love the gif version!

**Comment by cassiemc** [comment]
Seriously!!! @natalieworth @HPaulJohnson We should incorporate the gif into the social graphics somehow. Maybe a third option.

**Comment by natalieworth** [comment]
Yes! This is awesome @adiladil Love it!

**Comment by natalieworth** [comment]
@adiladil Could you WeTransfer the file and fonts for these and I can do something for the MozFest social graphics with these? Thanks!

**Comment by lovegushwa** [comment]
@cassiemc @adiladiladil @HPaulJohnson @edrushka @thornet @natalieworth @marcwalsh 

YES! 
I think we have cracked out social share AND some motion we can run on main stage screen between speakers. 

... It would be cool to develop a set of phrases in addition on the poster that people fill in. Perhaps more than one blank. Could have a different phrase every day to fill out in the morning, we scan or photograph the cards, then build a sequence to share on the main stage screen later in the day (might tie into video documentation nicely as bumpers, could turn into a live gif that's updated on the website every day during the conference.) 

And for the poster. One thing that's cool about the blank (also the acronym MOFO) is the dance around cursing. "Let's make a BLANK web." ... Let's play this up. Were not inviting people to drop the F bomb, but a little sub conscious hint at fist glance could give these posters some edge. ... Maybe just dropping the Pen icon would do this (or make it very subtle). We attach a pen next to the poster, so people get they can write on it.

**Comment by adiladiladil** [comment]
@natalieworth just WeTransfered you the file
the handwritten fonts i just did on paper and took into the computer

**Comment by lovegushwa** [comment]
Nice casual handwriting that looks good enough to be 5 different distressed typefaces @adiladiladil
A - Z plus some punctuation and I can knock out a typeface in an evening? I'm serious!

**Comment by adiladiladil** [comment]
I'll put those together then @lovegushwa

**Comment by lovegushwa** [comment]
@adiladiladil rad

**Comment by HPaulJohnson** [comment]
love this, and love the idea of turning this into social graphic and incorporating into the running video on main stage.

**Comment by Saallen** [comment]
:heart:  these designs- and how they can be translated to the main stage too.

**Comment by adiladiladil** [comment]
@lovegushwa here is the link to the handwritten A-Zs

http://we.tl/8PJS9qV1uo

**Comment by lovegushwa** [comment]
Excellent @adiladiladil let me see what I can do with these tonight.

**Comment by lovegushwa** [comment]
@adiladiladil let me know if this is useful.
https://drive.google.com/folderview?id=0B2qu3ExKWIlvWS1SMzctQ1d5OWc&usp=sharing

**Comment by adiladiladil** [comment]
@lovegushwa sweeeeeet. we can definitely now use this as a afont

**Comment by lovegushwa** [comment]
@adiladiladil if you had to prioritize another script or two which would it be?

**Comment by adiladiladil** [comment]
@lovegushwa I would do MozFont 3 and MozFont 5

**Comment by lovegushwa** [comment]
@adiladiladil where did you get this pattern? (or did you make it?) Can I get a copy?
<img width="586" alt="screen shot 2015-10-21 at 10 52 06 am" src="https://cloud.githubusercontent.com/assets/12228435/10645293/debd09c4-77e1-11e5-9c05-1d16a4fbed09.png">

**Comment by adiladiladil** [comment]
it's on Getty Images. if we were to use it we would have to purchase

http://www.gettyimages.com/detail/illustration/london-uk-royalty-free-illustration/166373822

**Comment by mmmavis** [comment]
tagging @Pomax cuz he has some brilliant insights on this

**Comment by cassiemc** [comment]
I'm going to close this since the assets were delivered with the festival guide. #212
