### ISSUE TITLE
Design tote bags

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#225]
Any idea what the specs are for these? @Saallen @marcwalsh cc @hannahkane

**Comment by marcwalsh** [comment]
@cassiemc see attached image for last year - We are going with just natural cotton, with a print on the front. It can be up to full colour however it's price dependant. 

Link to product is here:
https://thecleverbaggers.co.uk/natural-cotton-carriers-with-long-handles

See previous work below, but it's been very similar to this over the previous years so it would be great to shake it up a little! :) 

![fullsizerender](https://cloud.githubusercontent.com/assets/14007066/10142713/34c69624-660c-11e5-888f-6c69a37a11db.jpg)

**Comment by marcwalsh** [comment]
Looking at costings, we need to stick to a 1 colour print. If that's alright? @cassiemc

**Comment by cassiemc** [comment]
Perfectly fine @marcwalsh thanks!

**Comment by marcwalsh** [comment]
@cassiemc The same with these the milestone is too late for the print deadline. These need to be sent to print on the 9th October.

**Comment by cassiemc** [comment]
@marcwalsh I see october 12th in the spreadsheet?

**Comment by adiladiladil** [comment]
![tote2](https://cloud.githubusercontent.com/assets/11046943/10174783/8cd05488-66b9-11e5-8b28-f0a741793582.jpg)
![tote3](https://cloud.githubusercontent.com/assets/11046943/10174782/8ccd65ac-66b9-11e5-8265-b85a150079ee.jpg)
![tote1](https://cloud.githubusercontent.com/assets/11046943/10174784/8cd05668-66b9-11e5-84c2-10e3b6017183.jpg)

**Comment by Saallen** [comment]
I am loving the navy bag with red colour print.

**Comment by cassiemc** [comment]
I love that version too. @marcwalsh Can we print on both sides or just one? Ie. could we have straightforward mozfest logo on one side and more of an icon pattern on the other side? Might be worth saving the icon pattern for the t-shirts #208 so those are preserved as super special.

**Comment by cassiemc** [comment]
@marcwalsh I noticed in your original quote you mentioned we were going with natural cotton. Is there a way to get navy with pink?

**Comment by cassiemc** [comment]
@marcwalsh can you comment on the material / options for this?

**Comment by marcwalsh** [comment]
@cassiemc  - They do have navy and a pink print is possible as well, just waiting to get a new quote from the suppliers to check price difference.

**Comment by cassiemc** [comment]
Thanks @marcwalsh!

**Comment by marcwalsh** [comment]
@cassiemc  - Looking at the prices I've got back from the supplier it doesn't look like we will be able to do the coloured bag and colour print. Can we just stick to the natural bag and single colour print... Sorry!

**Comment by cassiemc** [comment]
No worries! cc @adiladil ^^

**Comment by adiladiladil** [comment]
![tote2](https://cloud.githubusercontent.com/assets/11046943/10376940/889aa410-6dce-11e5-943a-b7c812d031a8.jpg)
![tote1](https://cloud.githubusercontent.com/assets/11046943/10376941/88a4305c-6dce-11e5-9547-8f8fe447ad24.jpg)

**Comment by cassiemc** [comment]
I dig the second more abstract design for the tote! Would pink work instead of red?

**Comment by adiladiladil** [comment]
@cassiemc absolutely. i dont know why its showing up more red than pink here but it should be the same PMS color as on the MozFest site

**Comment by adiladiladil** [comment]
![tote3](https://cloud.githubusercontent.com/assets/11046943/10377065/3113f024-6dcf-11e5-9f9b-893ef6898654.jpg)

**Comment by Saallen** [comment]
:heart: :heart_decoration: :heart_decoration: ..incase you dont get it i LOVE these designs. Great job Adil. I wonder though about the youth icon, did you settle on something different last night?

**Comment by cassiemc** [comment]
@SaallenI love these too! I think I like the more random version in https://github.com/mozilla/2015.mozillafestival.org/issues/225#issuecomment-146659750. @adiladil made a new youth icon today, I believe @hannahkane emailed you about it. If we are good to go with that new one then we just need to update it here.

**Comment by marcwalsh** [comment]
Hey @cassiemc @adiladiladil, I need the artwork for these today to ensure that we have the bags delievered on time for the festival. Are you able to update this with the latest version of the youth icon and then send over the vectorised file please?

**Comment by cassiemc** [comment]
@adiladil can you provide the final vector artwork here?

**Comment by adiladiladil** [comment]
Here is the design for the tote
![mozfest-tote](https://cloud.githubusercontent.com/assets/11046943/10459108/0c7b614a-719c-11e5-9d5d-a419b5d13e14.jpg)

Here is the link to the vector files:

http://we.tl/3GZGIt0hEe

**Comment by cassiemc** [comment]
@adiladil There's a cluster of dots overlapping on the lefthand side of this poster, the lines emanating from the learning networks icon, and the newspaper seems as though it should be a bit higher to be centered amongst its emanating lines. Can you quickly go over that area with a fine-tooth comb?

**Comment by adiladiladil** [comment]
How does this look?
![mozfest-tote-new](https://cloud.githubusercontent.com/assets/11046943/10459739/e5a713f4-719e-11e5-9204-db574970db91.jpg)

**Comment by cassiemc** [comment]
@adiladil much better, thank you thank you! Can you link us to the final vector files?

**Comment by adiladiladil** [comment]
@cassiemc @marcwalsh here is the newest link for tote design:

http://we.tl/ZSmUc13SER

**Comment by cassiemc** [comment]
Thanks @adiladil! @marcwalsh please let us know if you need anything else, otherwise we should be good to close this ticket.

**Comment by marcwalsh** [comment]
Double checking with printers, will let you know ASAP

**Comment by marcwalsh** [comment]
Art work is great and the printers are happy. 

Good to close!

Thanks @cassiemc & @adiladiladil !

**Comment by cassiemc** [comment]
Woohoo!!! :cake: Thanks @marcwalsh, and big thanks @adiladil
