### ISSUE TITLE
Create social share graphics for Mozfest

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#226]
@KevZawacki Hopefully I'm not repeating a ticket here.

We want:
- [ ] 1 facebook social share graphic
- [ ] 1 twitter social share graphic 

A template for this is here: https://drive.google.com/folderview?id=0B4Q8pzCpDS_efmdTWVlCOXF2b0c3NUJreElJYVphLUtGNHVWemo0aXQyRDB1UFRubXVFdTA&usp=sharing

@HPaulJohnson When will you need this by for the Comms plan?

**Comment by KevZawacki** [comment]
Porting in info from an earlier, [poorly-placed ticket](https://github.com/MozillaFoundation/plan/issues/568):

    Should include date (Nov. 6-8) and location (London)
    Can draw on/be inspired by our trove of MozFest photos
    Possible copy: "Shape the future of the Web at MozFest 2015."

Aim for Oct. 5 completion? @cassiemc @HPaulJohnson

Lessons learned from Thimble/Webmaker social graphics

    Less copy = more engagement. Graphics like this perform best, compared to graphics like this.

    Illustrations > actual photos / screenshots

**Comment by cassiemc** [comment]
@KevZawacki I see you asked for Oct 12, was there a specific reason in mind (ie do we need that much lead time, maybe these are being used to sell tickets?) We had a bunch of print stuff bump up to the oct 9 milestone but could get @natalieworth to help us out here.

**Comment by KevZawacki** [comment]
@cassiemc OK by me to push back a bit -- no hard deadline. Just wanted to make sure we have a couple weeks before MozFest during which we can use the graphic.

**Comment by natalieworth** [comment]
Social share graphic iteration updates: https://redpen.io/p/mj9d57297ec1f7d435
Based on the design feedback yesterday, is it necessary to add more context within the image about the event ( e.g. where it is located or something like "buy tickets")? Or would the context be provided within the facebook/ twitter status?

cc @cassiemc @hannahkane @adiladil

**Comment by cassiemc** [comment]
@natalieworth As discussed in today's stand I don't think you need to add any more context wrt. to buy tickets. Can you confirm that @HPaulJohnson?

Design-wise, I'm not sure any of these are on the mark just yet. Would love to see some versions that are a little lighter, more energetic. The photos currently are a bit dark. It might be great to zero in on ONE person having an absolutely amazing time. Or we could continue down the icon route, but I'd suggest more colour.

**Comment by natalieworth** [comment]
Thanks @cassiemc, yeah I feel like the content is fine too. I feel images are stronger too for social sharing over heavy text. I'll explore the icon/ illustrative route with colours and look for more engaging photos. :)

**Comment by HPaulJohnson** [comment]
No need to add any more context around buying tickets. In fact, keeping them more generic allows us more flexibility to use them in lots of different ways. 

+1 to the comment about surfacing emotion and energy and zooming in on one or a small group of people. I like using photos and doing this with real people but we can always try different things and see what works bets.

**Comment by natalieworth** [comment]
Hi @cassiemc, updated some iterations on redpen: https://redpen.io/p/mj9d57297ec1f7d435

I also sourced these photographs from previous MozFest's that could work well based on @HPaulJohnson feedback: 
https://www.flickr.com/photos/sproutfund/9616924192/in/faves-47833020@N03/
https://www.flickr.com/photos/sharma_akash/9112550310/in/faves-47833020@N03/
https://www.flickr.com/photos/paul_clarke/8174891973/in/faves-47833020@N03/
https://www.flickr.com/photos/mozillaeu/8171964452/in/faves-47833020@N03/

Thanks

**Comment by natalieworth** [comment]
Hey @cassiemc, I've updated the pattern background, colours, and type style based on feedback. I'll keep working on these til the end of our day, so I may have a couple more/ refinements to upload tomorrow morning. Thanks
https://redpen.io/p/mj9d57297ec1f7d435

**Comment by cassiemc** [comment]
Nice @natalieworth!! I'm really liking the new patterns and colors, thanks. Left some comments on the redpens, but we are definitely getting a lot closer with this round.

**Comment by cassiemc** [comment]
@natalieworth Saw this and thought it might be good inspiration for the patterned option. 
<img width="484" alt="screen shot 2015-10-15 at 4 29 42 pm" src="https://cloud.githubusercontent.com/assets/1186326/10526630/1202592e-735a-11e5-881b-4b1ddc367cdd.png">

**Comment by natalieworth** [comment]
Hi @cassiemc, new pattern is up on redpen based on the example above: https://redpen.io/p/mj9d57297ec1f7d435
I'm liking the consistency in stroke weight and subdued colours in the example above, so I tried to make the updated pattern more cohesive with the icon designs and the other illustrations on the MozFest 2015 website. Thanks

**Comment by natalieworth** [comment]
Hi @cassiemc refined pattern and sharing images up on red pen: https://redpen.io/p/mj9d57297ec1f7d435

Thanks!

**Comment by cassiemc** [comment]
@natalieworth These are good. Solid options, and I like the Fira weights. Now just to finalize the photo option.

**Comment by natalieworth** [comment]
Hey @cassiemc , I've got some more photo iterations up on the red pen for the social sharing graphics: https://redpen.io/p/mj9d57297ec1f7d435

**Comment by cassiemc** [comment]
@natalieworth Fab! Nearly there, love the circle options with the dotted lines, and I like the other one too with the icons over the one photo. @lovegushwa want to weigh in?

**Comment by natalieworth** [comment]
@cassiemc Revised photographic designs are up on redpen: https://redpen.io/p/mj9d57297ec1f7d435 Thanks

**Comment by natalieworth** [comment]
Hi @cassiemc , updated social share designs on redpen (they're the last 6 options): https://redpen.io/p/mj9d57297ec1f7d435

If they're good to go I can export the different file sizes for the twitter and facebook resolutions.

**Comment by cassiemc** [comment]
@natalieworth R+. Let's go with artboard 97, 98, and 102. You can export the others as well, but in case @HPaulJohnson and @KevZawacki need a quick choice, let's use those ones. Can you post all 6 here as well, natalie? Thanks for all your hard work on this, they're stellar! I will file a new bug to make the gif social share image based on the poster.

**Comment by natalieworth** [comment]
Hey @cassiemc @HPaulJohnson @KevZawacki , I put the final png files for the twitter and facebook social sharing graphics up on the google drive. The first 3 options in each file are the main choices, but I have uploaded the other options as well. Thanks! https://drive.google.com/open?id=0B20-0lpP23c0TERlaFlNMU9MSWs

**Comment by natalieworth** [comment]
![mozfest_facebook_final_01](https://cloud.githubusercontent.com/assets/14876567/10648340/b45c4de6-77f2-11e5-8eec-7c7cbce0992a.png)
![mozfest_facebook_final_02](https://cloud.githubusercontent.com/assets/14876567/10648341/b45c956c-77f2-11e5-90e2-5a56ef0e5478.png)
![mozfest_facebook_final_03](https://cloud.githubusercontent.com/assets/14876567/10648342/b45ef0b4-77f2-11e5-9736-caf37484cf0f.png)
![mozfest_facebook_final_04](https://cloud.githubusercontent.com/assets/14876567/10648346/b8ec3d58-77f2-11e5-8015-28f96ade3dab.png)
![mozfest_facebook_final_05](https://cloud.githubusercontent.com/assets/14876567/10648347/b8ec441a-77f2-11e5-89df-d9bf22de89df.png)
![mozfest_facebook_final_06](https://cloud.githubusercontent.com/assets/14876567/10648345/b8ec46b8-77f2-11e5-9a75-8620f1c5c64a.png)

**Comment by cassiemc** [comment]
Great work @natalieworth. @KevZawacki if you confirm this is all you need we can close this sucker. :)

**Comment by HPaulJohnson** [comment]
these look fantastic @natalieworth - excited to put them to use.

**Comment by KevZawacki** [comment]
@natalieworth These are *awesome.* Well done -- can't wait to start posting them this week.

& thanks, @cassiemc, for all your help! These will seriously boost engagement on our MozFest posts.
