### ISSUE TITLE
Design "Our Submission Process" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#227]
Simple page with image at top.

Approved copy is:

Our Submission Process

This year, we're using GitHub to manage, review and curate sessions for MozFest. GitHub allows us to better collaborate and coordinate across the program in an open fashion.

Leading up to the event, MozFest's Space Wranglers will be reviewing all proposals and choosing sessions that best align with their Space objectives. You can follow this process on our GitHub repo.

Unfortunately, not all proposals will be accepted; the weekend simply is not long enough. But there's good news: everyone who proposed a session will be gifted a free ticket to the festival.

**Comment by cassiemc** [comment]
@hannahkane is this one important to complete asap? Not sure what the dependencies are here.

**Comment by hannahkane** [comment]
I think we should do this ASAP. We'll be announcing the final program soon, so people will have questions about how we reviewed the submissions. When we talked about this yesterday with @adiladil, we agreed it's quite simple. The main task is identifying an image to use in the header.

**Comment by cassiemc** [comment]
@natalieworth Can you help us select an image here? You can review the existing photos on the site at 
https://2015.mozillafestival.org/ (there are links in the footer with more pages)

Then browse https://www.flickr.com/photos/mozilladrumbeat/favorites/ to find a good one. Then we'll need to treat it like the existing photos on the site. Just need to make sure it's a crisp photo with good subject-matter (diversity and excitement/positivity are important to Mozfest) and is Creative Commons.

**Comment by natalieworth** [comment]
I've found 3 CC images that I think would work for the MozFest landing page background. All are high resolution/ good quality image sizes for web:

1. https://www.flickr.com/photos/paul_clarke/8171644993/in/faves-47833020@N03/
I think this highlights well the festival and Keynotes. I think it would also work well with the heading/ copy over the image.

2. https://www.flickr.com/photos/paul_clarke/8174891973/in/faves-47833020@N03/
I felt like this image showed engagement, positivity and diversity from a previous MozFest event. The only issue would possibly be editing and avoiding awkwardly laying the copy over anyone's face.

3. https://www.flickr.com/photos/paul_clarke/8175048219/in/faves-47833020@N03/
I felt that maybe this image was possibly too similar to the 2014 image, but I liked that the audience is facing the viewer on the landing page (compared to image 1, which has the audience's back turned). I also think it would also work well with the copy.

@cassiemc Should I gather CC images for each of different pages (e.g. "Tickets," "What to expect," etc.)?

**Comment by hannahkane** [comment]
Thanks, @natalieworth. I definitely want @cassiemc to weigh in on these choices, but I think I prefer the first or second option. The third seems too similar to the homepage image at https://2015.mozillafestival.org

Also, I just noticed that we're currently using the same image for the Tickets page and the Volunteer page. Maybe we should replace the Volunteer page image with one of the above.

**Comment by natalieworth** [comment]
@hannahkane I think these could also work for the volunteer page:
https://www.flickr.com/photos/newyouthcity/10559772014/in/faves-47833020@N03/
https://www.flickr.com/photos/digitalyouthnetwork/12030099454/in/faves-47833020@N03/

**Comment by hannahkane** [comment]
I like the first one. (I also like the second one, but we use it on the Teach site, and don't want to overuse it.) I'll file a separate ticket to replace that photo. Thanks!

**Comment by cassiemc** [comment]
@natalieworth I think there might've been a misunderstanding about what we were sourcing images for. We need to create a new page called 'Our Submission Process', the new copy for that page (which isn't built yet) is outined in comment 1, so we need a new photo for that (we don't need to replace any existing photos on the site).

Can you help us find a photo that demonstrates 'reviewing, selecting, proposing, volunteering, suggesting'? Might be someone with their hand up in a crowd. It might be someone who looks like a 'space-wrangler' who is looking out at a crowd of people. It should get across the idea of "many" being whittled down to "few". I know that is kind of abstract, but it can be a very loose relationship / inspiration for the photo selection.

Let me know if you have any questions here or IRC or in our 1:1 later!

**Comment by natalieworth** [comment]
I think these images could work for the new page. I feel like they represent the keynote/ sessions:
https://www.flickr.com/photos/sharma_akash/9110424907/in/faves-47833020@N03/
https://www.flickr.com/photos/mozillaeu/10490704864/in/faves-47833020@N03/

cc @cassiemc @hannahkane

**Comment by cassiemc** [comment]
I like the first one. @natalieworth could you treat it with the same color treatment and put it into a mockup of one of the existing pages so we can see how it looks proportionally / once cropped? Redpen link once you've done that please!

**Comment by natalieworth** [comment]
@cassiemc @hannahkane @adiladil  Do we have the photoshop file for the mockup?

**Comment by natalieworth** [comment]
Mockup of the image treatment is now on redpen: https://redpen.io/p/ab6b3526abd59e8c4f
cc @hannahkane @cassiemc @adiladil

**Comment by cassiemc** [comment]
@natalieworth Looks great, let's ship it! Can you post the final asset – just the photo – in this bug so @mmmavis can implement the change?

**Comment by cassiemc** [comment]
Actually I got it from the redpen. Here it is @mmmavis:
![img-submission](https://cloud.githubusercontent.com/assets/1186326/10249130/a959a2f0-68f1-11e5-8b67-574dc329961d.jpg)

Final copy is in the first comment.

**Comment by hannahkane** [comment]
Closing this since there's a separate ticket for the build. Thanks, @natalieworth!
