### ISSUE TITLE
  MozFest 2015 site: About page content

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#23]
- [ ] Update Marks speech
- [ ] Program team refresh
- [ ] About Festival paragraph refresh

**Comment by Saallen** [comment]
Updating this page for contact on the last 5 festivals
* 2010
* 2011
* 2012
* 2013
* 2014

Lead@Saallen
Consulted @edrushka @thornet @kevin

**Comment by Saallen** [comment]
**2010 content**
Dedicated to finding, energizing and creating a community of people working with technology to build participation, understanding and control into Internet life

**Comment by Saallen** [comment]
** 2011 **
After a sucessful and exciting first festival, MozFest moved to London hoping to replicate some of the prototypes and community spirit they felt in Barcelona. The festival phrase Arrive with an Idea, leave with a community was born
(@thornet - I am definitley taking creative liberties so please reign me in when I go too off narrative)

**Comment by Saallen** [comment]
**2012**
The festival phrase Arrive with an Idea, leave with a community was born and strong tracks emerged that would shape the narrative of the community. Title such as Build Webmaker and Teach The Web were the call to actions for the community of web entusiasts, educators and activists.

**Comment by Saallen** [comment]
**2013**
A collaborative festival for catalysts, change agents, technologists and creators was creating tools and resources that would shape the webs to come and how we would use it, with the likes of popcorn maker, thimble and open badges

**Comment by Saallen** [comment]
**2014**
With over 1700 people from over 50 countries  unitied to hack on innovative solutions for the web under tracks such as Advocacy and Policy, Art and Culture of the Web and the mobile web MozFest had become an architect of change within the mozilla community.

**Comment by Saallen** [comment]
@edrushka This page has been proofed by Michelle

**Comment by KevZawacki** [comment]
Copy edits for this page available here: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit

They begin on the first page beneath the headline "About page edits."
