### ISSUE TITLE
Remotee Challenge- Remote participation

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#231]
We are building a remote participation page for MozFest- off the success of last year, called Remotee Challenage. 
 @chadsansing has kindly stepped forward to help us curate this piece. 
Chad any other suggestions here of who would like to help?

What we need
- [ ]  Collection of curriculum that relates to our festival narrative that people can enjoy at home or at school
- [ ] Discourse page for people to report back to and/or keep the conversation  going

Found pevious years Remotee challenge - unfortunately at present the discourse page doesnt exist
* https://jess.makes.org/thimble/LTgzMjI4MTY=/mozfest-remotee-challenge

cc @hannahkane cc @cassiemc  cc @thornet

**Comment by Saallen** [comment]
Looping in the lovely and missed @iamjessklein .She kindly offered feedback from last year.
Here's a few points of feedback from last year:

*  The Remotee participation options need to be published and socialized a few weeks before the festival starts so that people are aware of it.
 * I would definitely leverage the Hives as they could be doing mini meetups or hangouts in all of their cities and communities, or just publicize that this is a free option open to all.
* You need staff who are remote as well as staff on site to have the remotees front of mind -  this way the remotee work can be publicized and integrated into the live event (and those in London will be able to join in initiatives started by remotees)
* Having asynchronous challenges worked really well because contributors were coming in from several different timezones - so I would go to sleep and then when I woke up there were responses to things that I posted the night before.
* Badges - motivators work. I just couldn't get them up and running last year, but you should double down on it.
* In retrospect, I felt like I was flying the remotee flag on my own, it would be neat to have remotee ambassadors, and incentives to lead this kind of initiative. 

I really like the mozfest in a box idea, but again, I'd keep in mind that a lot of remotees aren't commiting chunks of time to participate and might be casual participants.

**Comment by Saallen** [comment]
@omnignorant On the 1st Hive point, do you think this could be something we could plan for? Or they might be interested in?
I feel I could have some volunteers helping with the remotee challenge onsite as they would love to be more involved in the social aspect of this.

**Comment by chadsansing** [comment]
@hannahkane - maybe we could brainstorm some Thimble remote challenges w/ lite, fun badges run past folks?

**Comment by hannahkane** [comment]
@chadsansing - love the idea of using Thimble as a remote participation tool (and maybe we could have stations where MozFest participants could create "Wish You Were Here" postcards that we'd share with remotees). It's unlikely we'll have badges up and running by MozFest, though.

**Comment by chadsansing** [comment]
I will knit them. In all (most?) seriousness, though, in lieu of badges maybe we ought to develop some communications or something like an Easter Egg project discoverable by or pushed to remotees who accomplish x.

**Comment by thornet** [comment]
The Digital Me team will be making badges for all the pathways at Mozfest
and people will be able to use their app to collect evidence and get them.
Just flagging as possible overlap point.

On Tue, Oct 6, 2015 at 11:37 AM, Chad Sansing <notifications@github.com>
wrote:

> I will knit them. In all (most?) seriousness, though, in lieu of badges
> maybe we ought to develop some communications or something like an Easter
> Egg project discoverable by or pushed to remotees who accomplish x.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/231#issuecomment-145798627>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by Saallen** [comment]
Looping in @hjbailey as she as a remotee challenge for her localisation Space- Asking people to upload their local language for animal sounds? Also there is a drawing challenge . Aaaand we have a conversation piece/topic for discourse which will feed into what we do in the localisation space over the weekend. Does anyone on this thread have a page/lesson plan we can remix to help build these challenages? cc @chadsansing cc @hannahkane cc @omnignorant

**Comment by hjbailey** [comment]
Remote challenge to see how many languages we can get to participate in a simple translation 
exercise.  Cows, horse, cat, dog, duck goes ... ?

**Comment by iamjessklein** [comment]
It might be interesting to also frame a challenge simply around user testing the tool. For example, try it out by doing x, y, z and file bugs...

**Comment by Saallen** [comment]
Hey the awesome fuzzyfox has volunteered to run this at MozFest with some volunteers \o/

**Comment by Saallen** [comment]
@fuzzyfox has another idea to go alongside these challenages where @soapdog localisation session is expanded beyond the festival so that remotees can localise kts, resources and curriculum at the same time the session on site- If we had a couple of volunteers as moderators with @fuzzyfox wrangling it could work...... :confused:

**Comment by chadsansing** [comment]
The story so far:

- @fuzzyfox facilitates remote work at MozFest.
- @chadsansing & friends curate & develop materials ahead of time to including
  - A localize animals and their sounds challenge.
  - A drawing challenge.
  - A user-testing & bug-filing challenge.
  - A conversation on Discourse.

#amiright, @Saallen?

Suggestions:

- @chadsansing puts together a Thimble project that lets people use the new selfie feature to add hand-drawn pictures of local critters with optional, very general suggestions for uploading those animals sounds by a)finding a recording online or b)uploading users' imitations to Soundcloud. @fuzzyfox & events broadcast it during MozFest.
- @chadsansing puts together a #wishyouwerehere Thimble make for @fuzzyfox & events to broadcast during MozFest.
- @chadsansing puts together a Thimble template asking for help testing recently developed curriculum prototypes & we broadcast it to wranglers and sessions for organizers to remix for requesting testing on their jams during MozFest. @fuzzyfox curates a page linking to different bug-filing opportunities. 
- @Saallen and the intrepid events crew put together a list of, say, 8-10 tweet-length #mozfest #remote questions linked to Discourse threads and auto-schedule them to go out during Mozfest.
- @soapdog briefs @fuzzyfox on our soon-to-be-launched curriculum localization L10n campaign using Andre's .md method which allows novices to cut and paste localized .md translations to GitHub issues or experienced users to localize curriculum in repos by individual language for Andre to pull into Moz land. @soapdog and #fuzzyfox champion and run comms on local and remote MozFest work sprints on this campaign.
- @chadsansing and @fuzzyfox work up a remote challenge page in Thimble or something to link to these challenges.

Feedback? What's missing? Who would like to contribute what?

**Comment by chadsansing** [comment]
What do we think of [Wild about MozFest](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/7293/)?

cc @Saallen, @soapdog, @fuzzyfox, @hjbailey, @hannahkane, @omnignorant, @thornet

**Comment by Saallen** [comment]
Hey looping in @hjbailey for this Wild about Mozfest project- as its very similar to what she wants to achieve as an experience onsite.
:+1: to the proposals @chadsansing

**Comment by chadsansing** [comment]
@Saallen, design & publishing guidance? I'm not anywhere near the dev @iamjessklein is. What's our tolerance for the design aesthetic from Wild About Mozfest? For pages that are all designed differently?

@hannahkane - if we get, say, 4 MozFest remote challenge pages and a content doc ready by 10/23, any chance you can pull them into an official repo/landing page before MozFest? (I feel bad just for asking.)

**Comment by chadsansing** [comment]
Here's another possible challenge: [Test @ the Fest] (http://chadsansing.github.io/curriculum-testing/moz-fest-remote-projects/test-at-the-fest.html). Will work it up into a Thimble project, as well, for remix by other spaces/pathways/teams looking for testing.

**Comment by fuzzyfox** [comment]
@chadsansing All that sounds good to me ;) Also like the look of Test @ The Fest.

@soapdog I should have some time in the week to catch up about the l10n work chad mentioned. Let me confirm day/time options w/ you tomorrow

**Comment by chadsansing** [comment]
How does this postcard remix strike the remote team?

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/7978/

@fuzzyfox, do you feel ready to take over remote challenge wrangling entirely? Does that work for you, @saallen? I want to tweak Test @ the Fest and help with the remote challenge landing page, if I can be  of use, but if Fuzzy is the onsite lead, I'd like to hand over curation- and planning-decision-making to him from here on out.

**Comment by chadsansing** [comment]
Updated the [MozFest Postcard](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/7978/) tutorial.

**Comment by soapdog** [comment]
@fuzzyfox I have time this week for us to catch up! I am still improving the documentation and I've created a task about this L10N campaign work at https://github.com/mozilla/learning-networks/issues/271 (have no idea how to link issues from other repos)

**Comment by chadsansing** [comment]
@fuzzyfox, @Saallen - would be good to connect w/ https://twitter.com/mozfesttimeline for remote participation.

**Comment by ldecoursy** [comment]
Are you all using this thread on MLN Discourse? https://discourse.webmaker.org/c/events/mozfest 

Also, @kgorr can help with @mozteach Twitter stream to support this work too!

**Comment by Saallen** [comment]
hey @chadsansing loving the postcard :heart: just lost 20 mins uploading pictures.
I will connect you with Jon rogers and his kids who are running this page.

**Comment by fuzzyfox** [comment]
@chadsansing I'm happy enough to take on a leading role in wrangling this, however would like to ask that you also remain at the reins too while we finish the curation/planning in the run up to the fest. My available time right now for this is not as high as I'd like it to be if I was taking over entirely.

Also, thanks for the highlight of [@mozfesttimeline](https://twitter.com/mozfesttimeline), I think we should definitely link up w/ them.

**Comment by chadsansing** [comment]
@fuzzyfox, +1s. See [Discourse](https://discourse.webmaker.org/t/testing-needed-remote-challenge-thimble-projects/222/6).

**Comment by chadsansing** [comment]
Updated [Test @ the Fest](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/8541/) on Thimble after merging @fuzzyfox's pull request.

**Comment by chadsansing** [comment]
Let's spin up the narrative on this [landing page](http://chadsansing.github.io/curriculum-testing/moz-fest-remote-projects/index.html).

cc @fuzzyfox, @ldecoursy, @Sallen

**Comment by ldecoursy** [comment]
@kgorr

**Comment by KGorr** [comment]
RE: landing page

One small typo: "invite a friends"

We are also hoping to do a all-day tweetchat live from MozFest, so that would be an excellent part of the challenge - to participate and engage throughout the day. It's not finalized however, so @ldecoursy and I can keep you posted on that.

**Comment by iamjessklein** [comment]
small piece of feedback - the postcard (at least) feels a bit sad to me as a remotee. I get it that there is an event happening in London, but I'm clearly not there. I want to *participate* in a remote mozfest - not merely watch an event from afar. We work remotely, we can mozfest remotely :)

**Comment by chadsansing** [comment]
I hear you.

Is there a way to get at this content-wise, e.g. flipped - here's what you missed while at MozFest? A better way to re-frame it? Just prototyping off of suggestions here. @fuzzyfox, @Saallen, @hannahkane, @iamjessklein  - thoughts?

**Comment by KGorr** [comment]
Is it too late in the game to make a separate postcard for the remote participants? Maybe it could say "Join me for #livefrommozfest" (which is the hashtag I'm suggesting or our live twitterchat - still needs to be approved by @ldecoursy) or something like that. And then on the other side it says "Three things that I want to share with you". They can share it instantly to invite people to join us. This makes it active and pulls people into our conversation in real time. Thoughts?

**Comment by chadsansing** [comment]
+1

**Comment by chadsansing** [comment]
@Saallen, is this postcard revision something we can come back to Monday? When does this 'kit' need to ship, and to whom do we ship it for approval or whatever?

**Comment by iamjessklein** [comment]
What if it was something more active like - I'm making ____________ at #remotemozfest

**Comment by omnignorant** [comment]
just wanted to +1 @iamjessklein... but of course, there's gotta be a blank to do. So maybe it's a dialogue? 

Q: What are you making?
A: I'm making ________

Q: Can you help us with ______?
A: Sure! I'm making _______!

**Comment by Saallen** [comment]
I am linking in @hannahkane as she know more about timings for devs

**Comment by chadsansing** [comment]
Consensus on postcard, @fuzzyfox, @Saallen, @KGorr, @ldecoursy? Would like to ship whatever else needs to be finished today.

cc @iamjessklein, @omnignorant

**Comment by chadsansing** [comment]
How is this version of the postcard, @iamjessklein, @omnignorant?

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/9412/

**Comment by ldecoursy** [comment]
It looks good to me - one q though. Should it say "This year during #remoteMozFest I'm working on _______"

**Comment by fuzzyfox** [comment]
@ldecoursy: I think it would be best to leave it simply as #mozfest rather than #remotemozfest. For me we should try and make it feel like you're celebrating #mozfest proper, no matter where you are doing it. Less about geo, and more about celebrating.

Additionally I think it would be awesome to run both versions of this postcard. As I mentioned on the [discourse thread](https://discourse.webmaker.org/t/testing-needed-remote-challenge-thimble-projects/222/6?u=fuzzyfox) the previous version of the postcard can act as a great way to get information out. While this newer version @chadsansing has given us, to me, is more of a shared statement about working together on something, no matter where you are.

For me having a challenge to get people onsite thinking about those offsite is just as important as making the experience as inclusive as possible for those offsite. It can help enhance that feeling by encouraging more dialogue from onsite to the wider world, and prevent people being bubbled by the physical walls around them.

**Comment by hannahkane** [comment]
Saw I was pinged, but having trouble following the thread. Does anyone need anything from me?

**Comment by chadsansing** [comment]
@hannahkane - I am a MozFest remote page production n00b. 

- Do we need to host these somewhere other than on my repo or Thimble?
- If so, what kind of issue needs filed where and with what review?

Right now, you can see just about everything from http://chadsansing.github.io/curriculum-testing/moz-fest-remote-projects/index.html.

**Comment by hannahkane** [comment]
@chadsansing - ah, understood. I didn't realize a page was being built. We'd intended to host this on the MozFest site. Ticket is [here](https://github.com/mozilla/2015.mozillafestival.org/issues/195). Have asked @natalieworth to design a page based on your content, if that's alright with you.

**Comment by chadsansing** [comment]
Sounds good - mine is not a super-duper landing page :) I think the content addresses most of the feedback so far, though, of course, not perfectly, so now is a good time for folks to chime in on anything else that's needed. @Saallen, @fuzzyfox, @soapdog, @iamjessklein, @omnignorant, @hjbailey, @ldecoursy, @KGorr   - ready to ship? Any copy bugs still out there?

**Comment by fuzzyfox** [comment]
It would be great if we could get that page in such a way that we can add all the ways people can get involved. I can help work on that if/where needed, and have started creating a list of all the opportunities I know of beyond just the remote challenges ([etherpad]).

We should probably create a thread on Discourse to act as a lightning rod for additional methods to get involved too... something that people can add activities to as the festival progresses?

Mostly this thread has focused on the challenges, however there are other ways to keep an eye on the fest, and they probably shouldn't be left off a page about remote participation.

[etherpad]: https://public.etherpad-mozilla.org/p/remote-mozfest

If we can get that list fleshed out a little more/complete by the end of day is that going to give enough time @hannahkane?

**Comment by chadsansing** [comment]
+1 to what @fuzzyfox said.

**Comment by hannahkane** [comment]
I think that probably works. What do you think, @natalieworth?

**Comment by fuzzyfox** [comment]
@KGorr what hashtag are you looking at going with for the twitter chat? If its not yet locked in, could I throw #mozfestlive into the mix, its a little less tied to the venue for the chat, and so hopefully will promote more remote engagement with it too.

**Comment by ldecoursy** [comment]
+1 @fuzzyfox !

**Comment by cassiemc** [comment]
EOD will be fine, @natalieworth has a bunch of other stuff on her plate as well :)

**Comment by KGorr** [comment]
@fuzzyfox, not locked in. @ldecoursy and I should be locking that down tomorrow. We'll definitely add it the mix. Other ideas are that the team has thrown out there:     
#mozfestweb
#livefrommozfest
#mozfestonline
#mozfestchat

**Comment by KGorr** [comment]
Also @ldecoursy, I noticed that the tweetchat has become "all weekend long" on the remote curriculum...we were thinking it would just be a one-day, Nov 7 chat.  We should probably solidify before this gets finalized today. Thoughts?

**Comment by chadsansing** [comment]
@kgorr - no decision-making here, just copy. We can make the description for the chat whatever it's supposed to be. Is everything set?

**Comment by fuzzyfox** [comment]
I think the final thing we need to do, once we have that list from finalised, is help @natalieworth out a little by creating some draft copy to promote each item, and provide a little narrative around the items. This can be finalised later, but gives something more than just a list of items and links to work from.

sound good?

**Comment by chadsansing** [comment]
Sure - do you have a frame in mind, @fuzzyfox?

**Comment by fuzzyfox** [comment]
Right now all I have is that the message is that its about celebration w/o geo boundaries. I guess it could come w/ a cta for those onsite and those offsite too... Something along the lines of "Get involved and make a difference no matter where you are" and "Help others help you, share what you're working on with those not in london". 

Its only rough thoughts right now... and I'm about to hop on a train home :/ Will do some more thinking and get back to you with more if you don't beat me to the punch :P

**Comment by omnignorant** [comment]
message inspiration by way of @thornet http://www.ted.com/talks/taiye_selasi_don_t_ask_where_i_m_from_ask_where_i_m_a_local

**Comment by chadsansing** [comment]
Hack this copy (or paste in moar better copy!):

https://docs.google.com/a/mozilla.com/document/d/1Oic1ZK5Ct7ZY8kkTauVwNAuYiZzFwJv7SrcgUxvtvUM/edit?usp=sharing

**Comment by hannahkane** [comment]
Do we have final content for this page, @chadsansing @fuzzyfox ?

**Comment by chadsansing** [comment]
@hannahkane, @fuzzyfox - if we can get a quick Y/N on some of the copy here https://docs.google.com/a/mozilla.com/document/d/1Oic1ZK5Ct7ZY8kkTauVwNAuYiZzFwJv7SrcgUxvtvUM/edit?usp=sharing I feel good about it. Last call for input @thornet, @Saallen, @omnignorant, @KGorr, @ldecoursy, @chrislarry33, @natalieworth -

**Comment by ldecoursy** [comment]
Just made small comments/suggestions - looks good to me! This should also probs be a blog post.

**Comment by chadsansing** [comment]
@hannahkane, @KGorr, @ldecoursy, & @omnignorant have taken a look, and @natalieworth is on the doc now. Seems to have passed inspection :) Mash it up with the links from the draft landing page & run with it?

**Comment by hannahkane** [comment]
OK, closing this ticket, and moving over to [Design ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/195)

**Comment by fuzzyfox** [comment]
@ldecoursy I'm working on a blog post of my own to cover a lot of this, as well as explain a little more about the #mozfestremote group that will be working w/ me onsite. Will ask for a review on that when its ready (prob sat/sun). Will open a new ticket for that though.

**Comment by ldecoursy** [comment]
Sounds great @fuzzyfox. Later today or early tomorrow, we're going to post separately about the Web Literacy Basics curriculum l10n piece.

**Comment by chadsansing** [comment]
@fuzzyfox: Discourse threads for Test @ The Fest are live, and I updated the Thimble project with the new links.

https://discourse.webmaker.org/c/events/mozfest

**Comment by hannahkane** [comment]
@chadsansing - if there are any changes needed on the Remote Challenge page, can you please be sure to update the [implementation ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/179). Thanks!

**Comment by chadsansing** [comment]
@hannahkane - for sure. I only anticipate @ldecoursy 's forthcoming L10n link.

**Comment by ldecoursy** [comment]
Here it is! https://wp.me/p6e0l1-3Eq

**Comment by soapdog** [comment]
:+1: @ldecoursy, awesome! thanks a lot for the hard work
