### ISSUE TITLE
A4 card for Science fair / closing demo

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#234]
This is a really simple, straightforward asset, an A4 card intended to be folded over, with just the Mozfest logo. It is needed for teams to write their information on at closing demos. We should be able to print these onsite very close to the event.

Did I miss any specs? @Saallen @marcwalsh @hannahkane

**Comment by Saallen** [comment]
Yes we can print onsite- @marcwalsh will provide the diamensions

**Comment by marcwalsh** [comment]
It's quater A4 long lengthways. I've attached a couple of photos, but basically a piece of A4 card folded into 4 lengthways to make a triangle.
![img_0073](https://cloud.githubusercontent.com/assets/14007066/10193895/ac0f8b92-677d-11e5-98c5-bd1d6742d183.JPG)
![img_0074](https://cloud.githubusercontent.com/assets/14007066/10193897/add3f6d4-677d-11e5-9d72-d1e7c5fe472b.JPG)

**Comment by cassiemc** [comment]
Ah, that is so helpful, not what I was imagining. Thanks @marcwalsh!

**Comment by natalieworth** [comment]
Hi @cassiemc, @marcwalsh, @Saallen, A4 cards for MozFest are up on red pen. I can do a test print this afternoon to make sure they fold properly before print: https://redpen.io/p/edab6523098f16c8a5

**Comment by Saallen** [comment]
Nice!

**Comment by natalieworth** [comment]
Final file for the A4 cards on google drive: 
https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0T2MtTjkzdGtpbTg/view?usp=sharing
@Saallen @marcwalsh @hannahkane @cassiemc

**Comment by natalieworth** [comment]
@cassiemc @Saallen Are we able to close this issue too? The link to the google drive file is above.

**Comment by cassiemc** [comment]
@natalieworth These look good. I would remove the final option though, where the logo cuts into the grid. After that's done let's close.

**Comment by natalieworth** [comment]
@cassiemc I removed the last one and uploaded the pdf again to google drive: https://drive.google.com/open?id=0B20-0lpP23c0ZXFrUzBERmFhQWs

**Comment by cassiemc** [comment]
Great, thanks @natalieworth! @marcwalsh you should have what you need here. :)

**Comment by Saallen** [comment]
Hey reopening this issue to a  new request- can we make one Science Fair card that has on the top- Made at MozFest-
The idea is that we are celebrating cool MozFest makes from previous years, highlighting sessions, resources & tool kits that were once a session at  a previous festival but are now running and successful kits or platforms in the community cc @cassiemc  @natalieworth

**Comment by cassiemc** [comment]
Sure!

**Comment by natalieworth** [comment]
Hey @Saallen, I've posted some examples up on redpen just with a few questions for the updated Science Fair card. Thanks:
https://redpen.io/p/qy81d1e4d8db976f67

cc @cassiemc

**Comment by natalieworth** [comment]
Updates with a more stamp-like approach are up on red pen for these. Thanks: https://redpen.io/oudc903c808ad4c98e

cc @cassiemc @Saallen

**Comment by cassiemc** [comment]
Cool, thanks @natalieworth. A bit more ways to go... left some comments on redpen.

**Comment by natalieworth** [comment]
Hey @cassiemc, I like your point about doing something horizontal to allow for more writing space. I've got some rough sketches attached here. I was thinking more of an emblem/ banner could be good with an icon that could represent 'make' better (i.e. hammer, wrench, scissors, or pencil):
![img_3160](https://cloud.githubusercontent.com/assets/14876567/10765302/52c9d43a-7c8f-11e5-84fe-292f7c9a3221.JPG)
![img_3161](https://cloud.githubusercontent.com/assets/14876567/10765301/52c89c5a-7c8f-11e5-888e-99e919abf60c.JPG)
![img_3162](https://cloud.githubusercontent.com/assets/14876567/10765300/52c8a4d4-7c8f-11e5-9342-ff8b0ed7fa8c.JPG)
![img_3163](https://cloud.githubusercontent.com/assets/14876567/10765303/52cb7434-7c8f-11e5-847c-427b6d22a2b4.JPG)

**Comment by cassiemc** [comment]
@natalieworth I like the horizontal wavey banner idea. Not sure the icon is working, the problem with interpreting 'make' this way is that so many things are digital or programmatic. You could possibly use a hand or hands but it might be simpler to just use generic graphic styles. Did you see the dribbble search i linked in the redpen? Might get some more inspiration re. graphic detail: https://dribbble.com/search?q=seal

**Comment by natalieworth** [comment]
@cassiemc Updates for this are on redpen: https://redpen.io/uwaa9b0eb01d1e7a22 Instead of a wrench, pencil, etc. representing make, I was thinking I could include the gear icon. Then it's not to restrictive to science either. For the stamp-like approaches, I tried to incorporate some of the dribble examples. Thanks

**Comment by cassiemc** [comment]
YES! The gear is absolutely perfect. I like the top version! @Saallen does that work for you?

**Comment by natalieworth** [comment]
@cassiemc @Saallen I've uploaded the final version of this to the google drive. Print ready file for the 'Made at MozFest' template can be found here: https://drive.google.com/open?id=0B20-0lpP23c0MWZWV2w4ZHpkMkE

**Comment by Saallen** [comment]
:heart_decoration:  thanks @natalieworth - Is there somewhere Marc can access these files in one place so he can print easily on Wed?

**Comment by natalieworth** [comment]
Hey @Saallen, here's the link for pdf versions of all of the templates I created: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0MWZWV2w4ZHpkMkE I'm not sure if we have an github issue yet for everything that needs to be printed at Ravensbourne. I can upload link there if I find it. Thanks :)

**Comment by cassiemc** [comment]
@natalieworth The master doc for printing all assets is here: https://docs.google.com/spreadsheets/d/1nOphU77wnjZzkRyAhoo-KiSdZ2nD4HjUg1A4SQykMF4/edit#gid=0 Please do add links to source files for all that @marcwalsh needs to print at Ravensbourne. Thank you!

@marcwalsh @Saallen Closing this issue, please re-open if you need anything else.
