### ISSUE TITLE
A3 pages with mozfest logo, session template

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#235]
**Deadline:** Nov 5th

This is another straightforward asset, a large A3 page to serve as a template for facilitators to write their session info on. It could simply have the Mozfest logo on it if we run out of time, or could be a template with session name, box for description, etc.

We should be able to print these onsite very close to the event.

Anything else we need to know, @Saallen @marcwalsh @hannahkane ? How many will be needed?

**Comment by Saallen** [comment]
Hi @cassiemc 
Here is a [link] (https://drive.google.com/drive/folders/0B7cnpfRDzUyFVkFlaWdCVm1yUlk) to the blank templates we made last year . 
Here is the 2013 [version] (https://www.dropbox.com/home/Mozfest%202013/Graphics/print-assets/14%20-%20Hackable%20Session%20Poster?preview=mzfst13_hackableSessionPoster.ai)
It can be plain paper with logo also
Additional info
* We can print these the 5th of Nov 
* I will probably print about 200 to start with

**Comment by cassiemc** [comment]
Thanks @Saallen!

**Comment by natalieworth** [comment]
@cassiemc @Saallen These are the files in the google drive that I am referencing for the 2015 template:
![mzfst14_blank_templates_va-01](https://cloud.githubusercontent.com/assets/14876567/10293947/36def022-6b6c-11e5-9b1b-32510f084d35.jpg)
![mzfst14_blank_templates_va-04](https://cloud.githubusercontent.com/assets/14876567/10293953/3b884a4c-6b6c-11e5-95a2-63c46678a69d.jpg)
![mzfst14_blank_templates_va-08](https://cloud.githubusercontent.com/assets/14876567/10293957/402f946a-6b6c-11e5-8351-630edca29a88.jpg)

1) Should I be maintaining the 2014 style with the 2015 template (and also keeping the various layout options)? I've started a red pen project for the templates/ demo and science cards to make sure I'm on the right track:https://redpen.io/zj6ce226378e8a99e8 

2) For the sectional template version with session, description, etc.... what fields should I include? Thanks

**Comment by cassiemc** [comment]
These are great @natalieworth. Will leave it to @Saallen to comment on the fields & file types. /cc @marcwalsh in case he knows.

Also, between https://redpen.io/omc2650445ae7eb9d7 and https://redpen.io/vy7a28bd702b3dd901, I'm not sure if the MozFest branding should be upfront or more diminutive for the purposes of this card. I think either works, design-wise.

**Comment by natalieworth** [comment]
@Saallen @marcwalsh @cassiemc  More iterations based on last years templates are up on redpen:
https://redpen.io/p/qy81d1e4d8db976f67

I can adjust the section/ description drafts once the fields are finalized. Thanks

**Comment by Saallen** [comment]
Hi @natalieworth loving the designs- happy with all of them. I wondered though what section refered to on the page? I thought maybe it should of had session..but not sure of the idea behind it.
I think just having protrait is fine. thanks :)

**Comment by natalieworth** [comment]
Hi @Saallen, I was just using the section as more of a place holder. I was hoping that you could help me refine the wording for the different sections on the page for more of a template style design? I wasn't 100% on what the A4 templates were used for at MozFest. Or if it's easier, I can finalize the other line and grid designs if a template with different sections isn't needed. Thanks

**Comment by Saallen** [comment]
@natalieworth 
I like your wording, i think what you have works :+1: 
Just changing section to session allows a place for the name of the session.

**Comment by natalieworth** [comment]
Hi @Saallen, fixed the wording and adjust the colours to be more cohesive on red pen: https://redpen.io/p/qy81d1e4d8db976f67

cc @cassiemc

**Comment by Saallen** [comment]
:heart: looks great @natalieworth

**Comment by cassiemc** [comment]
@natalieworth just a couple small questions/comments on https://redpen.io/qe84b039caf46bc898

**Comment by natalieworth** [comment]
Hi @cassiemc , tweaked the layout again a bit on this one and added the new version to redpen:
https://redpen.io/p/qy81d1e4d8db976f67

**Comment by cassiemc** [comment]
@Saallen Should it say 'session name' instead of just session? That is my only question, otherwise R+ @natalieworth on the design, nice work.

**Comment by natalieworth** [comment]
Final file for the A3 session templates on google drive: 
https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0VHVuS0RXMW1LQ3M/view?usp=sharing
@Saallen @cassiemc

**Comment by Saallen** [comment]
Session name is probably better.

**Comment by cassiemc** [comment]
Nice, thanks @natalieworth! 
@Saallen @marcwalsh Final files are here: https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0VHVuS0RXMW1LQ3M/view?usp=sharing
