### ISSUE TITLE
Branding needed for additional swag bag items

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#236]
**Deadline:** October 12

Wondering if this is needed and by when? @marcwalsh @Saallen

**Comment by marcwalsh** [comment]
I'll get final deadlines for this today and add it to the spreadsheet also if needed?

It would just need to be simple, the cog and 'Mozilla Festival' or #MozFest  

@cassiemc

**Comment by marcwalsh** [comment]
@cassiemc Dates are as follows:

PRINTED SCHOOL DRAWING SET
Lead time: 12 working days
Order ideally needed by: 12th October
Print area: 5x50mm 
 
RECYCLED NOTEBOOKS A5
Lead time: 2 weeks
Order ideally needed by: 12th October
Print area: 207x145mm
 
RECYCLED NOTEBOOKS A6
Lead time: 2 weeks
Order needed by: 12th October
Print area: 143x100mm

**Comment by cassiemc** [comment]
@marcwalsh @adiladil Note we will probably keep this simple and straightforward due to the deadline. Mozfest logo okay? Is there a more generic shape or design we can use to make these coveted and widely reusable so they feel more useful / less like swag?

Also @marcwalsh can you please upload photos of these when you get a chance?

**Comment by marcwalsh** [comment]
@cassiemc Sounds perfect! Sure, I've edited my comment before with links. 

FYI. We're having either an A5 or A6 notepad. I'm just waiting for confirmation from another supplier and the print area might change, is that a major issue?

**Comment by cassiemc** [comment]
Nope not a major issues, thanks @marcwalsh!

**Comment by cassiemc** [comment]
Blocked on icons #213

**Comment by adiladiladil** [comment]
![notebook](https://cloud.githubusercontent.com/assets/11046943/10401150/12880aa2-6e8b-11e5-938d-e744e1da2cb0.jpg)
![notebook2](https://cloud.githubusercontent.com/assets/11046943/10401186/4cd46a20-6e8b-11e5-8252-5b7a12ec49e5.jpg)
![untitled-2-01](https://cloud.githubusercontent.com/assets/11046943/10401268/e09a68f4-6e8b-11e5-8ab0-21d0287d79a1.jpg)
![pencil-01](https://cloud.githubusercontent.com/assets/11046943/10401271/e41fc99c-6e8b-11e5-969b-1b4879b66cf1.jpg)

**Comment by marcwalsh** [comment]
@cassiemc @adiladiladil - Can I get these designs in vector format please. Looking to place the order today. :)

**Comment by cassiemc** [comment]
@adiladil we need vector files here, too please!

**Comment by adiladiladil** [comment]
@marcwalsh are we going A5 or A6 for the notebooks

also just wanted to triple check that the pencil case print area was 5mmX50mm...seems tiny

**Comment by marcwalsh** [comment]
We're going for A6 :) Let me double check... I did think that it was small.

**Comment by adiladiladil** [comment]
For the A6 Notebook: 

Blue notebook with white print:

![mozfest-2015-a6-notebook-new](https://cloud.githubusercontent.com/assets/11046943/10459999/596610e6-71a0-11e5-86d1-90872b226813.jpg)


Link to vector:

http://we.tl/gD0WUFNOev

**Comment by adiladiladil** [comment]
Here is the pencil case artwork at 5mmX50mm

you can use this Hi Res JPG for printers since they do full color print for these

![mozfest pencil-01](https://cloud.githubusercontent.com/assets/11046943/10460831/4adb5b9a-71a4-11e5-9ca2-a5181a0eefd3.jpg)

**Comment by adiladiladil** [comment]
actually, @marcwalsh @cassiemc 
Here is the link to for the pencil case artwork:

http://we.tl/XiBM3duj44

**Comment by cassiemc** [comment]
@marcwalsh are we good to close this one?

**Comment by Saallen** [comment]
We are all good :cake:
