### ISSUE TITLE
About Page Content : Update Festival Mission statement

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#24]
Festival outcomes have slightly altered.
How can we transcribe these into Marks speech?
I will talk to Mark about updating the festival text with @thornet input

**Comment by Saallen** [comment]
We will create a festival Mission statement - completely new for this year.

**Comment by edrushka** [comment]
@KevZawacki looks like Sarah created this ticket specifically for the Mark's "welcome message" speech bubble that will go on the 'What to Expect' page.

@Saallen confirming that Mark's message goes on 'What to Expect' and not 'About'. Also, Kevin can take a crack at writing this. Do you have any pointers or direction for him?

**Comment by KevZawacki** [comment]
Mark's note is here, on page 3: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit
