### ISSUE TITLE
Replace photo on Volunteer page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#241]
Noticed that we use the same photo on the Volunteer page as the Tickets page. Wondering if we can replace the image on the Volunteer page with this one:

https://www.flickr.com/photos/newyouthcity/10559772014/in/faves-47833020@N03/

@cassiemc - do you approve?

**Comment by cassiemc** [comment]
Yeah I think this is a good choice, nice work @natalieworth. Now we need to make sure it is cropped well to get rid of some of the clutter at the top, the visual noise from the lights and ceiling, and treat it with color as per the other photos on the mozfest site. 

Assigning to @natalieworth as a P2, please adjust if necessary @hannahkane.

**Comment by natalieworth** [comment]
@cassiemc @adiladil @hannahkane Is there a guideline or for the image editing? Or a specific blending mode/ .psd file somewhere of the gradient that I could follow for reference? If not, I have the colour properties for the gradient from the MozFest 2015 branding that I can match. Thanks.

**Comment by natalieworth** [comment]
@hannahkane @adiladil  Edited image for the volunteer page:
https://redpen.io/p/ab6b3526abd59e8c4f
https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0ZFRwZDNCUEZMNzg/view?usp=sharing

**Comment by cassiemc** [comment]
Great @natalieworth! R+

@mmmavis Here is the final asset:
![img-volunteer](https://cloud.githubusercontent.com/assets/1186326/10249247/39ac114e-68f2-11e5-8be1-09dedba089b8.jpg)
