### ISSUE TITLE
Build Pathways page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#247]
My suggestion:
 * Use the same design as the Spaces page, except Pathways won't have icons. 
 * Replace "Wranglers" with "Pathfinders," but @Saallen will work to collect Pathfinder bios, so we can use the same design pattern there as well.
 * Will need a different header image.
 * url: /pathways
 * Link to this page from the /sessions page now described in #176

cc @mmmavis @Saallen @cassiemc

**Comment by mmmavis** [comment]
> Put links to both Spaces and Pathways page in the main nav

need some clarification on this @hannahkane :hamster:

**Comment by cassiemc** [comment]
@natalieworth Can you help us source another image for this page? Very similar to the space page but we need a different header image. Think along the lines of people in clusters together, or people moving from one thing to another, or anything that gets across the idea of linkages or progression...

**Comment by hannahkane** [comment]
@mmmavis - just updated the first comment to reflect the latest thinking from our stand-up just now. Let me know if it's still unclear.

**Comment by natalieworth** [comment]
@cassiemc I think one of these 3 options would work. I can edit/ create a mockup once approved:
https://www.flickr.com/photos/paul_clarke/8174891973/in/faves-47833020@N03/
https://www.flickr.com/photos/newyouthcity/10559886703/in/faves-47833020@N03/
https://www.flickr.com/photos/mozillaeu/10511442416/in/faves-47833020@N03/

**Comment by cassiemc** [comment]
@natalieworth I like the last one

**Comment by hannahkane** [comment]
last one = wfm

**Comment by natalieworth** [comment]
Image and mockup are now up on redpen for Pathways page: https://redpen.io/p/ab6b3526abd59e8c4f
@mmmavis @hannahkane @cassiemc

**Comment by hannahkane** [comment]
w00t. looks good.

**Comment by cassiemc** [comment]
Yep, looks awesome, thanks @natalieworth

**Comment by mmmavis** [comment]
@hannahkane is this where I should find copy from(https://docs.google.com/document/d/1Q4HqCaMWxW6uYNDsCvRIhqhvVJaXgAE3lvn-Csl0se0/edi) ? Should I include the "Additional Text" section of each Pathway?

**Comment by hannahkane** [comment]
Hey @mmmavis - please use the pathways section of this doc: https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit

**Comment by mmmavis** [comment]
@natalieworth 

Would you advice how I should style the "Independent Pathway" label in my screencap below? :grin:  From the provided copy it seems like each Pathway is associated with a Space (e.g., Journalism Pathway) or called "Independent Pathway" otherwise.

<img width="981" alt="screen shot 2015-10-05 at 12 29 17 pm" src="https://cloud.githubusercontent.com/assets/2896608/10291109/c1715df2-6b5c-11e5-853f-02ca0be0d6d0.png">

/cc @cassiemc

**Comment by cassiemc** [comment]
@mmmavis I don't recall if we were going to include that information. @hannahkane can you comment? If we are, then I think italics below the main title is great.

**Comment by hannahkane** [comment]
I think it's useful context for people to know when pathways are associated with a particular space, so, yes, let's include those as italicized lines below the name of the pathway. Thanks!

**Comment by mmmavis** [comment]
@hannahkane looking like we are missing intro for the "Independent pathway Producing in the Open" pathway :eyes:

**Comment by hannahkane** [comment]
@Saallen, see Mavis's comment above. Can we get that final copy?

**Comment by Saallen** [comment]
Nicely spotted @mmmavis - this pathways has been cancelled :disappointed:

**Comment by mmmavis** [comment]
ah, gotcha :crying_cat_face:

**Comment by mmmavis** [comment]
live on https://2015.mozillafestival.org/pathways

**Comment by hannahkane** [comment]
yay! :cake:

**Comment by Saallen** [comment]
:balloon: whooopppp
