### ISSUE TITLE
Festival team page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#250]
Hi I forgot about a page for the festival team- I was just reminded by the visa application process where I need to reference my position to assist with requests.
I believe we have the full content on last years website- http://2014.mozillafestival.org/about/index.html
We would need to update the years that everyones has participated for but I think part from that we need little changes. I will of course check with the team themselves.
Would this be possible @hannahkane ?

**Comment by hannahkane** [comment]
@Saallen  - Yes, it's possible. Do you mean a page with just the six bios?

Can you please put all six completed bios + photos into a doc for us to reference? Then I'll create a design ticket and a build ticket to manage the work.

**Comment by Saallen** [comment]
@hannahkane I have started here
https://docs.google.com/a/mozilla.com/document/d/161Pp0X0y0DlwMnkGCB5kv586_dgFnGoPXuDqaR3DKlU/edit?usp=sharing

**Comment by hannahkane** [comment]
Thanks, @Saallen. I made a few minor copy edits, and updated references to the year, and the number of MozFests people have been involved with. Would be good to get an OK from everyone before we implement. Also - does everyone want to use the same photos as last year?

**Comment by Saallen** [comment]
@hannahkane Everyone has confirmed they are happy with the edits and pictures :)

**Comment by hannahkane** [comment]
K. Closing this ticket and opening a design ticket (#258) and a build ticket (#259).
