### ISSUE TITLE
Add Space Wrangler and Pathfinder bios-

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#252]
Abigail Cabunoc Mayes - Space Wranger Science

Abigail Cabunoc Mayes is the lead developer for Mozilla Science Lab, which is a community of researchers, tool developers, librarians, and publishers working to leverage the open web in research. Prior to joining Mozilla, Abby worked as a bioinformatics software developer at the Ontario Institute for Cancer Research where she was the technical lead on the WormBase website.
![ac jpeg](https://cloud.githubusercontent.com/assets/10194015/10319029/10bcfa44-6c64-11e5-8ef2-72c7d133bbe4.jpeg)

**Comment by Saallen** [comment]
Chad Sansing 
![chadsansing](https://cloud.githubusercontent.com/assets/10194015/10319070/3c062414-6c64-11e5-9d30-b53aecd43dfb.jpg)
works as a curriculum developer for the Mozilla Foundation and has a special interest in playful, participatory, and production-centered teaching and learning. Chad joined Mozilla after serving 14 years as a middle school language arts, social studies, and technology teacher and after several years of activity in the Mozilla and National Writing Project communities.

Twitter handle: @chadsansing

**Comment by Saallen** [comment]
Matt Rogers- Badges pathways
Matt is passionate about working with young people, particularly when it comes to using and experimenting with existing and emerging technologies. Before working for DigitalMe, Matt was a KS1-KS4 teacher for eight years most recently at a Primary School in South East London, where he also held the roles of CAS Lead Educatorand Mathletics Lead Educator. This experience directly feeds into Matt’s work on Safe, Naace CPD badges and Scout badges at DigitalMe.

**Comment by Saallen** [comment]
Grainne Hamilton - 
Grainne’s varied background includes leading the development of the Jisc Open Badges Toolkit, contributing to the Mozilla Discover project, which involved developing badge-based pathways to employment, as well as founding and facilitating the Open Badges in Scottish Education Group. Most recently, she was Senior Consultant at Blackboard, which involved helping a global range of clients make best use of their teaching and learning systems. 
http://www.digitalme.co.uk/assets/pdf/Grainne.jpg?timestamp=1443312000037

**Comment by hannahkane** [comment]
cc @mmmavis

**Comment by mmmavis** [comment]
hi there, are there more to come? just wondering when or how frequently I should be updating the `/sessions` and `/pathways`(not live yet) pages

**Comment by Saallen** [comment]
I would give it until Monday if thats ok with you?

**Comment by mmmavis** [comment]
yup yup just assign this ticket to me when it's ready to go :dancer:

**Comment by Saallen** [comment]
Ian Forrester- Space Wrangerl- Global Village

Ian Forrester is a well known and likeable character on the digital
scene in the UK. He has now made Manchester, UK his home, where he
works for the BBC's R&D north lab. He focuses on open innovation and
new disruptive opportunities via open engagement and collaborations
with startups, early adopters and hackers
https://www.flickr.com/photos/cubicgarden/8813084733/sizes/o/

**Comment by Saallen** [comment]
Lindsey Frost
Lindsey is the Gigabit City Lead for the MLN team, leading Mozilla's five-city effort to explore how high-speed networks can be leveraged for learning.  A native of Chattanooga, Tennessee, Lindsey is passionate about empowering leaders and learners to read, write, and participate on the (super fast!) Web. She's previously worked with the University of Tennessee and the Public Education Foundation and is a founder of DEV DEV, Chattanooga's citywide digital literacy initiative. 
![lindsey froast max](https://cloud.githubusercontent.com/assets/10194015/10387458/6cc7c19c-6e59-11e5-8962-eefdedcd5c67.jpg)

**Comment by Saallen** [comment]
https://docs.google.com/document/d/1c1btKHH_ngUPZl_E28WQq-QhybDBlWqu3fA2j4rQGHU/edit
Stacy Martin- Digital Citizenship

Stacy Martin is part of the Policy Team at Mozilla.  As a Senior Manager of Privacy and Engagement, Stacy focuses on building privacy community and education / awareness materials. She has created several teaching kits on topics such as privacy, passwords, and DRM.  Stacy also organizes Mozilla’s Privacy Lab, team teaches New Hire Privacy Training and leads Mozilla’s Privacy Day planning. She has been with Mozilla for 4 years.  Her latest passion is building a Global Advocacy and Teaching Task Force for privacy and other key Internet issues.  If you’d like to get involved with privacy issues or advocacy task forces, she invites you to come talk to her!

**Comment by Saallen** [comment]
![sg portrait-2](https://cloud.githubusercontent.com/assets/10194015/10396618/6bd1f748-6e9b-11e5-9da9-d4c85820eeb9.jpeg)
Sandra Gaudenzi - Pathway: Storytellers and Coders United

Sandra consults, researches, lectures, writes and blogs about interactive factual narratives.

She is one of the co-directors of the i-Docs conference (i-docs.org) and the Head of Studies of IF Lab (iflab.net), an EU training initiative for interactive documentary makers. She also hosts a regular IF Meetup in London, with the aim to create a community of professionals that want to work together and make their projects become reality!

**Comment by jvallera** [comment]
![_ar73872-x2](https://cloud.githubusercontent.com/assets/3729312/10400617/c58ab608-6e87-11e5-8e5d-3d6d7c79f277.jpg)


Julia Vallera (@colorwheelz) has been working in the arts as an educator, printmaker, public engagement artist, illustrator, consultant and designer for 16 years. She is a technology enthusiast and collaborates with many people to invent new ways to use it for STEAM (Science, Tech, Engineering, Arts, Math) education. As Network Manager at Mozilla Hive NYC Julia works with more than 70 cultural organizations to create new learning pathways and innovative educational practices for youth, educators, families, artists, technologists and more.

**Comment by Saallen** [comment]
thanks @jvehent

**Comment by Saallen** [comment]
Bekka Kahn- Pathfinder Online Learning Done Face To Face - A Pathway

Bekka Kahn works for P2PU and The Open Coalition, and is has been working on open education, open practice and free culture for 10 years. She’s also a recovering librarian, a PhD student at King’s College London, and an avid maker of jam. 
![rebecca kahn_cropped](https://cloud.githubusercontent.com/assets/10194015/10402058/db43e964-6eba-11e5-984f-c82421b5ce95.jpg)

**Comment by Saallen** [comment]
Ian Forrester- Space Wrangler Global Village
https://www.flickr.com/photos/cubicgarden/8813084733/sizes/o/
"Ian Forrester is a well known and likeable character on the digital
scene in the UK. He has now made Manchester, UK his home, where he
works for the BBC's R&D north lab. He focuses on open innovation and
new disruptive opportunities via open engagement and collaborations
with startups, early adopters and hackers."

**Comment by Saallen** [comment]
Heath bailey- space Wrangler Localisation
![heather](https://cloud.githubusercontent.com/assets/10194015/10454476/baa33486-71ac-11e5-9cca-06686713cc19.JPG)

Heather Bailey works for Translate, working behind the scenes for the last 15 years on localisations projects trying not to let them take over her house and her life. Born and raised in Southern Africa she loves the variety of people and culture in it and will always be a part of her identity. She has Illustrated a number of children’s books makes wedding dresses for fun and mostly loves connecting with people.

**Comment by Saallen** [comment]
Dwayne Bailey Space Wranger localisation
Dwayne
![dwayne](https://cloud.githubusercontent.com/assets/10194015/10454517/0ade20d2-71ad-11e5-96f2-f01790c81c73.JPG)
 is a proud father to two beautiful girls. His mission in life is to create a world where people can access and create in their own language. His motivation behind starting the Translate (a specialised localisation company) was to remove the language barrier between people and technology. For all the effort we put into getting information on screens, it might as well be miles away from the eyes that can’t read it.  So he travels the world passing on knowledge and giving localisers the tools to be able to make the changes they need for their languages. He loves Africa despite potholes and politics and would just like people to be able to get on with it without limitation.

**Comment by Saallen** [comment]
Sam Dyson- Space Wrangler Mozilla Learning Networks
![sam dyson 8-2014 v2](https://cloud.githubusercontent.com/assets/10194015/10527098/98015f6c-7386-11e5-983f-5780af7037bf.jpeg)


Sam is Director of Hive Chicago on the Mozilla Learning Network team. He's exploring the power of human networks to meet the opportunities and challenges inherent in the work of teaching and learning in the digital age. He provides strategic direction and sustainability for Hive Chicago as part of Mozilla's global leadership development and web literacy efforts. Sam has worked elsewhere in education including 10 years teaching high school physics.

**Comment by hannahkane** [comment]
@Saallen - Do we have enough of these that we should start adding them to the site?

**Comment by cubicgarden** [comment]
The link has pictures you can use of different sizes @sallen

**Comment by Saallen** [comment]
Yes please @hannahkane

**Comment by hannahkane** [comment]
ok. ping @mmmavis - these are ready to be added to the /sessions and /pathways pages

**Comment by cassiemc** [comment]
@mmmavis status? do you need any design help here?

**Comment by cassiemc** [comment]
Updating to new milestone.

**Comment by mmmavis** [comment]
sorry haven't had time to work on this yet.  this will be my todo on Monday

**Comment by Saallen** [comment]
:palm_tree:

**Comment by ioana-chiorean** [comment]
I think I can help here a bit - but for me it is unclear where the descriptions and pics should go exactly. @mmmavis  i can help with small changes like this too so ping me of needed.

**Comment by mmmavis** [comment]
This is [the original design ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/193) and mockup is here https://redpen.io/ub8b9d10c6b4251312.
