### ISSUE TITLE
Add section to /guidelines page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#253]
* Add a section after the "Raising Issues" section; same white background
* Headline (same style as R-E-S-P-E-C-T): Working in the Open
* Copy: MozFest planning is done in the open [perhaps link to the "Submission Process" page] because working in the open is one of our core values. We hope participants will benefit from this culture of transparency and collaboration during the Festival, and will continue to work with an open ethos in their projects after Mozfest. We recommend bookmarking WorkOpen.org and reading through the interviews with passionate advocates for open practices.

**Comment by mmmavis** [comment]
I made "done in the open" linked to the "Submission Process" page. Let me know if this needs any edits. :bowtie:
