### ISSUE TITLE
pathway copy feedback

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#255]
Hey @KevZawacki I showed the pathway content to the SW tonight and they added their comments to the doc. Could you take a look and let me know what you think?
https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit

cc @hannahkane

**Comment by KevZawacki** [comment]
@Saallen Just incorporated SWs' feedback. Good to go!

**Comment by hannahkane** [comment]
I didn't realize we were still editing this copy. Does this mean that this page is now out-of-date? https://2015.mozillafestival.org/pathways

**Comment by KevZawacki** [comment]
@hannahkane There were no changes to the Pathways copy -- and shouldn't be going forward -- so that page is up-to-date.

**Comment by Saallen** [comment]
:rainbow:

**Comment by hannahkane** [comment]
yay! thanks.

**Comment by Saallen** [comment]
@hannahkane @KevZawacki @mmmavis 
I have some late additions to the pathways copy- 5 to be exact from Science- Kevin I can now see you are already across them- Can we get them added to the website?

**Comment by mmmavis** [comment]
@Saallen for sure! I can have the /pathway page updated

do you remember which pathway(s) in particular that I should be updating? it's fine if you don't - I can do a complete copy-and-paste again :grin:

**Comment by KevZawacki** [comment]
Hi @mmmavis, new pathways are listed as pending copy in [this doc](https://docs.google.com/document/d/10bCR0xgUMzzPUN_PBUUtj1XTvG0GM7pFnJ6HoixnFqY/edit).

**Comment by cassiemc** [comment]
@KevZawacki are we good to close this issue?

**Comment by KevZawacki** [comment]
@cassiemc OK by me!
