### ISSUE TITLE
Adjust icons based on feedback

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#256]
From https://github.com/mozilla/mozfest-program/issues/586

**Comment by hannahkane** [comment]
Hey @adiladil @cassiemc and @Saallen. Just looking at the Youth icon now—I hate to prolong this process further, but I really don't think that icon fits with the rest of the set. It seems overly simplistic, and doesn't particularly communicate "youth" (IMO). I remember Cassie had suggested a version of the smiley face on a kid's block (like a three dimensional ABC block). Wondering if we can see a version of that before making a final decision.

My sense is we can get to 95% on all of the things that depend on the icon set (tshirt, tote bag, etc.), but still take the time to get this icon right, and do a switcheroo at the last minute.
