### ISSUE TITLE
Add icon for Fringe Events page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#257]
Have agreed in #178 to add "Attend a Fringe Event" as a CTA on the site, at the same level as "Get in touch," "Tweet," and "Volunteer." So, now we need a similar icon.

**Comment by natalieworth** [comment]
@hannahkane @cassiemc These 3 options could work for the Fringe icon (ticket, bullhorn, or clock). I've got a mockup too of them with the other icons on red pen: https://redpen.io/kcfe800e736b6ba50d
![fringe_icons_01-15](https://cloud.githubusercontent.com/assets/14876567/10405399/80f5150a-6e8d-11e5-9715-c61770a1e5b3.png)

**Comment by hannahkane** [comment]
I like the ticket! Seems the most event-y to me. Thanks, @natalieworth!

**Comment by natalieworth** [comment]
@hannahkane Here's the link to the .ai file containing the icons. Let me know if I can export or set the file up differently for the site? Thanks https://drive.google.com/open?id=0B20-0lpP23c0YVpnOXZDZ1k2cXM

**Comment by cassiemc** [comment]
@natalieworth could you please export that as an svg? It will need to be white, as well.

**Comment by natalieworth** [comment]
@hannahkane @cassiemc Added the white svg file to the google drive link above

**Comment by hannahkane** [comment]
w00t. thanks, @natalieworth.
@mmmavis - this is the icon that we'll be needed to finish out the Fringe Events page ticket

**Comment by cassiemc** [comment]
Updating the assignee to @mmmavis

**Comment by mmmavis** [comment]
@natalieworth the borders around the existing icons are done in CSS. Can you help export a border-free icon? :grin:

**Comment by natalieworth** [comment]
Hi @mmmavis, updated svg icon file is in google drive: https://drive.google.com/open?id=0B20-0lpP23c0YVpnOXZDZ1k2cXM

**Comment by mmmavis** [comment]
lovely! thanks you @natalieworth !

closing this ticket now (icon will land as part of https://github.com/mozilla/2015.mozillafestival.org/issues/178)
