### ISSUE TITLE
Design Festival Team page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#258]
Copy is here: https://docs.google.com/a/mozilla.com/document/d/161Pp0X0y0DlwMnkGCB5kv586_dgFnGoPXuDqaR3DKlU/edit?usp=sharing

Photos can be pulled from last year's site: http://2014.mozillafestival.org/about/index.html

Need to both design and build this page this heartbeat.

**Comment by cassiemc** [comment]
@natalieworth to help source a team-y picture for the header

**Comment by natalieworth** [comment]
Hey @cassiemc @hannahkane I think one of these images would work well for the header:
https://www.flickr.com/photos/mozillaeu/8172664276/in/faves-47833020@N03/
https://www.flickr.com/photos/mozillaeu/8172583258/in/faves-47833020@N03/
https://www.flickr.com/photos/mozillaeu/5156735187/in/faves-47833020@N03/

**Comment by hannahkane** [comment]
I think the first one is nice, and the most "team-like".

**Comment by cassiemc** [comment]
I like both the first and the third... The third has a really nice mix of ages and ethnicities (love the woman in the center). @natalieworth could you treat both then we can make a decision?

**Comment by natalieworth** [comment]
Hi @cassiemc @hannahkane , I've treated the images with the blue and red treatment also found on the 'contact us' page. Here's the link to the edited and mockup images: https://redpen.io/p/ho3b473cc9b07a267f

**Comment by cassiemc** [comment]
I really do love this version here: https://redpen.io/gjb069f7d2878df10b @natalieworth do you think you could adjust the photo so the headline is a little away from her chin – more on her shoulder? Once you've done that you can post the file here so @adiladil can mock up the page.

**Comment by natalieworth** [comment]
@cassiemc Let me know if this one works better: https://redpen.io/gjb069f7d2878df10b

**Comment by cassiemc** [comment]
Yes, love it. Now just need a download link for the image so @adiladil can fill out the rest of the page. Thanks @natalieworth.

**Comment by natalieworth** [comment]
Hey @adiladil, here's the link to the image file for the Team page: https://drive.google.com/open?id=0B20-0lpP23c0NjlVSHZMT2tHaU0 Thanks

**Comment by adiladiladil** [comment]
@natalieworth thanks... just requested access to the photo.
I'll use this for the Team Page mockups

**Comment by adiladiladil** [comment]
@cassiemc @hannahkane 
Here is the link to the redpen for feedback

https://redpen.io/p/gp54b663798941438c

![mozfest team-15](https://cloud.githubusercontent.com/assets/11046943/10497189/9ba04eac-7292-11e5-9bd1-a663e770a9e0.jpg)

**Comment by SpikeUK** [comment]
I may have missed something but only five of us? Where is @Saallen ?

**Comment by hannahkane** [comment]
Good eye, @SpikeUK. :) I don't think it matters, though, since we're just approving the design in this ticket. When we build the page, we'll make sure all of the bios are there.

@adiladil - design looks good to me. Not sure we have any copy for the paragraph below "Meet the MozFest team," though.

**Comment by adiladiladil** [comment]
@SpikeUK @hannahkane Here is the update

https://redpen.io/p/gp54b663798941438c

![mozfest team-15](https://cloud.githubusercontent.com/assets/11046943/10517103/47c60348-7329-11e5-8b19-fb34d7647e9b.png)

**Comment by cassiemc** [comment]
Design R+ :)

**Comment by hannahkane** [comment]
Closing this and unblocking the implementation ticket.

**Comment by SpikeUK** [comment]
Argh, no - is it too late to change the copy? It is my fifth MozFest - not my sixth (last line of my bio)
No idea how that got through - sorry :( :(

**Comment by hannahkane** [comment]
@SpikeUK - I updated the doc, which is linked to from the [implementation ticket](https://github.com/mozilla/2015.mozillafestival.org/issues/259), so when this page gets built, it should be corrected.

cc @mmmavis

**Comment by SpikeUK** [comment]
@hannahkane Thank you :) I did not have access to the Google Doc or I would have corrected it myself. Have a great Friday!!
