### ISSUE TITLE
Build Festival Team page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#259]
Design will happen here: #258 

url: /team
link: let's add it to the bottom-most line of the footer, to the right of "About." The link can read "Festival Team"

Team bios are here: https://docs.google.com/document/d/161Pp0X0y0DlwMnkGCB5kv586_dgFnGoPXuDqaR3DKlU/edit

**Comment by hannahkane** [comment]
blocked on design

**Comment by hannahkane** [comment]
unblocked!

**Comment by mmmavis** [comment]
Space Wrangler and Pathfinder bios and photos refer to https://github.com/mozilla/2015.mozillafestival.org/issues/252

**Comment by hannahkane** [comment]
@mmmavis - the Space Wrangler and Pathfinder bios aren't relevant to this ticket. The /team page lists the six bios of the Festival Staff (Michelle, Gunner, Misty, Sarah, Spike, Marc). Their bios are [here](https://docs.google.com/document/d/161Pp0X0y0DlwMnkGCB5kv586_dgFnGoPXuDqaR3DKlU/edit)

**Comment by mmmavis** [comment]
@hannahkane ah, you are right!
