### ISSUE TITLE
edit request : Youth zone description on /sessions page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#260]
Copy reads, "Young people and adults will work in tandem across three **workshops** and 30 sessions. Together, we’ll explore new technology and how it’s relevant to all participants."

It should say, "Young people and adults will work in tandem across three **pathways** and 30 sessions. Together, we’ll explore new technology and how it’s relevant to all participants."

:pencil2:  cc @hannahkane 

**emphasis** is just to show the difference; the word should not appear bold

**Comment by hannahkane** [comment]
@mmmavis - possible to make this minor copy change today?

**Comment by Saallen** [comment]
Another edit request- this time for Storytellers and coders unite @mmmavis 

This is a pathway for those interested in creating factual interactive stories that can change the world. Join others to create new interfaces and interactive dynamics for stories to feel meaningful on the Web. Brainstorm on real projects and help building a community of professionals that want to work together and create amazing projects!

Pathfinders twiiter handle is @sgaudenzi

thanks

**Comment by mmmavis** [comment]
okay, noted, my todo for today :stuck_out_tongue:
