### ISSUE TITLE
Content capture meta-bug

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#263]
This ticket is to track content capture plans for MozFest 2015 (see our notes [here] (https://docs.google.com/document/d/1QtSxRfO6USTyHlFjCzYm6CFoYM3PL5BjiYJ0tfUuwrE/edit)), including:
- photography
- videography
- editorial content
- media partnerships

This work is in collaboration with Tim Murray from MoCo.

cc @HPaulJohnson @KevZawacki @Saallen @thornet

**Comment by SpikeUK** [comment]
I have a good photographer (https://www.flickr.com/photos/chaoticeunoia) signed-up to be a local volunteer - if she is happy, would you like her assigned to this project?

**Comment by thornet** [comment]
٩(^ᴗ^)۶

**Comment by edrushka** [comment]
Spike - sure. We have an abundance of video and photo help this year, and are trying to find meaningful projects for everyone.

**Comment by SpikeUK** [comment]
@edrushka OK - if acceptable, I will ask my volunteer to focus (did you see what I did there ;-) ) on taking pictures of volunteers. Over the years I have been conscious that we have a real dearth of images of MozFest volunteers.

**Comment by SpikeUK** [comment]
Another thing, Was introduced to Rahel Bailie (https://twitter.com/rahelab) by Dees as someone to livetweet from the fest - ok to ask her to cover proceedings on main stage?

**Comment by thornet** [comment]
From a conversation with Mark: 

* Let's focus on what the output of the Friday footage would be. Current preference is to have it be almost documentary-like, to illustrate how Mozilla does leadership development and really showcase that. 

@edrushka I suggest we set up a quick chat or email thread with Mark to capture the nuance and frame how the Friday footage is shot and used.

**Comment by edrushka** [comment]
Meeting with Mark is booked for this Friday.

**Comment by thornet** [comment]
Hero!

On Mon, Oct 19, 2015 at 6:31 PM, Erika Drushka <notifications@github.com>
wrote:

> Meeting with Mark is booked for this Friday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/263#issuecomment-149272278>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by edrushka** [comment]
@HPaulJohnson @KevZawacki can you please reply to @SpikeUK's question above about live tweeting?

**Comment by lovegushwa** [comment]
@edrushka we should connect on video / discuss how to work with this years volunteers.

**Comment by KevZawacki** [comment]
Hi @SpikeUK, re: live tweeting -- Rahel is welcome to share her experiences from her personal handle. She should make sure to tag "@Mozilla" in her tweets -- then we can see and RT certain updates.

**Comment by edrushka** [comment]
Film/video ticket is here: https://github.com/mozilla/2015.mozillafestival.org/issues/283  cc @lovegushwa

**Comment by SpikeUK** [comment]
@KevZawacki Thanks - "@Mozilla" or "#MozFest"? - or both?

**Comment by KevZawacki** [comment]
@SpikeUK Both is best

**Comment by SpikeUK** [comment]
:+1:

**Comment by cassiemc** [comment]
@edrushka Do we need to keep this open or are there now separate bugs?

**Comment by edrushka** [comment]
Open, please, in case people have general content questions.
