### ISSUE TITLE
Fundraising presence at MozFest

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#264]
This ticket is to track fundraising ideas for MozFest 2015.

#### Reasons to have a fundraising presence at MozFest 2015:
- provide information for attendees that Mozilla is a non-profit
- provide networking opportunities for attendees affiliated with other non-profit orgs
- demonstrate to media and institutional funders that we're actively engaging in donor stewardship

#### Ideas for presence:
- set up a table on the 4th floor beside the comms hub with a 'Did you know that Mozilla is a non-profit?' banner
- staff the table throughout the festival to explain what being a non-profit entails
- have donor thank you cards available for attendees to sign, if they desire
- have fundraising.mozilla.org on a laptop so people can see how we fundraise open
@valianttry any other ideas?

#### Optional
- I would like to try a 'Donate to Mozilla' bucket so people can contribute cash if they desire. While the funds collected would of course be appreciated, the real goal here is to invite people to take ownership in the Mozilla project by choosing to donate. AFAIK, this has never been tried at MozFest before, so I'm seeking input on this idea from @thornet @Saallen @HPaulJohnson

**Comment by thornet** [comment]
I like this idea, esp. being set up near the comms hub. 

Regarding donations, it might be interesting to put the bucket next to the coffee stands. The idea being: "instead of buying a cup of coffee, you could donate to mozilla!" 

However, I'm not sure what the legal / admin requirements are around reporting cash donations. Sometimes those can be tricky, but maybe after a certain amount?

**Comment by Saallen** [comment]
There are no legal requirements but we will want to have full transparency- that this money does not cover coffee or any MozFest costs. I would suggest not to have it here but set up a proper booth- area to sign cards for donors, show where our money goes and how we spent it. Whoever is manning this booth be prepped for BBQ questions- much much are our operational cost, do we publish our yearly accounts and how we spend our money. I think the key thing here is as Erika d said invite people to take ownership of the project, show how we spend it and what we can achieve together.

**Comment by thornet** [comment]
Makes sense! Let's do it!

On Fri, Oct 16, 2015 at 5:49 PM, Sarah Allen <notifications@github.com>
wrote:

> There are no legal requirements but we will want to have full
> transparency- that this money does not cover coffee or any MozFest costs. I
> would suggest not to have it here but set up a proper booth- area to sign
> cards for donors, show where our money goes and how we spent it. Whoever is
> manning this booth be prepped for BBQ questions- much much are our
> operational cost, do we publish our yearly accounts and how we spend our
> money. I think the key thing here is as Erika d said invite people to take
> ownership of the project, show how we spend it and what we can achieve
> together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/264#issuecomment-148752054>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by edrushka** [comment]
Wooo! Fundraising presence at MozFest! Thanks for your support on this idea, you two! :two_hearts:

I've been thinking this through, and there are really two ways to frame this idea:
Option 1: Educate and ask attendees to donate (as outlined above).
Option 2: Educate and ask to attendees to thank our donors (like we did at Whistler).

The key difference is how we want attendees to see themselves: as recipients of our donor's generosity or as donor-contributors themselves. There's arguments to be made either way (and regardless of what we chose, we'll be asking everyone who gives us an email address to donate to our EOY campaign).

What are your thoughts on which frame will resonate most with our attendees?

**Comment by valianttry** [comment]
We could do both, and just treat the donate ask as a "light touch". For example:

1. Put out a "Give what you can" box. During mozfest, show "donations totalizer" maybe on a screen, since our EOY campaign has launched already in DE; but also show "total raised at Mozfest" as a slice of that pie. 
2. Have Thank You cards out with pens as an ongoing project to invite anyone to participate. I particularly love the idea of some non-staff signing the cards this time. We can also have cards mailed from London office to UK donors (we have many UK donors).

**Comment by valianttry** [comment]
Forgot to mention I :heart:  we are going to do this (whatever 'this' turns out to be)! Thanks for taking the lead @edrushka and thanks @Saallen and @thornet for being so willing. Sometimes asking for money is weird / ick but it's part of who we are (and crucial to our mission). :hand:

**Comment by edrushka** [comment]
Discussed with Sarah. Will focus on thanking donors first, with the ask for money secondary.

**Comment by edrushka** [comment]
![img_20151019_164657](https://cloud.githubusercontent.com/assets/4515662/10594431/ef5179b6-7681-11e5-8f26-64e2bbab6969.jpg)

What I'm thinking so far. I've nixed the cash donation box as it will be too hard to monitor. Instead, will ask people to donate online.

**Comment by chrislarry33** [comment]
love it. i want to do some time at the table.

**Comment by edrushka** [comment]
We're having two staff poster-making sessions on Thursday and Friday. @sabrinang, @cassiemc  would looooove some of your skills to help me make the signage legible, if you can spare any time.

**Comment by cassiemc** [comment]
Sure, I'm in! On Thursday I will probably be stuffing the pins for the gear store swag bag thing, but my day is wide open on Friday.

**Comment by sabrinang** [comment]
@edrushka I'll be there to help! I'll have time on Thursday (An-Me gets in on Friday so I'll be working on Web Lit stuff with her then).

**Comment by cassiemc** [comment]
@edrushka I'd recommend you send an event invite out if you still need help with stuff. Otherwise, are we able to close this ticket, or file smaller follow-up tickets? Might be better in the fundraising repo :)

**Comment by valianttry** [comment]
Just coming back from PTO and have to say....... this is really amazing. :smiley:
