### ISSUE TITLE
Finalize 'Photo consent' documentation & language

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#271]
It might be unrealistic to ask everyone to sign a release form when they arrive to the festival.
I would like to email all pre festival with bare schedule outline and information about documenation at the festival- proposed content about the live documenting could look something like this

MozFest will be documented in a variety of forms, including video and photography. If you do not wish to be captured in an photos or video- please request a yellow lanyard from registration which will signify to all our media operators that you do not want to be photographed, interviewed or captured in group shots.

We ask all attendees to 
There is a variety of ways you can take precautions to ensure your own privacy and that of others.
Be mindful of others when taking photos, especially of young people and those who will be wearing the yellow lanyard.
We will be filming the 4th floor key notes but you can watch them from the ground level where there will be no recording of from the balconies above floor 5. 
Request a yellow lanyard when you register.
Avoid taking large sweeping landscape photos
Please note there will be rooms where no photos or recording in any capacity will be allowed and these areas willl be clearly marked.

Would love some feedback here from others @Melechuga @KevZawacki @edrushka :camera:

**Comment by KevZawacki** [comment]
@Saallen Works for me :-)

**Comment by edrushka** [comment]
Works for me, although I don't know the ins and outs of the law on this. The release form last year came from the Open Standard.

**Comment by edrushka** [comment]
I think Rainer and Spencer might want a release form though. Especially if their footage will make its way into other Mozilla videos (non-MozFest) like the Fundraising Thank You. Because their interviews will be more controlled, I think it will be possible for them to get people to sign the forms as needed.

**Comment by Melechuga** [comment]
This looks good! I would add a line about consenting to these principles...something like:  "by attending MozFest, you consent to following our participation guidelines (link) and photo/video documentation principles(?)." I'd also reiterate it somewhere by the entrance.

**Comment by cassiemc** [comment]
@Saallen do we need a physical copy of this hung in the venue? If so, I can file a new issue as part of the wayfinding materials.

**Comment by marcwalsh** [comment]
Hi @cassiemc yes we do - this will cover more general group releases for people that might be caught in crowd shots, apart from those who are wearing a no photo lanyard.

**Comment by cassiemc** [comment]
OK thanks @marcwalsh! I am adjusting this issue title slightly to reflect finalizing the content/language for this that we can then use in the design. New design issue filed as #302

**Comment by cassiemc** [comment]
Closing this. We have a poster designed in #302, just needs to be printed. Thanks all!
