### ISSUE TITLE
Wayfinding meta-bug

### ISSUE THREAD

**Issue by lovegushwa** [mozilla/2015.mozillafestival.org#276]
This ticket is to track work around Mozfest wayfinding including:

- large scale map
- hub orientation spot 
- session signage
- spaces banners
- floor vinyl

**Comment by lovegushwa** [comment]
Make a simple map that show what spaces are on which floors:

Map large:
- Foyer and Speaker floor,
- Poster size
- Mounted to foam board
- Display on easel or wall
- Quantity: 4x

Map medium: 
- On each floor in central corridor and in elevators
- Tabloid size 
- Mounted to foam board
- Display on wall
- Quantity: 20x

**Comment by lovegushwa** [comment]
HUB ORIENTATION SPOT:
A kind of info-booth help desk located in each "space" 

Journals
Science 
Open news
Localization 
Digital citizenship 
Global village

I need a link to images of and all design assets for a previous space.

**Comment by lovegushwa** [comment]
SESSION SIGNAGE:
A way of marking sessions within a space. Could be a DIY template each session fills in, could be per-printed. 

I need a link to a list of all sessions organized by space.

**Comment by lovegushwa** [comment]
SPACES BANNERS: 
These hang off rails and can be seen from main congregating areas on Foyer and Speaker floor.

- 1.2 x 2m
- printed on lightweight, nylon fabric
- 2 grommets attached to the top of each banner for hanging.

Blocker!!
I need to know which spaces banners we should make (all of them, some of them?)

**Comment by lovegushwa** [comment]
FLOOR VINYL: 
Can send people in the direction of Spaces on particular floors. Can be produced in the two days prior to Mozfest. Would work well with the map that gets people to a floor.

Blocker!!
- really difficult to plan this without walking the building / having very good knowledge of how people walk through the building and what's in a line of sight.

**Comment by lovegushwa** [comment]
@Saallen @cassiemc @marcwalsh

Unfortunately I have journey duty Monday and Tuesday (I have been told I can work on my laptop while I'm there, god help us if I'm chosen for a jury). We need to pick maybe two of these and @natalieworth and Beth can help. Any thoughts on what's practical and what we could cut or how else we can get help here @cassiemc ?

**Comment by cassiemc** [comment]
Boo jury duty!!! That could not be worse timing :)

But I think we can get this covered. @Saallen does Beth have a github name? Is she totally on-board now?

We will be able to reuse the floor map that @adiladiladil is designing for the Festival Guide in #212 . It should all be vector so easy to isolate that and print independently at different scales.

We should be able to print anything basic on-site at Ravensbourne. I believe @Saallen is contracting another student to help with that. Sarah do you have contact info for our print liaison yet? Will they be printing other things as well?

I'm not sure the printing on fabric will be possible at this point as we'd likely have to contract that out. Am I correct in thinking that, @marcwalsh @Saallen? We could *possibly* paint them ourselves given the hand-lettering in the posters, which I'm comfortable doing but I don't arrive in London until Thursday afternoon.

From what I understand, pathways do not have orientation spots. They are collections of sessions that happen in various spaces. My sense is that we should concentrate on the spaces (the floors) and the room numbers. @Saallen is there a master list yet of all the accepted sessions and rooms / locations where they will be held? I believe you were still working on that last week. And I understand this needs to be hackable to some degree.

I'll file bugs for these things and keep it under a 'wayfinding' label so it's easily trackable. Thanks for all this foresight @lovegushwa.

**Comment by cassiemc** [comment]
@lovegushwa I've filed everything above as separate issues with the ```wayfinding``` label: https://github.com/mozilla/2015.mozillafestival.org/labels/wayfinding

I'd like to close this meta bug, so please let me know if I've missed anything and if so, file it as a new bug. Thanks!
