### ISSUE TITLE
Automatic session notes-

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#277]
Hi @mmmavis 
In prevous years we have created Session notes on etherpads for facilitators to use during their sessions as a resource for the participants during and after the festival. The amazeballs @fuzzyfox has coordinated within the session description in the schedule.
@fuzzyfox in previous years how did you do this voodoo magic?
We would love to continue this trend for this year and encourage other folks to build this these sessions to continue to work in the open

cc @hannahkane @thornet

**Comment by cassiemc** [comment]
@fuzzyfox any thoughts here? (excited to see you soon!!!)
@mmmavis thoughts?

**Comment by ioana-chiorean** [comment]
Just a small reminder that the etherpads transitioned to https://public.etherpad-mozilla.org. 
@fuzzyfox  let me know if u need help here.

**Comment by fuzzyfox** [comment]
Unfortunately I don't think this voodoo is possible using new etherpad. In the previous instances we utilized a configuration trick that was available to team pads. This is no longer the case.

It may still be possible to do this using some API magic and bulk-creating etherpads, though I'm not 100% sure we can do this without having the keys to the etherpad castle... :| Will do a little looking into this for you.
