### ISSUE TITLE
Large maps for wayfinding

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#279]
**Deadline: October 28th**

We need 4 large poster-sized maps to be mounted on foam board for wayfinding. They'll be placed on the foyer and speaker floor, displayed on easels (preferable) or on the walls.

We also need 20 medium sized maps, also mounted on foam board, to be placed on each floor in central corridor and in elevators. Tabloid size (what's the uk equivalent?)

- [ ] large maps on foamex x4
- [ ] medium maps on foamex or thick cardstock, x20
- [ ] individual floor maps (how many @lovegushwa?)
- [x] ~~buy foam core~~
- [x] ~~print and mount on foam core~~
- [ ] secure easels

We can use the vector maps from the festival guide #212 

Just need to determine a size. What is the max size we are able to print at Ravensbourne @marcwalsh? Foam core is typically 32x40'' max.

cc @lovegushwa @Saallen

**Comment by cassiemc** [comment]
@marcwalsh to look into easels, Ravensbourne might still have them

We may just print the 20 med-sized posters on thicker card at Ravensoubourne, but the others we will probably have printed & mounted by (pixart)[https://www.pixartprinting.co.uk/wide-format/printing-banners-mesh/ecoflat-banner/]

Printer needs a 5 working day turnaround, so Nov 29th should be good.

**Comment by marcwalsh** [comment]
@cassiemc - Could we aim for Oct 28th for the deadline if possible to ensure delivery as we're looking to have all deliverables by the 4th November to ensure there is buffer time for postage/courier delays.

**Comment by cassiemc** [comment]
Sounds good @marcwalsh

**Comment by cassiemc** [comment]
This is blocked by the map being created on the Mozfest Guide #212

**Comment by lovegushwa** [comment]
We also need individual maps of each floor for the info booths #280

**Comment by cassiemc** [comment]
Have updated comment 1 to reflect additional needs.

**Comment by natalieworth** [comment]
For the 4 large posters, here are the available sizes from the printer?
https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/acrylic/

Which do you think would be best for the space? 70cm x 100cm is close to the 32" x 40" size. Or we could do square.

cc @cassiemc

**Comment by natalieworth** [comment]
Map drafts and some questions are up on red pen @cassiemc. I'm using the A4 size for UK (it's close to tabloid).

**Comment by lovegushwa** [comment]
Awesome @natalieworth , you should use A3 (closest to Tabloid), A4 is the equivalent of Letter. (I used ISO paper sizes in my last job :)

**Comment by lovegushwa** [comment]
@natalieworth do you have the redpen link?

**Comment by natalieworth** [comment]
Ah sorry I meant A3

**Comment by natalieworth** [comment]
A4 is letter I think

**Comment by natalieworth** [comment]
@lovegushwa  Here's the link https://redpen.io/zg6913681be2834c2c

**Comment by lovegushwa** [comment]
@natalieworth cool :) yes A3 is the size we want !

**Comment by cassiemc** [comment]
@lovegushwa What is the plan for printing and mounting these?

**Comment by lovegushwa** [comment]
@cassiemc I think we should print, mount and install these at the school on Friday. We can omit the larger maps and just do A3.  

It will be tight, but it gives us the opportunity to drop spaces names into the map before printing and it looks like there won't but much room on the map to write or place a tiny sticker.

**Comment by cassiemc** [comment]
@lovegushwa That sounds fine. I do think we should reassess the map layouts and make them vertical, with possible adjustments to how each room is labeled (could use lines out to larger text if the type is too small as-is). We might wait to decide re. space labels until we see that new layout. cc @natalieworth

**Comment by marcwalsh** [comment]
@natalieworth @lovegushwa - We will need these A2 sized which is 16.5in x 23.4in they need to be pretty big to ensure they can be seen from a bit of a distance.

**Comment by natalieworth** [comment]
Hey @lovegushwa:

![map_04-01](https://cloud.githubusercontent.com/assets/14876567/10740056/48ad2d24-7bdd-11e5-837d-d05e82b7b020.png)
![map_04-02](https://cloud.githubusercontent.com/assets/14876567/10740057/48c697fa-7bdd-11e5-8f0d-912a5945c156.png)
![map_04-03](https://cloud.githubusercontent.com/assets/14876567/10740058/48c9b32c-7bdd-11e5-8fb3-66150bbc00c8.png)

**Comment by natalieworth** [comment]
@lovegushwa Emailed the ai file to you. Are we keeping the 4 large maps too, or just sticking with the A3 size?
Updates on redpen too: https://redpen.io/p/zc3ebeaf4e02b0814e
cc @cassiemc

**Comment by lovegushwa** [comment]
@cassiemc @natalieworth 
I think we can simplify the map. 

We list what's on each floor (the session, coffee, water, etc.) in a kind of a reductive directory list that mimics how the building stacks around the flight of stairs. Next to that directory list we then provide a detail map of a particular floor. We need to create a map for each floor anyway. 

<img width="546" alt="screen shot 2015-10-26 at 1 16 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/10741305/40cc9bb0-7be4-11e5-9c07-1c236913fa47.png">

<img width="551" alt="screen shot 2015-10-26 at 1 16 19 pm" src="https://cloud.githubusercontent.com/assets/12228435/10741438/130cc97e-7be5-11e5-8310-8eb3025ecf7b.png">

**Comment by marcwalsh** [comment]
@cassiemc @lovegushwa @natalieworth  - Hey, just checking in with this. For the large maps, we're looking for indiviual A2 prints of each map on foamex rather than a map of the entire venue.

Is this for something different, sorry if there's been a miscommunication!

**Comment by lovegushwa** [comment]
@marcwalsh we are sorting this out in the next hour and will let you know. Will probably be something like four copies of the same A2 map.

**Comment by marcwalsh** [comment]
@lovegushwa - If these are the main maps then let's make it bigger still if it's simple for you. Can we go for A1 instead?

**Comment by lovegushwa** [comment]
@marcwalsh we can do A1, were still sorting out exactly what we will make. Should let you know soon.

**Comment by lovegushwa** [comment]
@cassiemc @natalieworth here is a draft of where we can go with the maps. 
Needs some more beautification, any content missing? Any additional explanation needed?

![mozfest2015_map_jordan-01](https://cloud.githubusercontent.com/assets/12228435/10769145/d0e4ca34-7ca1-11e5-8819-a92c6fbabd15.jpg)

**Comment by cassiemc** [comment]
@lovegushwa Why are certain floors in green?
Would prefer the Ravensbourne logo in pink, I think, however we can match the festival guide at this point since that's already gone to print. And some of the icons seem disproportionate to each other.

**Comment by lovegushwa** [comment]
Color not final, I was working quickly .
Why do we need the ravensbourne logo at all? It seems unnecessary and does
not improve the function of the map. I'll fix the icons :)

**Comment by cassiemc** [comment]
That's fine to eliminate it. I do think it adds an air of official-ness and connects to the other map in the guide but I'm not going to debate it too much! It's worth thinking about the scale of the two maps, to be sure one is clearly a zoomed out and one is clearly a zoomed in view.

**Comment by natalieworth** [comment]
Hey @lovegushwa Did you need me to help with these still?

**Comment by cassiemc** [comment]
@Saallen @thornet Are you guys any closer to finalizing the floor names / are you still planning to do that soon? If so, then we should plan to get the A1 maps to printers as soon as we have that info and can finalize the assets. If not, then we might forgo the A1 maps in lieu of the smaller, more complete maps we make ourselves at Ravensbourne. cc @lovegushwa

**Comment by cassiemc** [comment]
@lovegushwa Do you have an update on these assets?

**Comment by natalieworth** [comment]
@lovegushwa I'm going to close this if that's all good? Not sure if we have to post the final files here? Thanks :)
