### ISSUE TITLE
Design info booth help desk

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#280]
**Deadline: October 28th**

Not sure if this is being covered elsewhere, but we can tie design of the booth into our other wayfinding materials.

@Saallen @marcwalsh can you post pics of previous info booths, or any current details about this? We'll need to know what the potential is for customizing this, how many booths, and where they will be located.

cc @lovegushwa

**Comment by lauralillepruun** [comment]
@cassiemc  <img width="232" alt="screen shot 2015-10-21 at 2 14 02 pm" src="https://cloud.githubusercontent.com/assets/15231997/10645906/27cf70c2-77fe-11e5-8d64-d63fb954f655.png">

**Comment by lauralillepruun** [comment]
<img width="620" alt="screen shot 2015-10-21 at 2 14 29 pm" src="https://cloud.githubusercontent.com/assets/15231997/10645917/3993d078-77fe-11e5-8f74-24452246b614.png">

**Comment by lovegushwa** [comment]
@cassiemc @lauralillepruun any idea where the digital files are for the posters in the 1st photo?
maybe @sabrinang has them :) ?

**Comment by sabrinang** [comment]
@lovegushwa Unfortunately, I don't have these assets (I believe it would be from the contractor who worked on it last year).

**Comment by Saallen** [comment]
@lovegushwa all posters are in the dropbox files I shared in a previous call

**Comment by cassiemc** [comment]
@lovegushwa heads up if there are any assets that need to be printed externally we'll have to move the milestone forward on this.

**Comment by lovegushwa** [comment]
I believe this is a set of old posters:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvVmxsNnR2RW1VaWs/view?usp=sharing

<img width="862" alt="screen shot 2015-10-21 at 1 47 55 pm" src="https://cloud.githubusercontent.com/assets/12228435/10649720/635492e8-77fa-11e5-8bd0-c9f1ea55c769.png">

**Comment by lovegushwa** [comment]
@cassiemc So we need to develop a set of A3 posters above. If these were mounted to foam core they would look way better. Also we need a individual map of each floor.

**Comment by lovegushwa** [comment]
@lauralillepruun I'm thinking Beth can work on these posters.

**Comment by cassiemc** [comment]
@lovegushwa I spoke to @marcwalsh this morning and if we want them mounted, we might want to order them premounted on foamex rather than do them ourselves, unless we can wrangle a student or Beth to do it. Just hard to arrange all the supplies (and find the time) logistically. However, we are running out of time to order these from an external source.

**Comment by lovegushwa** [comment]
@cassiemc totally, you can see from the 1st photograph they will look much better on foamex. 
Perhaps it's time to embrace that DIY esthetic.

**Comment by cassiemc** [comment]
Bringing up the deadline since it seems like we'll be ordering them out. Deadline of getting them to the printer on Oct 28th should put us in a good spot.

**Comment by lovegushwa** [comment]
Info for Beth (Ravensborn alumni working with us on way-finding :)

Example of previous posters:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvVmxsNnR2RW1VaWs/view?usp=sharing

Copy for sessions posters:
https://2015.mozillafestival.org/sessions

**Comment by cassiemc** [comment]
Updating to the new milestone. @lovegushwa what is the plan for printing these?

**Comment by lovegushwa** [comment]
@lauralillepruun Is Beth on github OR can you send me Beth's email again so I can get her started?
Thank you!

**Comment by lauralillepruun** [comment]
@lovegushwa it's beth.lardner11@gmail.com

**Comment by lovegushwa** [comment]
@cassiemc Beth is going to send a draft tomorrow. 
@lauralillepruun you are setting a meeting up with Beth and myself I think?

**Comment by lauralillepruun** [comment]
@lovegushwa Yes, what time would be good for you?

**Comment by lovegushwa** [comment]
9am is perfect if that works.

**Comment by lauralillepruun** [comment]
@lovegushwa Would 9.15 be ok?

**Comment by lovegushwa** [comment]
Perfect thank you !

**Comment by lovegushwa** [comment]
@marcwalsh these are ready to print at https://www.pixartprinting.co.uk
https://drive.google.com/folderview?id=0B2qu3ExKWIlvQTdxU2VBMnZPUVE&usp=sharing

8 files total, 1 of each
<img width="856" alt="screen shot 2015-10-29 at 7 02 59 pm" src="https://cloud.githubusercontent.com/assets/12228435/10837251/576108a6-7e74-11e5-9ed2-8f0b42e4a912.png">

1 file total, 10 copies
<img width="880" alt="screen shot 2015-10-29 at 7 31 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/10837258/6e5e58d8-7e74-11e5-8bbf-bd65d92a58a1.png">

**Comment by marcwalsh** [comment]
All ordered!

**Comment by lovegushwa** [comment]
Great thank you Marc!

**Comment by marcwalsh** [comment]
Artwork confirmed, sent to print. Closing...
