### ISSUE TITLE
Design floor vinyl stickers

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#281]
This will be hard to design ahead of time without being in the space. Perhaps we can come up with some generic decals to design and cut ahead of time, then lay it all out when we get there. Suggest:

* arrows
* 1-3 cutouts for each floor with the space name
* icons for help, toilets, food... anything else @Saallen? 

Other ideas @lovegushwa?

What is the deadline for getting the vinyl printed and cut @Saallen? (Do Laura, Beth or the contracted students have github names?)

**Comment by lauralillepruun** [comment]
I think besides the space names, we would need to direct people to the toilets, water and the info desk perhaps.

**Comment by lovegushwa** [comment]
@cassiemc @lauralillepruun  true we could set the files up so you can flip the direction of the arrow when installing. I would focus just on the space names to keep it simple (perhaps with the addition of coffee / water stations) The building signage can direct people to toilets. The info desks should be centrally located in a space, so if you find the space you find the info desk?

@cassiemc I have 1 student that's available to help (not a whole class). Cutting and installation will take a day or more. Also these need to be removed after.

**Comment by lauralillepruun** [comment]
The info desks are on each floor, so as far as I know, there could be more than 1 space on a floor, but still only one info desk. They are usually situated at the top of the stairs as you reach a floor.

**Comment by lovegushwa** [comment]
@lauralillepruun I just want to confirm, info desks are different than hub orientation spots?

**Comment by lauralillepruun** [comment]
@lovegushwa no they are the same things

**Comment by lovegushwa** [comment]
@lauralillepruun let's get Beth started on planning this. @Saallen do you approximately when the Spaces on each floor will be locked down so we have defined map? This is also crucial for #280 #279

**Comment by Saallen** [comment]
@lovegushwa in previous years we have not allocated the spaces to floors until the Thursday of the event. The plan is however to work on this work flow this week

**Comment by lovegushwa** [comment]
@Saallen yes that would be excellent if possible :)

**Comment by cassiemc** [comment]
@Saallen any updates on floor assignments? @lovegushwa I'd venture to say we could start on this before we have that info. Going to remove the 'blocked' label.

**Comment by lovegushwa** [comment]
@marcwalsh 
Can you ask your contacts at Ravensbourne college the exact specifications of the vinyl we need to order?

- What brand do they prefer if any ?
- What roll width?
- Will we need to cut the roll down to flat sheets for the Zund machine?

Once we get the specifications, please order a pink roll that's close to or matches Pantone 191 or 812. If you can't find a close match order black.

- Matte finish (not glossy)
- We need a 1.2x20m

**Comment by lauralillepruun** [comment]
@lovegushwa @marcwalsh I'm waiting for Lauren to put me in touch with the guys, as soon as she does, I will check with them about the vinyl and order it

**Comment by lauralillepruun** [comment]
@lovegushwa this is the reply I got-  the zund machine is A1 in width but it can be longer, however the length has to be A1
there is no preference on brand,
and it doesnt have to be cut as the machine has a vaccuum bed which allows it to fit it

Does that answer all your questions?

**Comment by lovegushwa** [comment]
@lauralillepruun 
Metamark Vinyl is good, it should be broadly available. 

M4-382M (Magenta Matte) if available. If not M4-311M (Black Matte) 
760mm roll width. 30m length to be on the safe side.

http://www.metamark.co.uk/pages_sv/4seriesgl.htm#gloss
<img width="886" alt="screen shot 2015-10-30 at 11 54 39 am" src="https://cloud.githubusercontent.com/assets/12228435/10855349/48066ede-7efe-11e5-952f-910e2343d062.png">
