### ISSUE TITLE
Design session signage

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#282]
I have a feeling this might have already been covered by #235, which is a blank, hackable sheet that session leaders are expected to fill out. Am I right @Saallen?

@lovegushwa let us know if that meets your needs for this or if you have additional ideas.

But I'm otherwise not sure that it makes sense to design session titles ahead of time, given the hackability of the schedule.

**Comment by lovegushwa** [comment]
@cassiemc  I love the idea of hackable session titles. When speaking with @Saallen one of the most confusing parts Mozfest wayfinding is trying to locate your session in a space. 
It sounds like doing this right could have a really big impact.

We could stick with the session template, ideally we get it off the surface of the table. (kind of like those restaurant flags with a number on them.) Printing on something really bright (and we only use that color for session titles.) Typesetting the names would make them much more readable across a room but not necessary.

I know were short on time.

(this could be done with 2 pieces of foam board hinged with tape.)
![5e50249ac95e4682d76eba1d77eb31eb-1](https://cloud.githubusercontent.com/assets/12228435/10642522/f622ec64-77d2-11e5-962d-29965b73a0f9.jpg)

**Comment by cassiemc** [comment]
It's my impression that session names will need to be hung on walls rather than placed on tables. cc @Saallen

**Comment by lauralillepruun** [comment]
No, we would want the session names to be on tables as they will most probably be changed a lot and will need to be accessible. We can move the tables around easily, but if we stick something on the wall if might not be the first thing people see due to the layout of the spaces.

**Comment by lauralillepruun** [comment]
Oops, forgot the @cassiemc

**Comment by cassiemc** [comment]
ah, ok @lauralillepruun – where will the tables be? is there a table outside each room?

**Comment by lauralillepruun** [comment]
@cassiemc there will be numerous tables in each space so we can place one of them to be towards the entrance of the space to make it more visible. Almost all of the spaces are open so there aren't any separating wall/doors, only pillars.

**Comment by marcwalsh** [comment]
+1 to @lauralillepruun - We were thinking something simple like small 'pub style' chalkboards that are given to each wrangler for their sessions to use.

**Comment by lauralillepruun** [comment]
@cassiemc @lovegushwa something like the first pins on here https://www.pinterest.com/sarahretro/signage-ideas/

**Comment by cassiemc** [comment]
Ok sounds like @lovegushwa was on the right track then! :) Jordan, does chalkboard seem like a possibility? What about a strip of colorful vinyl you could write on with Sharpie? Might make readability hard.

**Comment by lovegushwa** [comment]
@cassiemc @lauralillepruun 

1   table top sign holder:
http://www.amazon.co.uk/Displaypro-Acrylic-Desktop-Counter-Display/dp/B00F42SZM4/ref=sr_1_6?ie=UTF8&qid=1445454493&sr=8-6&keywords=sign+holder

(for pre laminated cards, some one in the shop could make these)
http://www.amazon.co.uk/EPOSGEAR%C2%AE-Acrylic-Display-Place-Holders/dp/B008FL6R8K/ref=sr_1_212?s=officeproduct&ie=UTF8&qid=1445454893&sr=1-212&keywords=sign+holder

2    Flag style sign holder (these are cheap and easy to store!):
http://www.amazon.co.uk/Argon-Tableware-Table-Number-Holders/dp/B002OS2L30/ref=pd_sim_sbs_229_10?ie=UTF8&refRID=1QJC0NYBRPAA2WCGNGH1

3    DIY sandwich boards / we make these


4    Chalk board
http://www.amazon.co.uk/BHMA-Limited-Dark-Oak-Easel/dp/B014SY7YFM/ref=sr_1_46?s=kitchen&ie=UTF8&qid=1445455104&sr=1-46&keywords=table+top+chalk+board


![img_20151021_120338](https://cloud.githubusercontent.com/assets/12228435/10647269/32c59c16-77ec-11e5-9751-48dffe193ad4.jpg)

**Comment by cassiemc** [comment]
I like the flag style and think we could design a really nice template for them. I like the chalkboard too and I'm sure we could make it work but it seems a little outside of brand.

**Comment by lauralillepruun** [comment]
I agree about the flag style ones.

**Comment by lovegushwa** [comment]
@lauralillepruun @cassiemc 
Cool, I agree :)  ... who can order these and how many do we need?
http://www.amazon.co.uk/Argon-Tableware-Table-Number-Holders/dp/B002OS2L30/ref=pd_sim_sbs_229_10?ie=UTF8&refRID=1QJC0NYBRPAA2WCGNGH1

**Comment by lauralillepruun** [comment]
I can order them. As far as I know, we have 8 spaces, and 19 pathways so maybe I should order 30. They are a bit pricier so I'll double check with Sarah re the budget, but it should be fine. Will let you know as soon as I have the go ahead to order.

**Comment by cassiemc** [comment]
I've seen low-fi versions of these too. Sticks in a bag of sand sort of thing. Is that an option @lovegushwa ?

**Comment by lauralillepruun** [comment]
drama over. I missed the bit when it said 'box of 12' :) I can definitely order them!

**Comment by lovegushwa** [comment]
@lauralillepruun @cassiemc I agree let's order them.

**Comment by cassiemc** [comment]
sweet!

**Comment by natalieworth** [comment]
@Saallen Is it necessary to include both 'session name' and description sections for the session cards at each table? We'd have more space if we just used 'session name,' but I wasn't sure if the description was important to include on the table holder cards. Thanks

**Comment by lauralillepruun** [comment]
@natalieworth I'm pretty sure we are ok to just include the session name

**Comment by natalieworth** [comment]
I've got versions of the new 'session name' cards up on redpen:
https://redpen.io/kg57f9c533b60e6738

I'm thinking these will be printed on a heavier weight/ card stock paper. We could either do a shape or just a rectangle. Rectangle may logistically be easier if there's a lot that need to be printed.

**Comment by natalieworth** [comment]
cc @lovegushwa  too ^

**Comment by natalieworth** [comment]
Hey @cassiemc and @lovegushwa, updates to the session name cards are on redpen. I've posted a few comments/ questions I had too:
https://redpen.io/quf942902c8d234d41

**Comment by cassiemc** [comment]
Great @natalieworth I left some comments. Could you mock up how that would look in the metal flag post things we ordered?

**Comment by lovegushwa** [comment]
@natalieworth @cassiemc also we may print these in black and white on Neon
paper so they REALLY stand out.

**Comment by cassiemc** [comment]
@lovegushwa where will the neon paper be used? A little concerned it won't mirror anything else if used here, but maybe you have plans to use it elsewhere in wayfinding?

**Comment by lovegushwa** [comment]
@cassiemc well your right about it not being used in other parts of the
wayfinding (we could figure out how to include it in the info both design
possibly.)
But, I do think these signs are hyper critical (the biggest problem in
prior years) and a very bright color like neon will help people scan the
room for signs. So from a purely functional point of view, I think the
benefits of neon trump brand consistency, this will also come across as
really apparent. No one will say, "I wonder why they used neon?"   ... :)
of course I don't know how much other neon people bring to Mozfest so if we
think there is going to be a bunch of other neon orange signs in the room
than perhaps a blue gradient is better.

CC @natalieworth

**Comment by cassiemc** [comment]
Agree these signs are hypercritical. It's impossible to know what materials people will bring, but there has always been a very strong DIY maker aesthetic presence at mozfest so I think that's a valid concern.

I think the neon could be more effective if we actually used it consistently, say neon pink that is also mirrored with neon pink vinyl, and possible behind or with the official maps. Or perhaps used specific shapes or strategies that only official mozfest uses. (ie. layers of foam core, poster board, foam core, posterboard so that it pops out 3d)

**Comment by lovegushwa** [comment]
@cassiemc neon pink is a great idea! Let me send over some sketches on how
we might use it in some of the other parts of the system.

**Comment by Saallen** [comment]
We supply folks with card, paper, pens, markers and other art treats so we will ensure that we dont order any other neon- CC @lauralillepruun here for confirmation
Side not we have 39 pathways!!!! I left a note on the red pen that Session name is enough on the cards as these are orientation markers for sessions :card_index:

**Comment by natalieworth** [comment]
Hey @lovegushwa @cassiemc , here are some mockups of the session name tags. I've put them up on redpen too: https://redpen.io/p/zc3ebeaf4e02b0814e

![sessionname_mockup_01](https://cloud.githubusercontent.com/assets/14876567/10742868/c0365870-7bec-11e5-8ca9-3a35d2802364.jpg)
![Uploading SessionName_mockup_02.jpg…]()

**Comment by cassiemc** [comment]
Woot, that's helpful @natalieworth! Makes me think we should design with a larger margin at the bottom, probably adding some height to the card (people will probably push the sign all the way down and the ring will end up overlapping handwriting). Are these designed to be a certain number of cards per paper? Would love to reduce the amount of paper waste if possible.

**Comment by marcwalsh** [comment]
@natalieworth @cassiemc - Can I get dimensions for these so I can cost up printing please.

Would these be double sided?

**Comment by natalieworth** [comment]
@cassiemc - Updates are on redpen with a larger margin at the bottom:
https://redpen.io/p/zc3ebeaf4e02b0814e

@marcwalsh, I made the designs to fit 2 to an A3 paper size along with a bleed. In the image below, the bleed is marked with the red line. We should also be able to print these double sided.

![a4_mockup-04-03](https://cloud.githubusercontent.com/assets/14876567/10745537/fe7d211e-7bff-11e5-8024-21f0e1678ab4.jpg)

**Comment by cassiemc** [comment]
@natalieworth I definitely like the blue version. Just one comment about the label type.
@marcwalsh We could potentially print these on cardstock at Ravensbourne but they would need cutting.

**Comment by natalieworth** [comment]
@cassiemc updated the 'session name' to caps and up on redpen: https://redpen.io/fw40cd519fbe9093e1

![sessionname_mockup_10](https://cloud.githubusercontent.com/assets/14876567/10773389/65f465e2-7cb8-11e5-8ed4-8c86486ddab7.jpg)

**Comment by lovegushwa** [comment]
These need to be printed on light card stock ~200gsm paper. Tricky at A3,
thick enough to not flop over in the stand, light enough to run through a
printer without jamming. For that reason it would be great if we had these
printed outside if possible and we can use a little bit thicker stock and
print on both sides. I'm ok with letting the idea of neon paper go.

**Comment by cassiemc** [comment]
Ok cool! If we can print out, let's do it. cc @marcwalsh

**Comment by marcwalsh** [comment]
@cassiemc @lovegushwa - Amazing! I think we're just going to get these printed with Aspect, it will make it a lot easier especially with the quantity. 

Are you able to send me across the artwork?

**Comment by cassiemc** [comment]
yay! @natalieworth has the artwork

**Comment by natalieworth** [comment]
Print ready files for this are here in .ai and pdf format with bleed and trim marks set: https://drive.google.com/open?id=0B20-0lpP23c0N3lCSkh2eU55VU0

cc @cassiemc @lovegushwa @marcwalsh @Saallen

**Comment by lovegushwa** [comment]
looks good, @marcwalsh let's print these double sided.

**Comment by cassiemc** [comment]
@marcwalsh let us know if we're good to close this, thanks :)

**Comment by natalieworth** [comment]
Closing this with final files here: https://drive.google.com/open?id=0B20-0lpP23c0N3lCSkh2eU55VU0
