### ISSUE TITLE
Clarify videography at MozFest

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#283]
We'll have 4 distinct video teams:
#### 1) Dosed 
- they will create the 2016 promo video
- they've shot, edited and composed the music for the last two years' videos
- Erika D will be point of contact during the day

#### 2) Rainer & Spencer from MoCo
- they shot the Webmaker promo video
- they'll be conducting a series of controlled interviews in a quiet location with questions coming from Tim Murray and MEM. Questions will be written to elicit in-depth, emotional responses from attendees about why they care about the web. 
- this footage may be edited into a MoCo project at some point (tbd)
- part of the discussion will be about Mozilla's role as a non-profit, and how we can thank our donors. This footage will be used to make a [Fundraising Thank You Video] (https://github.com/mozilla/donate.mozilla.org/issues/430)
- MEM will be point of contact during day (need to confirm this)

#### 3) Ravensbourne Students
- ~~Teams of Ravensbourne film/media students will be conducting a weekend-long shoot with their peers, interviewing them before and after attending the festival to see how their views of the open web change after attending mozfest.~~
- ~~Point of contact will be their instructor~~
- **Update Oct 26 Ravensbourne students will not be filming at MozFest**

#### 4) Air Mozilla
- The lovely AirMo team will be joining us again. This year, Dosed will provide them with a very high quality video stream and we'll get them the keynote slides ahead of time to integrate into the final videos.

cc @Saallen @HPaulJohnson :video_camera::movie_camera::video_camera::movie_camera:

**Comment by edrushka** [comment]
Note that the Ravensbourne idea was not accepted. I'll post update plans when they become available.

**Comment by cassiemc** [comment]
@edrushka assigning this to you, please feel free to change if that's innaccurate.

**Comment by cassiemc** [comment]
@edrushka Any updates here, can we close?

**Comment by edrushka** [comment]
I'd like to leave this open for now as some specific pieces of the video work are still in flux.
