### ISSUE TITLE
Create space names & icons to stick on the large maps

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#285]
The spaces will not be allocated and finalized by the time we print the Festival Guides. If possible we should make some size-appropriate vinyl stickers we can print on the large foamex maps that will be in the space.

cc @lovegushwa

**Comment by lovegushwa** [comment]
@cassiemc cut Vinyl will be really difficult, you have to pull out all the letter counter forms with an x-acto blade, and it's almost impossible to do below 30pts ... We could do printed stickers, we can also print on color vinyl (like you can print back ink on yellow vinyl with a UV printer for example.) ...  We could also leave blank's on the maps and have the space wranglers fill them in! It would tie the map to the poster nicely.

**Comment by cassiemc** [comment]
stickers would be fine and good!

**Comment by cassiemc** [comment]
It doesn't sound like we are going to do this. Since we'll be printing med-sized posters onsite, we should be good to wait until the spaces are allocated.
