### ISSUE TITLE
Prepare slide template and final designs for mainstage speakers

### ISSUE THREAD

**Issue by HPaulJohnson** [mozilla/2015.mozillafestival.org#286]
Mainstage speakers are in the process of preparing talking points and suggesting slides to accompany their talks. We'll take those ideas, polish the design and put them in a single template for a cohesive look/feel across the entire program. 

cc: @cassiemc

**Comment by edrushka** [comment]
adding myself

**Comment by cassiemc** [comment]
Plan when we last spoke was for @lovegushwa to come up with a template then pass this bug off to @natalieworth who can help with the final implementations.

@HPaulJohnson do you know the deadline for speakers to submit their materials?

**Comment by HPaulJohnson** [comment]
We've asked to have them by the end of the week though we should expect some slip and don't arrive until early next week.

**Comment by edrushka** [comment]
When the template is done, let's add it to the Ravensbourne TV ticket here: #300

**Comment by lovegushwa** [comment]
@HPaulJohnson we should consider using one of the official templates, we
can augment a bit if needed?

BLUE
https://docs.google.com/a/mozilla.com/presentation/d/1OKEoa_RWBGMxPfPs32cjB9R3SgYvhURNCcahLTVcI-s/edit?usp=sharing


Also, do we say we have a preference for Google Slides (so we can
collaboratively share and edit.) Provide a Power Point OR Keynote as a
backup, and a guideline for creating a PDF as a last resort?

... If we can swing it my preference is Google slides only!

<https://docs.google.com/a/mozilla.com/presentation/d/1OKEoa_RWBGMxPfPs32cjB9R3SgYvhURNCcahLTVcI-s/edit?usp=sharing>

**Comment by HPaulJohnson** [comment]
Using the official templates works for me. I think we can request everything in Google slides and use that for everything.

**Comment by HPaulJohnson** [comment]
forgot to add, are there versions of these official templates without the "confidential" small print at the bottom? we'll want to take that out at the very least.

**Comment by lovegushwa** [comment]
@HPaulJohnson good idea, I'll see if we can pull that out.

**Comment by cassiemc** [comment]
@HPaulJohnson We should talk about the strategy for the slides for individual speakers. We think the template absolutely makes sense but doing everyone's slides may not... let's follow up offline.

**Comment by cassiemc** [comment]
@sabrinang Looks like @lovegushwa needs help with adjusting the template. Can you help with this? We're aiming to have it done end of this week / early next week. When do you fly out to London?

**Comment by lovegushwa** [comment]
@sabrinang so I think it's straight forward. You have been doing lot's of deck work for teach, if you think something is missing or does not work well in the official template feel free augment. 

- We need to pull the confidential and Tabzilla out.
- We could also maybe add some Mozfest flare to the title slide (very subtle, could be the gear).
- Could be nice to show a few ways to place an image or graphic (think people that have no design background.)

CC @HPaulJohnson @cassiemc

**Comment by cassiemc** [comment]
@kristinashu is going to take this one on instead of @sabrinang. Thanks Kristina :)

**Comment by kristinashu** [comment]
@lovegushwa @cassiemc here are the updated slides:
- Removed confidential and Tabzilla
- Added some background pattern to the title slide
- Added three options of image layouts

I did two version, one with the Mozilla light blue https://docs.google.com/a/mozilla.com/presentation/d/1ce0FxNJ1XnBbT6ZECdEJ1St87u86PL5kByBXohrSAE4/edit?usp=sharing
and another with the MozFest dark blue https://docs.google.com/a/mozilla.com/presentation/d/1JyLTCgLypUHYnbBpg7NVaKTYlswB4HCaOqKLdye5JBw/edit?usp=sharing

Let me know what you think.

**Comment by cassiemc** [comment]
Thanks for this @kristinashu, such a big help. I like that you included two different color schemes, and love the background. A few things:

* Are slides 2-5 intended to be completely blank?
* I would include a title page with name of the talk, name of the presenter, and their position / organization
* Slide 7 - the pic doesn't look properly placed on the page. Was there meant to be a caption or something?
* Would include a slide treatmeant for bullets
* Would include a thank you / end page, with their contact info
* Their images are most certainly not going to be treated as they are on our mozfest site. Can you include some standard logos, icons, and regular photos? We might want to figure out how a presenter would treat standard elements. Think your most basic, non-designer client.

@HPaulJohnson is it worth compiling a little list of resources to pull from, like the Noun Project, our flickr pool, for folks to draw assets from?

**Comment by kristinashu** [comment]
@cassiemc here's the updated template: https://docs.google.com/a/mozilla.com/presentation/d/1JyLTCgLypUHYnbBpg7NVaKTYlswB4HCaOqKLdye5JBw/edit?usp=sharing

I'm using templates and all the slides you see are examples of the template pages. 
- The placeholder text doesn't show up in the thumbnail view, you have to click on the slide to see the content. 
- The template has bullet formatting (copied from Mozilla's master blue deck) - if you type in a bullet you can see the styling (you could also view the master template).
- Added a page with some MozFest logo and icons people can pull from (regular page not a template).
- Added a title page with the name of the talk, name of the presenter, and their position / organization and then a thank you page with contact info.
- Replaced the placeholder images in the slides with a regular image -  this image is just a placeholder to give presenters a sense of layout and they can add whatever image suits their content.

When someone is adding their slides they should use one of these template layouts (this way it'll be easy to update styling if we need to).
<img width="1372" alt="screen shot 2015-10-30 at 1 56 07 pm" src="https://cloud.githubusercontent.com/assets/1068783/10857869/03fe2eb0-7f0e-11e5-98c3-d619e5e73634.png">

**Comment by kristinashu** [comment]
@lovegushwa would you be able to take a look and let me know if this is good to go?

**Comment by cassiemc** [comment]
@kristinashu This looks great, thanks. @HPaulJohnson does this work for you? Are you okay with just the blue version or do you want to give people the choice between this and say, pink?

**Comment by cassiemc** [comment]
Also, @HPaulJohnson Do you think these files will need some help with final cleanup, once speakers have added their content? If so, we might need to clear out some time Thursday evening or Friday for a couple designers to do that. Not sure when the actual presentations are taking place. cc @edrushka

**Comment by HPaulJohnson** [comment]
@kristinashu @cassiemc - these are perfect. let's just go with the blue to keep it simple. 

I would definitely love some time to cleanup the final slides, probably Friday. There aren't going to be tons of slides but they will definitely need some designer love.

**Comment by HPaulJohnson** [comment]
I dropped in the title slides for all the speakers and lightening talks. 

A few of these didn't fit the exact format so I had to tweak and they could use a design review. See slides: 8, 10-13, 17 in the attached doc: https://docs.google.com/a/mozilla.com/presentation/d/1JCSN_9DRhTKe3PiK6y6uxLD-Md_0lsLCNhDzyjkpfCs/edit?usp=sharing
