### ISSUE TITLE
Bug: Team Festival Page Layout on Safari

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/2015.mozillafestival.org#287]
When loading the /team page in Safari, the text is overlapping the images.

<img width="960" alt="screen shot 2015-10-23 at 16 24 55" src="https://cloud.githubusercontent.com/assets/14007066/10697219/bdf48696-79a2-11e5-999b-b8af7328c032.png">

**Comment by cassiemc** [comment]
I can confirm this is happening on my version too – Safari Version 9.0.1 for mac.

**Comment by hannahkane** [comment]
Not sure @mmmavis will have time for this. @Pomax - is this something you could look at?

**Comment by Pomax** [comment]
unfortunately, not today (working on windows machines the entire day), but I can look at it over the weekend if needed?

**Comment by hannahkane** [comment]
This one's pretty bad, so would be great if someone could look at it. 

@cassiemc - maybe you or you and me together should triage the QA tickets that have been filed, and identify the ones that are "mustfix"?

**Comment by mmmavis** [comment]
I just merged a workaround to fix the problem on Safari. Will be live soon.

**Comment by cassiemc** [comment]
@hannahkane I'll have a look at the list and help triage as soon as I get through the rest of my github mail!

**Comment by cassiemc** [comment]
@hannahkane Just had a look and I think P1 / P2 labels are working pretty well. The unlabeled ones are usually nice-to-haves.
