### ISSUE TITLE
Fix copy on /team

### ISSUE THREAD

**Issue by thornet** [mozilla/2015.mozillafestival.org#288]
https://2015.mozillafestival.org/team

Small fix: it's not Mozfest's seventh year, but sixth. 

Should be: 
"Michelle curates Mozfest and is proud to see the festival into its sixth year."

**Comment by cassiemc** [comment]
@mmmavis This looks done but may need to be merged as I'm not seeing it updated on the live page. Can we close?

**Comment by cassiemc** [comment]
This is still not reflected on the live site.

**Comment by mmmavis** [comment]
@cassiemc merging into `develop` triggers staging site deployment and merging into `master` triggers production site update.

I'll update the `master` branch now.

**Comment by cassiemc** [comment]
woot, thanks @mmmavis! :+1:

**Comment by mmmavis** [comment]
live on https://2015.mozillafestival.org/team :tada:

**Comment by ioana-chiorean** [comment]
Yay! Thanks for the merge! :tada:
@thornet's description is now clean :dancer:

**Comment by cassiemc** [comment]
yay, thanks for your help @ioana-chiorean! :confetti_ball:
