### ISSUE TITLE
Add link to schedule app 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#289]
Put "Schedule" in the top nav (in the spot currently occupied by "Sessions"), and move links to the Spaces and Pathways pages down to the footer.

**Comment by Saallen** [comment]
Hi @hannahkane - I would like to keep it as its a less busy page, and on the schedule the focus is sessions.

**Comment by hannahkane** [comment]
OK, it will make the name of the current /sessions page strange, since I think attendees would be expecting to see the schedule app there. What if we put "Schedule" in the top nav (will go to the full schedule app), and move links to the Spaces and Pathways pages down to the footer and/or link to them from the What to Expect page?

**Comment by cassiemc** [comment]
@hannahkane I like your suggestion. Do we need a design then for adding those links to "what to expect"?

**Comment by cassiemc** [comment]
@hannahkane is this still blocked?

**Comment by hannahkane** [comment]
Yes, will be blocked until we have the schedule app finalized. Re: design help—I'm thinking we can use existing styles to add links to those pages.

**Comment by cassiemc** [comment]
@hannahkane @mmmavis Shall we add this link tomorrow, or do you have a plan as to when?

**Comment by hannahkane** [comment]
@mmmavis and @Saallen are chatting about this in an email thread. will add you.

**Comment by hannahkane** [comment]
@mmmavis - can we do this one now?

**Comment by mmmavis** [comment]
done.
