### ISSUE TITLE
MozFest 2015 site: Call for Proposals form

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#29]
Create Call for Proposals form for this years website.
Format will follow previous years but we will not ask people to submit under Tracks or Themes but tags.
There will be a pre-determined set of tags which will speak to the narrative in development.
Below I will outline the possible first draft of tags accroding to Mark festival narrative so far

Lead @Saallen
Consulted @edrushka & @thornet

**Comment by Saallen** [comment]
First draft of possible tags- noting there are three rows of four on the current redpen draft so we will narrow the list to 12.
Q: is it possibel to restrict one tag per line or three tags per submission?
Q : Do we want the traditional themes still within ?

 - [ ] Make
 - [ ] Lead
 - [ ] Teach
 - [ ] Invent
 - [ ] Community
 - [ ] Activation 
 - [ ] Empowerment
 - [ ] Curriculum
 - [ ] Clubs
 - [ ] Craft
 - [ ] Media
 - [ ] Index
 - [ ] Place
 - [ ] Sciences
 - [ ] Data
 - [ ] Policy
 - [ ]Advocay
 - [ ] Communications
 - [ ] Teach
 - [ ] Invent
 - [ ] Play
 - [ ] Community
 - [ ] Science
 - [ ] Data

**Comment by edrushka** [comment]
This strikes me as a lot to make people choose from. Could we limit the tags to three pools?
- Themes
- Format (hands on hack session, fireside chat, group conversation, traditional lecture etc.)
- Skill level (kid friendly, beginning, intermediate code knowledge recommended, advanced etc.)

**Comment by Saallen** [comment]
so these are the first draft- our tags will be our filter. The idea with this list is that we remove half of the potential tags above. Format and skill level we always change post submission.

**Comment by Saallen** [comment]
Final list of Tags- request input on the row three around artisan tag versus other suggestions ??
**Row one**
* Make
* Lead
* Teach
* Invent
* Play
 
**Row two**
* Learning
* Craft
* Citizenship
* Science
* Journalism
* Arts
 
**Row Three**
* Youth
* Artisans [tech, maker, coder, developer?] 
*  Activists
* Educators
* Localizers
