### ISSUE TITLE
Create a rockin' MozFest playlist

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#291]
@OpenMatt - could you put together a cool playlist to be used when the mainstage isn't active? Minimal electric violin ;) 
I believe we're showing photos of our international communities, so maybe the music could represent some of that?

cc @HPaulJohnson @KevZawacki

**Comment by OpenMatt** [comment]
@edrushka hmmm I'll try to think of some stuff...
