### ISSUE TITLE
New  Flickr account for MozFest

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#292]
Hey @edrushka  new Flickr account for uploading all Paul Clarkes photos
 Account name : Mozillafestival
Password - shared on another platform
I will transfer over 2013 and 2014 photos into this account so we have one space where we know we pull official festival photos

**Comment by SpikeUK** [comment]
We will also be encouraging Festival Volunteers to take pictures of Volunteers at work (rest & play). I would like them to upload those to Flickr as well. Can we agree a common tag, or set of tags to ensure we can find these in the future.
Could I suggest the obvious "MozFest" and "MozFest15" the optional "Volunteers"?
Thank you.

**Comment by cassiemc** [comment]
@Saallen Assuming this will take some time once the account is set up. Is this a P1 (must have) or a P2 (nice-to-have)?
