### ISSUE TITLE
Order supplies to Ravensbourne

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#293]
Ordering to:
Marc Walsh / MozFest
Ravensbourne
6 Penrose Way
London
SE10 0EW
UK

- [x]   6  utility knifes (the kind with snap off blades)
http://www.amazon.co.uk/Draper-DIY-08694-Retractable-Knife/dp/B00BO89RI8/ref=sr_1_22?ie=UTF8&
qid=1446070192&sr=8-22&keywords=utility+knife

- [x]    2 painters tape 
http://www.amazon.co.uk/ScotchBlue-Painters-Original-Multi-Surface-2090-48A/dp/B00004Z4DU/ref=sr_1_6?s=officeproduct&ie=UTF8&qid=1446072883&sr=1-6&keywords=painters+tape

- [x]    2 hot pink masking tape
http://www.amazon.co.uk/Washi-Masking-Tape-deco-tape/dp/B00DFXAW1G/ref=sr_1_2?s=officeproduct&ie=UTF8&qid=1446073237&sr=1-2&keywords=pink+masking+tape

- [x]    1 pack of 10 ...  Foam board 5mm A0
http://www.amazon.co.uk/Foamboard-White-A0-5mm-Packed/dp/B004UYH6CM/ref=pd_sim_229_1?ie=UTF8&refRID=0Z3DV1CYEX9SQ3QNG1G8&dpID=31WiMI-LEdL&dpSrc=sims&preST=_AC_UL160_SR133%2C160_

- [x]    3   3m spray adhesive
http://www.amazon.co.uk/3M-Spraymount-200-Adhesive-Spray/dp/B000J68HBO/ref=pd_cp_229_2?ie=UTF8&refRID=0JNPPWWXD39XVYFAHQW0&dpID=41voasoTybL&dpSrc=sims&preST=_AC_UL70_SR70%2C70_

- [x]    3   3m double sided foam tape, 3meter length
http://www.amazon.co.uk/3M-Double-Sided-Acrylic-Mounting/dp/B00CO89CE6/ref=sr_1_1?ie=UTF8&qid=1446070274&sr=8-1&keywords=3m+tape

- [x]    1   nylon string (hot pink, baby blue, or white.)
- [x]    15  broad tip black markers (for posters and session labels)
Similar to:
http://www.amazon.co.uk/uni-ball-Posca-Broad-Chisel-Marker/dp/B000N6MGV2/ref=sr_1_sc_2?s=officeproduct&ie=UTF8&qid=1446072998&sr=1-2-spell&keywords=broad+tip+markes

- [ ]     3  aluminum rulers (2@~.5m 1@1m) ... (does the school have these?)
- [x]     2  measuring tape
- [x]     xacto knife cutting boards (does the school have cutting surfaces?)

- [ ]     Black or hot pink Vinyl ... working on specifications

**Comment by lovegushwa** [comment]
- Foam board (we need to decide quantity )
- 3m super 77 (glue, this is the best option if available in the UK)
- 3m double sided foam tape
- nylon string
- 100 sheets neon orange paper 180 - 250gsm cardstock, A4
- 25 broad tip black markers (for posters and session labels)

...

**Comment by cassiemc** [comment]
@lovegushwa added the above to the master list, with some questions for you.

**Comment by marcwalsh** [comment]
@cassiemc - Hey, we have a space in Ravensbourne's prototyping labs to use for this. So I would recommend that you have the supplies delivered there instead - Have a chat with @lauralillepruun she will be able to place the order for you!

Address:

Marc Walsh / MozFest
Ravensbourne
6 Penrose Way
London
SE10 0EW
UK

**Comment by cassiemc** [comment]
Woot, thanks @marcwalsh and @lauralillepruun

**Comment by cassiemc** [comment]
@lovegushwa I don't think we need neon paper any more, correct? Please edit the first comment as needed. Let's get this list finalized soon so @lauralillepruun can hopefully help us order.

**Comment by lauralillepruun** [comment]
@cassiemc yes let me know what you need and I'll get on it :)

**Comment by lovegushwa** [comment]
@lauralillepruun @marcwalsh @cassiemc I think we are good to go.
Beth is checking on what kind of Vinyl we can use on the Zund machine.

**Comment by cassiemc** [comment]
@lovegushwa list looks great to me.

**Comment by lauralillepruun** [comment]
@lovegushwa Is this what you need me to order? 
- Foam board (we need to decide quantity ) - 3m super 77 (glue, this is the best option if available in the UK) - 3m double sided foam tape - nylon string - 100 sheets neon orange paper 180 - 250gsm cardstock, A4 - 25 broad tip black markers (for posters and session labels)

**Comment by cassiemc** [comment]
@lauralillepruun The complete list is in the first comment (@lovegushwa and I have been editing it there as a master list). There are a couple outstanding questions you could perhaps help with re. what's available in the Ravensbourne space.

* 3 aluminum rulers (2@~.5m 1@1m) ... (does the school have these?)
* xacto knife cutting boards (does the school have cutting surfaces?)

**Comment by lauralillepruun** [comment]
@cassiemc I'm checking about the rulers and cutting surfaces now and then get on with ordering :)

**Comment by lauralillepruun** [comment]
@cassiemc  I can only find rulers of 1m and 1.2m. will those do?

**Comment by lauralillepruun** [comment]
@cassiemc how many cutting boards do you need and have you decided about the vinyl?

**Comment by lovegushwa** [comment]
@lauralillepruun @marcwalsh 
Sorry I forgot these, I just realized a need 2 squeegee's and 2 spray bottle for vinyl instillation on Wednesday:
http://www.amazon.co.uk/Carbon-Wrapping-Squeegee-Di-Noc-Oracal/dp/B007VTPD14/ref=sr_1_2?ie=UTF8&qid=1446481790&sr=8-2&keywords=3m+vinyl+squeegee

http://www.amazon.co.uk/SIBEL-Ball-water-spray-bottle/dp/B003WJH7HA/ref=sr_1_8?ie=UTF8&qid=1446481875&sr=8-8&keywords=spray+bottle

**Comment by lauralillepruun** [comment]
@lovegushwa Done!

**Comment by lovegushwa** [comment]
Yay, thank you Laura!

**Comment by cassiemc** [comment]
Assuming most things have been ordered by now, so closing. Thanks for all your help @lauralillepruun, see you in London shortly!
