### ISSUE TITLE
Design polish for Mozfest site

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#294]
At first blush some of the design could be cleaned up on the Mozfest site.

- [ ] improved bio pictures on the spaces and pathways descriptions
- [ ] improved bio pictures on the team page
- [ ] some better typography
- [ ] possible animations

Focus should be on streamlining the UX and navigability of the who, what, where logistics (session names / times / descriptions), as that's where we predict users might have the most trouble. 

I need help identifying issues, @vazquez @flukeout @kristinashu @sabrinang @xmatthewx Do you guys have a sec to review and highlight anything that stands out on https://2015.mozillafestival.org/ ?

**Comment by vazquez** [comment]
I'll do it today.

**Comment by vazquez** [comment]
Some ideas in addition to @cassiemc's:

- [ ] On Thursday, move the "Weekend Outline" section above the note from Mark.
- [ ] On Thursday, add a link on the home page right below the sub-headline that takes visitors straight to the Weekend Outline.
- [ ] Maybe add an "Outline" link to the navigation links.

**Comment by xmatthewx** [comment]
Added a few issues to:
 - improve the UX for people getting directions (#295, #296)
 - finding pathways (#297)
 - fix layout bug on mobile (#298)
 - and improve header and menu (#299)

**Comment by ioana-chiorean** [comment]
Overlapping Sessions & Play buttons ( #304 ) 
Text wrapping & alignment ( #306 )
Map - get directions (#307 )

**Comment by natalieworth** [comment]
The sessions page is still displaying the old Youth Zone icon: https://2015.mozillafestival.org/sessions (not sure if there is already a ticket for this though?)

**Comment by cassiemc** [comment]
All the issues flagged here have been filed as separate issues. Going to close this as I don't think we'll actually have time to address any of the polish pieces.
