### ISSUE TITLE
Add link to map for directions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#295]
I love the map under Location. And... many users will want to get directions via their map app rather than read our description. Currently, they will need to copy the address from the little map pop-up and then paste it into their map app. 

I recommend we add a button to open a link to google maps in the "How to get there" section. Maybe in the map pop-up as well. If there's a way to do this for both ios and android, even better.

**Comment by ioana-chiorean** [comment]
My proposal from #307 - slightly different ( no button and default maps app not only gmaps)
"When people tap the map or the point on it they most of times expect to open it in a different app ( Google Maps, Here maps, OSM etc ) or new tab with again some directions ( on google maps etc)"

**Comment by cassiemc** [comment]
@ioana-chiorean if we can open the address in the default map, fabulous. And, if we don't have to add a button, just tap the map, that works even better. I think that's a fine plan and is ready for dev work. I'll close #307 since we're going with that plan here.

**Comment by hannahkane** [comment]
I'm calling this a P1 because it seems like expected functionality. Is anyone available to help with this?
