### ISSUE TITLE
Location map makes it difficult to scroll

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#296]
The map on the Location page is beautiful. And... the pan and zoom make it difficult to scroll the page.  

One possible fix: lock pan and pinch to zoom. Users can still use the +/- icons to browse the map a little. Most users will just want the address and button to open their own map for directions (#295).

**Comment by cassiemc** [comment]
I'm good with this solution, @xmatthewx. Read for implementation.

**Comment by cassiemc** [comment]
To clarify via #309, we should lock the map to pinch and zoom on both mobile and desktop.

**Comment by ioana-chiorean** [comment]
This PR might fix it but needs a review as I am new to this. cc @mmmavis 
https://github.com/ioana-chiorean/2015.mozillafestival.org/pull/2

**Comment by hannahkane** [comment]
@mmmavis - can you please review the PR when you have a chance?
