### ISSUE TITLE
Nav to Pathways

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#297]
Right now, it appears that the only way to access the Pathways page is via the text link at the top Schedule page. Might nice to put a button below the text about Spaces.  Once I'm on the Pathways page, might be nice to have a button back to Spaces.

**Comment by cassiemc** [comment]
We could have a look at the copy on these pages, but wondering if the addition of the schedule app will render this one moot. cc @hannahkane

**Comment by hannahkane** [comment]
I would say so, @cassiemc. Will be adding prominent links to both pages from the What to Expect page, and "Sessions" becomes the link to the full Schedule.

**Comment by cassiemc** [comment]
Ok, let's ```won't-fix``` this then. Thanks @hannahkane!
