### ISSUE TITLE
Fix responsive widths for mobile

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#298]
I see a couple of problems with rendering in Chrome on Android 5. 

# 1. 
On all or most pages, I can scroll horizontally. This reveals an odd bar on the right side. 

![screenshot_2015-10-26-12-24-29](https://cloud.githubusercontent.com/assets/53411/10735483/94fb7b08-7bde-11e5-945c-12103c1cac65.png)

# 2. 

The ticket buttons on too wide for the view.

![screenshot_2015-10-26-12-28-34](https://cloud.githubusercontent.com/assets/53411/10735482/94fb679e-7bde-11e5-8a54-b6ce98331eaa.png)

**Comment by ioana-chiorean** [comment]
<img src="https://cloud.githubusercontent.com/assets/1391451/10740478/27b31b4e-7c2b-11e5-9858-49b7f532a928.jpg " height="600" width="300" >

This also reproduces on Firefox for Android.

**Comment by cassiemc** [comment]
@ioana-chiorean I updated the issue title, thanks!
@mmmavis is this easy for a contributor to help with? If so could you add the ```needs-help``` label for someone to pick up?

**Comment by ioana-chiorean** [comment]
Investigating it further more, on Firefox on Firefox OS it is slightly worse:

<img src="https://cloud.githubusercontent.com/assets/1391451/10744489/f7216f7c-7c42-11e5-8c84-e882e76806dd.jpg" width="300" height="550" / >

**Comment by ioana-chiorean** [comment]
Similar but not reproducing on other plaforms - #310
