### ISSUE TITLE
Balance header on mobile 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/2015.mozillafestival.org#299]
Site looks and works great on mobile. The header and menu could use a little improvement. The margin between the Mozilla tab and Mozfest logo seems large. The margin below the menu seems small. The menu items feel a bit shy. 

![screenshot_2015-10-26-12-43-22](https://cloud.githubusercontent.com/assets/53411/10735760/fea23faa-7bdf-11e5-91a9-7899bc1a2cb1.png)

Here's a quick mock up of how it could be iterated, making the menu items buttons on touch screens. 

<img width="861" alt="screenshot 2015-10-26 13 01 12" src="https://cloud.githubusercontent.com/assets/53411/10736148/d447d3f8-7be1-11e5-8737-84c92ad704cf.png">

**Comment by cassiemc** [comment]
This could definitely use some improvements. I can have a look at the UI tomorrow.

**Comment by cassiemc** [comment]
I doubt we will get to this prior to mozfest but will leave it open if anyone else can help.
