### ISSUE TITLE
MozFest 2015 : Footer links

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#30]
Working from the [Red Pen] (https://redpen.io/xpb06352b8b252e96c) this issue decide the final pages linked out from the Footer. 
Lead @Saallen
Consulted @edrushka & @thornet 

Top CTA on the main page is 
* Call for Proposals 
* Tickets
* Location

**Comment by Saallen** [comment]
Footer links should be- and in order of preference -
* About
* What to expect
* Participation Guidelines
* Fringe Events

**Comment by Saallen** [comment]
Three big Footer links as per cassies design
* Contact 
* #MozFest
*  Remote Participation

With contact containing press contact info
#Mozfest contains social media ( or maybe just twitter)
Remote participation could be a page that is not live until a month from the festival but on the day could contain, discourse chat, lesson plans and Air mozilla link to live sessions..

Feedback most welcome :smile:

**Comment by edrushka** [comment]
Works for me. As per our discussion, we'll change the phrasing on the buttons to: 
- Contact (or Contact Us)
- Connect on Twitter
- Participate Remotely

**Comment by Saallen** [comment]
I just looked over the wireframe conversations from before and Volunteer sign up is not accounted for.
Is it too late to add or should it be a page we link out?

**Comment by edrushka** [comment]
I think we should make it one of the big blue buttons. We can move Connect on Twitter to the text list in the footer (since there's not a ton of Twitter activity this early).
