### ISSUE TITLE
Graphics for Ravensbourne TV

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#300]
@marcwalsh hope I'm not creating a duplicate ticket.

We can share the mainstage slide template for the Ravensbourne TVs if you give us the size/format you need it in.

Thanks!

**Comment by marcwalsh** [comment]
@edrushka they need to be 1920x1080 JPEG format. Probably best to have it at 72dpi, as they need to be as small of a file size as possible.

**Comment by cassiemc** [comment]
@edrushka Who's doing the mainstage slide template, is that in another bug?

**Comment by edrushka** [comment]
Thanks Mark. Mainstage template is in #286

**Comment by lovegushwa** [comment]
@edrushka @marcwalsh just to clarify these are the screens around the building and not next to the stage.

**Comment by edrushka** [comment]
Yes, that's right @lovegushwa

**Comment by marcwalsh** [comment]
@lovegushwa Yep that's right, I think they are run off Raspberry Pis now compared to Mac Minis last year. It might be worth setting up a meeting with them to discuss expectations of what your planning. The software is more simplistic than before.

**Comment by cassiemc** [comment]
@edrushka @marcwalsh @HPaulJohnson Can anyone clarify what type of content we can have on these screens? I think somewhere along the line someone mentioned live updates w/ session names and locations, or content that was more based in location/way-finding. A lower maintenance option is to just have a simple slideshow that riffs off the mainstage graphics.

**Comment by Saallen** [comment]
Hey - these mininet screens in previous years have been used for
* Wiki access info
* Scedule access details
* lunch info
* water locations
* Coffee
* main stage air moz

**Comment by marcwalsh** [comment]
I've seen these designs (https://redpen.io/qy71f00b290e5dcbf0) on #290 - Are we able to use this as a template for the info mentioned before. @edrushka @lovegushwa
