### ISSUE TITLE
Print more Mozfest posters (beyond the festival guide)

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#301]
All the posters so far are printed on the back of the guides which are going in the totes (meaning in a perfect world every person gets one).

I think we should consider printing 30-50 extra ones (more than this @lovegushwa?) to post around the venue to add to the festive feel. 

Unless @marcwalsh @Saallen you don't think that's necessary, if we are getting a LOT of extra festival guides?
 
We might need to adjust the print file a bit for printing on our own at Ravensbourne. @marcwalsh do you know the max size we can print at Ravensbourne, and whether they can accommodate bleed? Can someone help do this next week?

**Comment by marcwalsh** [comment]
I'm going to be onsite on the Wednesday morning at Ravensbourne to print these for you. We can print up to 42" wide, which can accomadates up to [A0+] (http://www.wrongdesign.com/images/Sizecharts.pdf) and then to the length of what ever is on the roll. It's worth having the bleed, to ensure that we have some trimming room.

**Comment by cassiemc** [comment]
I have leaned toward a size between A2 and A3 to keep the posters human-sized and not too intimidating to write on. @marcwalsh – here's a file that is 42 inches wide that can be used for printing 2-up. Crop marks are the black lines.

EPS: https://www.dropbox.com/s/c9oxmv1m5g69ovs/A3ish%20posters.eps?dl=0
PDF: https://www.dropbox.com/s/7mrmcre2hno9f1a/A3ish%20posters.pdf?dl=0

Let me know if you need anything else!
