### ISSUE TITLE
Create a 'photo consent' poster

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#302]
We will need to hang a poster someone in the lobby of the venue that outlines our photo consent policy. This content is being finalized in #271

@marcwalsh @Saallen Can you comment on any additional needs for this poster? What are the size requirements and where do you imagine visitors will first see this (ie will it be on a wall, or as a sandwich board on the registration tables? Will we need more than one copy?)

**Comment by cassiemc** [comment]
@HPaulJohnson to help confirm the content today/early tomorrow.

**Comment by Saallen** [comment]
@cassiemc posters from last year - https://docs.google.com/document/d/1F2xkjrGCHCffS9y2f1vddzJnBMQLEghzZL1yKlJsGME/edit
It is too time consuming to ask everyone to sign a consent form so it would be good to have something that says how avoid being photographed..

**Comment by cassiemc** [comment]
@Saallen thanks a bunch! I had to request access but am sure this will be very helpful. @sabrinang are you down for taking a stab at this?

**Comment by Saallen** [comment]
@cassiemc  if you refresh you should be able to access

**Comment by cassiemc** [comment]
Fab thanks @Saallen! @HPaulJohnson can you review that doc for final copy?

**Comment by HPaulJohnson** [comment]
@cassiemc @Saallen reviewed the copy and suggested edits in the comments.

**Comment by cassiemc** [comment]
@HPaulJohnson fab, thank you! I cleaned up and finalized the copy here with some art direction.

@Saallen or @marcwalsh do you guys have a pic of the yellow lanyard that will be used? How big do we want this sign to be? I'm assuming we'll print this on-site at Ravensbourne and probably mount it ourselves on foamcore.

Assigning to @sabrinang, please work with @natalieworth to streamline fonts/colors/style for this. Shouldn't take more than an hour or two to design, possibly illustrate, and typeset. Thanks!

**Comment by Saallen** [comment]
Its a plain yellow lanyard but i dont have a picture. It should be A1 to go behind the regstratio desks on the ground level

**Comment by natalieworth** [comment]
Hey @sabrinang , I'll post the 2015 MozFest style guide for this here: https://drive.google.com/open?id=0B20-0lpP23c0czdPaGlfdFV4Unc

**Comment by cassiemc** [comment]
@Saallen bright yellow? neon yellow? pale yellow? cadmium medium yellow? ;) we might just go with black and white to be safe!

**Comment by Saallen** [comment]
Yes this is a  serious announcement :)

**Comment by cassiemc** [comment]
@sabrinang please let us know you're on-board to do this. Thanks!

**Comment by sabrinang** [comment]
@cassiemc thanks for flagging - I'll work on this today!

**Comment by natalieworth** [comment]
@sabrinang https://drive.google.com/open?id=0B20-0lpP23c0d0RWaW42T242SW8

**Comment by sabrinang** [comment]
progress on redpen: https://redpen.io/p/mw9711f42a39d82a6c
@cassiemc Do we want a title for the poster? (I put Photo & Video Consent on the mockup) Let me know if this poster is heading in the right direction

**Comment by cassiemc** [comment]
@sabrinang definitely on the right track, love the illustration, thank you! Left a few comments in redpen.

**Comment by sabrinang** [comment]
@cassiemc - redpen updates: https://redpen.io/p/mw9711f42a39d82a6c
- mozfest name tag illustration
- blue stipe bg
- changed air.mo icon and moved section

@Saallen Does the title "Photo & Video Consent" work for the title of the poster?

**Comment by cassiemc** [comment]
Sweet @sabrinang, almost there,  thank you! Left a few comments on redpen to consider.

**Comment by sabrinang** [comment]
@cassiemc - updated redpen: https://redpen.io/no2cdc4162247f3987
- balanced out spacing
- rearranged text order

**Comment by sabrinang** [comment]
@cassiemc R?
https://redpen.io/no2cdc4162247f3987

**Comment by sabrinang** [comment]
@lovegushwa Can you give me a design review? https://redpen.io/no2cdc4162247f3987 R?

**Comment by sabrinang** [comment]
Thanks @natalieworth for redpen feedback :)

I exported: 
- various file extensions .ai, .pdf *(1 with bleed & trim marks and 1 without)* & .png here: https://drive.google.com/folderview?id=0B4Q8pzCpDS_eeEVHZmZ4ZjJtYWc&usp=sharing
- A1 dimensions 594mm x 841mm or 23.39" x 33.11" *(with 0.125" bleed)*

@marcwalsh @Saallen Let me know if there is anything else you need for it to be printed.

**Comment by lovegushwa** [comment]
@sabrinang I left a few comments about how to tie the color a little closer to the other print assets. Other than that R+

**Comment by cassiemc** [comment]
This is great @sabrinang thank you! 
@marcwalsh Note Sabrina's comment above with the final print files.

**Comment by cassiemc** [comment]
@marcwalsh Let us know if we're good to close!
