### ISSUE TITLE
Design QA for schedule app

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#303]
@mmmavis will let us know when she's ready for this.

Currently she's building it at http://mmmavis.github.io/mozfest-schedule-app/
eventually the url will be: schedule.mozillafoundation.org

**Comment by ioana-chiorean** [comment]
I can volunteer to do some QA on it. Feel free to ping e when is done @mmmavis

**Comment by cassiemc** [comment]
Thanks @ioana-chiorean! I'll be fleshing out QA bugs and labeling them with needs-help, might be another hour or so before I get to it, but feel free to pick any of those up as you see them in the future!

**Comment by cassiemc** [comment]
@xmatthewx Can you help us figure out what major platforms we should be testing the schedule app on? Feel free to cross any of these out or add more.

### Mobile
- [ ] iOS (6+?)
- [ ] Android (Nexus 5+?)
- [ ] FF OS??

### Desktop
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] ie10
- [ ] ie11

**Comment by xmatthewx** [comment]
We've used the list below in the past, supporting the latest version and one before it on desktop. I don't think you need to worry about the stock Android browser for Mozfest. Also, IE is probably a very small segment of our audience (4% on Webmaker site).

- [ ] Desktop
    - [ ] Chrome (latest - 1)
    - [ ] Firefox (latest - 1)
    - [ ] Safari (latest - 1)
    - [ ] IE (latest - 1) 
- [ ] Android
    - [ ] Chrome (latest)
    - [ ] Firefox (latest)
    - [ ] ~~Android browser (4.4+)~~
- [ ] iOS
    - [ ] Chrome (latest)
    - [ ] Safari (latest)

**Comment by cassiemc** [comment]
Thanks @xmatthewx let's go with that list.

**Comment by cassiemc** [comment]
Also, let's file any issues here: https://github.com/mozilla/mozfest-schedule-app/issues

**Comment by ioana-chiorean** [comment]
@cassiemc is if available yet?

**Comment by cassiemc** [comment]
App is ready for QA here: http://mozilla.github.io/mozfest-schedule-app/
File any issues here: https://github.com/mozilla/mozfest-schedule-app/issues

**Comment by cassiemc** [comment]
Lots of QA issues filed in the schedule app repo. Closing.
