### ISSUE TITLE
Session and Play button overlap on mobile

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#304]
On  Firefox for Android at least the buttons overlap making it a bit difficult to use.

<img src="https://cloud.githubusercontent.com/assets/1391451/10740666/16d16b72-7c2c-11e5-9e2e-5ef6d803e905.jpg" width="300" height="550" / >

<img src="https://cloud.githubusercontent.com/assets/1391451/10740794/d9670d68-7c2c-11e5-8ce1-16f49d3672d6.jpg" width="300" height="550" / >

**Comment by cassiemc** [comment]
This might depend a bit on the redesign of the header links in #299

**Comment by ioana-chiorean** [comment]
Investigating it further more, on Firefox on Firefox OS is displayed perfect: 
@xmatthewx or someone else - can you confirm how it is on chrome ?

<img src="https://cloud.githubusercontent.com/assets/1391451/10744533/4886d30c-7c43-11e5-8181-b66cbb6e8a61.jpg" width="300" height="550" / >
