### ISSUE TITLE
Bug: No content displayed on Fringe page whilst using Safari 

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/2015.mozillafestival.org#305]
Strange things are happening on safari... @mmmavis @hannahkane 

<img width="1016" alt="screen shot 2015-10-26 at 19 58 34" src="https://cloud.githubusercontent.com/assets/14007066/10740835/5d767fd2-7c1c-11e5-9874-7417042e2cc8.png">

**Comment by Pomax** [comment]
Are there any errors in the dev tools console? (preferences -> advances -> "Show Develop menu in menu bar" option, then in the tool bar: develop -> show error console)

**Comment by mmmavis** [comment]
<img width="894" alt="screen shot 2015-10-28 at 12 47 56 am" src="https://cloud.githubusercontent.com/assets/2896608/10782438/9487aacc-7d0d-11e5-893d-5d02fc956d0c.png">

I think we probably need to explicitly call `require('whatwg-fetch');` in `fringe-events.jsx` to fix this issue.  I'll submit a patch.

Thanks for reporting @marcwalsh :smile:
