### ISSUE TITLE
Text - wrapping and positioning

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#306]
In some places the text wrapping is not the best:

1) Centered alignment makes it hard to read 
<img src="https://cloud.githubusercontent.com/assets/1391451/10740853/374add6a-7c2d-11e5-97ff-7d657338fc0a.jpg" width=''300" height="550" / >

2) Here we might want a compact/squared one not left aligned. 
<img src="https://cloud.githubusercontent.com/assets/1391451/10740863/3f470962-7c2d-11e5-93f3-5f5912e616be.jpg" width=''300" height="550" / >

**Comment by cassiemc** [comment]
1) Agree, we need to decrease the line spacing on points that wrap to two lines
2) We could centre the text, but I wouldn't justify it, that would make more rivers in the text. My instinct is to centre the text to match the other mobile styles.

@ioana-chiorean could use your help identifying additional pages where this is happening. Or if it's just this one page could you post a link?

**Comment by ioana-chiorean** [comment]
some more: 
<img src="https://cloud.githubusercontent.com/assets/1391451/10796548/51602bd0-7da7-11e5-8445-ade570f78a80.jpg" width=''300" height="550" / >

<img src="https://cloud.githubusercontent.com/assets/1391451/10796555/57ea56ce-7da7-11e5-9883-f831e424f46c.jpg" width=''300" height="550" / >

**Comment by ioana-chiorean** [comment]
So I have parsed all pages and saw the followings: 

* Location - starts centered aligned, continues with left alignament
* What to expect - left 
* Sessions - centered
* Volunteer with us - centered
* Fridge - left
* About - centered
* Team - left
* Guidelines - centered, left, centered
* Submission - centered

**Comment by hannahkane** [comment]
@cassiemc - would you prefer this were P1 or P2?
