### ISSUE TITLE
Map - on desktop - zooming to easy

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#309]
Going to https://2015.mozillafestival.org/location and panning up/down will zoom in and out on the map. This should be blocked. 

Firefox for Android
OS X 10.10.5

**Comment by cassiemc** [comment]
@ioana-chiorean is this a duplicate of https://github.com/mozilla/2015.mozillafestival.org/issues/296 or is this another different issue?

**Comment by ioana-chiorean** [comment]
@cassiemc  - it might - but i though #296 is on mobile only ( i think there is no difference between desktop and mobile -> so yeah - might be the same)

**Comment by cassiemc** [comment]
I think #296 is a general solution but will add a note to clarify re. mobile vs. desktop. Thanks @ioana-chiorean!
