### ISSUE TITLE
MozFest 2015 : What to expect page content

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#31]
Outline as seen on [Red pen] (https://redpen.io/gn1052aeb36e026ed5)

Content required for the following titles -(titles are place holders for time being)
 - [ ] Mozilla Festival Mission Statement - Mark's welcome message
 - [ ] Participating at MozFest
 - [ ]  Weekend outline

Lead by @saallen
Consulted @edrushka & @thornet @KevZawacki

Will create subtickets for these website paragraphs

**Comment by KevZawacki** [comment]
Edits and fresh copy for these pages available here, on pages 3 and 4: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit
