### ISSUE TITLE
Firefox on Firefox OS - Bottom buttons are cut 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#310]
interesting enough on Firefox on Firefox OS the bottom buttons are cut (by default, no panning performed) : 

<img src="https://cloud.githubusercontent.com/assets/1391451/10744579/a169920c-7c43-11e5-8415-d54bbb037a80.jpg" width="300" height="550" / >

**Comment by hannahkane** [comment]
@Pomax - any chance you could help with this one?

**Comment by Pomax** [comment]
I don't have a new enough FFOS device, but if I can find one at the office I can try to see what's going on.

**Comment by ioana-chiorean** [comment]
@Pomax - just as FYI - I see this on a Flame ( not  the new device )

**Comment by mmmavis** [comment]
This is probably resolution related and not specific to OS.  I will take this on @Pomax
