### ISSUE TITLE
Update youth icon on sessions page

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#312]
https://2015.mozillafestival.org/sessions is displaying the old youth icon. It should be a cube with a smiley face.

**Comment by ioana-chiorean** [comment]
Do we have the file up? I can link it.

**Comment by cassiemc** [comment]
was just sourcing it now! uno momento

**Comment by cassiemc** [comment]
@ioana-chiorean Here it is: https://www.dropbox.com/s/putcaa5j09ho2qe/icon-youth.svg?dl=0

**Comment by ioana-chiorean** [comment]
Done in #314 but I have a feeling that he icon is not centered, We might need another form of it. Who can help with the design? 
cc @cassiemc @mmmavis @adiladiladil

**Comment by cassiemc** [comment]
Since this appears to be addressed in #314, I will close this issue here.
