### ISSUE TITLE
More icons needed for Schedulep app

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#313]
In the original mockup, the session "card" contains icons for **time, facilitator, space and pathways**.
<img width="676" alt="screen shot 2015-10-27 at 1 15 43 pm" src="https://cloud.githubusercontent.com/assets/2896608/10771220/dc6f4a86-7cac-11e5-8b0b-15afeb48e8c6.png">

We want to add another meta **"location"** to indicate the physical location where the session takes place. So I wonder if we should find another icon to substitute the "pin" icon we currently use for Space and use that "pin" icon for the newly added "location" meta instead?

/cc @cassiemc

**Comment by cassiemc** [comment]
@mmmavis can you add the location information after the space name? So "Mozilla Learning Network, 8th floor, Room 101"?

**Comment by ioana-chiorean** [comment]
I like @cassiemc proposal.
But if we will need another one, for space we might use an icon similar to map one ( https://www.google.com/search?q=map+icon)

**Comment by cassiemc** [comment]
I think it'd be good if the visitor starts to associate spaces with actual physical locations, so grouping 'em makes sense to me.

**Comment by hannahkane** [comment]
+1 to grouping them; that was the original idea

**Comment by mmmavis** [comment]
+1 let's go with this idea :tada:
