### ISSUE TITLE
Create gif for post-festival sharing

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#316]
Context: When MozFest ends on Sunday evening, and throughout Monday and Tuesday, there's typically been a lot of social media activity using the MozFest hashtag. We'd like to create a fun, branded piece of content for people to share.

Idea: There will be [hackable posters] (https://redpen.io/sg568f0ca9eb7c9348) on the walls throughout the venue. Let's get the photographer to capture a few of these, and combine them into an animated gif with a bit of branding at the end of the loop.

@flukeout - is this something you could help with?
@HPaulJohnson @KevZawacki

**Comment by HPaulJohnson** [comment]
cc: @secretrobotron

**Comment by cassiemc** [comment]
I like this idea very much! For context, though you can probably just ignore, @natalieworth's awesome social share graphics for pre-fest are in #226

**Comment by cassiemc** [comment]
Assigning to @flukeout please let us know if you're on-board!

**Comment by cassiemc** [comment]
**Note:** the real deadline for this can't be Nov6 as we won't have images by then. @edrushka is Sunday Nov 8 cool, or do you need it mid-fest?

**Comment by edrushka** [comment]
Ready to ship by Sunday evening when the Demo Party ends. Note that we can cheat a little, and fill in some posters ourselves if needed. I can also ask the photographer to deliver some photos on Saturday.

**Comment by flukeout** [comment]
I'll set up a template over the next couple of days so that we can test it out with some sample images.

**Comment by edrushka** [comment]
Awesome! Thanks Luke! @HPaulJohnson do you want to weigh in on how to brand this? I'm thinking it would be better to have this as 'Mozilla' rather than 'MozFest' to give it a longer life.

**Comment by HPaulJohnson** [comment]
I like the idea of having a longer life, but it's a question of what people will be more compelled to share. If the branding doesn't impact the answer to that, go with "Mozilla" but if "Mozfest" makes it more personal, topical, and compelling to share I think we should stick with that.

**Comment by cassiemc** [comment]
Why don't we make two versions? Switching out the logo shouldn't take long.

**Comment by flukeout** [comment]
Just a note here, that animated GIFs wont work when shared via Facebook, but Titter will be just fine.
Do we have any copy for the final screen, @HPaulJohnson @KevZawacki?

Something like...

```
[ Mozfest Logo ]
See you next year?
```

**Comment by flukeout** [comment]
I have a super-rough cut here - I mocked up 5 poster photos and am looping over them twice and ending on a little CTA page.

![gif-poster](https://cloud.githubusercontent.com/assets/25212/10897486/9e529252-8176-11e5-83fe-6295269e6e6f.gif)

This is only about a meg, and for Twitter we can go up to 3 MB so we can add a few more images probably as well as make nicer transitions.

@edrushka Is this kind of what yo had in mind?

**Comment by HPaulJohnson** [comment]
@edrushka and I just looked at this together. A few comments: 

We can remove the final slide with the CTA ("join us next year..."). This will be used in social media so will be surrounded by other copy in which we can include that type of CTA. I think it will be more likely shared without the marketing message included at the end of it. Can end with just #mozfest only. 

For the graphic, I think the original idea was to have the poster be static and just have the words change. The different backgrounds make it more visually interesting but harder to read in my opinion. Question is whether it's interesting enough without the background and just different words cycling through? Maybe we need better words.

**Comment by flukeout** [comment]
Thanks for the feedback everyone. I'll pick up work on this tomorrow and make it so that the posters will be centered and easier to read. I think a cool effect would be to slowly zoom in on the poster in each shot.

**Comment by cassiemc** [comment]
@flukeout You could also keep the backgrounds, but have them at the same zoom level so the poster is always the same size, that way only the text and the backgrounds are changing. I really like how the changing backgrounds emphasize different contexts, it might be cool to see how this would work with real life contexts around ravensbourne. 

Re. slow zoom, I think the feel we're going for is fast, energetic, diverse with lots of different people and ideas, so I'd add more words and posters rather than focus on fades or zooms between the images.

**Comment by edrushka** [comment]
I've noticed people are retweeting this: https://twitter.com/inpointsorg/status/663283855206588417 with their own remix. This is actually what we were hoping to achieve with this shareable piece. Maybe we don't need to create a gif and instead should just retweet this?

**Comment by edrushka** [comment]
Kevin, Luke and I discussed this. We'll retweet the picture instead. It's better as it's more remixable. Closing this. Thanks everyone!
