### ISSUE TITLE
MozFest 2015 site: Investigate using Sched to organize session proposals

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#32]
We are 99% sold on the sched app as the schedule app for the festival but this ticket is another version of #27 but investigating Sched to organise session proposals.
Last year we requested facilitators  to answer[ 13 questions ] (https://docs.google.com/a/mozillafoundation.org/forms/d/18s7lBIRoE4toeIhmm_7bStFqoWf2v-pEdPrbw4Bk31A/edit#) but this could be reduced to 10 valid questions.
Sched allows for similar fields to be imported to.

Linking in those I think would be interested in this conversation
@secretrobotron @ScottDowne @edrushka @thornet @ryanpitts @toolness

**Comment by Saallen** [comment]
From @ScottDowne 
Here is a list of fields for Sched session creation: https://scotttest2015.sched.org/editor/api#session-add
Some are required, oddly start and end time are required. We'll need to fill in something fake and change it later.
There is a spot for custom fields, so we can get whatever we want from the user.
I think the only required things in that list that are a human readable things are name and type. The rest is either integration concern, or custom values.

**Comment by Saallen** [comment]
@ScottDowne - Can I log in here with my normal sched creds?

**Comment by ScottDowne** [comment]
Oh, weird, the docs are locked under an account...

**Comment by ScottDowne** [comment]
Here is a better link: https://sched.org/api#session-add

**Comment by Saallen** [comment]
There I was actually counting the fields and you just created your own API........ :laughing:

**Comment by secretrobotron** [comment]
:+1: super cool. At the very least, we can just concatenate the questions from the form into the description field for the wrangler to digest and clean up.

**Comment by Saallen** [comment]
I have gone through the process of adding a session into the fields on Sched and I am trying to clean the data up now. Just a thought though while I do this....the sessions will be not seen on the website then?
Only when we confirm the sessions coming to the event.....then even it might not be until sept/oct. This could be an issue as folks like to see their submitted sessions

**Comment by ScottDowne** [comment]
@Saallen Yeah, initially the session is marked as unpublished, which is hidden to the public until we decide to turn it on.

Sched can also invite people to the session, which can happen any time, before or after we make it public, whatever works best for us.

**Comment by Saallen** [comment]
I spoke with Sched.com on email around our ask for the back end and the alignment of the upload. They are suggesting we submit to Google docs then upload once we know which sessions we want on the app.

**Comment by Saallen** [comment]
I am proposing a meeting this evening @9:30pm BST- will send an email now

**Comment by ScottDowne** [comment]
Interesting. Did they give a reason why?
