### ISSUE TITLE
Update 'Mozilla Learning Networks' Space copy on MozFest website

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/2015.mozillafestival.org#320]
Update the MLN Space copy on both the [MozFest website](https://2015.mozillafestival.org/sessions) and MozFest mobile app. 

New copy will replace all existing copy, and read:

Leaders demonstrate what the Web can do. The Mozilla Learning Network Space at MozFest will convene and catalyze leaders who equip others to advance their lives on the Web.  Our leadership Space and Pathways are part of a broad effort to cultivate a global network of web literacy leaders, people of all stripes and ages who are teaching others to read, write and participate on the Web while still actively learning themselves. 

cc @hannahkane @LindseyFrost @samueledyson

**Comment by cassiemc** [comment]
Just a note/FYI – that the old copy will still be in the Festival Guide since that's gone to print.

**Comment by hannahkane** [comment]
@mmmavis - to make sure this change is reflected on both the /sessions page and in the schedule app, should I also add this change to the spreadsheet?

**Comment by KevZawacki** [comment]
@cassiemc Good point. No problem. :-)

**Comment by ioana-chiorean** [comment]
@KevZawacki all descriptions have 2 paragraphs? Can I split it like:

Leaders demonstrate what the Web can do. The Mozilla Learning Network Space at MozFest will convene and catalyze leaders who equip others to advance their lives on the Web. 

Our leadership Space and Pathways are part of a broad effort to cultivate a global network of web literacy leaders, people of all stripes and ages who are teaching others to read, write and participate on the Web while still actively learning themselves. 

I can change it on the website.

**Comment by KevZawacki** [comment]
@ioana-chiorean Yes, that works for me. Thanks!

**Comment by ioana-chiorean** [comment]
Thanks for quick reply @KevZawacki . This was done in #322 .
Closing it up and will follow in there with more feedback if needed.
