### ISSUE TITLE
Reorder the 'what to expect page'

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#321]
On Thursday Nov 6, or before, we should move the "Weekend Outline" section to the top of the page, above the note from Mark.

https://2015.mozillafestival.org/expect

cc @hannahkane does this work for you?

**Comment by ioana-chiorean** [comment]
I can take care o it around 5th evening or 6th morning (after we get the needed confirmation)

**Comment by hannahkane** [comment]
Thanks, @ioana-chiorean - that would be amazing!

**Comment by mmmavis** [comment]
I'd suggest having the PR ready first so when the time comes we can just hit the merge/deploy button :bowtie:
