### ISSUE TITLE
Meet & Greet cards for Mozfest participants

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#325]
This was overlooked in the master print list... We'll need it asap to order them externally.

This is basically a business card sized paper, on card stock, for people to write on when they meet someone. 

@marcwalsh any more details to add? What should the card say?

**Comment by cassiemc** [comment]
This will be due Monday Nov 2 EOD UK time / 9am PT. We should prob aim to finish this Friday (sorry @natalieworth!)

**Comment by cassiemc** [comment]
From @marcwalsh:  "it should basically say who I am, what I do, and how to contact me" The context is that when someone meets a new person at Mozfest, they can give out this card as a way to keep in touch.

**Copy:**
Nice to have met you at Mozfest 2015! Let's stay in touch.
Name: ___________________
How to reach me: ________________
What we talked about: _____________________

**Comment by natalieworth** [comment]
Hey @cassiemc , got some rough drafts from these cards up on redpen: https://redpen.io/koe5e7c7fd5344fa7d
Thanks

**Comment by natalieworth** [comment]
@cassiemc Refinements up on redpen: https://redpen.io/dob2c1c78ff8cab534

**Comment by marcwalsh** [comment]
@natalieworth looks awesome! Just confirming sizes they need to be 85mm x 55mm please. We're going with Pixart as they are around £200 less than local printers. 

https://www.pixartprinting.co.uk/digital-litho-printing/printing-business-cards/

**Comment by natalieworth** [comment]
@cassiemc @marcwalsh Uploaded to redpen the version with the 85mm x 55mm dimensions:
https://redpen.io/p/qj26933057979f7d94

**Comment by marcwalsh** [comment]
This is perfect @natalieworth - Am I able to get the PDF please?

**Comment by marcwalsh** [comment]
@natalieworth - Would it be possible to get these before 10:30AM PST?

**Comment by natalieworth** [comment]
@marcwalsh Here is the link to pdf file with bleed: https://drive.google.com/open?id=0B20-0lpP23c0OTlWMWlxN25JcEE

**Comment by marcwalsh** [comment]
I'm receiving this error from the printers.
<img width="839" alt="screen shot 2015-11-02 at 18 57 48" src="https://cloud.githubusercontent.com/assets/14007066/10891062/b2877a90-8193-11e5-8c91-c6d8b071d215.png">

**Comment by marcwalsh** [comment]
@natalieworth

**Comment by natalieworth** [comment]
Hi @marcwalsh , sorry I think I exported the wrong bleed amount. Here is the updated file with the 5.9x8.9cm settings: https://drive.google.com/open?id=0B20-0lpP23c0OTlWMWlxN25JcEE

**Comment by marcwalsh** [comment]
Perfect, all accepted and good to go! Closing...

**Comment by cassiemc** [comment]
Nice work @natalieworth, thanks @marcwalsh!
