### ISSUE TITLE
Site zoomed out at first load

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#326]
Just got this earlier at first loading and was wondering if anybody else had it. 
As it is a mole page zooming in/out is blocked so this should not happen. 

Not critical as after refresh is ok. 

<img src="https://cloud.githubusercontent.com/assets/1391451/10831601/4975ab82-7e8f-11e5-9e76-d1f43c2e33e9.jpg" width="300" height="550"" />

**Comment by hannahkane** [comment]
I can't reproduce this. What browser?

**Comment by ioana-chiorean** [comment]
Firefox for Android.

**Comment by mmmavis** [comment]
I don't have an Android device around to test this.  Will check it out on Nexus 4 when I get home.

**Comment by ioana-chiorean** [comment]
i will close this as I only hit it once :)
