### ISSUE TITLE
Small content updates for the website-

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#331]
There are some minor content updates required on the website - many have been captured on other issues but not updated so thought I should make a new issue for them all so they are easier to manage and update
- [ ] Contact info on guidelines page #197 
- [x]  Twitter handles on Global Village bios Jon Rogers - @ileddigital
 Ian Forresters- @cubicgarden and Jasmine Cox - @wearesorryfor 

cc @mmmavis @hannahkane @ioana-chiorean @thornet

**Comment by ioana-chiorean** [comment]
I can take care of them @Saallen - I just need a confirmation on #197 on the new texts ( for ex the text propose has no phone etc)

**Comment by ioana-chiorean** [comment]
Second part is covered in PR #332

**Comment by hannahkane** [comment]
I'm going to close this because now this is just a dupe of #197
