### ISSUE TITLE
Create template for Twitter photos

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#338]
@natalieworth can you create a single template with the MozFest branding that we can pop photos into to tweet? Sort of like a frame. If you make the photo part square, then we can use both landscape and portrait shots.

@KevZawacki can you please provide dimensions?

cc @cassiemc (this can be P2 - nice to have)

**Comment by KevZawacki** [comment]
@natalieworth We can make the template the same size as the past MozFest Twitter graphics

**Comment by cassiemc** [comment]
@edrushka Yes this seems like a definite 'if there's time' P2 issue. @natalieworth I would also prioritize EOY work over this. 

Wondering if we have evidence that a frame like this increases engagement (or if there is another goal in mind?). It reminds me of when you go to a theme park and get your picture taken on a roller coaster, the frame that your photo comes in... haha :)

@edrushka Maybe a simple way to associate the photos with Mozfest is to put a watermark over one of its corners? The Mozfest logo in white, maybe at 80% opacity?

**Comment by edrushka** [comment]
Ohh good idea @cassiemc. WFM! Does that work for you @kevzawacki?

**Comment by KevZawacki** [comment]
Sounds good!
