### ISSUE TITLE
Add all designed content for MozFest 2015 to Drive/Dropbox

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/2015.mozillafestival.org#339]
@cassiemc @lovegushwa @adiladiladil @natalieworth (Sorry if I missed anyone!)

Are we all able to add these to shared Google Drive folder or to Dropbox please?

Thanks!

**Comment by lovegushwa** [comment]
Hey @marcwalsh you can access the MozFest drive here:
https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eeXZyWkdQa2hNOXc&usp=sharing
