### ISSUE TITLE
MozFest Registration Platform Operational review

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#34]
Ti.ti and Stipe are under MoFo operational review

Current status : Just opened

**Comment by Saallen** [comment]
t&cs with Ops now. waiting on signature

**Comment by Saallen** [comment]
T&Cs now with Ti.to for review and signature

**Comment by ScottDowne** [comment]
@Saallen not sure if we can close this or not?

**Comment by Saallen** [comment]
:100:
