### ISSUE TITLE
Is there a Medium Publication for mozfest?

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/2015.mozillafestival.org#343]
I remember seeing some issue (but unsure of repo) on encouraging the use of Medium at #mozfest as a network for possible syndication.

Is there a publication anyone has set up that we should join?

**Comment by cassiemc** [comment]
@Saallen @HPaulJohnson @edrushka Do any of you know the answer to this?

**Comment by edrushka** [comment]
https://medium.com/mozilla-festival

**Comment by cassiemc** [comment]
Thanks @edrushka!

**Comment by jgmac1106** [comment]
Thanks @edrushka. I see that @KevZawacki is the editor. Authors can no longer submit stories to publications but first need to be invited by the editor.

Do you want to open the publication up for all participants or keep it more locked down? Either way you will need to think about methods to inviting contributors.

If you want an "official" publication I have no problem running one that participants can contribute to, but I  like the idea of the main mozfest publication.

We can use tags and sections to set it up in any way.

**Comment by HPaulJohnson** [comment]
@jgmac1106 anyone can contribute and tag their posts using #mozfest hashtag. We can then include those into the Mozfest publication (that's the way content is curated within Medium platforms for specific publications, at least as we understand it). The idea would be to pull all #mozfest content into that single, official publication. 

If you want to help with that curation and editing we'd love it. Let's connect when you get to London and sync up on a plan. 

cc: @KevZawacki

**Comment by jgmac1106** [comment]
Sounds good. I would love to help out. We can catch up at #mozfest. Your understanding is slightly off in that an author has to be added to the publication and then they have to add their story to the publications.

Publications consist of editors and authors. All authors have to be invited by editors first. 

The tags features is just to organize sections in a publication.  So you could have a featured story and a tag for each pathway for example.
