### ISSUE TITLE
Add pathway descriptions to schedule app

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#344]
Hey @mmmavis - is it possible to port the description for each pathway from https://2015.mozillafestival.org/pathways to the schedule?

Note that not all the descriptions are done - @thornet will ask people to do this at the Thursday Space Wrangler meeting.

**Comment by edrushka** [comment]
cc @secretrobotron @alicoding

**Comment by hannahkane** [comment]
Moving this to https://github.com/mozilla/mozfest-schedule-app/issues
