### ISSUE TITLE
MozFest Schedual Review : Bugzilla for Legal and Security

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#35]
Sched.com is under Legal and Security review

Current Status : Held

**Comment by Saallen** [comment]
This review is highlight some blockers
Big blocker is that sched,com holds onto sign up details post event- 

"One piece here that is worring me is that we are creating an API where submitted proposals on the MozFest site will then move to sched.com and we will be giving the app peoples email addresses who might not be sucessful with their submissions to the festival. The app then keeps their details even if they are not attending the festival"
Opening the CFP with just google docs might be our first action rather than using Sched.com but will update this issue as this developes @edrushka @ScottDowne

**Comment by ScottDowne** [comment]
Interesting.

Google docs is still an option.

One thing that comes to mind is the email field is a custom field. Couldn't we just delete it ourselves when we're done with it?

**Comment by Saallen** [comment]
I am asking this question now :)

**Comment by ScottDowne** [comment]
From Sched, the email field (or any field) and the session itself is retained for two weeks after deletion.

Is that all we need to know?

**Comment by Saallen** [comment]
Security are still reviewing- I do have a meeting on Thursday to confirm T&CS with legal

**Comment by Saallen** [comment]
@ScottDowne @edrushka Just left a meeting with security and legal around using sced.com
the security review highlights that
* Sched.com could sell our details to third party
* Security is non existant but Security are running an RRA today -(rap risk ass)
* Privacy is not great and they want to know more about passwords.

Will continue to update once the final RRA results are back

**Comment by Saallen** [comment]
We are no longer using Sched.com so will close this bug
