### ISSUE TITLE
  MozFest 2015 site: Landing page content

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#36]
Kevin to finalize copy for landing page. Latest redpen [here] (https://redpen.io/sc30fb6f0c48af467e) but keep your eye on the [etherpad] (https://etherpad.mozilla.org/mozfestkickoff) for updates in the design.

**Comment by KevZawacki** [comment]
Landing page edits can be found here: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit

They are on page one beneath the headline "Landing page edits."
