### ISSUE TITLE
MozFest 2015 Participating at MozFest

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#37]
Copy lead @KevZawacki 
Consulted @edrushka @Saallen

Remixing last years statement but with a nod to our Academy element and the over-arching educational clubs 
Last years content:
MozFest is a yearly festival with hundreds of passionate people exploring the Web, learning together, and making things that can change the world. It's very hands-on and immersive. Sometimes it will feel chaotic, but everyone is open-minded and eager to help you make and learn with them.

Participants of every age and experience are welcome. We believe that everyone has something to share and something to learn. Youth are especially encouraged to come and lead sessions, but MozFest is truly an event for all ages! There's a creche on-site as well as activities for young people and industry experts.

MozFest runs for three days, beginning on Friday evening with a "Science Fair," where we demo exciting projects from across the web. Saturday and Sunday are full days of sessions, hacking and good coffee. There is a party on Saturday night, and the festival ends on Sunday evening with a closing demo party, showcasing what we made together.

**Comment by edrushka** [comment]
Clarifying: this is an overview of how the festival works, and how to dive in and get the most from it, and not Mark's welcome message.

The way the page is designed, this will directly follow Mark's message though.

**Comment by Saallen** [comment]
Three keys goals of the festival this year are

    1. Rally around a common cause: "Help people wield the web."
    2. Experience the Mozilla Learning vision.
    3. Be systematic about bringing, celebrating and up-leveling leaders.

Wield the Web is not a fully accepted slogan but I will let Mark make the final decision here. The learning vision speaks to the Academy and clubs

**Comment by KevZawacki** [comment]
Participating at MozFest copy is here, on page four: https://docs.google.com/document/d/1KjLd6W0hbHlu16anwMP7J-MKEd0e7HjJceFv7Y_p9NI/edit
