### ISSUE TITLE
MozFest 2015 site: Build site

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#38]
#### This ticket is for Scott's build

Additional tickets:
[Meta-ticket in plan] (https://github.com/MozillaFoundation/plan/issues/374)
[UI tickets] (https://github.com/mozilla/mozillafestival.org/issues?q=is%3Aopen+is%3Aissue+label%3A%222015+Site%22+label%3ADesign)
QA ticket

**Comment by edrushka** [comment]
Here are the SVG assets from Adil: https://www.dropbox.com/sh/woqt8g4oaq72ad0/AAAEYtaZbh2ocSTunjEtpTZua?dl=0

**Comment by ScottDowne** [comment]
It's getting close. https://mozfest-2015-staging.herokuapp.com/

I'm adding in a list of things I still need to do, mostly for my own organization. Seems like a lot, but most of it is p2/not a blocker.

P1 and a blocker to shipping.
- [ ] Proposal form needs error handling and validation.
- [ ] Proposal form needs success happenings.
- [ ] Insert Mark Surman signature and photo.
- [ ] Plug in real sched paid account and remove my free test account.
- [ ] Live site and better staging site with Travis integration. -jbuck

P2 but cannot ship it as is, so a blocker. So either needs to be finished or links need to be hidden.
- [ ] Home page play button needs to open a video? This isn't clear to me, so I'll probably be pining people asking about that. P2
- [ ] Volunteer page. P2
- [ ] About page. P2
- [ ] Contact us page email links. P2.

P2 and not a blocker.
- [ ] Tickets page could have fancier use of ti.to with custom buttons.
- [ ] Fringe events page.
- [ ] Where to stay bit at end of what to expect page.
- [ ] Hover states. -ricardo

**Comment by ScottDowne** [comment]
Something that occurred to me, we need some sort of success message when a proposal is successfully submitted. Maybe a button for "submit another proposal"? Do we encourage people submit multiple proposals?

Also need an error message when a required field is missing. There would be an error message for each field. Examples: "session name is a required field" or "you must agree to our privacy policy"

These would appear under each field in red.

**Comment by edrushka** [comment]
@Saallen are we encouraging multiple proposal submissions? What should the success message say?

@ScottDowne let me know if you need a hand with copy for the 'required field is missing' messages. What you've given as examples is fine, but happy to help if you need it.

**Comment by ScottDowne** [comment]
@edrushka Yeah, I can use those errors.

I do need copy for two other errors that are a bit more involved. For duplicate session name submissions, example "A session with that name already exists, please change the name and try again"

The other error is a little weirder. It's a generic catch all error. It's really just a fallback, but shouldn't be hitting it. The copy should give them something to do, maybe an email for help? Maybe "Error submitting session proposal, please try again later or email help@mozilla.org" Something like that.

**Comment by edrushka** [comment]
@ScottDowne for duplicate sessions, what you have suggested is great.

For the catch-all error, how about "Uh oh! There's an unknown error with your session proposal. Please try again later, or email [address] for help." @Saallen what address would you like them to email?

**Comment by ScottDowne** [comment]
For now, this is what I have as a placeholder session proposal success page: https://mozfest-2015-staging.herokuapp.com/session-add-success

If we want to add a button to propose another, that's easy. Until then though, I felt it was better to leave it out.

**Comment by Saallen** [comment]
Yes, people can submitt another or many sessions for consideration so giving them a clear pathway to submit again would be appreciated.
There is one address for all festival enquiries which is festival@mozilla.org so all contact paths lead to this address. Eventurally we will need another pathway for press but I will field all enquires until closer to the festiavl.
 
Before I add the text to be seen post submission- did we confirm whether we could see submitted proposals anywhere? I am guessing that by using the sched.com app this will not be possible??

**Comment by ScottDowne** [comment]
@Saallen perfect, that answers my questions.

For the sched question. We're hiding the proposed submissions from anyone cept admins to the sched account. I have this working on the staging site.

**Comment by cassiemc** [comment]
@ScottDowne Here is the final photo of Mark as well as his signature: https://www.dropbox.com/sh/njzalxillwaus0q/AAAsg_dukij8UuWQpCtBSTRTa?dl=0

![mozfest ui 1 -05](https://cloud.githubusercontent.com/assets/1186326/7889282/94bbff16-060c-11e5-84d7-38042576d391.png)

**Comment by Saallen** [comment]
Hey, I spoke with Adam on Friday and it has been advised that we do not use BSD for any MozFest 2015 apart from Updates sign up. So we might have to hide the volunteers link on the footer until I build the sign up form on TI.TO-  I need to work on this with Spike, our volunteer coodinator and we have a meeting this week. I might have the volunteer form on a separate ti.to account so Spike can have autonomy.I will work as fast as I can here.

**Comment by ScottDowne** [comment]
Because a lot of p1s are done, I'm cleaning up the above list:

P1 and a blocker to shipping.
- [ ] Update schedule for weekend in what to expect page
- [ ] Live site and better staging site with Travis integration. -jbuck
- [ ] Volunteer page no longer links to BSD, needs to be something else.
- [ ] About page.

P2 and not a blocker.
- [ ] Tickets page could have fancier use of ti.to with custom buttons.
- [ ] Hover state update when session is poposed.

P2 and needs to be done closer to the event.
- [ ] Fringe events page.
- [ ] Where to stay bit at end of what to expect page.
- [ ] Mobile support improved, not great.

**Comment by ScottDowne** [comment]
@Saallen I filed the volunteer issue as a new issue and assigned you for now: https://github.com/mozilla/2015.mozillafestival.org/issues/69

**Comment by Saallen** [comment]
Thanks @ScottDowne will work on that asap- Wanted to return to the view submitted proposals question from above- So submitted sessions can only be seen by those with admin rights. Those who submit a proposal cannot see their sessions?
