### ISSUE TITLE
Mozfest 2015 site needs to live somewhere

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/2015.mozillafestival.org#39]
We need to host the site I'm working on here: https://github.com/ScottDowne/2015-mozfest

It doesn't need to stay in that repo, I just dumped it in there for now.

We probably want a staging site.

And finally, some sort of travis build.

I have never set one of these up (I probably should with jbucks help) or jbuck needs to do this. Either way, @jbuck hi.

**Comment by jbuck** [comment]
I've pushed the content in this repository to mozilla/2014.mozillafestival.org, and pulled the content from ScottDowne/2015-mozfest into this repository.

**Comment by jbuck** [comment]
I've deployed this to https://mozillafestival-org-2015.herokuapp.com/ as a staging environment, and I'll file issues for required fixes as I see them

**Comment by jbuck** [comment]
@ScottDowne @edrushka @Saallen The site is now deployed at https://2015.mozillafestival.org . Please test and let me know if you encounter any errors. Once someone gives me the go-ahead I will change the https://mozillafestival.org redirect from http://2014.mozillafestival.org to https://2015.mozillafestival.org .

**Comment by edrushka** [comment]
:grin::grin::grin::grin::grin::grin:  **YAY!**  :grin::grin::grin::grin::grin::grin:

@Saallen I'll let you do the honours for the redirect. Just say when you're ready.

**Comment by jbuck** [comment]
@ScottDowne reported that email sending wasn't working, which was totally because I didn't configure that correctly. But it's working now!

**Comment by Saallen** [comment]
Ready!!! This is so great guys, I was on the site this morning, proposaing sessions and jumping around tabs. THANKSSOOOOOOOMUUCHHHHH :fireworks:

**Comment by ScottDowne** [comment]
:heart: :tangerine: :full_moon: :four_leaf_clover: :dolphin: :cherry_blossom:

**Comment by jbuck** [comment]
Okay, redirect is set :tada:
