### ISSUE TITLE
add hover states to site

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/2015.mozillafestival.org#40]
Code lives here right now: https://github.com/ScottDowne/2015-mozfest

**Comment by vazquez** [comment]
Submitted PR, waiting on thumbs up.
https://github.com/ScottDowne/2015-mozfest/pull/1

Adding hover states for:

    Navigation bar
    CTA
    Footer icons
    Links

**Comment by ScottDowne** [comment]
merged

Has a few issues I listed in the PR, leaving this open until those issues are also merged.

**Comment by ScottDowne** [comment]
Only thing left here is the submit button on proposals whiting spinner is a bit odd now.

**Comment by ScottDowne** [comment]
I'm just closing, it's good enough.
