### ISSUE TITLE
Can we change the name of this repository to "2015.mozillafestival.org"?

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#41]
Hey @edrushka @mmmavis @ScottDowne could I rename this repository to "2015.mozillafestival.org"? I'd like to do this to more accurately reflect that this is the 2015 version of the site.

**Comment by ScottDowne** [comment]
I see no reason why that would cause an issue.

I do wonder if it would just be easier and better to make a new one for 2015 instead of converting the 2014 to 2015?

Either way, I'm fairly happy.

**Comment by mmmavis** [comment]
We used to have one repo for each year's MozFest site but it gets harder to track all the GitHub tickets.  If I remember correctly, this "mozillafestival.org" repo was actually the "2012/2013" site repo and we decided to port 2014 site's stuff over and just have a single repo for MozFest site.

**Comment by mmmavis** [comment]
If we decided to rename this repo to "2015.mozillafestival.org" I would prefer creating a new repo just cuz this repo now contains commit history from the 2012 site to 2014's and I think "mozillafestival.org" is a more suitable name.

**Comment by mmmavis** [comment]
(one note: I'm not helping with MozFest site build this year :eyes: so I might not be a good decision maker :hamster: )

**Comment by jbuck** [comment]
@mmmavis I pushed all of the content that was in this repository to the mozilla/2014.mozillafestival.org repository, and pulled @ScottDowne 2015-mozfest site into this repository. The only reason I'd prefer to rename this repository is so that we wouldn't need to refile tickets.

**Comment by jbuck** [comment]
Okay, I renamed the repository because it seems like you both had conerns about the commit history... and I pushed the commit history into another repo. Thanks for your input!
