### ISSUE TITLE
Server needs configuration for sched endpoint

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#42]
Right now the server is configured to point at @ScottDowne's testing endpoint, we should make this a configurable option.

**Comment by jbuck** [comment]
The server will also need to push this configuration endpoint to the public/index.html file https://github.com/mozilla/2015.mozillafestival.org/blob/47e2e64b47493d4df7e3325796d608566163a7b2/public/index.html#L27 and it needs to use HTTPS instead of HTTP.

**Comment by ScottDowne** [comment]
Did this here: https://github.com/mozilla/2015.mozillafestival.org/pull/61/files

Reopen or refile if more needs to be done.
