### ISSUE TITLE
Inclusion and Diversity paragraph flows weirdly

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#43]
![screenshot 2015-06-01 11 05 07](https://cloud.githubusercontent.com/assets/578466/7915854/4739abaa-084e-11e5-9d71-d8dcc7547ab3.png)

**Comment by Saallen** [comment]
Flagging this with @KevZawacki

**Comment by KevZawacki** [comment]
cc @edrushka 

Thanks, all. Looks like the copy was scrambled along the way. I propose we change it to:

"Mozilla welcomes and encourages participation by everyone. It doesn't matter how you identify yourself or how others perceive you. MozFest activities are inclusive and support diversity. 

Mozilla welcomes contributions from everyone, as long as they are constructive and respect the Mozilla community. Our community includes, but is not limited to, people of varied age, ability, culture, ethnicity, gender, gender-identity, language, race, sexual orientation, geographic location and religious and political views."

This is delicate language — can we notify the original author(s) before finalizing the change?

**Comment by Saallen** [comment]
We took this statement directly from  [mozilla participation guidelines] (https://www.mozilla.org/en-US/about/governance/policies/participation/)

**Comment by KevZawacki** [comment]
Ah, I see. Let's keep it the same, then, but with this formatting:

The Mozilla Project welcomes and encourages participation by everyone. It doesn’t matter how you identify yourself or how others perceive you: we welcome you. We welcome contributions from everyone as long as they interact constructively with our community, including, but not limited to, people of varied age, ability, culture, ethnicity, gender, gender-identity, language, race, sexual orientation, geographical location and religious views."

Mozilla-based activities should be inclusive and should support such diversity.

**Comment by ScottDowne** [comment]
So I'm not sure what's being asked here. It looks like there are three asks.

1. Copy is wrong?
2. The paragraph is cut in two, and placed on the next column.
3. The first word on the second column is capitalized, when it shouldn't be.

Number 3 to me is the issue. If the copy is wrong, I can update it. I did see a few words different from the copy I copied from wherever I initially got it and the link @Saallen linked. I'm updating it to match the link @Saallen linked and fixing the cap. I'm not sure how to fix #2, I copied the UI comps, changes to that should be run by a designer, but I'm happy to make them.

**Comment by ScottDowne** [comment]
Updated: https://mozillafestival-org-2015.herokuapp.com/guidelines

Feel free to reopen or refile if I didn't quite get it right.

**Comment by KevZawacki** [comment]
Thanks, Scott. One final update: can we change "welcome" to "welcomes." That's it!

**Comment by ScottDowne** [comment]
Done
