### ISSUE TITLE
Tito ticketing is live now?

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#44]
It looks like I can purchase a ticket right now? https://mozillafestival-org-2015.herokuapp.com/tickets

**Comment by jbuck** [comment]
Scott and I tested this. We found that Scott can see the ticket registration live because he's signed-in to tito. I have no idea why I can see the ticket registration though, I'm not signed in.

**Comment by ScottDowne** [comment]
It's a bug on ti.to's side, they are aware of it.

For now I'm going to just remove the link. We can add the link when we want it to go live, thus not being blocked by ti.to.

**Comment by ScottDowne** [comment]
This hides it: https://github.com/mozilla/2015.mozillafestival.org/pull/57

Keeping this ticket open, but we're unblocked.

**Comment by Saallen** [comment]
We can allow the page to go live now- contract is just being adjusted but both sides have already agreed to terms in writing. @ScottDowne do you need me to push the live button on the ti.to website?

**Comment by ScottDowne** [comment]
Looks like we can close this.
