### ISSUE TITLE
About page is not loading

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#45]
Getting a blank content page for About link

https://mozillafestival-org-2015.herokuapp.com/about

**Comment by jbuck** [comment]
I'm getting an error in the console: "Warning: Failed propType: Required prop `image` was not specified in `HeroUnit`. Check the render method of `About`."

**Comment by ScottDowne** [comment]
Was still waiting for assets on that one, so it was delayed.

**Comment by ScottDowne** [comment]
Done
