### ISSUE TITLE
Bugs: Contact page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#46]
We are no longer working with Ablion PR so can you please remove 
" If you have a press inquiry, you can email us at mozfest@albiondrive.org."

**Comment by ScottDowne** [comment]
Fixed, not sure yet how long it takes to be live.

I'll keep this open until I see it live.

**Comment by Saallen** [comment]
:+1:

**Comment by ScottDowne** [comment]
Live
