### ISSUE TITLE
Call for Proposals

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#48]
Is this the final form? As we are missing the tags?
https://mozillafestival-org-2015.herokuapp.com/proposals

**Comment by ScottDowne** [comment]
Yeah, missing tags. When I did it I still had open questions about tags, so I just did everything else.

**Comment by Saallen** [comment]
@thornet has asked for more information around what the CFP is and how to submit. I have copy for this already. Would we like to add this as a paragraph to the top of the page or as a link out?

**Comment by ScottDowne** [comment]
@Saallen for row three tags, I have this info:
Youth
Artisans [tech, maker, coder, developer?]
Activists
Educators
Localizers

Artisans feels unfinished to me.

I think maker and/or developer make the most sense to me. Not sure if we want one or both though. For now I'm leaving it as developer. My reasoning is all in that list have the potential to make something.

**Comment by ScottDowne** [comment]
@Saallen For the dropdown labels, right now I have three: Themes, Modes and Audience.

Seeing how only one can be selected, I feel like themes and modes should be theme and mode.

**Comment by Saallen** [comment]
:+1: @ScottDowne for labels
I like you thought process on the dev v's Maker- Happy with your decision :)

**Comment by ScottDowne** [comment]
Tags are added. We can iterate on them in new tickets, closing this one.

**Comment by Saallen** [comment]
Note on tags- type is an important filter for us- 
If Theme could translate as type then we can easily search on the backend of sched.com
