### ISSUE TITLE
Update Mark's speech bubble with latest version

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#63]
Here's the latest. Note that Mark has *not* signed off yet (although this should be v. close):

Dear Friends,

MozFest is an annual celebration of the world’s most valuable public resource: the open Web. Participants are diverse -- there are engineers and artists, activists and educators. But everyone shares a common belief: the Web can make lives better. The Web unlocks opportunity, spurs creativity, teaches valuable skills and connects far-flung people and ideas.

MozFest is about improving the open Web with new ideas and creations. It’s also about sharing the open philosophy. By 2025, five billion individuals will be online, many exclusively through their smartphones. And it’s so important these new users discover a Web that improves each and every person's life.

There are threats and challenges. Some companies and governments seek to wrestle control of the Web away from the public. There is also a lack of education around web literacy, the ability to meaningfully interact and create online. When users don't fully understand how the Web works, they can't harness its potential.     

We can change this. At MozFest, we unite for creative sessions, peer learning and brainstorms. Together, we devise ways to teach web literacy; to be Freedom Fighters who stand up for the Web; and to ensure the next billion people to come online find a fully-open platform. 

Come ready to learn, teach and create. We’ll see you in London.

—Mark Surman

**Comment by ScottDowne** [comment]
I love having copy changes in tickets vs google docs or redpens

:heart:

**Comment by ScottDowne** [comment]
Updated copy: https://mozillafestival-org-2015.herokuapp.com/expect

Feels wordy, I kinda liked it better with only three paragraphs, fit better in the space.

**Comment by edrushka** [comment]
I just got confirmation that Mark approved this. No further changes should be necessary.
