### ISSUE TITLE
Volunteer page link to ti.to and not BSD

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/2015.mozillafestival.org#69]
Right now the volunteer link in the footer links to a BSD form.

There was talk of moving this over to ti.to in https://github.com/mozilla/2015.mozillafestival.org/issues/38

Not sure what's involved or what blockers that has yet.

**Comment by Saallen** [comment]
We will just need to link a new TI.TO account here for volunteers- I will make some copy here so it can sit above the ti.to integration block

**Comment by edrushka** [comment]
@Saallen Is this still happening or will we stick with the BSD page that's currently live?

**Comment by Saallen** [comment]
I have been waiting on Spike to get back to me about moving over as he was going to build the page- I might build the volunteers page now on ti.to myself then he can just share the account with me . Give me a couple of hours to test.

**Comment by Saallen** [comment]
I have set up the volunteer sign up sheet in ti.to now and given @ScottDowne admin access so you can integrate this page into the website and remove the bsd link

**Comment by Saallen** [comment]
Set a new milestone on this issue so that we can swap out the pages before we promote the updated site.

**Comment by ScottDowne** [comment]
I did this, but I took the quick solution and just linked directly to the ti.to link.

However, we could probably add an initial page between them, with a bit more to info to explain what it is maybe? @Saallen thoughts?

**Comment by Saallen** [comment]
Good idea as it's not as slick as the other page @ScottDowne will write something up in the morning

**Comment by Saallen** [comment]
Small text below- linking in @KevZawacki for help with text

Volunteers are integeral to what we do at Mozilla and its not different at MozFest. MozFest would not be able to take place without the time, dedication and love that our volunteers invest in the festival. 
 
The roles are varied, from operational set up such as making swag bags and flashing computers,  to running the welcome desk and assisting with press, to hands on programming help within the sessions. We just ask that you give us 4 hours of your weekend and then you can attend the festival for free for the rest of the weekend. We try place people in roles they are interested in and rotation of roles is encouraged. We do provide training pre event and we have several volunteer socials where we share festival news.
All volunteers receive a MozFest T-shirt and meals while working at the festival but unfortunately we cannot cover travel to and from the event.
We meet bi-monthly in the MozillaLondon office so come say hi and find out more about how to get involved. The next Mozpub is in September - Email festival@mozilla.org for more details

**Comment by KevZawacki** [comment]
Thanks, @Saallen. My proposed edits: 

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love our volunteers invest.

Volunteers at MozFest do so much, from running the welcome desk and arranging schwag bags to assisting press and helping with programming. We try to place people in roles they’re most interested in, and rotation of roles is encouraged. We provide training before the event, and we host several volunteer socials.

Volunteers are asked to share four hours of their time. As a thank you,, we’ll cover the festival’s ticket cost. Volunteers also receive a MozFest t-shirt and meals. Unfortunately, we cannot cover travel to and from the event.

The MozFest team meets bi-monthly in Mozilla’s London office, so come say hi and learn more. The next Mozpub is in September — email festival@mozilla.org for details.

**Comment by SpikeUK** [comment]
All looks great to me thanks Sarah and Kevin.

One correction please - two commas in third para "...As a thank you,,
 > we’ll cover the..."

Spike

**Comment by ScottDowne** [comment]
Updated to staging: https://mozillafestival-org-2015.herokuapp.com/volunteer

If everything looks good we can get @jbuck to ship it.

**Comment by SpikeUK** [comment]
All looks great to me thanks @ScottDowne
