### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#71]
I know this is just a marker piece currently but as I read it I head voices in my head complaining.
With the timings on the Saturday and Sunday- can they read as follows- I  **bolded** the change request
Saturday
8:00 Doors open
9:00 Welcome & Opening Keynotes
 **10:30** Morning sessions begin
12:30  Lunch
14:00 Afternoon sessions begin
17:30 to 18:30 Evening lightning talks

**Comment by ScottDowne** [comment]
Building staging with these changes now.
