### ISSUE TITLE
Tags and Filter searches- matching CFP to Sched.com

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#80]
Note on tags- type is an important filter for us-
If Theme could translate as type then we can easily search on the backend of sched.com

**Comment by ScottDowne** [comment]
I was playing around with theme mapping as type and mode mapping to subtype.

When viewing sessions from the admin page, it looks like this

![table1](https://cloud.githubusercontent.com/assets/197334/7991195/52a7bf7c-0ac4-11e5-8ef4-e1da6f99ea5c.png)

You see the theme first, and the mode under it in brackets.

They also become searchable.

**Comment by ScottDowne** [comment]
Scratch the above image, it's bad.

I'm not using subtype, but just tags. Also adding theme to session type too.

**Comment by ScottDowne** [comment]
Closing this. Updated to use tag, and they seem to work pretty well in sched, and are simple and clear.

I felt like using other fields that kinda match but not really was more confusing than useful.
