### ISSUE TITLE
QA test MozFest site on staging

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#81]
Site we're testing: https://mozillafestival-org-2015.herokuapp.com/

File your feedback as issues within this repo and make sure to add the QA label.

## Functional Testing
- **Cross-browser testing**
  - **Desktop**
    - [ ] Chrome (Latest - 2)
    - [ ] Firefox (Latest - 2)
    - [ ] Internet Explorer (10+)
    - [ ] Safari (7+)
- [ ] Check layout on common variation of screen resolutions

#### Landing page functionality
- [ ] Can view video
- [ ] Top nav buttons work (Call for Proposals, Tickets, Location)
- [ ] Submit a Proposal button works
- [ ] Footer links work

#### Submit a Proposal form
Try submitting one or more proposals. Don't worry - we'll delete them after.
- [ ] Form works as expected
- [ ] Success message received, with link to submit another session

#### Tickets page
 **This should take you to the page but you will be unable to purchase a ticket. This is expected.**

#### Location page
- [ ] Map zooms as expected
- [ ] links work

#### Other pages (About, What to Expect, Participation Guidelines, Get in Touch, Tweet MozFest, Volunteer with Us)
- [ ] links work

## Design & Copy
- [ ] Is the static text clear, concise, and meaningful?
- [ ] Are all static text words spelled out (correctly!) and abbreviations used only when space is limited?
- [ ] Is static text capitalized according to Webmaker standards?
- [ ] Do buttons follow the Webmaker standards for size and position?

/cc @ScottDowne @edrushka @Saallen

**Comment by SpikeUK** [comment]
Really like it in general. Would like to add some copy to the Volunteer page (https://sendto.mozilla.org/page/s/mozfest-2015-volunteer) giving more detail about what vols do.
Two typos on Participations Guidelines page (https://mozillafestival-org-2015.herokuapp.com/guidelines) "...These guidelines cover **out** behaviour as participants, facilitators, speace wranglers, staff, volunteers, **bendors**, and anyone else..."
Thank you
Spike

**Comment by ScottDowne** [comment]
@SpikeUK Sweet, thanks. The typos are fixed.

**Comment by SpikeUK** [comment]
(cough) "...speace wranglers..." should be "...space wranglers..." - sorry, missed that one :)

**Comment by ScottDowne** [comment]
No prob, typos are easy to fix.

Updating now.

**Comment by hannahkane** [comment]
/about page typos:
 * "Mozilla's anual" should be "Mozilla's annual"
 * "affectionaltely known as" should be "affectionately known as"
 * "educatios" should be "educators"
 * also two instances of lower-case "web" on that page

**Comment by hannahkane** [comment]
/location has an instance of "Mozfest" instead of "MozFest," which I believe is the standard

**Comment by hannahkane** [comment]
/guidelines has an instance of "Mozfest" instead of "MozFest" in both the title and body copy of the "Raising Issues" section.

**Comment by cassiemc** [comment]
The initial video play isn't working as intended. The video should be full-width, and the text (including the header) should fade up and off the screen to focus you on the video.

**Comment by SpikeUK** [comment]
Subtitle text of video needs a lot of work. Was it created by a machine? ;-)
