### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#82]
Enable compression for the following resources to reduce their transfer size by 722.7KiB (77% reduction)

**Comment by ScottDowne** [comment]
Did you mean to list some "following resources"? or is something implied?

**Comment by jbuck** [comment]
There is a list of resources, but practically speaking if you just enable the gzip plugin you're good to go.

**Comment by jbuck** [comment]
If you just add a gzip plugin to middleware it'll compress everything we need to, I bet

**Comment by ScottDowne** [comment]
Is there a plugin we have used before for this? Or one that we know is good?

**Comment by jbuck** [comment]
https://github.com/expressjs/compression is a solid choice

**Comment by ScottDowne** [comment]
think this is done
