### ISSUE TITLE
Add cache-control headers to server

### ISSUE THREAD

**Issue by jbuck** [mozilla/2015.mozillafestival.org#85]
Right now it's serving files with `Cache-Control:	public, max-age=0` which is no good.

**Comment by ScottDowne** [comment]
Not familiar with what that is doing, where that is specified or what I need to change it to.

**Comment by jbuck** [comment]
That response basically means "Don't cache any files at all". If you don't specify a Cache-Control header yourself then Express will set that header to `public, max-age=0`. I'd recommend changing it to something larger; maybe 3600 to cache files for an hour?

**Comment by ScottDowne** [comment]
This should do it. R?

https://github.com/mozilla/2015.mozillafestival.org/pull/119/files

**Comment by ScottDowne** [comment]
https://github.com/mozilla/2015.mozillafestival.org/pull/119
