### ISSUE TITLE
Footer on the Volunteer Form might need to be adjusted

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#86]
Congratz on the new MozFest site!!! IT LOOKS SO MUCH BETTER THIS YEAR :dancers: :dancers: :dancers: 

https://sendto.mozilla.org/page/s/mozfest-2015-volunteer

The footer section has a Webmaker logo(not sure if this was intended) and links out to several pages on webmaker.org.  I have a feeling that some/all of them will no longer exist once the the new Webmaker site is out.  Maybe it's worth verifying with the Webmaker team?  :eyes:

**Comment by Saallen** [comment]
Hi Mavis
This page is changing and so the links will not be used- but good catch- had not considered this before. Will make adjustments on other BSD LINKS

**Comment by Saallen** [comment]
Closing this issue as ti.to form will be used going forward instead of BSD
