### ISSUE TITLE
Add a non-white background-color to .hero-unit

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#88]
It took me about 3 secs to load the `.hero-unit` background and the light grey background color makes the white text on top not really visible.

![screen shot 2015-06-04 at 11 55 33 am](https://cloud.githubusercontent.com/assets/2896608/7991961/c956b2fe-0ab0-11e5-9886-7ed8ee2e3d61.png)
(screenshot taken on the homepage)

**Comment by ScottDowne** [comment]
I just made it the gradient that matches the image.
