### ISSUE TITLE
Error message on Proposal Form should be positioned closer to the field it is related to

### ISSUE THREAD

**Issue by mmmavis** [mozilla/2015.mozillafestival.org#90]
Error message on Proposal Form should be positioned closer to the field it is related to.

![screen shot 2015-06-04 at 12 01 50 pm](https://cloud.githubusercontent.com/assets/2896608/7992082/871b8940-0ab1-11e5-85b5-ec55d0e946d6.png)
(screenshot taken on https://mozillafestival-org-2015.herokuapp.com/proposals)

**Comment by ScottDowne** [comment]
So, less top margin is the idea?

**Comment by mmmavis** [comment]
heh that's what I would do :grin:

**Comment by ScottDowne** [comment]
fixed
